### ISSUE TITLE
Rewrite Bristleback in lua to include a cooldown

### ISSUE THREAD

**Issue by Minnakht** [OpenAngelArena/oaa#1006]
Apparently we don't have an issue for this yet as far as I could tell by looking through the list and this is a pretty important thing to do given how much Baumi talks about it on Discord, so here it is recorded for posterity as a Thing that Needs To Be Done.

Bristleback's ability Bristleback releases a Quill Spray every amount of damage he takes from the back, and there's meant to be a minimum refractory period between said releases. There currently isn't, which makes Bristleback excessively virile.

**Comment by Trildar** [comment]
Done in #1088.
