### ISSUE TITLE
Shadow Shaman Serpent Wards not giving last hits

### ISSUE THREAD

**Issue by Helvettium** [OpenAngelArena/oaa#1008]
As the tittle says, Shadow Shaman's Serpent Wards don't give last hits (and the gold associated), at least from creeps, didn't occur to try kill bosses with them at the moment.

This was noticed as I was testing out Shadow Shaman solo, I haven't yet played an actual match with him, so I don't know what happens if the wards kill a boss or another player.

**Comment by Chronophylos** [comment]
What level was the ulti when this happened?

**Comment by Helvettium** [comment]
3 I believe, didn't farm to lvl 4 ulti because I noticed this while doing ancient camp.

**Comment by Helvettium** [comment]
I'm currently starting a match with SS to see if the bug happens throughout the match.

**Comment by Chronophylos** [comment]
Yeah I did too to see if there are any exceptions. Turns out Level 1 is bugged too, I suppose it's a bug with the implementation.
Thanks for the report
