### ISSUE TITLE
Re-implement Spawn Spiderlings in Lua

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#1011]
And make level 5 and 6 spawn stronger Spiderlings rather than more Spiderlings. Was always the plan for summon abilities that scale in number, unless the plan changed.

**Comment by warpdragon** [comment]
Yup. Keep summons and illusion counts low if possible. Im not sure but i think theyre connected with some lag issues

**Comment by Chronophylos** [comment]
They are, as well as the Purge Tester increasing Entity Count, which increases Lag

**Comment by warpdragon** [comment]
Progress?

**Comment by l34Um1** [comment]
Closed because old.

**Comment by Haganeko** [comment]
Should probably keep this open. We still need to do it and it's a basic task. Without it we can't really progress the ability.
