### ISSUE TITLE
Omniknight's Guardian Angel lets you dive the Fountain

### ISSUE THREAD

**Issue by fenec250** [OpenAngelArena/oaa#1022]
Omniknight's Ult lets you survive the fountain. You still get Muted, can't see a thing and can't do much, but you can occupy the fountain while a teammate destroys their team.

While this is not critical (I only ever do it when the enemy team was disconnected) it would be nice to fix this at some point.

Also, with Ags Omniknight can assist allies in the other Duel.

**Comment by Haganeko** [comment]
Probably fixed by @Chronophylos's fountain rework. Thanks for the report!

**Comment by CrazyByDefault** [comment]
Would it be a good idea for the fountain to apply a strong purge to enemies that enter? This helps with not just Omni ult but other buffs aswell.

**Comment by Chronophylos** [comment]
Check out #1016. I just reduce HP and Mana no purge needed
