### ISSUE TITLE
Martyr's Mail can cause infinite damage echo on self

### ISSUE THREAD

**Issue by CrazyByDefault** [OpenAngelArena/oaa#1029]
Martyr's Mail doesn't ignore damage dealt to yourself, which can cause infinite damage instances which will either kill you or, depending on the situation, crash the game. 

How to recreate - 

* Pick a hero who can do self-damage - centaur for now.
* Max out Double Edge, get Martyr's Mail. DO NOT SKILL ANY TALENTS FOR NOW.
* Use MM followed by Double Edge. You'll be denied. Check the log, you'll find this - 

![20170605211907_1](https://cloud.githubusercontent.com/assets/22311967/26792946/c44b59de-4a39-11e7-940f-4af756f66e78.jpg)

* Next, skill talents and get the +10%magic resist talent.
* MM and Double Edge again, game crashes. 

All _echoed_ damage instances of MM happen on the same server tick. If the echoed double edge kills you within a few bounces (like my screenshot), no issues, you die
If you have sufficient reduction to reduce the double edge echoed damage to less than 1 eventually, you create infinite echoes that can't kill you, in a single tick

First instance reported by _Юра Лох_ on Discord, I dug deeper.

**Comment by Chronophylos** [comment]
Woo a Bug Report that is helpful. 
Thanks!

**Comment by CrazyByDefault** [comment]
Aww, I was gonna fix it too! You beat me to it
😶

**Comment by Chronophylos** [comment]
😛
