### ISSUE TITLE
Guardian Greaves farming effect missing

### ISSUE THREAD

**Issue by Helvettium** [OpenAngelArena/oaa#1034]
The guardian greaves farming effect is not currently in the game and there was no change log regarding it's removal in the newest patch, as such I'm reporting it.

**Comment by Helvettium** [comment]
or if it is in the game, then it isn't mentioned in the item description and doesn't give gold pop ups when creeps are killed and I am quite sure that it doesn't give gold to to your total directly either.

**Comment by SquawkyArctangent** [comment]
It's the latter, except it does give gold to your total. You can really see this if you grab 'em and farm with illusions, your gold in the bank spikes up really hard when you kill something.

**Comment by Helvettium** [comment]
ok. glad to know, it was just a missing description text.
