### ISSUE TITLE
Update Charge_BKB code (and others as we add in items)

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1038]
Ok so we're creating a bunch of new item KVs this week. Already merged are the KV for Charge BKB and other items which may or may not work as expected (I already know Charge BKB above lvl 1 does nothing).

Please take care to check and update as necessary.

**Comment by chrisinajar** [comment]
basically add this to lua: `item_charge_bkb_2 = item_charge_bkb`

**Comment by Trildar** [comment]
Was there anything other than Charge BKB that had issues with this?

**Comment by l34Um1** [comment]
Closed because old.
