### ISSUE TITLE
Guardian Greaves "greed effect" bug

### ISSUE THREAD

**Issue by Maroxis** [OpenAngelArena/oaa#1060]
When upgrading greaves with upgrade core the greed effect is gone. Dropping and picking up fixes it.

**Comment by KarmaticNeutral** [comment]
This is not specific to GGs. Most aura items have this bug often

**Comment by Trildar** [comment]
Yeah. This is one of the most annoying things about aura modifiers. #1046 should have mitigated this though. And that would have been pushed in 1.2.2, assuming that went public already.

**Comment by Haganeko** [comment]
This is a known bug, and has been reported elsewhere.
