### ISSUE TITLE
Still need to fix charge based abilities with duels

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#1061]
What were you doing? going into a duel with a charge ability on cooldown What was supposed to happen? the ability (in this case shrapnel) was supposed to refresh either one charge or all of them What happened instead? the ability icon refreshes but due to a lack of charges it does not allow it to be cast Anything else maybe make it so that the way that duels refresh abilities is the same way a refresher orb would, allowing charge based heroes to not have a disadvantage

**Comment by DoctorGester** [comment]
Valve just added an API which allows refreshing charges, this might be helpful:

https://github.com/ModDota/API/commit/e5b663570a52767a76d868a567c4251bd47dbded#diff-21dd4632308f0abaf2919865db89da6aR1866

**Comment by warpdragon** [comment]
Let's do it.

**Comment by Haganeko** [comment]
I thought this was done.

**Comment by warpdragon** [comment]
if it's done we can close it. i'm not sure.
