### ISSUE TITLE
Battle Fury upgrade path

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#1062]
What were you doing? Upgrading Battle fury What was supposed to happen? Upgrading until T5 What happened instead? despite showing the stats for the T5 battle fury it did not have a recipe Anything else not sure if this is a bug or just someone forgetting to put in a recipe

**Comment by imaGecko** [comment]
How old is that report?

**Comment by KarmaticNeutral** [comment]
I saw it today, but I'm not sure. I forgot to check reports for a couple days

**Comment by imaGecko** [comment]
Probably outdated
#1017

**Comment by KarmaticNeutral** [comment]
can anyone test this quick?

just in a cheat lobby
-gold 920583
-item upgrade_core_4
-item upgrade_core_4
-item upgrade_core_4
-item upgrade_core_4
then buy BF 5. If it works we can close this

**Comment by Haganeko** [comment]
That had been reported before - only four battlefuries had been planned/implemented but each stat KV had five entries.

**Comment by KarmaticNeutral** [comment]
Nice!
