### ISSUE TITLE
Many heroes can't level spells appropriately

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#1063]
What were you doing? Playing as Troll Warlord What was supposed to happen? Ultimate available for level up at appropriate levels What happened instead? ultimate would not level up past 1 until fifth level normal abilities were available Anything else it also showed that I could level up abilities at levels that I couldn't

What were you doing? Playing tusk What was supposed to happen? Level up my ultimate What happened instead? I couldn't skill my ultimate past level 1 until level 28, but then I could skill it twice Anything else If I didn't skill my ultimate at level 6 I couldn't skill it at all until level 28. there was no level up icon over it, but the little notch bellow the skill was outlined like I should be able to level it. This only affected my ultimate, I could skill talents and my other abilities normally.

Baumi - Yesterday at 3:34 AM
elder titan never gets enough visible skill points for his ult
this happens every game

What were you doing? Leveling up What was supposed to happen? I should be to skill one of my skills What happened instead? Could not see the level up icon or use hot keys to skill it

**Comment by imaGecko** [comment]
visual bugs are fairly consistent on some heroes, possible on every hero.
cannot confirm not being able to level up at all

**Comment by KarmaticNeutral** [comment]
People can't use hot keys so it's not just UI issues. For some reason people are not allowed to level up spells at certain levels.
