### ISSUE TITLE
Charger Pillars spawn in other boss pits

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#1064]
What were you doing? trying to kill shrek What was supposed to happen? its just shrek What happened instead? a charger pillar spawned in there as well

What were you doing? In a duel What was supposed to happen? Charger towers are not supposed to spawn What happened instead? Charger tower spawned

**Comment by Chronophylos** [comment]
We could check if the Tower is Inside the arena

**Comment by imaGecko** [comment]
would it be possible to have uniform arena sizes?

**Comment by Chronophylos** [comment]
They're roughly the same size
It depends on the map creators

**Comment by chrisinajar** [comment]
Pillar position selection has been rewritten, not sure how it behaves

**Comment by Trildar** [comment]
It doesn't have any arena bounds checking, so it's probably about just as likely to spawn outside.

**Comment by Haganeko** [comment]
Isn't this fixed?

**Comment by l34Um1** [comment]
Closed because old.
