### ISSUE TITLE
Fountain killing spot

### ISSUE THREAD

**Issue by Maroxis** [OpenAngelArena/oaa#1078]
You can easly kill anyone in fountain when standing in this spot: ![image](https://i.imgur.com/kwBr2dn.jpg)
Fountain can't reach you and you can target anyone in fountain when having pike. You can get there using forcestaff that removes those 3 trees that usually are there.

**Comment by allanvbhg** [comment]
Soo? If 4 people dc you have a way to kill them

**Comment by Chronophylos** [comment]
You should be able to stand there
Maybe someone can extend the fountain to there

**Comment by allanvbhg** [comment]
In discord it says you send. It should be able

**Comment by Chronophylos** [comment]
(I edited my comment)

**Comment by Haganeko** [comment]
Trees were put there so people couldn't get on it. Fountain extension or removal of the path there are necessary. @warpdragon waaaaarp.

**Comment by Haganeko** [comment]
Did #1213 also fix this?

**Comment by Trildar** [comment]
Confirm with Warp, but I believe he said it shouldn't be possible to get up there anymore. We'll see about that I suppose.

**Comment by warpdragon** [comment]
Yeah it needs a more comprehensive testing than im capable of

**Comment by warpdragon** [comment]
Theer is no such highground near the fountain now. Also the latest unmerged map branch puts blink blockers in those areas so fountain camping should be much more difficult if not impossible.
