### ISSUE TITLE
Missing Infinite Bottle Icon

### ISSUE THREAD

**Issue by Maroxis** [OpenAngelArena/oaa#1091]
Confirmed by teammates/enemies

**Comment by Haganeko** [comment]
The item icon or the effect icon? Or both? The whole game or from some point on? Do you have video? Logs?

**Comment by Maroxis** [comment]
It's just the item icon, i'll try to take screenshoot when next game starts

**Comment by Maroxis** [comment]
http://imgur.com/a/NOlC9

**Comment by Maroxis** [comment]
actualy there are more icons missing:
http://imgur.com/a/a6pya

**Comment by Trildar** [comment]
```[ W VScript              ]: Script Runtime Error: GetAbilityTextureName called with 2 arguments - expected 1
[ W VScript              ]: stack traceback:
[ W VScript              ]:     [C]: at 0x7ffc6455a880```
Quite possibly Valve breaking APIs again.

**Comment by DoctorGester** [comment]
All lua ability/item icons and corresponding buffs without GetTexture override are broken if the icon is defined in KV through AbilityTextureName.

**Comment by Trildar** [comment]
Any known fix? Aside from presumably writing a `GetAbilityTextureName` override for every single item/ability. What even is the second argument it's giving the function...

**Comment by Chronophylos** [comment]
Probably a level
Maybe you could test this by adding that function

**Comment by Trildar** [comment]
It's a boolean. Wonderful, more unexplained booleans.

**Comment by Chronophylos** [comment]
`void GetAbilityTextureName(bool breakAPI)`

**Comment by Trildar** [comment]
`string GetAbilityTextureName(bool breakAPI)` actually. And strangely appropriate seeing as it was returning `true` when I tested it.

**Comment by Chronophylos** [comment]
hahah

**Comment by chrisinajar** [comment]
`called with 2 arguments - expected 1`

`expected 1`

Looks like they're sending a param they should not be.

**Comment by chrisinajar** [comment]
```
function item_satanic_core:GetAbilityTextureName(brokenAPI)
  return self.BaseClass.GetAbilityTextureName( self )
end
```
😂

**Comment by SquawkyArctangent** [comment]
wait why would you ever override GetAbilityTextureName just to return the same value it was going to return in the first place what

why would you ever do that with a function in the first place

**Comment by chrisinajar** [comment]
That function fixes the problem.

**Comment by Trildar** [comment]
This can be closed now.
