### ISSUE TITLE
How I can limit the border of tooltip in jquery?

### ISSUE THREAD

**Issue by randomnum** [OpenAngelArena/oaa#1096]
Hello I am using tooltip with codemirror , what I want is to make the border of tooltip not out of the border of the editor ... see to this link to show how the border of tooltip out of the border of the editor : [https://jsfiddle.net/tooaq4oc/13/](url) 
this is the css  
`.tooltip{background:red;z-index:1000;}`
this is the script : 
```
var cm = CodeMirror(document.getElementById("editor"), {
    value: "function myScript() {\n    return 100;\n}",
    mode: "javascript",
    indentUnit: 4,
    lineNumbers: true,

});

var textMarker;

$('#add').click(function() {
    textMarker = cm.markText({
        line: 1,
        ch: 4
    }, {
        line: 1,
        ch: 10
    }, {
        className: 'marked-text'
    });

    $('.marked-text').tooltip({
        title: 'This is a return statement sfdl glrflg rgmlf',
        container: 'body',
        delay: { "show": 500, "hide": 100 },
        animation: false
    });
});

$('#remove').click(function() {
    if (textMarker) {
        textMarker.clear();
    }
});
```

How I can solve this problem ?

Note : I want to title of tooltip appare at all , so the panding 0 can not solve the problem

**Comment by Maroxis** [comment]
Can you update link? It's not working.

**Comment by randomnum** [comment]
https://jsfiddle.net/tooaq4oc/15/

**Comment by DoctorGester** [comment]
I'm sorry to ruin the fun but what does this have to do with OAA?

**Comment by Haganeko** [comment]
I have no idea what this is. I assumed it was related to this person trying to contribute. Is it not?

**Comment by randomnum** [comment]
@DoctorGester I search on issuse about tooltip and I found people ask on OAA , so I ask here ... sorry if I ask in wrong place .... But I did not knew where I must ask

**Comment by DoctorGester** [comment]
This is a DOTA2 custom game repository, it uses its own javascript and XML (not HTML) based UI so the chance of you finding help here is very low.

**Comment by randomnum** [comment]
can any body help me to find the place I can ask question on tooltip and jquery?

**Comment by Chronophylos** [comment]
checkout https://stackoverflow.com/
