### ISSUE TITLE
Upgraded Guardian greaves and Charge bkb

### ISSUE THREAD

**Issue by CynicalDemon** [OpenAngelArena/oaa#1121]
Guardian greaves don't give the correct amount of armor when upgraded to farming greaves or higher (aura and other stats still work fine).

Charged bkb can be upgraded without needing to spend upgrade cores on the magic wand upgrades by clicking on the next bkb recipe instead.

**Comment by Haganeko** [comment]
I believe the second part is intended, if you mean that charge BKB upgrade only costs one core once the item is made.

**Comment by CynicalDemon** [comment]
Yeah that's what I meant. It just seemed off since it said the magic wand needed upgrade cores as well.

**Comment by Trildar** [comment]
The recipe displayed is to go from a regular BKB to charge BKB, which I think actually isn't right because it costs more cores to combine later due to needing high level Magic Wand. Sidegrade probably also shouldn't be the primary recipe.

**Comment by Trildar** [comment]
As for Guardian Greaves, turns out the item was giving the armor bonus the aura was supposed to. And the aura was probably giving nothing.

Thanks for the reports, but in future, it would be better to make separate reports for unrelated issues such as these.

**Comment by Trildar** [comment]
Closed by #1123 and #1163.
