### ISSUE TITLE
Final duel victory

### ISSUE THREAD

**Issue by Maroxis** [OpenAngelArena/oaa#1133]
There is a bug when you lose first final duel then win normal and final duel you dont win the game. You have to win some more duels.

**Comment by chrisinajar** [comment]
I've also had this case work, so there is more contextual information needed.

**Comment by chrisinajar** [comment]
there *was* a bug where if you timeout the final duel then lost the next duel the goal would be extended by 20 instead of 10, but that's recently been fixed.
