### ISSUE TITLE
Fix Missing CD info in KV

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1139]
uno problemo @ Copywriter
When u make an item KV where the CD reduces every level, you should notice it's supposed to go
```"AbilityCooldown"      "35.0 30.0 25.0 20.0 15.0 15.0 15.0 13.0 10.0"```

if yours doesn't look like this, it needs to be fixed to look like that.
The reason is, and this is why Valve did it this way, because players need to see that when they upgrade the item that the CD will reduce
Baumi already fixed Forcestaff so dont' worry about that one

**Comment by imaGecko** [comment]
This should be fixed
