### ISSUE TITLE
Unstable Concoction Bug after Duel

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1144]
Enter Farming Stage
As Alchemist, in the middle of a teamfight cast "Unstable Concoction" (the first part). Duel starts before I get to cast "Release Unstable Concoction".

Enter Duel Stage
The "Unstable Concoction" stuns me. Duel happens. I die. Duel ends.

Enter Farming Stage (again)
Back in the teamfight. I cast "Unstable Concoction" (the first part). Instead of getting replaced with "Release Unstable Concoction" like it should, it instead goes on cooldown. I stun myself due to being unable to cast this.

**Comment by Trildar** [comment]
Unstable in more ways than one I see.

**Comment by warpdragon** [comment]
Moved to bur-reports. Post there next time.
