### ISSUE TITLE
Wraith King Aghanims

### ISSUE THREAD

**Issue by imaGecko** [OpenAngelArena/oaa#1158]
Currently Wraith King is a problem as his Aghs

Proposed Solutions:

Haganeko: Make his Aghanims have a lower duration and radius, possibly for duels only.

imaGecko: Make Wraiths have full hp and be killable. So you can fight until you run out of hp or time.

KarmaticNeutral: Wraiths count as dead for the purposes of winning the duel, so if all 5 heroes are in wraith form you lose the duel.

My opinions:
I don't like reducing radius or duration as this is just another "make this op ability bad" approach, the problem is one of current game mechanics and this doesn't get solved until these values get nerfed to no end.
My idea was that this wouldn't have a big impact in many teamfight situations as you don't want to kill something that's already dead, but in cases where your whole team gets caught in a bad situation you can get properly punished for it and don't get the current get out of jail free card. 
Though it is certainly a nerf to every full glass cannon in WKs team but one day they are gonna learn the value of reflex cores.
As for Karmatics approach it does give you a way to win the duel, by killing all of them and ignoring the wraiths. Problem is that you can hardly ignore the wraiths as they all deal damage as if they were still alive. This would only affect duels were the nerf is most needed though the Aghs is certainly very strong outside of the duel with the very low respawn times and plenty of teamfights

**Comment by KarmaticNeutral** [comment]
As it stands I favor Gecko's idea (regardless of my opinion of it being sloopy) due to continued fighting of wraiths where enemy can't flee. I think my idea is missing something and I would like to find that.

**Comment by CrazyByDefault** [comment]
I have another idea - 

Heroes in Wraith Form _except Wraith King himself_ are illusions which have full health and mana, and can cast abilities (but not use item actives) - basically like [Vengeance Illusions](http://dota2.gamepedia.com/Vengeful_Spirit#Abilities), for the same duration as normal Wraith Form.

**Comment by Minnakht** [comment]
If or when it's necessary to rewrite Reincarnation entirely to give it different functionality like that, that idea might be considered.

**Comment by Zarnotox** [comment]
If it's possible to have 5 seconds for duels only I would probably prefer that, but 5 seconds globally is fine too although his aghs outside the duel might be bad in that case

**Comment by Nexren** [comment]
I do not think it needs Balanced.

**Comment by l34Um1** [comment]
Closed because old and not a real issue.
