### ISSUE TITLE
Martyr's Mail has wrong pips, and needs T4 and T5

### ISSUE THREAD

**Issue by Techniclinus** [OpenAngelArena/oaa#1173]
You can uppgrade blademail to lvl 4
by using 1 uppgrade core  lvl 1.
lvl 1,2,3,5 is normal

**Comment by allanvbhg** [comment]
And to level 5 ?🤔

**Comment by Trildar** [comment]
I think he means it can be upgraded to Martyr's Mail with a UC1. Martyr's Mail has pips for tier 4 and 5, but considering its stats, I think the tier is correct, it's just the pips that are wrong.

**Comment by imaGecko** [comment]
martyrs mail has the stats of a t2 and t3, I wonder if that should be made a t4 and t5 to allow that line to t5. Was probably an oversight from when all items were supposed to go to t5

**Comment by allanvbhg** [comment]
The pips of martyrs need to be. 2/3 3/3 right?

**Comment by Chronophylos** [comment]
We'd need Martyrs Mail 4 and 5 too

**Comment by imaGecko** [comment]
do we want martyrs mail 2-5 or 4-5?

**Comment by Chronophylos** [comment]
I'm thinking 2-5

**Comment by allanvbhg** [comment]
Is there 2 more upgrades for it than? Cause it only has 2 levels and level 2 martyrs is t3. So we can make it a t4/5 too if we make more levels using t3/4 cores.

**Comment by imaGecko** [comment]
I don't think this one should be a ladder, because one isn't s definite upgrade of the other

**Comment by allanvbhg** [comment]
Every item needs a t5

**Comment by allanvbhg** [comment]
Than we make those?
