### ISSUE TITLE
Players going behind fountain. At the cave.

### ISSUE THREAD

**Issue by Techniclinus** [OpenAngelArena/oaa#1174]
All heroes who can blink or close to storm spirit R and players who bought a blink dagger can blink behind the fountain bug?

I dont know if you should be able to or not.

**Comment by Chronophylos** [comment]
It's not a Bug, some time ago we even had a path where you could walk past the fountain into the cave.

**Comment by imaGecko** [comment]
but at the moment it is not intended to be possible anymore

**Comment by warpdragon** [comment]
We've taken care of this in an upcoming patch. Also bug-reports. Post there next time. Even though it's not a bug, it's still a bug-report, technically.
