### ISSUE TITLE
Code JOBS

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#118]
### Override the Following Summoning Spells

1. Giant Treant
Nature's Prophet's "Force of Nature" (the treants) must become very powerful at levels 5 & 6 **without** just creating massive armies of trees (massive armies cause lag, inhibit proper movement and targeting, etc). There is a unit in .../npc/units called "npc_dota_furion_giant_treant_#" that will solve this. Starting at level 5, some or all of NPs treants become **4x** as powerful (thus cutting the number of treants needed in half). This basically means overriding vanilla "Force of Nature" with a custom LUA version. Link to Pizzalol spell: <https://github.com/Pizzalol/SpellLibrary/blob/master/game/scripts/vscripts/heroes/hero_furion/force_of_nature.lua>

2. Giant Spiders
The exact same thing as above. The new unit is called "npc_dota_broodmother_giant_spiderling_#". There is also a "npc_dota_broodmother_giant_spiderite_#" incase it's needed. I believe the Spiderite is the unit associated with the spell's Debuff/spawning mechanic but I'm not entirely clear as to how. No Pizzalol spell reference can be located. Perhaps the implementation would be similar to the Eidolon spell, found below.

3. Giant & Colossal Eidolon
Same as above. "npc_dota_giant_eidolon" and "npc_dota_colossal_eidolon" are the level 5 & 6 Eidolon, respectively. Unfortunately I can't think of a way to implement them without writing a new spell. Pizzalol spell: <https://github.com/Pizzalol/SpellLibrary/blob/master/game/scripts/vscripts/heroes/hero_enigma/demonic_conversion.lua>

### Create New Item Summoning Spells
1. Turret. Basically a placeholder KV file with similar properties to a pugna ward; name is "npc_dota_turret". Needs pretty heavy coding. It should use a portion of the Hero's damage and apply onHit Procs. Ability KV probably needs heavy editing as well as the tooltip. Needs an ability.

2. Spell Totem. Similar to above but for "npc_dota_spell_totem". This item summons a totem that casts all the player's abilities and item abilities with shared cooldowns.

3. Healing Mine. Ability should spawn multiple "npc_dota_healing_mine" in front of the player, these can be picked up by nearby allies for healing.

4. Throwing Dagger. Ability should throw a dagger projectile which will create a "npc_dota_throw_dagger" in the ground at a location. After x seconds, the player may teleport to the dagger. I believe the teleport follows the same onAttacked break rules as Blink dagger.

5. Decoy Courier. Ability should create an "npc_dota_decoy_courier" which walks around, has fake items, and explodes on death.

**Comment by Chronophylos** [comment]
Can you mark what is done?
Giant Treant should be done

**Comment by chrisinajar** [comment]
This should be basically done, and if any part isn't then individual tickets should be opened.
