### ISSUE TITLE
Hero tweaks

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#1186]
- [x] Make bosses immune to Reaper's Scythe.
- [x] Give bash abilities a cooldown. (#1189)

**Comment by Maroxis** [comment]
Don't forget about killing bosses with axe's dunk

**Comment by Chronophylos** [comment]
His dunk is not strong enough. It's not percentage based.

**Comment by Maroxis** [comment]
but a lot of bosses have little health and a lot of armor, so you can 1 shoot 1/3 of their health

**Comment by Haganeko** [comment]
Scythe kills bosses at 70% health if you have it at max level. And that's because we nerfed it.

**Comment by Trildar** [comment]
We actually already had #607 for giving CD to bashes. Was never done though.

**Comment by Chronophylos** [comment]
Culling Blade threshold:
`250 325 400 550 1150`
Most T1 bosses have less that 2K HP
Later bosses all have more HP
And when you have the `1150` threshhold you'll most likely encounter bosses with >10K HP

**Comment by Haganeko** [comment]
Finishing a boss also puts Culling Blade on CD, which is not ideal for Axe.

**Comment by l34Um1** [comment]
I disagree with The Swarm. Swarm is a nice alternative way of tanking bosses, I don't think we should take it away. Scythe is kinda broken though.

**Comment by Haganeko** [comment]
Weaver is doing very very well, though... Wanted to nerf him somehow. If we're not doing this, then what?

**Comment by l34Um1** [comment]
Implement more detection. Reveal on scan is still missing.

**Comment by allanvbhg** [comment]
What about making gem edible, cause no one wants to carry a gem now because an item is way more important?

**Comment by Chronophylos** [comment]
No
we talked way too often about this
the final answer was always no

**Comment by l34Um1** [comment]
Implement Dust effect on upgraded Mekka. Make Scan reveal. Give Urn offensive active detection (and nerf its damage). Some ideas.

**Comment by Haganeko** [comment]
I was thinking we could put dust on an offensive area item, instead of a defensive one. A Shiva upgrade, or urn of Sorcery if that's still a thing

**Comment by allanvbhg** [comment]
How does that work? Detection on urn? Add a dust effect?

**Comment by l34Um1** [comment]
I would like to have the detection on support items. Supports still need a bit of love (although they are super underrated atm).

**Comment by allanvbhg** [comment]
Yes but how does urn reveal invis?

**Comment by Minnakht** [comment]
@allanvbhg It doesn't yet, but a change could be made where the urn DoT also reveals whoever it's on

**Comment by Chronophylos** [comment]
On activation around the target

**Comment by Haganeko** [comment]
Can we have Urn of Sorcery with dust effect plz

**Comment by allanvbhg** [comment]
Oh oke thanks, sounds fitting

**Comment by allanvbhg** [comment]
Why not add the smoke effect to shivas? Alot of people buy shivas, and than make it so the blast reveals invis targets for the duration of the blast (or longer)

**Comment by Chronophylos** [comment]
> I was thinking we could put dust on an offensive area item, instead of a defensive one. A Shiva upgrade, or urn of Sorcery if that's still a thing
-- Haganeko

> I would like to have the detection on support items. Supports still need a bit of love (although they are super underrated atm).
-- Baumi

**Comment by allanvbhg** [comment]
An offensive support item 🤔 how does that work

**Comment by Haganeko** [comment]
See urn.

**Comment by Bigpadaa** [comment]
Nerf Windrunner she is able to tank the boss 24/7 with her windrun

**Comment by allanvbhg** [comment]
Make an issue for it?

**Comment by allanvbhg** [comment]
Or give bosses true strike?

**Comment by allanvbhg** [comment]
Or make it so windrun doesnt work on boss attacks

**Comment by Haganeko** [comment]
Done two weeks ago.
