### ISSUE TITLE
Ammend Creep Spawner

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#1187]
Needs to support variable (with time) weights for each camp.
As in, each possible camp spawn gets an entry; its chance of spawning is proportional to that.

**Comment by Chronophylos** [comment]
What do you mean?
Do you went a spawn chance variable for every creep?

**Comment by Haganeko** [comment]
Each camp possibility - for example, med camp can spawn three harpies, or it can spawn two, or it can spawn two bears - needs a controllable weight, so that we can control number of creeps per camp per spawn.

**Comment by l34Um1** [comment]
Closed because old.
