### ISSUE TITLE
Charge BKB 3 Not Working

### ISSUE THREAD

**Issue by LostWalker** [OpenAngelArena/oaa#1200]
I got a charge bkb on troll and it worked fine until I upgraded it. When I upgraded it, no charges were added when spells were cast. 
I'm not sure if this is a constant bug because this is my first time playing with the item, nor how to reproduce it if it's not constant so if anyone knows more about it, please reply.

**Comment by Haganeko** [comment]
Thank you for the alert.
There's a repository specifically for bug reports over at https://github.com/OpenAngelArena/Bug-Reports.
Did you attempt dropping the item and picking it back up?

**Comment by LostWalker** [comment]
Forgot that was something that fixes a lot of bugs in this mode. I didn't try to do it, but I will try to reproduce the bug and see if it fixes it (keeping the bug report template in mind)

**Comment by Trildar** [comment]
Should be fixed by #1163.
