### ISSUE TITLE
Implement OAA unique items

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#121]
Here's a quick rundown of the items
- [x] Refresher Core - Octarine with Refresher
- [x] Satanic Core - Octarine with Satanic
- [x] Shivas Cuirass - Shivas plus AC
- [x] Shivas Rush - Shivas plus Drums (both actives combined)
- [x] Shroud of Shadows - Make self/ally invisible + Not attackable
- [ ] Urn of Sorcery - AOE Urn that gains charges on enemy spellcast
- [ ] Vlads Helm - Vlads plus Dominator
- [x] Stoneskin Armor - Toggle to gain armor
- [x] Trumps Fists - Deso + Skadi
- [ ] Aether Glasses - Increases AOE of spells, not range
- [ ] Azazel's Crossbow - Double Calldown
- [x] Charge BKB - Magic Immunity Active charges on enemy spellcast
- [ ] Dash Staff - Push self forward, 0.1s invinc. frame, charge based CD
- [ ] Allied Euls - Cyclone self, allies, or enemies
- [ ] Jump Dagger - Jump to unit
- [x] Lucience - Switch between heal and movespeed auras
- [x] Martyr's Mail - Heal allies for % damage taken
- [ ] Rainbow Radiance - Toggle between MS/AS/dmg/Heal/Armor/Magic auras
- [ ] Pull Staff - Move self or other unit backward
- [x] Proximity Radiance - Aura that does high damage at a set distance from caster
- [x] Siege Mode - Toggle to gain splash attack (+range?), lose ability to move
- [ ] Staff of Confusion - Target enemy's spells target themselves
- [ ] Staff of Confusion - Target ally's or enemy's abilities' heal/dmg are reversed

Edit by @Chronophylos: Added checkboxes

**Comment by spar36** [comment]
I was in the call today (3/11) but had to leave before the end. I know you guys were talking about a central place to store info. What on this list has been done so far?

**Comment by chrisinajar** [comment]
@warpdragon can you make these checkboxes with ` * [ ] ` and remove the completed ones? That or we can just close the ticket and open granular ones later, your call

**Comment by Chronophylos** [comment]
Checkboxes look cool. I added them.

**Comment by Haganeko** [comment]
Refresher Core, Stoneskin Armor, Lucience, Charge BKB should be checked.

**Comment by warpdragon** [comment]
Nearly half-way there! Still plenty of cool items that need creating! See above.

**Comment by Rasor1911** [comment]
Don't we already have the Pull Staff?

**Comment by Honeth** [comment]
Current version of pull staff is making "bad" we wanted it to pull similair to pudge hook instead of force staff backwards

**Comment by Minnakht** [comment]
Siege Mode is go, apparently.

**Comment by mjoodgamer** [comment]
what about rich man's shield which is an item combined by poor man's shield and hand of midas 
witch grants you i higher block like and upgrade for poor man's shield but you get a passive whitch grants you an ability that make you  whenever you take XX damage you get XX gold

**Comment by Haganeko** [comment]
This issue is for things which have been discussed and approved. You can place suggestions in the separate, eponymous repository, or at the discord. Thank you!

**Comment by Chronophylos** [comment]
https://github.com/OpenAngelArena/suggestions

**Comment by VilkkuV** [comment]
I'm implementing Urn of Sorcery and have few questions about it.
1. Is it supposed to give 75/85 mana regen or 75%/85% mana regen?
2. Why Level 2 requires Upgrade Core 2 instead of Upgrade Core 1?
3. Should creeps be affected by the Soul Release?
4. Why there is nothing about bonus armor or health regen aura in item description?

**Comment by Haganeko** [comment]
1. Expose a KV for constant mana regen. The design is older than the vanilla urn rework. 
2. It is a tier 2 at level 1, so its level 2 is tier 3
3. No. 
4. I think it loses the aura as part of the upgrade. Expose a KV for armor, I guess. 
5. For now I guess use regular urn. The art team will make something.

**Comment by Trildar** [comment]
He's asking mainly based on what the framework KV files currently have.
@VilkkuV I'm pretty sure the mana regen is percentage. 75/85 constant mana regen is utterly insane. The tooltip is probably largely a copypasta from Urn, and whoever did it forgot to add in the Mek stats as well. You can add in stuff if it's missing.

**Comment by VilkkuV** [comment]
Thanks!

**Comment by Haganeko** [comment]
It should be flat - urn was changed and now gives flat mana instead of a%

**Comment by Trildar** [comment]
True. The value needs to be changed immediately for that though, as we definitely can't have an item giving 75/85 constant mana regen. XD
Suggestions?

**Comment by Haganeko** [comment]
Regular urn gives 2...
4/9/16/36

**Comment by VilkkuV** [comment]
That would work.
BTW Do we need level 1 and 2 Urn of Sorcery or level 2-5?

**Comment by allanvbhg** [comment]
It builds out of urn 1 so 2-5

**Comment by imaGecko** [comment]
It's Urn of Sorcery 1-4, being tier 2-5 items

**Comment by warpdragon** [comment]
https://cdn.discordapp.com/attachments/265224959427608576/312725251135897610/unknown.png

**Comment by VilkkuV** [comment]
Suggestion for prices of Urn of Sorcery level 3 and level 4?
Level 1 - 5215
Level 2 - 8715
Level 3 - ?
Level 4 - ?

**Comment by warpdragon** [comment]
Outdated.
