### ISSUE TITLE
Problem with the mirror boss

### ISSUE THREAD

**Issue by prsnnami** [OpenAngelArena/oaa#1216]
So our team and the enemy team were attempting different mirror bosses, and our boss spawned the enemy silencer which was half the map away. Is not a breaking bug, not even sure it is a bug tho.

**Comment by Haganeko** [comment]
Thanks! Do note that there is a repository exclusively for bugs over at https://github.com/OpenAngelArena/Bug-Reports, however

**Comment by warpdragon** [comment]
Moved to bug-reports. post there next time.
