### ISSUE TITLE
Duel does not end

### ISSUE THREAD

**Issue by prsnnami** [OpenAngelArena/oaa#1219]
Yesterday, it happened twice, if a player disconnects , the duel doesnot end, we have to wait for it to time out. Not sure how to replicate tho, one game the player disconnected before picking a hero , next game he disconnected while in the duel.

**Comment by Haganeko** [comment]
It's a known issue. We're working on it.

**Comment by warpdragon** [comment]
moved to bug-reports. post there next time.
