### ISSUE TITLE
Manta broken

### ISSUE THREAD

**Issue by prsnnami** [OpenAngelArena/oaa#1221]
Dont know the exact reason but it is really broken, has more illusions(3 at lvl 1), gives way more damage , idk , but get manta and gg, dont know why because i havent used it.

**Comment by Haganeko** [comment]
This isn't very clear. If you could look at the bug report submission docs over at the bug report repository (https://github.com/OpenAngelArena/Bug-Reports), it would probably help.

**Comment by Trildar** [comment]
Sort of known. Though I hadn't made an issue for it. #BlameChrono.
Not sure what's up with the damage though. I assume you mean the illusion damage is more than it should be?

**Comment by prsnnami** [comment]
in a game right now, there were 10 units , 2 heros 8 illusions , i am earth shaker , lvl 3 dunk , illusions took less damage than the heros

**Comment by prsnnami** [comment]
i could test specific things if you want , playing against a lvl 1 manta illusions should not be that hard

**Comment by prsnnami** [comment]
and they tell me the manta cant be upgraded

**Comment by prsnnami** [comment]
and deal too much damage, acc to them

**Comment by Haganeko** [comment]
Dunk doesn't count illusions since shaker aghs was changed. Could be that.
Will try to look at Manta KVs.

**Comment by Trildar** [comment]
The extra illusion is a code issue, just FYI so you don't have to look in KV for that. Upgrading is probably the only thing purely KV related.

**Comment by Haganeko** [comment]
Was looking at the KV for both problems. I could find no obvious issues, though.

**Comment by prsnnami** [comment]
tried it myself , doesnot look like they take more damage , its probably not 350%, and also 4 illusions are too op for early game

**Comment by Trildar** [comment]
Fixed by #1222.
