### ISSUE TITLE
Implementing sounds (re: Allied Cyclone)

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1234]
Thanks to Dr. Gester cuz I was able to figure this out using the Crumbling Island Arena source found at <https://github.com/DoctorGester/crumbling-island-arena/>

ok so basically the abilities in CIA seem to be activating sounds in the following way:

function <some shit>:OnSpellStart()
  some sub-function
      projectile:EmitSound("Arena.Brew.HitQ")
-----
Arena.Brew.HitQ is defined in /content/soundevents/custom_sounds like [this](https://pastebin.com/qm42XdtN)
and the sound itself is just an mp3 file in content/sounds
it could not be more simple (in theory)

**Comment by warpdragon** [comment]
Also music seems to be handled in a similar way. Just put them in *.mp3 and shove them in content/sounds/music/<whatever>

We will then create a sound event which can either tie-in with the Valve API's hooks like "on startup, game victory, game defeat, etc" if that's actually possible. That or we can simply call them explicitly through code. Like it's probably so f**king easy we could have this implemented tomorrow if you can find someone to do the work.

**Comment by Haganeko** [comment]
I am pretty sure we have a "don't implement any music without a mute button" policy... 
But the guy who was implementing that (prostosanja IIRC) gave up

**Comment by warpdragon** [comment]
lol we don't need a mute button... the game has one already. Settings > Sound >Music Volume.

**Comment by warpdragon** [comment]
Also that's incidental to the point of this research. I don't care if/how you use it but here it is.

**Comment by warpdragon** [comment]
I tried. Turns out i suck at lua.

**Comment by Chronophylos** [comment]
Nooo,
Please don't put all sounds in music
Put item sounds in `content/sounds/items` and so on.
Sound file you can use are mp3 and wav but ogg may also work.

**Comment by warpdragon** [comment]
Closed.
