### ISSUE TITLE
Fountain Protection

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1240]
Implement an aura that covers both high ground areas near the fountain. 

The aura provides armor to allies and applies heartstopper aura to enemies. This effect only starts when enemies step into the aura range and gets more powerful as time progresses.

The idea is to make chasing into the area possible but camping impossible.

If this isn't clear I can elaborate, but it seems fairly straightforward to me.

**Comment by Haganeko** [comment]
I don't know that we need the HP drain, but I'm on board.

**Comment by warpdragon** [comment]
This will become the new "soft anti-camp" for fountain/cave/outer-path areas. Closing this and creating a new thread.
