### ISSUE TITLE
Puck Duel Cheese Fix

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1244]
Puck can contest the highground by spamming phase-shift.

I propose we exclude units with "phase-shift" from HG rewards. And have the exclusion linger for a second to force him to stop using "phase-shift" for a second in order to contest.

**Comment by warpdragon** [comment]
Puck can also become unkillable in duels which is the real issue.

**Comment by warpdragon** [comment]
my suggestion, for what it's worth, is to create a duel-only consumable with the following properties:
1. silences in a medium aoe upon activation.
2. not purchaseable until atleast 10 seconds into the start of a duel to prevent abuse.
3. same duration/cost as dust.

**Comment by warpdragon** [comment]
![Concept Art](https://user-images.githubusercontent.com/13878439/27691377-d001832c-5cb1-11e7-97b7-97badf5fcbb9.png)

**Comment by l34Um1** [comment]
I don't like that idea at all. Better would be to tie global silence to the high ground bonus after a very long period of time (so long that it basically only gets activated if someone stalls).

**Comment by allanvbhg** [comment]
why not make it buyable after like 4 min, onstead of after just 10 sec. so it can only be used to fix stall. And baumi that will still not fix it, cause puck can also just spamm in any random spot. The point is she cant be killed to finish the game.

**Comment by l34Um1** [comment]
how exactly is global silence relevant to where puck is spamming?

**Comment by allanvbhg** [comment]
oh wait i tought you wrote, tie it to the high ground area. But what does silencing the bonuses do? isnt it meant to silence abilitys so they cant stall?

**Comment by l34Um1** [comment]
yes allan, I meant for the global silence to apply to the bonuses that the high ground does. come on man, you can figure this one out on your own

**Comment by allanvbhg** [comment]
sorry im still tired af.

**Comment by warpdragon** [comment]
Seems to me like a 2-part solution. Is this correct:
1 exclude phase-shifted units from HG 
2 include silencing enemy team into delayed HG reward

**Comment by l34Um1** [comment]
ye but super delayed

**Comment by Haganeko** [comment]
Not enough. If puck uses shift while in shift, I don't think he'd get silenced (Global Silence does not affect hidden units). Though I guess whatever way we implement this could include that.

**Comment by warpdragon** [comment]
Programmers confirm API exposed "out of world" units. Project is go.

**Comment by warpdragon** [comment]
Wow if i post in here it beeps in the other room! Boop

**Comment by Haganeko** [comment]
Will open new issue for implementation.
