### ISSUE TITLE
Add Cave Comeback Factor

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#1249]
Add a comeback factor which multiplies gold given by the cave. Suggested value is:
`exp(ln(m)t/(1+|t|))`
Where m is the maximum multiplier and t is a scaling factor times the relative difference in wealth between the teams.
`t = k*(MyTeamWealth-YourTeamWealth)/LeastTeamWealth`
Exposing the bound m and the scaling factor k somewhere would be helpful.

**Comment by Haganeko** [comment]
Currently, best estimate for initial m and k are:
m = 2
k = 1/10000

**Comment by Zarnotox** [comment]
Wouldn't it be better to make 1/k increase over time?

**Comment by Haganeko** [comment]
Actually, since I made the t-value relative, no... But then that is now a terribly low value. Updated!

**Comment by warpdragon** [comment]
afaik this has been taken care of. Closed.

**Comment by Haganeko** [comment]
AFAIK it hasn't. If you say so, however... 
@chrisinajar?

**Comment by warpdragon** [comment]
really? I thought u did it like 2 patches ago...

**Comment by Haganeko** [comment]
I have the numbers... Turns out I can't code.
All I did was change the cave from two minutes per room to three, and include a factor which makes its increase grow faster than normal creeps'

**Comment by l34Um1** [comment]
So is this or not? It says merged but I don't believe it's actually in the game.

**Comment by Haganeko** [comment]
It is not in the game.

**Comment by Haganeko** [comment]
No longer relevant since all of the cave will be reworked.
