### ISSUE TITLE
Reduce Leash on Non-Rosh Bosses

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1253]
We've moved the outer Boss Pits much closer to the map. Is it possible someone in #coding could reduce the leash distance... 50% or so?

**Comment by warpdragon** [comment]
Ok maybe not 50% trildar says its 800. It might just be that the leash bugs out sometimes. I dunno i was going off baumis last video "New Map". Still, for the record, the pits are much smaller than when we defined the leash ranges originally

**Comment by l34Um1** [comment]
Closed because old.
