### ISSUE TITLE
[PRIORITY] Make Mekka, Urn and Scan apply Dust

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1259]
Make Mekka, Urn and Scan apply Dust. Scans cooldown needs to be reduced to 90 seconds. Urn Dust effect lasts as long as Urn debuff. Mekka and Scans Dust last as long as Dust lasts.

**Comment by Haganeko** [comment]
I dislike this on mekans. It creates conflicting incentives. 
Does this apply to Urn of Sorcery, as well?

**Comment by wWilliyamS** [comment]
Let's consider the ease of which supports can cover the map with sentries with all their money from Boots of Travel's commensalism.

**Comment by Haganeko** [comment]
Money is not the problem. The problem is the opportunity cost of having an inventory slot occupied by detection which does nothing else. In vanilla, where supports are starved for money, that's not a problem. In OAA, where each item is a huge boost in power, and everyone can afford to get six slotted, that cost is prohibitive.

**Comment by wWilliyamS** [comment]
6 seconds of not having a sixth item is not really prohibitive. If you were to get jumped by a right-clicker, you're dying with or without that sixth item.

**Comment by Haganeko** [comment]
You're still thinking like vanilla. Remember, these supports have farm. 
Also, if the other team is also doing this, then it's a full time job. It won't end with just six seconds.

**Comment by wWilliyamS** [comment]
The supportive build costs almost the same in OAA as the damage+survivability build because of core upgrade gold costs. It would be nice to be able to have a reflex item that is also a ward slot as well as having urn and mekkah apply dust.

**Comment by Haganeko** [comment]
Everyone already has a free ward slot at the fortify button. Unless you mean an item which lets you place sentries?

**Comment by wWilliyamS** [comment]
Like the "Observer and Sentry Wards" (Ward Dispenser) item, but with reflex core stats.

**Comment by Haganeko** [comment]
This has a few problems. First, it breaks with the design of reflex items as defensive options.
Second, people already have wards as mentioned. 
Third, there is a separate repository for suggestions.

**Comment by Chronophylos** [comment]
priority. sits here for 26 days

**Comment by l34Um1** [comment]
Closed because old.
