### ISSUE TITLE
Picking random hero.

### ISSUE THREAD

**Issue by Techniclinus** [OpenAngelArena/oaa#1274]
I picked a random hero 4 times and i crashed all of the times.
I dont know if its a patch bug, game bug or just my PC and i culdnt reconnect to the game either.

(Sorry if i spell anything wrong i live in Sweden.)

**Comment by Chronophylos** [comment]
Do you have the console output or a recording of the game?

(Don't worry about spelling)

**Comment by warpdragon** [comment]
Moved to bug-reports. Post there next time.
