### ISSUE TITLE
Duel and Hidden Units

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#1276]
As discussed in #1244, we want to fix Puck being able to win duels effortlessly. This means two things:

- [ ] Ammend High Ground so that there's a one second delay between reaching it and it starting to consider you, and so that hidden units count as not being on the high ground (that way, they can neither interrupt others from gaining stacks, nor gain stacks themselves)
- [ ] Make it so the capture has a last effect, much later than Triple Damage, which would silence all enemy units, including invulnerable and hidden ones.

**Comment by Honeth** [comment]
Instead of silence couldn't we make it like alright if you can manage to stand on the high ground uncontested for x duration the all the enemies within 1800 radius of you get killed (invis,hidden doesn't matter they just die)

**Comment by Haganeko** [comment]
How is that better? In any case, there was plenty of time for discussing this in the original issue, and before even that in Discord.

**Comment by Honeth** [comment]
alright i'm not sure if i was there in that meeting but silence seems fine aswell

**Comment by Zarnotox** [comment]
I'm guessing you should also be muted for the duration, else puck just goes manta and starts over

**Comment by Honeth** [comment]
we can just use doom(the ulty) for it though

**Comment by Haganeko** [comment]
I think for now it's just a silence, which makes him come out. We can make it need a strong dispel if need be.

**Comment by Zarnotox** [comment]
Well what does "much later than Triple Damage" mean, would puck be able to stall a duel till it ends if he purges off 1 silence, or maybe 2 silences? (since you'd need the same time to apply it again)
The problem is puck being able to never lose a final duel, if one item can prevent that the problem isn't fixed imho..

If people don't want to be silenced + muted they should just go to the highground imo

**Comment by Haganeko** [comment]
Puck needs to get out of the shift to purge anything. And again, it can be made unpurgeable. If you guys still need to discuss this for some reason that did not exist in the previous two weeak the discussion issue was up, go on discord.

**Comment by l34Um1** [comment]
Closed because old.
