### ISSUE TITLE
Where is Meepo?

### ISSUE THREAD

**Issue by prsnnami** [OpenAngelArena/oaa#1277]
Its been a while since the mod released and i think you guys should first get all the heroes done. Meepo might be harder because of the boots not implementing it doesn't seem fair. Or is he being added? And regarding the boots i don't think power treads and phase have any problem, and if the tp boots shared gold among all the tp boots holders (i guess what baumi said once, rather than all players getting extra creep gold, the extra gold gets divided) , it would probably be OK for meepo too. Just my thoughts. Also how do the mana boots work, do they increase your gpm or set your passive gpm to a number?

**Comment by Haganeko** [comment]
Meepo would take a lot of work to add, for a hero who's not very popular. Plus, he'd be hell to balance. 
With how much we still need to put into the mod, it's just not a priority.

**Comment by prsnnami** [comment]
better have him balanced before adding custom stuff which may make it harder to balance imo. I am asking because i want to play that hero and honestly shouldn't the mod have every hero before adding custom scripts, not adding something because its hard just sounds lazy.

**Comment by Haganeko** [comment]
We still have to fix bugs, settle on a map design, introduce bosses... All of which are more essential to the game than a hero we're not even sure is actually possible to implement as it is.

**Comment by Chronophylos** [comment]
Do not worry Meepo will come, but not now.

**Comment by SquawkyArctangent** [comment]
I would honestly say that it's likely Meepo will not ever be enabled unless he gets an entirely new ultimate.

**Comment by prsnnami** [comment]
Well that sucks. Really wanted to try him and he is not even a decent pick in other AAs. Hope you guys find a solution cause it would be a waste of such a unique hero design.

**Comment by warpdragon** [comment]
Closed.
