### ISSUE TITLE
Players not recieving Farming/Reflex Core

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1278]
Need to check that all players, even those who disconnect during/before bosses, then reconnect after, still get cores.

This is a slight high-level re-work of how cores are rewarded. Should be an easy coding fix for someone who knows the core reward code.

**Comment by Chronophylos** [comment]
For clarification: you want all players to get cores. Even if they are disconnected?

**Comment by Haganeko** [comment]
Yes. Not like cores are shareable, anyways.

**Comment by l34Um1** [comment]
Closed because old.
