### ISSUE TITLE
Fix KotL Illuminate damage Talent

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#1283]
I remember there being a report a long time ago about KotL's Talent interacting weirdly with levels 5 and 6 of the ability (damage decreases or something like that). I'm unsure if there's still an issue, someone could check if I don't get to it first.

**Comment by Haganeko** [comment]
The ability probably needs to be rewritten in lua. If it is, recall the bonus damage from the talent is independent of channel time.

**Comment by Chronophylos** [comment]
I'd need more information to do anything

**Comment by Haganeko** [comment]
The KotL talent is supposed to add 200 damage to the ability, regardless of channel time. It currently snaps the progression back to 100 damage per second of channel as well, regardless of our KV

**Comment by l34Um1** [comment]
Closed because old.
