### ISSUE TITLE
HUD health regen CAP

### ISSUE THREAD

**Issue by Honeth** [OpenAngelArena/oaa#1285]
Dota 2 currently caps health regeneration at 1000hp/s but only in the HUD.

Could someone try looking into making the cap higher or just removing it entirely (making it integer cap instead).

this might be easy for just the player would be great if it worked on all heroes for every player/ spectators.

**Comment by Chronophylos** [comment]
The cap can't get removed, it's hard-coded. We need to make a custom HP Bar UI for that,

**Comment by Yahnich** [comment]
no u don't, you just need to replace the valve label with your own

**Comment by Chronophylos** [comment]
right. That make me wonder even more what Valve was thinking.
