### ISSUE TITLE
Buff Dazzle's Poison Touch

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#1289]
Poison Touch isn't very interesting as is. We want to add new effects to levels 5 and 6.

- Level 5: Make it autocastable on attack (same CD as it would have to cast normally);
- Level 6: Make it pierce spell immunity.

**Comment by Zarnotox** [comment]
Ehm i'm not sure about that level 6. What is the thought process behind that?

**Comment by Haganeko** [comment]
The thought process is we need something new every level, and physical damage spells already tend to pierce spell immunity.

**Comment by Zarnotox** [comment]
Do other physical spells also tend to permastun?

**Comment by Haganeko** [comment]
With a two-three second delay, but hm...
That is really something of a deeper issue than just OAA - the permastun is also possible in vanilla. We would need to work on what anyhow.

**Comment by Zarnotox** [comment]
I don't know, are we also going to give other heroes spells on every attack? It could be nice on Bane his brain sap, batrider his sticky napalm, shadow demon his shadow poison, QoP her shadow strike and skywrath his arcane bolt /s

**Comment by Haganeko** [comment]
None of those spells are known for gaining a new affect on every level. Poison Touch (and, you will note, dragon form) are.

**Comment by Zarnotox** [comment]
What about a slow after the stun and a split like double stifling dagger?

**Comment by Haganeko** [comment]
Wait, so now we want to permastun two people? 
A slow after the stun could be useful, I guess...

**Comment by chrisinajar** [comment]
@l34Um1 thoughts?

**Comment by Zarnotox** [comment]
Looking through issues to become more active again. I think this one might be outdated since the new poison touch?

**Comment by Haganeko** [comment]
Yes.
