### ISSUE TITLE
Terrorblade gets no benefit for skilling his level 4 and 5 ultimates.

### ISSUE THREAD

**Issue by wWilliyamS** [OpenAngelArena/oaa#1291]
His level 3 ultimate is the same as his level 4 and 5 ultimates.

**Comment by Haganeko** [comment]
Cast range increases greatly. There is no tooltip, but we're working on it.

**Comment by allanvbhg** [comment]
Is only cast range enough though?

**Comment by allanvbhg** [comment]
Nvm you cant really change more about it. (But cd)
