### ISSUE TITLE
Heaven's Halberd active mana cost scales for no additional potency.

### ISSUE THREAD

**Issue by wWilliyamS** [OpenAngelArena/oaa#1292]
The mana cost increases from 100 at lv1 to 400 at lv5 with no increased potency for the active's effect. This feels _terrible_. The cooldown does decrease, but that hardly justifies the increased mana cost and it only exacerbates the mana cost problem, especially if you're using Halberd on a strength hero like Sven who needs most of his mana pool to cast his 700 mana ultimate.

**Comment by warpdragon** [comment]
Halberd is only purchased on Sven in 1% of normal dota games. Source: <https://www.dotabuff.com/heroes/sven/items>

Your support should be buying this item and should have no problem affording the mana to cast it.

**Comment by Haganeko** [comment]
Also, this was done.
