### ISSUE TITLE
Upgrading "Greater Enrage Crystal"

### ISSUE THREAD

**Issue by Darksold** [OpenAngelArena/oaa#1294]
If you want to upgrade the "Greater Enrage Crystal" into the  "Divine Enrage Crystal" and you put it into the quickbuy the game tells you that you need an "Invisibility Crystal"  for it although it works just fine.

**Comment by Haganeko** [comment]
That's just how items with multiple recipes work. No way to fix I without completely overriding the UI. Also, there are separate repositories for bugs and suggestions.
