### ISSUE TITLE
Juggernaut's Ultimate and Charge Boss Pillars

### ISSUE THREAD

**Issue by Darksold** [OpenAngelArena/oaa#1295]
If Juggernaut uses his ultimate on an enemy in the Charge Boss Arena he can jump onto the Pillars of the Charge Boss.

**Comment by warpdragon** [comment]
Hmm. This seems simple to fix. Anyone?

**Comment by warpdragon** [comment]
Not necessarily a "bug" perse. But I'm moving it to bug-reports anyway.
