### ISSUE TITLE
Lone Druid is problematic

### ISSUE THREAD

**Issue by wWilliyamS** [OpenAngelArena/oaa#1298]
1. Lone Druid uses his bear before the duel.
2. His bear does not teleport with him into the arena.
3. Bear can't return yet because it's level 1.
4. Lone Druid uses his refreshed Q to get a new bear.
5. Lone Druid dies in duel.
6. Bear dies in response.
7. No more Bear outside of duel, because it died.
8. No bear for farming, Q is on cooldown.

The extant solution is Lone Druid players getting good and not using their bear before the duel, but I figure you all should know about this.

**Comment by allanvbhg** [comment]
He should use the bear in duels, its one of druids most powerpull tools. And also chen and enchantress get their creeps as well. So we need to fix it.

**Comment by wWilliyamS** [comment]
You can use the bear in duels because the ready Spirit Bear will still be ready after the duel where you used it as long as you didn't use the bear before the duel. Likewise, Terrorblade can Metamorph in a duel and still have his Metamorph available after a duel as long as he didn't Metamorph before the duel. You'll have to quickly put items on the Bear during the duel but it should be fine.

**Comment by l34Um1** [comment]
Lone Druid requires special care and attention that he hasn't received yet. Consider the entire hero a work in progress. Your concerns are very valid and your complaints are reasonable but we simply haven't worked on LD yet.

**Comment by Ynscription** [comment]
Also it's not possible to upgrade the bear's boots because of the farming core limitation, (wich I understand) but perhaps something could be arranged for lonedruid? Also when the bear uses tp home it gets stuck often in the trees south of the spawn.

**Comment by warpdragon** [comment]
Closed.
