### ISSUE TITLE
Uriel Illusion Fountain Camping

### ISSUE THREAD

**Issue by Ynscription** [OpenAngelArena/oaa#1299]
So we were killing Uriel and we got interrupted by the enemy team we all died or something funny happenned and then we had an uriel illusion of a hero of the enemy team spawn-camping our base. We talked with the other team and they werent fighting any Uriel. Eventually they killed the Uriel that spawned the illusion and it was solved. Killing the illusion just made it reappear moments later in the same spot near our fountain.

**Comment by warpdragon** [comment]
Moved to bug-reports. Post there next time.
