### ISSUE TITLE
Arc Warden Double + Greater Arcane

### ISSUE THREAD

**Issue by DeiRex75** [OpenAngelArena/oaa#1306]
If Arc Warden has Greater Arcane Boots and uses Tempest Double, it seems to be that his Illusion's boots give money towards the real one.

**Steps to Produce/Reproduce**
1. Buy Greater Arcane Boots
2. Watch Gold
3. Use Tempest Double
4. See increased Gold income

**Expected Results**
The same money income without Tempest Dobuel.

**Actual Results**
Doubled money income of arcane boots.

**Comment by Haganeko** [comment]
I believe this is intended, as long as his double doesn't get bonus money from his own kills and vice versa. 
In any case, thank you for the report. Do note, however, that there is a separate repository for bug reports.

**Comment by DeiRex75** [comment]
Oh, thank you.
I will post it there :)

**Comment by warpdragon** [comment]
Moved to bug-reports. Post there next time!
