### ISSUE TITLE
bkb 50 strength for free bug

### ISSUE THREAD

**Issue by lordcakealot** [OpenAngelArena/oaa#1315]
so basically, every time you use a bkb it levels up the item, without the need for cores. it doesnt change how much stats you gain from the item until you drop it and pick it back up. so basically you can get 50 strength for free pretty easliy

**Comment by Haganeko** [comment]
This is a known issue. We're working on it.

**Comment by lordcakealot** [comment]
oh right

**Comment by Haganeko** [comment]
Thank you for the report, anyways!

**Comment by lordcakealot** [comment]
no problem, just to let you know, i may have told a few people, and it might get out of hand soon. sorry!

**Comment by warpdragon** [comment]
Moved to bug-reports. Post there next time!
