### ISSUE TITLE
Original OAA Boss Project: Slime, Carapace, etc.

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1325]
#### Notable stats
Lots of magic resistance and armor.

#### Abilities
 * Phase 1: Rightclicks
 * Phase 2: Push away and disarm non-target heroes. Effect is cancelled when boss is stunned.
 * Phase 3: Pulls the farthest hero to himself (like a forcestaff push) 
 * Phase 4: Pulls the farthest hero to himself and creates an arena that the pulled enemy can't leave

#### Balance
Expose the following as configurable variables in KV format
 * Base movement speed, hp, regen, damage, attack speed
 * pull range
 * wind effect push speed
 * duel arena aoe

#### Notable stats
**Crossbow Attack**: Azazel shoots 2 bolts into the air that comes down after a short delay with a visual indicator. The botls comes down one after another (in different areas), and deals damage in the indicated AoE. **This ability is used in all 3 phases**.

Starts out with a ranged autoattack, converts to melee at phase 3.

#### Phase 1:

Regular ranged rightclick.

#### Phase 2:

As soon as phase 2 is triggered Azazel shoots (2 bolts) from his crossbow. As the bolts land he teleports to one of them, while the other location spawns an illusion.
The illusion and Azazel are linked up together. They then slowly move in a circular fashion around the arena. If you touch the link, you get damaged and stunned. Both Azazel and the illusion still do regular ranged attacks during this.
If you damage the boss enough, the illusion disappears and Azazel enters phase 3. If you kill the illusion he receives damage, which is just enough to trigger phase 3.

#### Phase 3:

He gains a spear, becoming melee.

Spear Ability: A swiping attack that after a windup, pushes enemies caught in it across the arena.
Meteors: Meteors start raining down, leaving permanent fire marks where they land. The meteors deals damage in the indicated AoE, and the fire marks deals AoE damage over time.

#### Balance

Expose the following as configurable variables in KV format

HP, right click damage, armor, movespeed.
Damage of the crossbow blasts.
Phases HP threshold.
Phase 2 link's damage and stun duration.
Phase 2 movement speed.
Illusion damage dealt/taken.
Meteors damage, both the initial impact and the DoT.
Rightclick damage for phase 3 also need to be seperately adjustable.

#### Notable stats

This boss moves around the boss arena in a pattern, shooting projectiles in its wake. Maybe it is moving backwards and shooting, maybe it is shooting from its back.
No autoattack.
Anyone standing directly on the way gets trampled (damaged and stunned).

#### **Phase 1:**

The boss moves in a simple pattern, like a circle or a figure eight.

#### **Phase 2:**

More complex movement pattern (example below), chosen from a pool of two.
<img src="https://cloud.githubusercontent.com/assets/25013178/23051031/21e46eb0-f4ad-11e6-8da2-1ef93e7943d5.png" width="100" height="100" />
Shooting is faster.

#### **Phase 3:**

Movement pattern is erratic, changing between a few patterns every now and then (can be comprised of all the earlier ones). Bullet hell.

#### **Balance**

Expose the following as configurable variables in KV format

Base movement speed, hp, regen, armor etc. Movement speed is especially important.
Rate of fire.
Damage and duration of the trample stun.

#### **Notable stats**

Has a carapace of sorts with chinks in it. Hitting from the direction of a chink (a ~10 degree window?) automatically crits (or otherwise shows clearly that it causes extra damage).
Has a decent-powered melee attack.
Has a slow turn rate.

Phase 2 at 80% hp
Phase 3 at 30% hp

#### **Phase 1:**

The boss has two chinks, and attacking from a 10 degree window around the chink's center will deal extra damage.

#### **Phase 2:**

Every now and then (say, 10 seconds), a chink will start to glow. After two seconds, the chink will deal AoE damage in a cone (the same area from which extra damage is possible)

#### **Phase 3:**

More chinks (four), the charge-up is quicker (one second?) and it happens more frequently (every 5 seconds?)

#### **Balance**

Expose the following as configurable variables in KV format

Base movement speed, hp, regen, armor etc.
Angle and bonus damage for attacking a chink.
Charge time, frequency, angle and damage for the AoE cone ability.

#### Notable stats
Is always floating around the arena into random directions with 150 or so movement speed

#### Arena Modifications
* The entire arenas border has a mirror effect going on 
	* preferably even a visual effect 
	* maybe people can even bounce spells off of it 
	* If any of the bosses abilities hit the mirror they are reflected and continue flying

#### Abilities
* Phase 1: 
	* throws out orbs that deal damage when you touch them 
	* These orbs are relatively big, don't dissappear until the boss is dead and bounce of the mirrors 
	* There is a maximum amount of them, like 4 or so

* Phase 2: 
	* the boss starts firing a Kamehameha style laser 
	* Before he does so he makes a dash away from the enemies 
	* The lasers direction is clear 
	* The laser bounces of the mirrors multiple times (unsure about the speed but either very fast or instant) 
	* You take damage for every frame you touch the laser

* Phase 3: 
	* the boss now starts throwing smaller but faster orbs into the fight 
	* There is no limit to these so the fight becomes a race against the clock since eventually the entire arena will be covered

#### Balance
Expose the following as configurable variables in KV format

 * Base movement speed, hp, regen, armor etc
 * damage, speed, aoe of orbs 
 * damage, speed, aoe, length of laser

#### Notable stats

doesn't attack regularly
* instead his attacks follow a more "dark souls" logic
		* he swings his sword in a big arc
		* any enemy that touches the sword takes damage
		* if you are in 200(?) range of the boss you will always get it

*every attack has a lengthy wind-up
* during wind-up the ground will have particles showing where the hitbox of the sword will be, allowing people to dodge
* every attack deals significant damage although people should be able to tank 4-5 hits
* there are 3 different kinds of sword swipes (see images in folder)
		*swipe 1 "Thrust": long range, targeted at an enemy in the backlines
			* selects an enemys location at the beginning of wind-up, doesn't home afterwards
<img src="https://cloud.githubusercontent.com/assets/24982519/22711401/53eb0258-ed81-11e6-8ee9-d4eeba49e160.jpg" width="100" height="100" />
		* swipe 2 "frontswipe": short range, targeted in such a way that it hits as many enemies in range as possible
<img src="https://cloud.githubusercontent.com/assets/24982519/22711398/53e4be5c-ed81-11e6-991c-6c7523b181ee.jpg" width="100" height="100" />
			* swipe 3 "backswipe": same range as frontswipe, comes out at random times as a fast follow up to frontswipe
<img src="https://cloud.githubusercontent.com/assets/24982519/22711399/53e6b536-ed81-11e6-92f4-c48c18874ca7.jpg" width="100" height="100" />
			* has a shorter wind-up than frontswipe
			* covers mostly the same area as the frontswipe, doesn't do new targeting

#### Abilities
* Phase 1:
	* just the regular attacks to get people used to what the boss can do
* Phase 2:
        * boss gains "rush" ability
		* long cooldown (10s?)
		* needs to be visually obvious
		* boss holds out sword with active hitbox to the right of him 
	<img src="https://cloud.githubusercontent.com/assets/24982519/22711400/53e8f4a4-ed81-11e6-8034-956407b0552d.jpg" width="100" height="100" />
		* boss rushes to a location in the arena
<img src="https://cloud.githubusercontent.com/assets/24982519/22711397/53e3a5bc-ed81-11e6-943e-0487e4da978f.jpg" width="100" height="100" />
			* enemies hit by the sword take massive damage
			* enemies hit by the boss get pushed away, get slowed and take a little damage
* when the boss finishes the rush he does a big aoe swing attack that deals massive damage 
<img src="https://cloud.githubusercontent.com/assets/24982519/22711396/53e30940-ed81-11e6-85f0-af7c3f76000a.jpg" width="100" height="100" />

* Phase 3:
	* boss gains teleport ability
	* before each swing he teleports behind a random enemy in the arena and then the wind up starts

#### Balance
Expose the following as configurable variables in KV format

 * Base movement speed, hp, regen, damage, etc
 * AOE of Attacks
 * Rush Speed
 * Windup speed

#### Notable stats
instead of dying the boss splits into 2 smaller slimes
 * smaller slimes have 75% HP of the original
 * splits a total of 3 times

#### Abilities
 * jumps into the air to attack
		* shadow appears below him while he is in the air to show where he is
		* travel time is significant enough to allow for proper dodging
		* deals damage where he lands
			* all enemies hit are pushed away and slowed massively
			* this is his highest single source of damage
 * if you "kill" him he starts shaking violently
		* during that stage he is invincible and throws small projectiles all over the arena
			* they work just like the regular jump, thrown into the air, with a shadow telegraphing where they land
			* come in different sizes
			* players need to focus on dodging them
			* if hit they take damage and are slowed

#### Balance
Expose the following as configurable variables, either at the top of the lua file or in KV format

 * Base movement speed, hp, regen
 * Size of the Slime
 * damage of the jump
* duration of the jump
* push distance and slow duration and %

#### **Notable stats**

While fighting Havres, she is always indicating a direction. All units fighting her experience a pull in that direction. While they can act fully, they will always have to make time to compensate for that pull with their movement. Example: She indicates to the right. If you now try to walk to the right you'll go faster; if you try to go to the left you'll be slower and if you try to walk up or down then you'll actually end up tilted to the right.
To go along with this, her main source of damage are paintings she draws on the ground. There'll be a line of particles that draws a pattern on the ground and after it is complete the pattern lights up and becomes active. If you touch this pattern you take damage and become disarmed. While fighting him you'll always have to be moving to avoid being pulled into these drawings.

#### **Arena Modifications**

None are necessary.

#### **Phase 1:**

Havres draws simple patterns, which last for a short time and expire

#### **Phase 2:**

Havres now adds to patterns already in place, and each one lasts longer.

#### **Phase 3:**

Havres now also has two projectile spells she can throw out:
- A fast-moving projectile, which deals damage on hit
- A low-moving, large projectile which deals damage over time during contact

## Rotating Shield Boss

Expose the following as configurable variables, either at the top of the lua file or in KV format

Base movement speed, hp, regen, armor etc.
Pattern damage, frequency (cooldown?), and duration.
Projectile damage and speed.
Pull strength and direction change frequency.

A boss that has simple agro mechanics but has a rotating shield making timing of spell usage highly important.

Most of this boss will be copied from the shield boss.

**Comment by l34Um1** [comment]
This needs to be updated and turned into seperate issues.

**Comment by Haganeko** [comment]
It was. We can bring the old issues back if you want.

**Comment by Haganeko** [comment]
Obsolete. Closing.
