### ISSUE TITLE
Power Treads need LUA

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#133]
I've got a 90% working pair of greater power treads on my fork. atm they give proper everything except no toggle. toggle will be a bit of a trick:
1. Need a boot of every stat type (agi, int, str)
2. Need to make only one of 3 craftable (does not matter which. maybe str) so the shop doesn't have 9 billion pair of treads showing
3. Each pair needs an ability that replaces itself with the next item in the series (str -> agi, agi -> int, int -> str)
In the end there will be: 
- greater_power_treads_1_i
- greater_power_treads_1_s
- greater_power_treads_1_a 
- greater_power_treads_2_i
- greater_power_treads_2_s
- greater_power_treads_2_a 
- greater_power_treads_3_i
- greater_power_treads_3_s
- greater_power_treads_3_a 
- greater_power_treads_4_i
- greater_power_treads_4_s
- greater_power_treads_4_a 
- greater_power_treads_5_i
- greater_power_treads_5_s
- greater_power_treads_5_a

**Comment by DoctorGester** [comment]
It's literally 1 item_lua with a GetTexture method

https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Lua_Abilities_and_Modifiers

Absolutely 0 need for multiple abilities.

**Comment by warpdragon** [comment]
Help wanted.... you seem like the ideal candidate gester

**Comment by chrisinajar** [comment]
Gester pls :1st_place_medal:
