### ISSUE TITLE
Question - will immediately close this after answered

### ISSUE THREAD

**Issue by CsharpNoobDude** [OpenAngelArena/oaa#1341]
Are there going to be bots for this game mod?
Because I have TERRIBLE internet connection, so I only can play with bots.
I have to watch Baumi's videos in 360 quality...

Anyway, I have seen the chat commands table, and there is an option for bots. 
Is there going to be an option available to play this with bots?

Because I think it would be awesome, if they would know how to play this gamemod, farm their items | teamfight in the duels | gank, etc. But it would ofc and undoubtedly be hard as fuck.

**Comment by Chronophylos** [comment]
RamonNZ added bots ~4 months ago.
You can add them with `-addbots` in a cheats enabled lobby.
And for questions you should checkout the OAA discord

**Comment by CsharpNoobDude** [comment]
@Chronophylos I don't have discord, is there a subreddit?
And could you please answer me, if the bots can actually play the gamemod in it's full potential?
(As I have described in the question above, can they farm their items? Farm the bosses they need? Pick up only the items they need, etc.?)

**Comment by CsharpNoobDude** [comment]
Also, I have just tried it, the game just simply crashed.

**Comment by Chronophylos** [comment]
We don't have a subreddit.
Well sort of, they we're made for an earlier version of OAA but they go and farm and kill other heroes.
They can buy Items but I don't know how intelligent they are.
Checkout RamonNZ's [doc about bots in OAA](https://github.com/OpenAngelArena/oaa/blob/master/game/scripts/vscripts/bots/docs/AAO%20Bot.txt)

**Comment by Chronophylos** [comment]
Yeah that's totally possible

**Comment by CsharpNoobDude** [comment]
@Chronophylos  Okay, no they actually work, but they only do the duels, and the rest of the time they look at the fountain. You can control them, but they will walk back as soon as you do not control them anymore.

Well, a shame. Do you know, if RamonNZ is going to improve  update the bots for the current version?
Thanks for answering my questions!

**Comment by Chronophylos** [comment]
He vanished shortly after he added V3 so no

**Comment by CsharpNoobDude** [comment]
Thanks anyway.
Well, then I have to wait a year, because then our town's internet is going to be better....
I appreciate it. 
Have a nice day!

**Comment by Chronophylos** [comment]
FeelsBadMan

**Comment by CsharpNoobDude** [comment]
@Chronophylos  Yeah, it kinda does, but thanks!
I hate seeing the videos baumi uploads, because I can't fucking play it myself.
Really FeelsBadMan.

So all I really do in dota is play against custom bots. Which is actually pretty fun. Can't wait for the OpenAI bot they showed at the International.

**Comment by Chronophylos** [comment]
My connection is really bad too, but not that bad.
Also I'm using LTE which is pretty good in comparison to what I'd have otherwise
