### ISSUE TITLE
Lion ulti is not working?

### ISSUE THREAD

**Issue by shem-sergey** [OpenAngelArena/oaa#1348]
Yesterday, on 22 August, I was playing Lion and his Ultimate was useless. It didn't do any damage and description didn't say anything about damage. All the animations, mana cost, cooldown worked as it should, only damage was missing. This bug was observed by me on the first 3 levels of ulti upgrade without and with Aghanims Scepter.
Not sure if this bug should be opened as an issue here, but looks like the best place.

**Comment by imaGecko** [comment]
Fixed in #1342

**Comment by Haganeko** [comment]
There is a separate repository for bug reports. In any case, it's apparently fixed.

**Comment by imaGecko** [comment]
personally wouldn't close the issue until the actual update is out, just letting people know that nobody needs to look into it anymore

**Comment by Haganeko** [comment]
I mostly closed it because it's in the wrong place.
