### ISSUE TITLE
Stoneskin needs LUA

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#137]
Stoneskin works mostly and has accurate tooltips
https://github.com/AngelArenaAllstars/oaa/compare/master...warpdragon:muh_features
need LUA in order to make it delay by 1.5 seconds on initial toggle (the armor buff should be delayed.) Maybe put in a cool animation.

**Comment by DigitalG** [comment]
Should it be like cast point or just a delay?

**Comment by warpdragon** [comment]
@spar36 get those icons togglin

**Comment by Haganeko** [comment]
Is this done? @warpdragon

**Comment by Chronophylos** [comment]
Yes according to my [changelog](https://github.com/OpenAngelArena/oaa/releases/tag/v0.1.0) it is.
