### ISSUE TITLE
Remember music player mute settings between songs

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#1375]
Currently the music player unmutes each time the song changes, we should fix that so that it remembers what state it was in

**Comment by ProstoSanja** [comment]
does it?
ill check it

**Comment by chrisinajar** [comment]
it might not on each song change, but it definitely does eventually

**Comment by ProstoSanja** [comment]
will solve that

**Comment by ProstoSanja** [comment]
Cant find this problem, if someone catches it, please tell me
