### ISSUE TITLE
Spell Lifesteal only works on item_octarine_core

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#138]
Spell Lifesteal doesn't work on any of our octarine items except original item_octarine_core.
https://github.com/AngelArenaAllstars/oaa/compare/master...warpdragon:muh_features
Also I had to drop all the satanic health/dmg and all the refresher mana regen and hp regen because i used:
"BaseClass"    "item_octarine_core"

Who wants to fix?

**Comment by Chronophylos** [comment]
@warpdragon  is this fixed?

**Comment by chrisinajar** [comment]
i fixed this a while ago
