### ISSUE TITLE
Translation Script Missed Some Stuff

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1383]
>>Abilities are being rewritten, items are changing -- but no new lines appear. Usually , when lines are changed , the previous tl'ed strings get removed. Now that doesn't happen. Blink, "alt" of upgrade cores 2-4, glimmer cape, vladimir, urn of shadows, urn of sorcery properties, dagon, eul's properties, mekansm, force staff -- untranslated ..Likely more.

-- Paraphrased from Translation-help on Sept 1

**Comment by chrisinajar** [comment]
should be fixed
