### ISSUE TITLE
If somebody DCs before the First duel The duel will just wait till its over not till the duel is finished when all died

### ISSUE THREAD

**Issue by Bigpadaa** [OpenAngelArena/oaa#1384]

**Comment by Bigpadaa** [comment]
https://puu.sh/xpvWE/b1eafb6917.jpg

**Comment by Bigpadaa** [comment]
And its continuing to the further on duels

**Comment by Bigpadaa** [comment]
https://puu.sh/xpwbI/ec97ad3725.jpg

**Comment by imaGecko** [comment]
This one will haunt us for the rest of our lives and never disappear ._.

**Comment by Haganeko** [comment]
Thank you for the report. This is a known bug, which has been reported before. Also, there is a separate repository for bug reports.

**Comment by Bigpadaa** [comment]
Wheres the link?

**Comment by chrisinajar** [comment]
Fixed in master, release blocked by #1408
