### ISSUE TITLE
When you go into the Duel when you even muted the Music the music will still start playing

### ISSUE THREAD

**Issue by Bigpadaa** [OpenAngelArena/oaa#1385]

**Comment by imaGecko** [comment]
https://github.com/OpenAngelArena/oaa/issues/1375

**Comment by ProstoSanja** [comment]
Oh, this may be the case. 
Because I tested it with just background songs. And they work perfectly. Thanks gecko

**Comment by imaGecko** [comment]
Sure, don't know what I did but sure
