### ISSUE TITLE
When using Refresher Core it shows no Particles for the enemys that you refreshes it

### ISSUE THREAD

**Issue by Bigpadaa** [OpenAngelArena/oaa#1386]
https://puu.sh/xpxwb/5e2ff026af.jpg

**Comment by Trildar** [comment]
Refresher Core didn't have any particles or sounds previously. They've since been added and should be visible to enemies as well. Can someone confirm?

**Comment by Zarnotox** [comment]
This seems to work now

![dota2_2017-11-28_13-25-58](https://user-images.githubusercontent.com/9365457/33319735-f96c8094-d43f-11e7-97a5-9258b5df83f6.jpg)

![dota2_2017-11-28_13-25-53](https://user-images.githubusercontent.com/9365457/33319742-ff1ef45e-d43f-11e7-8543-98bf121567d1.jpg)

**Comment by l34Um1** [comment]
Closed because fixed.
