### ISSUE TITLE
If a player with TP Boots last hits a creep that someone else has damaged, they get both last hit and assist bounty

### ISSUE THREAD

**Issue by MedicBear** [OpenAngelArena/oaa#1389]

**Comment by Haganeko** [comment]
Thank you for the report. Do note there is a separate repository for bug reports, however.

**Comment by MedicBear** [comment]
Sorry my bad, I just assumed that issues would be the right place to post it, could you link me the other repository?

**Comment by Haganeko** [comment]
https://github.com/OpenAngelArena/Bug-Reports
Sorry it's a bit of a mess.

**Comment by warpdragon** [comment]
githib.com/openangelarena/bug-reports

**Comment by chrisinajar** [comment]
No they don't.
