### ISSUE TITLE
Blink Blocker Bug - Bottom Right

### ISSUE THREAD

**Issue by spar36** [OpenAngelArena/oaa#141]
If you try to blink into the bottom right area of the map, you get pushed into the wall, where you are stuck until you can blink out of the wall. 

*** Did this on fork of master with AM lvl 1 blink.

![blink blockers](https://cloud.githubusercontent.com/assets/7379439/23915563/e0cebaee-08bf-11e7-9f73-eb843d5c9061.PNG)

**Comment by spar36** [comment]
I just tested it at the top left and the same bug exists there.  Also, the blink blockers don't actually apply to the walls, so you can blink on top of the walls and walk around.

**Comment by chrisinajar** [comment]
I think the duel arenas need to have their blink blockers replaced with simply unwalkable terrain, and then expand the duel radius to include that unwalkable terrain. That should at least bump you out to the tree line or something, where you'll probably also get stuck
