### ISSUE TITLE
need fix on manta style and 1v1

### ISSUE THREAD

**Issue by RamyALaa** [OpenAngelArena/oaa#1415]
I tried some items with my friend on 1v1, there is some issues :  
When i use Mantastyle , there is a display issue, then it cause some lag. 
More i used it, more i had lag. (same for my friend).

On 1v1, after few minutes, it begin to be very hard to kill monster and even more for the boss. 
the problem is that we can't upgrade differents items at level 2 and more, i succeed to upgrade only one item at level 4 and the others only level 1(maybe there is a wayto get more than 1 upgradecore 1/2/ and more, but i didn't find it) and then it's impossible to kill a new boss alone. 

I know that this workshop should be played by more than 2 players, but it's funny too on 1v1
Maybe add a 1v1 mode ?

I very liked this workshop, so i hope that you will fix these issues.
I will not hesitate to post every issue i'll find

EDIT :  it was a SHORT GAME mode
RK47

**Comment by chrisinajar** [comment]
i couldn't possible care less about how a 1v1 game plays out, sorry. it's just not what we're designing the game for.
