### ISSUE TITLE
Dagon does not interact with illusions the same as vanilla

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#1455]
Dagon was rewritten in Lua so that it could be given spell amp at the levels above vanilla, but it wasn't written to interact with illusions the same way as vanilla Dagon. Vanilla interaction is apparently to instantly kill illusions, except for if they have Shallow Grave, in which case it just brings the illusion to 1 HP.

**Comment by l34Um1** [comment]
This was recently fixed.
