### ISSUE TITLE
Being set to a constant 1 hp for the rest of the game.

### ISSUE THREAD

**Issue by 101necro** [OpenAngelArena/oaa#1462]
Causation: Getting hit by the last boss. When it seems to have copied a particular item. Not sure which item though.

It does not increase with regen or lifesteal and will be constantly set back to 1. It managed to happen to an entire team meaning that you could sit outside the fountain with a radiance and kill everyone continuously. Has a strange interaction with io, where it seems to make the target tethered to invincible if he doesn't die himself.
Quite a funny bug though,

**Comment by Haganeko** [comment]
Thank you for the report. That is a covfefe bug. We are aware of it and attempting to fix it.

**Comment by chrisinajar** [comment]
Where's the ticket for this bug?
