### ISSUE TITLE
Make Meteor Hammer do extra damage against bosses

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1472]
Currently meteor hammer has a seperate damage value for towers. Replace that with a seperate damage value for bosses.

**Comment by bell1020** [comment]
I'll start working on it immediately. My plan for implementation is to create a new Lua script that implements a thinker similar to that of how Lina's light strike array works but, with a check to determine if said enemy is boss to apply additional damage determined in item_meteor_hammer.

**Comment by l34Um1** [comment]
In the game.
