### ISSUE TITLE
Reduce creep bounty for TP/Mana Boots

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1473]
Create a value that decreases how much money you earn from the creep kill bounties. 

Example:

Creep is worth 100g

Mana Boots reduce by 50%

Player with Mana Boots gets 50g

Player without gets 100g

**Comment by Trildar** [comment]
Did you mean this for both Greater Travels and Arcanes, or just the one that gives passive GPM? And if it's the former, did you still want shared creep assist bounty?

**Comment by l34Um1** [comment]
Closed to reopen.
