### ISSUE TITLE
New PL lvl 25 talent(-5 CD on Doppelganger) is almost breaking the game.

### ISSUE THREAD

**Issue by Valiens** [OpenAngelArena/oaa#1478]
Because of this new PL talent  max lvl doppelganger has 1 sec CD without any additional CD from item and that creates about 30-40 units with invincibility, which not only makes it impossible to kill PL but also lags the game greatly.

**Comment by chrisinajar** [comment]
Remove the cooldown changes past level 4, make level 5 and 6 have cast range `800` and `1000`

**Comment by Haganeko** [comment]
Isn't Yzanas doing this? #1484
