### ISSUE TITLE
Starting items disappearing

### ISSUE THREAD

**Issue by Nortlen** [OpenAngelArena/oaa#1501]
So I played captains mode in OAA and after the picking screen I bought my items and then there was a pause. When the duel started I noticed that I don't have any items or gold except for a tp scroll. I suppose it is a conflict with the new starting scroll and OAA picking screen, since there isn't a strategy time. I think you buy your items and then at some point the game gives you your starting items, which is just a tp scroll and therefore it deletes your items. But I am not sure about that, also don't know when exactly my items disappeared.

**Comment by chrisinajar** [comment]
Did you have starting gold though? Also, did the game give you meepo?

**Comment by Nortlen** [comment]
Yes it was that game and no I had 0 gold. Also I am not sure whether wraith brand and tangos cost all of your gold.

**Comment by Nortlen** [comment]
But I wasn't the meepo

**Comment by carlosrpg** [comment]
Deprecated i guess? could we close this?
