### ISSUE TITLE
Broodmothers spiders won't tp in the duel

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#1516]

**Comment by Trildar** [comment]
There is a `CDOTA_BaseNPC_Hero:GetAdditionalOwnedUnits` function that might help with this. Given, it will probably need to be filtered for unwanted units.

**Comment by Zarnotox** [comment]
Tested: They do tp in, they won't tp out
https://streamable.com/2ltil

**Comment by carlosrpg** [comment]
https://github.com/OpenAngelArena/oaa/pull/1649
