### ISSUE TITLE
Remove treads recipe

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#152]
Right now the basic dota treads have a recipe added to them. we don't want to edit any of the base items from dota, so this should be removed.

**Comment by spar36** [comment]
@chrisinajar So you mean make it so that you just buy power treads instead of building them? ie. remove the recipe.

**Comment by chrisinajar** [comment]
your first sentence seems wrong but the second is correct. you still need to build them, but you build them like in normal dota. We're not change *any* base items *at all*. This is a change from base dota.

**Comment by RamonNZ** [comment]
This issue is bigger than just Power Treads. You will need to discuss with Warpdragon but somebody added base costs to Tranquils, Phase Boots and Tranquil Boots recipes from what I can see. Possibly other items, I don't know.

**Comment by Haganeko** [comment]
Items with recipes that cost 0 autocombine. On the other hand, at least in the cases of vanilla dagon and diffusal, the base recipe is used as a component of later versions of the item. If we have their recipes at 0, items which use their recipes as upgrade recipes will autocombine with cores, which is undesirable.

**Comment by spar36** [comment]
close this out
