### ISSUE TITLE
Add HotS style capture points after defeating a boss

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#1521]
Instead of rewarding the team who gets the last hit on a boss, require them to hold the arena for a short moment to capture it. This makes boss sniping much more reliably go in the favor of the team who can win a fight, instead of who gets lucky / axe cheese...

Should look like HotS camps or like a much larger color coordinate revive particle from the dota tombstones.

**Comment by l34Um1** [comment]
Here are some screenshots of how it works in HotS.

First you kill the camp (boss). Then the capture point unlocks. 

![2](https://user-images.githubusercontent.com/24982519/33502120-2bf41b7a-d6df-11e7-84d0-4359c82606d0.jpg)

If a hero enters the capture point the point starts being captured for the team. This process is halted if someone from the enemy team enters the capture point. If all heroes leave the capture point it resets to starting state. Capturing a point should take 10s. This is not sped up by having multiple heroes in the circle.

![unbenannt-4](https://user-images.githubusercontent.com/24982519/33502052-f76abe22-d6de-11e7-8a75-b19ae4b66738.jpg)

If a team manages to fully capture the point they get the reward. In our case cores.

![unbenannt-3](https://user-images.githubusercontent.com/24982519/33502250-aa6e5a10-d6df-11e7-9e94-3b08cdadd482.jpg)

**Comment by warpdragon** [comment]
lol i forgot baumi had started playing HOTS. Now it all adds up.

**Comment by warpdragon** [comment]
so we were thinking of using the rosh timer for this purpose. Basically it would be a dial that could turn right or left, and then once it reached the end of the dial it would be "captured". it's very similar to HOTS but not quite. I wonder if the little HOTS status bar would be easier?
![image](https://user-images.githubusercontent.com/13878439/33502586-b0800aba-d6ae-11e7-846a-7ee40edb2fd4.png)

**Comment by l34Um1** [comment]
Status Bar makes it much more obvious which team is capturing. Can we color the Roshan timer to indicate which team is capturing atm? If so then that's perfect.

**Comment by warpdragon** [comment]
theoretically

**Comment by Zarnotox** [comment]
Would this also be necessary if only one team damaged the boss?

On the one hand I think it would be annoying to capture it every time even without being contested.
On the other hand it might be harder for people to understand why you have to capture the point if it never showed up on earlier uncontested boss kills.

**Comment by l34Um1** [comment]
Yes it always shows up.

**Comment by warpdragon** [comment]
yeah i can probably create the particle and give it to chris with the proper control points. i was hoping to have him test it on the Roshan_timer.vpcf particle system but apparently that one's got some C++ black-magic attached that makes it spin so I'll just copy-pasta it and try and make it controllable.

**Comment by warpdragon** [comment]
I suspect the rotation is controlled by either CP:1 Range:1-120 or CP:11 Range:1-1000

**Comment by Trildar** [comment]
Not C++. The particle itself just has a rotation operator that unfortunately can't be controlled from a CP. Go to the clock hand particle, timer_hand_parent or something like that. If you disable the rotation operator and set the lock movement operator to lock rotation as well, then the hand can be rotated by changing the orientation of CP 1.

**Comment by warpdragon** [comment]
dude it's all good though. Carlos did the thing! 
![image](https://user-images.githubusercontent.com/13878439/33639982-0a43099e-d9fc-11e7-881f-475ee156c04b.png)

**Comment by carlosrpg** [comment]
refer to https://github.com/OpenAngelArena/oaa/pull/1543

**Comment by carlosrpg** [comment]
![3388d506-b3ce-48ed-9713-36df73265479](https://user-images.githubusercontent.com/759671/33739575-b998a938-db84-11e7-8e3b-fc44899709d4.gif)
I know this is not what we were talking about (using roshan clock) but we could use this.
this ControlPoints for Color and Radius of the middle sprite to show progress
