### ISSUE TITLE
Help each other with broken PRs

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1542]
The following PRs are essentially ready to merge but have stalled to to a small bug requiring specialized attention basically from the programmers:

1. #1525 Charger New Custom Model - Fails on the channeling animation. Works fine otherwise.
2. #1506 First implementation for SiltBreaker Ogre Tank Boss - Similar to the above.
3. #1499 Map update WIP - Everything is ready to merge except the Fountain Needs to be fixed.

**Comment by Haganeko** [comment]
#1525 is closed, #1506 is merged, and #1499 says READY. Closing.
