### ISSUE TITLE
Make Unstable Current respect cooldown

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#1544]
It doesn't.

**Comment by Trildar** [comment]
There's a need for a general KV parity update really. Apparently Valve updated more stuff with tooltip values and such. Hence why Travis is having a fit.

**Comment by chrisinajar** [comment]
Still? I really think this is fixed, and if it's not it's probably already detected by Travis. We should avoid opening tickets for stuff Travis already is forcing us to fix anyway.
