### ISSUE TITLE
**TRANSFORMATION** Item: Sonic

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1549]
# Sonic
## Explanation
Toggle. When toggled on your hero gains flying movement, increased movement speed and bonus vision. Your hero also gains negative status resistance, meaning anything that would usually be reduced by status resistance gets increased instead.
## Recipe
- ancient_janggo_2, upgrade_core_2, recipe
## Behavior
- Targetting: Self/Instant
- New Active Ability: Increased movement speed, flying movement, vision bonus, negative status resistance (status vulnerability)
![sonic](https://user-images.githubusercontent.com/13878439/33667930-46f8f82e-da6c-11e7-95d8-01e3ebf4cc0e.png)
- Notes: Breaks trees in small AoE at the end to prevent pathing errors.
- cooldown, movement speed bonus, negative status resistance, vision bonus

## KV
- speed_bonus, vision_bonus, negative_status_resist, janggo stats

**Comment by Haganeko** [comment]
When was this design debated?

**Comment by warpdragon** [comment]
it wasn't

**Comment by Haganeko** [comment]
Then just putting it up for implementation is bad form.

**Comment by warpdragon** [comment]
So it feeding 11 kills as Spectre in 15 minutes.

**Comment by Haganeko** [comment]
Irrelevant.

**Comment by Haganeko** [comment]
Irrelevant.

**Comment by deadshoes** [comment]
hello completely new to this, looked through the kv tutorials today and made an attempt at creating this item. I dont really know how to use the dota client to test this though.
[item_sonic_1.txt](https://github.com/OpenAngelArena/oaa/files/1857236/item_sonic_1.txt)

**Comment by Haganeko** [comment]
You need to look at the install instructions for how to test things. Also, the KV by itself will do nothing. You'll need a lua code as well.

**Comment by deadshoes** [comment]
my bad i thought i could avoid lua by making it a data driven item

**Comment by Haganeko** [comment]
You can, but I thought the toggle with a cooldown would be impossible to make datadriven.

**Comment by Yahnich** [comment]
don't use datadriven

**Comment by genious97** [comment]
Is anyone currently working on this issue, because if not I would be interested?

**Comment by zelding** [comment]
in progress at #2172

**Comment by mikibun** [comment]
@zelding Is this still being worked on?

**Comment by DarkoniusXNG** [comment]
This was implemented.
