### ISSUE TITLE
New Fountain Help

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1562]
Ok our fountain has never *really* done its job perfectly. The reason? The dota 2 fountain was designed (poorly) by valve to ALWAYS sit in the corner of maps. When you put your fountain somewhere besides the corner of a map, all of a sudden things like the locations of incoming teleports, Healing Aura range, and Location of the anti-camping weapon dont' really work the way you'd like them to. Fortunately we've already come up with a solution for the laser. But I want to take it a step further. I want to separate the laser and the regen into two separate units and control a custom regen aura so that it only effects units within the fountain.
I have already designed the fountain. There's a large tesla coil on the northern edge that kills enemy players with an arc of electricity (currently works 100%). The problem is, the stupid regen aura and teleport are bound to this unit (the tip of the coil is actually the unit dota_fountain). Here's a picture:
![new fountain](https://user-images.githubusercontent.com/13878439/33770074-5e92ac20-dbfa-11e7-85bb-8cd036a1bbd3.png)

Outlined below are the requirements:

#### npc/units/oaa_fountain.txt
- [ ] Is a building for the purposes of Town Portal
- [ ] Located in the exact middle of the start-area for Town Portal
- [ ] Has ability oaa_fountain

#### npc/abilities/oaa_fountain.txt
- [ ] Links to script file oaa_fountain.lua

#### vscripts/abilities/oaa_fountain.lua
- [ ] Applies regen modifier
- [ ] Modifier has entity reject based on IsTouching or similiar

#### npc/units/oaa_lazor.txt
- [ ] is not a building
- [ ] is the tip of the tesla coil
- [ ] Has ability oaa_lazor

#### npc/abilities/oaa_lazor.txt
- [ ] Links to script file oaa_lazor.lua

#### vscripts/abilities/oaa_lazor.lua
- [ ] Applies lazor
- [ ] Modifier has entity reject based on IsTouching or similiar

**PS. all the starting area stuff is in a single Prefab now in /structures.**

**Comment by warpdragon** [comment]
nope

**Comment by warpdragon** [comment]
feel free to poke around

**Comment by carlosrpg** [comment]
what need fixing?

**Comment by Haganeko** [comment]
Splitting the fountain regen from the fountain unit, so it can be moved around.

**Comment by mikibun** [comment]
Is this still being worked on, or has it been solved?

**Comment by warpdragon** [comment]
Um u can close this. Its old af. We decided to move in a different direction.
