### ISSUE TITLE
Boss aggro conditions

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#1573]
The new Siltbreaker bosses aggro on proximity rather than only after taking significant damage like most bosses. Probably want to change that if possible. Charger also aggros on proximity, but in his case, having a damage threshold would be impractical. Perhaps he should at least be changed to aggro on any damage?

**Comment by carlosrpg** [comment]
I already did it a few patches ago, can someone confirm it is ok now?

**Comment by carlosrpg** [comment]
Tested. Fixed.

**Comment by carlosrpg** [comment]
still waiting to be closed

**Comment by Haganeko** [comment]
So it's done?
