### ISSUE TITLE
Charger and Heartpiercer

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#1574]
Heartpiercer disables all of the Charger's armour, making it easy to right click him without having to bother with baiting him into pillars. So the armour needs to be replaced with some other method of damage mitigation.

**Comment by carlosrpg** [comment]
I think this boss actually need so resistance to armor reduction instead.

**Comment by chrisinajar** [comment]
It should use damage reduction. Basically armor on bosses is broken in OAA, there's 1 hero that removes base armor and another that removes added armor.
