### ISSUE TITLE
**TRANSFORMATION** Item: Healer

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1580]
# Healer (Transformation Item)
## Explanation
Toggle. When toggled on all healing coming from your hero is amplified but your attacks are turned off. The healing amplification scales.
## Behavior
- Toggle

## Recipe
- mekansm_1, upgrade_core_1, recipe

## Active Ability
- Can't attack. All-healing bonus (2x)

## Passive
- mekansm aura

## Key Values
-  CD, %heal_bonus, mekansm stats, mekansm aura

**Comment by DarkoniusXNG** [comment]
Added a similar effect to Ghost King Bar.
