### ISSUE TITLE
**TRANSFORMATION** Item: Merge

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1581]
# Merge (Transformation item)
## Explanation
Toggle. When toggled on your heroes Mana pool merges into its HP pool. This means the HP and Mana are simply added together and then considered HP. Same goes for Mana and HP regen, they are merged and then considered HP regeneration. For now I want to keep it as simple as this with no multipliers but I think it would be a good idea to have multipliers in the KVs anyway, so we can adjust it later. When you would use mana you now use HP instead. This uses a conversion factor, meaning that 100 Mana doesn't equal 100HP. This factor is also needed in the KV files. The transformation also turns of attacking.
## Behavior
- Toggle

## Recipe
- bloodstone_3, upgrade_core_3, recipe

## Active Ability
- Merge HP & Mana pool
- Mana costs deal dmg to caster
- Can't attack

## Passive
- bloodstone stats

## Key Values
- CD, conversion_factor, bloodstone stats

**Comment by Nortlen** [comment]
When you lose hp/mana does it drain your mana pool first or how is it supposed to work?

**Comment by l34Um1** [comment]
You don't have a mana pool anymore. Pretty sure this is clear in the description.

**Comment by Nortlen** [comment]
So we display it as having 0 mana and it adds the amout of mana to your hp, but how much mana will you have after you turn it off?

**Comment by l34Um1** [comment]
That's a good question and something I should have made clear in the issue.

As you merge it should save the current % of maximum Mana/HP you currently have. When you unmerge it will take those % values and redistribute them but also considering the % of merged HP compared to when you originally merged.

Example:
You have 100 HP and 100 Mana max.
You are 50 HP and 25 Mana. So 50% HP and 25% Mana. You merge. You end up with 75 merged HP. This is our baseline 100%. If I now heal to 150 HP and umerge I'm at 200% of my baseline. So if I unmerge I'll end up with 200% of the 50% HP and 25% Mana, meaning 100 HP and 50 Mana.
