### ISSUE TITLE
Item: Devastator

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1586]
# Devastator
## Explanation
Upgrade for Desolator. Active: Cast in a line, deals attack damage to all enemies hit and applies minus armor and a slow.
## Behavior
- Point Target

## Recipe
- Desolator, upgrade_core, recipe

## Active Ability
- Line projectile
- OnSpellhit_debuff()
  - movespeed reduction
  - armor reduction

## Passive
- Desolator stats, desolator passive

## Key Values
- CD, range, projectile_speed, dmg, armor_reduction_base, armor_reduction_active, movespeed_reduction, desolator stats, desolator passive

**Comment by Kage40k** [comment]
Gonna try working on this as my first contribution and my first actual piece of code =).

**Comment by adalessa** [comment]
Hi, I am starting with lua and I am giving a shot to this one. First question, should this be only an upgrade from the lvl 5 or is a complete different path from the first desolator ? 
The projectil I am guessing should be something like a mirana arrow that pierce enemies, correct ?

**Comment by Haganeko** [comment]
Should probably start as a tier two. That would mostly be a KV change, however, and shouldn't impact the lua itself too much.

**Comment by l34Um1** [comment]
Upgrades out of desolator 2. Projectile more like shockwave. Ideally red and different overall

**Comment by adalessa** [comment]
I use the line dragon slave as reference to make it work. I was able to apply the slow and minus armor on hit to all the enemies. Also I have been able to recreate the desolator pasive, now I am dealing with the armor reduction and I have a question. Should the armor reduction stack or the last one should be applied over the other one ?

**Comment by l34Um1** [comment]
The debuffs don't stack, the most powerful one applies.
