### ISSUE TITLE
Shadow Fiend, Viper, Underlord Tower Talent Rework

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1589]
# Shadow Fiend
Have his level 15 talent "Presence Aura Affects Building" instead apply double the minus armor to bosses.

# Underlord
Have his level 15 talent "25% Firestorm Building Damage" instead double the % burn effect against bosses.

# Viper
This was not addressed by Baumi in his notes, but I can see from the NPC files that it has not yet been addressed. Namely that his level 20 talent "Poison Attack Affects Buildings" should instead double the % effect against bosses also.

Don't forget to also update the tooltips.

**Comment by Raizenza** [comment]
i'm still learning but the bosses are treated like creature and creep ( charger , twin) if i put the talent to double the effect it also affect normal creep.

**Comment by Haganeko** [comment]
Needs ability reimplementation to double the damage when the enemy has "boss resistance"

**Comment by Yzanas** [comment]
Shadow Fiend aura already affects bosses
Doubling the % vs bosses would be way too hard for me to implement so I will be implementing placeholders for the three heroes (balance discussed with Chogex, Jay, Chris and Naeil)

**Comment by mikibun** [comment]
Is this being worked on or can this be closed?

**Comment by DarkoniusXNG** [comment]
Fixed long time ago, closing now.
