### ISSUE TITLE
Remove Reflex Core

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#1590]
# Remove Reflex Core

- Remove all Reflex Core requirements from existing item recipes
- Remove Reflex Core as Roshan item drop

**Comment by chrisinajar** [comment]
`Replace Reflex Core with Transformation Core as Roshan item drop`

that logic is really simple and can be found in `boss/ai.lua`

**Comment by warpdragon** [comment]
RIP
