### ISSUE TITLE
Charger spawns pillars forever and it breaks the game

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#1592]
Frostivus update broke charger AI somehow, I guess that means we can blame Vic.

![image](https://user-images.githubusercontent.com/422331/34027348-60c17bde-e19f-11e7-80d9-9ea016d703bc.png)

**Comment by carlosrpg** [comment]
It was probably fixed

**Comment by chrisinajar** [comment]
confirmed
