### ISSUE TITLE
OAA Bosses: Slime

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#1595]
# **Implementation**

- [x] Lore determined
- [ ] Boss coded
- [ ] Custom model added
- [ ] Custom particles added

# **Notable Stats**
Instead of dying, the boss splits into two smaller copies of itself, each with 75% of the original's HP. Each copy can also split itself, down to a total of three splits.

# **Abilities**
## Slam
Jumps into the air, towards a target location; a shadow (particle) appears below him to show where he is. Traveling speed should be slow enough (suggestion: 300) to allow for dodging.
Once the boss lands, all enemies on the area should take damage, be pushed out and slowed (suggestion: 80%).

## Split
Once the boss hits 0 HP, it becomes invulnerable and starts shaking violently. It then throws small, randomly sized projectiles at random points in the arena. Each one works exactly like a mini Slam. Suggested duration: five seconds. Then the Slime splits.

# **Balance**
Expose the following as configurable variables, either at the top of the lua file or in KV format

 * Base movement speed, hp, regen
 * Size of the Slime
 * Damage of each ability
* Slam speed
* Slam push distance and slow duration and %

**Comment by GymLeaderGiovanni** [comment]
Lore: Spawned from some ungodly corner in the pits of Hell this miserable amorphous blob writhes with malicious intent and its master sets it upon you.
