### ISSUE TITLE
OAA Bosses: Runaway

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#1597]
# **Implementation**

- [ ] Patterns chosen
- [x] Lore determined
- [ ] Boss coded
- [ ] Custom model added

# **Notable stats**

This boss moves around the boss arena in a pattern, shooting projectiles in its wake. Maybe it is moving backwards and shooting, maybe it is shooting from its back. Takes short stops when stunned, and at regular intervals.
No autoattack.
Anyone standing directly on the way gets trampled (damaged and stunned).

Phase 2 at 80% hp
Phase 3 at 40% hp

# **Phase 1:**

The boss moves in a simple pattern, like a circle or a figure eight. Stops should be frequent and long (suggestion: five seconds still, then ten moving).

# **Phase 2:**

More complex movement pattern (example below), chosen from a pool of two.
Shooting is faster. Stops are shorter (suggestion: three and a half seconds still, then eleven and a half moving).

# **Phase 3:**

Movement pattern is erratic, changing between a few patterns every now and then (can be comprised of all the earlier ones). Bullet hell. Stops should be even shorter (suggestion: two seconds still, then thirteen moving).

# **Balance**

Expose the following as configurable variables, either at the top of the lua file or in KV format

 * Base movement speed, hp, regen, armor etc. Movement speed is especially important.
 * Rate of fire at each phase.
 * Damage and duration of the trample stun.
 * Frequency and duration of stops at each phase.

**Comment by GymLeaderGiovanni** [comment]
Lore: This is Buer, President of Hell, who uses flowery rhetoric to beguile mortals. As He wheels about his lair Greek sophistry spews from his mouth, seeking mortal ears.

**Comment by l34Um1** [comment]
I want to close this. Don't think this design would work very well for the game.

**Comment by Haganeko** [comment]
D=
Muh baby.
