### ISSUE TITLE
Any upgrade that requires a boss item should also have a recipe

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#161]
We shouldn't have item upgrades be ambiguous, for example having an aghanim's and an octorine core and then trying to upgrade your power treads.

**Comment by spar36** [comment]
Starting on it now, will finish tomorrow, morning-ish. To confirm, Bosses drop these items:

item_combiner
item_farming_core
item_reflex_core
item_upgrade_core

**Comment by spar36** [comment]
close this out

**Comment by spar36** [comment]
and this one @chrisinajar
