### ISSUE TITLE
Duel spawn location bug

### ISSUE THREAD

**Issue by RamonNZ** [OpenAngelArena/oaa#163]
If you spawn into the bottom right duel zone, then are unlucky enough to spawn into the bottom left of that zone, the first one or two players spawning there get stuck in trees. Not much fun...

![bug location](https://cloud.githubusercontent.com/assets/25876203/24069730/d992c336-0c13-11e7-8001-a3ce477f004b.png)

**Comment by Chronophylos** [comment]
We could define a location for every hero.

**Comment by RamonNZ** [comment]
+ this:
https://cdn.discordapp.com/attachments/261459464689942529/292816267306336256/unknown.png

**Comment by RamonNZ** [comment]
I'm not 100% sure, but I haven't noticed a bad location spawn into the duels in a long time.

**Comment by Haganeko** [comment]
Close this?
