### ISSUE TITLE
Give TP Boots, Mana Boots and Tranquil Boots a downside

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1672]
Create a value that decreases how much money you earn from the creep kill bounties. Display the value in a colored warning text in the tooltip. Add the value into KV.

Example:

Creep is worth 100g

Mana Boots reduce by 50%

Player with Mana Boots gets 50g

Player without gets 100g

For clarification, this value goes on Boots of Travel, Mana Boots, Guardian Grieves and Tranquil Boots from the moment the farming core is infused.

**Comment by Haganeko** [comment]
What about the TP sharing?

**Comment by l34Um1** [comment]
I don't think we need to give TP boots the "split among everybody with TP boots" and "reduced creep gold bounty" but I do think if we only give them the first everybody will only buy them again. I think that OTA will buy TP boots on all heroes with inbuild farming abilities and double dib on farm as much as possible. Even with the reduced bounty per boot.
It's also cleaner if they all share the reduced creep bounty thing, we can have the same orange warning text on all of them making it more beginner friendly and I dont think people will want to reduce their gold bounty on more than 2 or 3 heroes anyway.

**Comment by Trildar** [comment]
Not really that important, but might as well ask. Should the bounty be rounded down, up, or to nearest (which would effectively be round up for 50%)?

**Comment by l34Um1** [comment]
Whichever is the easiest. If equal, round down.

**Comment by Zarnotox** [comment]
Somebody working on this? If not I have some questions:

- @l34Um1 in a stream you said it would be okay if mana boots only reduced creep gold by 50%, is that still the case or should multiple mana boots share gold between each other?
- We could reduce tp boots "creep gold" and add a small-medium gold reward if you tp to a hero based on distance (maxing out on base<->middle of map), this might bring up some more interesting gameplay too.

**Comment by Trildar** [comment]
I am working on it. Actually have it pretty much done, but have been looking into alternative methods and also haven't gotten much time to organise it. I basically made creep kill gold handling custom, so there's a fair number of changes involved.

**Comment by l34Um1** [comment]
No gold sharing, only the creep gold reduction. 

That is a balance change. While the idea is cool, I don't want to do multiple balance changes at once. It makes it difficult to tell the impact of the individual changes.

**Comment by Zarnotox** [comment]
Okay then I might take a look at some transformation items

**Comment by Trildar** [comment]
Implemented in #1748.
