### ISSUE TITLE
Change boss resistance passive to also make the boss stun immune

### ISSUE THREAD

**Issue by carlosrpg** [OpenAngelArena/oaa#1692]
I was talking to baumi and we agree bash is op against bosses right now, the optimal strategy is just hit the boss and hope a bash comes out before the boss abilities.

The proposed design is :
Once the boss is stunned this ability will purge the current stun and make the boss stun imunne for 5 seconds, this modifier then goes in cooldown for 7 seconds

The immune time and cooldown must be set on KV file to allow better balance later on.

**Comment by Haganeko** [comment]
Is this in

**Comment by mikibun** [comment]
Is this in/is someone working on this, or can this be closed?

**Comment by AbitTheGray** [comment]
I have it ready. Gonna PR in 24 hours if it is still wanted.

Checks (and removes) only `modifier_bashed`.

**Comment by carlosrpg** [comment]
Plz don't this ticket should be closed.
We use Siltbreaker protection for preventing stuns, not all bosses have it
