### ISSUE TITLE
Share farming cave xp/gold to the entire team + implement comeback factor

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1698]
Share all experience and gold earned in the cave to the whole team, no matter how many heroes are in the cave or how many actually got last hits. Gold or experience earned this way can't be modified in any way. Not by hand of Midas, bot by TP boots, not by tranquils, etc.

To go along with this the cave needs a strong comeback factor. The do and gold earned is increased for the team with the lower total xp and gold networth. @Haganeko

**Comment by Haganeko** [comment]
Whoever goes to implement this, I have your factor. Well, #1249 has it too but.

**Comment by l34Um1** [comment]
In the game
