### ISSUE TITLE
Blood mage bug

### ISSUE THREAD

**Issue by Nortlen** [OpenAngelArena/oaa#1701]
I was testing blood mage in OAA with Huskar, and I was taking damage when I attacked something, even though I didn't have burning spear active. These were my items: Regeneration Crystal, Silver Edge, Shiva's Guard, Treads, Blood Mage
I also took the lifesteal talent, no idea whether that is important.

**Comment by Nortlen** [comment]
Ignore what I said above.
The I was taking damage from the power treads cleave. I don't know whether the cleave is affected by spell amp, but it shouldn't be, since cleave in normal Dota isn't.

**Comment by Derk00** [comment]
In that case the issue can be closed

**Comment by Nortlen** [comment]
Should I make a new issue with it then?

**Comment by Derk00** [comment]
I don’t know if it is intentional that cleave from power treads is affected by spell amp

**Comment by OTAJumperjay** [comment]
Cleave, psiblades and lunar glaves are all affected by spell amp even in regular doto
