### ISSUE TITLE
Blood Mage-Cleave Bug

### ISSUE THREAD

**Issue by Nortlen** [OpenAngelArena/oaa#1702]
You take damage from cleave when using Blood Mage. Tested it with Sven and Power Treads

**Comment by Derk00** [comment]
Did you test if it increased the cleave damage?

**Comment by Nortlen** [comment]
It doesn't.

**Comment by Nortlen** [comment]
But you still take the damage.

**Comment by Haganeko** [comment]
This is normal. Also, there is a separate repository for bug reports.
