### ISSUE TITLE
Items are deleted if you die while the aura is being refreshed

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#1715]
and it sucks

**Comment by carlosrpg** [comment]
wait, what? you mean while it is being upgraded?

**Comment by OTAJumperjay** [comment]
exactly! the item shortly disappears to reapply the aura and if you die in that moment you're items are gone

**Comment by Derk00** [comment]
Just tested it myself and it just straight up dissappeared

**Comment by Derk00** [comment]
Could a deathcheck just before the item is returned help fix this?

**Comment by Yzanas** [comment]
Persumably fixed in #1717 can this be tested?
