### ISSUE TITLE
Make unit files match their respective ability kv values

### ISSUE THREAD

**Issue by imaGecko** [OpenAngelArena/oaa#1739]
Example:
Eidolons tooltip hp for level 6 is 2480, actual hp is 420

**Comment by samuraiJak** [comment]
So you want the actual HP to be 2480 right? New to the game, just confirming. Please bear with me.

**Comment by l34Um1** [comment]
yes

**Comment by samuraiJak** [comment]
okay so I noticed that the damage values Eidolons lvl 5 and 6 are also off, has the tooltip not been updated or have the actual values not been passed on?

**Comment by CptBabineaux** [comment]
I believe this issue is fixed, why is it still open?

**Comment by imaGecko** [comment]
Did anyone actually check all unit files?
The example that I gave was fixed and Yzanas noticing Shadow Shaman Wards

**Comment by CptBabineaux** [comment]
Yep i checked files and tested in game, it all seems good to me but there is still a chance we both missed something.

**Comment by imaGecko** [comment]
Lycan Wolves don't match, Warlock Golems don't match

**Comment by CptBabineaux** [comment]
i will go through it all tomorrow

**Comment by CptBabineaux** [comment]
I have fixed the values, i have the files. how do i do this pull request stuff?

**Comment by CptBabineaux** [comment]
[lycan_summon_wolves.txt](https://github.com/OpenAngelArena/oaa/files/1652260/lycan_summon_wolves.txt)
[warlock_rain_of_chaos.txt](https://github.com/OpenAngelArena/oaa/files/1652261/warlock_rain_of_chaos.txt)

**Comment by Haganeko** [comment]
Well, you follow the instructions on github for noobs.
Do you have a fork, and an updated clone of it?

**Comment by CptBabineaux** [comment]
yeh i did all the instructions and stuff

**Comment by Haganeko** [comment]
Okay. Are you in the discord? Would be easier to talk there. Anyways, are you using CLI or GUI? I'm only familiar with CLI

**Comment by CptBabineaux** [comment]
i have both, im in the discord aswell

**Comment by CptBabineaux** [comment]
I believe this can be closed, unless i have missed some files. doubtfull tho i went through them all.

**Comment by imaGecko** [comment]
#1803
