### ISSUE TITLE
Erroneous 22 maps in Arcade view

### ISSUE THREAD

**Issue by wtogami** [OpenAngelArena/oaa#174]
![oaa](https://cloud.githubusercontent.com/assets/93665/24076649/6980e188-0bf3-11e7-926c-83cc70a6b30a.png)
OAA currently erroneously shows 22 maps while only the bottom most is desired.

A few other modes like *Last Hit Exercises* exhibit this same buggy behavior.  Meanwhile many other maps like *Angel Arena Reborn* work as expected.

**Comment by ProstoSanja** [comment]
What is the correct ma, aaa or blackmap??

**Comment by ProstoSanja** [comment]
#187

**Comment by ProstoSanja** [comment]
merged, can be closed
