### ISSUE TITLE
BUG: Ancient at 0 hp

### ISSUE THREAD

**Issue by eevee911** [OpenAngelArena/oaa#1741]
- Untargettable
- Unkillable by neither team
![20180111151025_1](https://user-images.githubusercontent.com/24459911/34830804-4cb74f0a-f6e5-11e7-8208-3c0ebf4c1293.jpg)
end

**Comment by Haganeko** [comment]
Thank you for the report. Do note, however, that there is a separate repository for bug reports, and that this is a known bug. Reproduction scenario and other such details would be useful.

**Comment by imaGecko** [comment]
Difference between issue on bug report and issue on here:
Bug Reports: a is supposed to happen, b happens instead, some observations to help find the cause
Here: x is 100% the cause, go fix it
