### ISSUE TITLE
Make our Workshop Page not shit

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1752]
So our workshop page is really awful, I think we can all agree on that. Here are some ideas for what we should do to fix that. Please also leave some ideas or thoughts on how you think we could do it.

- [x] Make a 5 minute introduction video (I'll do that when I find the time)

- [x] Proper and nice screenshots

- [x] Better description

**Comment by l34Um1** [comment]
Here is a link to some screenshots, we need more and better ones though. https://imgur.com/a/h8q8H

**Comment by zelding** [comment]
You could also add some edited pictures, that explain some key concepts/changes, maybe even a list of new items that don't exists in the base game

**Comment by l34Um1** [comment]
More screenshots: https://imgur.com/a/vZm8k

**Comment by l34Um1** [comment]
https://pbs.twimg.com/media/DBUMyV2VYAAVAQa.jpg

**Comment by l34Um1** [comment]
https://imgur.com/a/BqoFU

**Comment by l34Um1** [comment]
https://imgur.com/q4z6aDm

**Comment by l34Um1** [comment]
Done.

**Comment by zelding** [comment]
The last and 4th from behind pictures are very low resolution
