### ISSUE TITLE
Cave Rune: Hasted Double Damage

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1768]
See #1767 for explanation on how the Cave Runes work.

Functions just as the regular Dota Haste Rune and Double Damage Rune combined.

Maximum Movement Speed
Unslowable
100% Increased Base Damage
Duration: 30 seconds

Expose all of these as KVs.

**Comment by ThatMusicWriter** [comment]
Working on it now. do you want it to be stackable so one person can carry more than one into a fight, or should it stick to just one per item slot?

**Comment by ThatMusicWriter** [comment]
#1795

**Comment by heinekeg** [comment]
Is anyone working/still working on this? Saw that [ThatMusicWriter's PR](https://github.com/OpenAngelArena/oaa/pull/1800) is closed, and wanted work on this
