### ISSUE TITLE
Some form of tribute to Pimp my Peon

### ISSUE THREAD

**Issue by Sythrus** [OpenAngelArena/oaa#1772]
So I'm seeing several possible things that we could add for this purpose.
1. A new boss. 
2. New item.
3. A tombstone that when clicked on says something about Pimp my Peon sacrificing itself for OAA.
For the Tombstone could you use the siltbreaker culinary pages that were lying around everywhere?

**Comment by Sythrus** [comment]
sorry if i did something wrong, this is literally my first time using Github

**Comment by Haganeko** [comment]
There is a separate repository for suggestions. You will find it under OpenAngelArena/suggestions.
This is for stuff we've already decided to actually do.
