### ISSUE TITLE
Lone Druid Midas XP

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#1774]
Currently, OAA's Midas implementation doesn't ever grant XP to Lone Druid if used on his bear. Vanilla Dota seems to have a weird rule of only granting the XP if the the hero is within XP range (1500 units) of the unit that is Midas'd.

OAA Midas should be changed to either match vanilla Dota behaviour, or possibly just always grant the hero the XP without range restriction.

**Comment by DarkoniusXNG** [comment]
Fixed several months ago. Closing now.
