### ISSUE TITLE
Stretch Goal: Add Meepo

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1783]

**Comment by Aknhide** [comment]
Well. I randomed Meepo today. And... It doesn't work. Not in the game. It doesn't work FOR the game. I admit, I ragequited and i'm sorry for that. But Meepo is just useless, when game escalates more than normal dota game. He benefit only from stat items, and does it wery poorly. Yes, he's good at killing bosses, he's good at clearing the cave, but he sucks against heroes when it goes beyond T1 cores. No matter how good are the items on the main Meepo, clones are just trash. Add the fact that you cant micro them cuz they are teleporting to the main one all the time. Also clones dont "refresh" in and out of the duel, so you can enter it with low hp, or after it ended you can immediately die from poison. This can be fixed, but the clones... You'll have to change hero design for Meepo to work and not become OP.

I'm sorry for ragequitting. But.... maybe you'll figure something out to make it work.
GL HF

**Comment by warpdragon** [comment]
This has nothing to do with the thread. Meepo has been added. Closed.
