### ISSUE TITLE
Stretch Goal: 10v10 Map

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1785]

**Comment by carlosrpg** [comment]
Can we close? From now one the remain work should be done in separated issues I think

**Comment by Haganeko** [comment]
Agreed.

**Comment by Trildar** [comment]
Seconded (Thirded?). What are the main things left anyway? Proper Duel handling for 10v10? Anything else?

**Comment by Haganeko** [comment]
I think warp is still experimenting with the map, and I might need to look at creep distribution depending on how it ends up. But those are details.
