### ISSUE TITLE
OAA Website

### ISSUE THREAD

**Issue by Gumnutt** [OpenAngelArena/oaa#1789]
Hey guys,
I was wondering if it would be worth while creating an oaa website. For the most par I feel I would be helpful for the tournaments etc as seen in this [video](https://www.youtube.com/watch?v=P6EwTIXwI7A). I think that we could get this up quickly if you think this would be worth the time I'm happy to help out or start building and see where we end up

Gumnut

**Comment by CptBabineaux** [comment]
As I understand it there is already a site being planned. Check out the oaa development discord, some people were talking about it earlier

**Comment by Gumnutt** [comment]
Do you have a link to the discord?

**Comment by CptBabineaux** [comment]
As far as I understand links are not allowed to be shared, go to the instructions on github and follow them. They will lead you to it.

**Comment by Gumnutt** [comment]
awesome thankyou
