### ISSUE TITLE
Item Particles: Enrage Crystal

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1811]
A quick red burst effect, similar to abaddons shield being popped

**Comment by carlosrpg** [comment]
Can we close this?

**Comment by l34Um1** [comment]
Oh they are in? They don't work do they?

**Comment by carlosrpg** [comment]
This was working on previous versions. It is broken again now.
Fuck those precaches

**Comment by carlosrpg** [comment]
It is in the game
