### ISSUE TITLE
Item Particles: Reflection Shard

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1814]
Yellow outline around the hero while active. When something gets reflected it has a small particle explosion before dissapearing

**Comment by carlosrpg** [comment]
Outline models on particles are usually very difficult, and since the particle is the same for multiple heroes this just make things worse. I recommend against it.

**Comment by l34Um1** [comment]
I actually like the lotus orb bubble, I would just like it recolored. White would be great.

**Comment by carlosrpg** [comment]
https://github.com/OpenAngelArena/oaa/pull/1947

**Comment by Haganeko** [comment]
To be closed pending confirmation it works.

**Comment by carlosrpg** [comment]
Sure, not in the game yet

**Comment by carlosrpg** [comment]
It is in the game

**Comment by imaGecko** [comment]
#1947
