### ISSUE TITLE
Item Particles: Vampire

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1817]
When activated a red circle appears around the heroes feet, it moves quickly, expanding and contracting. In an ideal world, the attacks of the hero lead to a visual effects similar to the Lifesteal effect from heroes of newerth. Red lines that come from the hero hit and get absorbed by the hero attacking. https://youtu.be/OY432TRpcjY?t=2m40s

**Comment by Haganeko** [comment]
#1835
