### ISSUE TITLE
Aeon disk doesn't have recipe definition

### ISSUE THREAD

**Issue by zelding** [OpenAngelArena/oaa#1822]
This is missing:

https://github.com/OpenAngelArena/oaa/blob/49117209af377d0d5ca522675e78a872b17c698d/game/scripts/npc/items/item_aeon_disk.txt#L1

this:
https://github.com/dotabuff/d2vpkr/blob/dcb4e47b9574d0789ecc855f69b68b5832d8a176/dota/scripts/npc/items.txt#L6954

**Comment by imaGecko** [comment]
Technically it's not missing, for vanilla items you only need to include what you are overwriting.
Should still add it for completions sake

**Comment by zelding** [comment]
I've started working on the item-site again, and it is throwing off my things :D

**Comment by imaGecko** [comment]
can even disregard what I said, I'm gonna need the recipe to add the recipe icon with the small dots
which also happened to be next on my list of things to clean up
