### ISSUE TITLE
Far Sight: Change so that only one Far Sight effect can be active from the same hero

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1830]
Current situation:

Tinker buys Far Sight.
Spams Far Sight all over the map with rearm, giving his team absolute vision and map control since you can have multiple Far Sights active at once. 

Should be changed to:
When Tinker tries to casts the second Far Sight it doesn't work and gives an error message until the previous duration fully ended.

**Comment by Haganeko** [comment]
That's not the best fix - he can still check everywhere. Why not just make it non-rearmable?

**Comment by l34Um1** [comment]
He can check but he can't provide unlimited vision which is the main issue. Let heroes be strong.

**Comment by Chogex** [comment]
I don't think that this is going to be good enough of a nerf
for far sight + rearm
since the main thing you do with it is check every boss and go fight the enemy team that's behind and then fight them
making it so that you can't catch up

**Comment by l34Um1** [comment]
I disagree. You guys were just in a game where you lost to it, I spectated it. This should be enough of a nerf. With 2 Far Sights + Scan you can very safely guess enemy location with any team anyway.

**Comment by Haganeko** [comment]
In this case you only need one and there is no cooldown, though?

**Comment by l34Um1** [comment]
Yes but my point is that you don't need Tinker to know enemy location.

**Comment by Chogex** [comment]
Yes multiple far sights do give a ton of map awareness. But even having 5 of them is not enough to have constant vision over all bosses. Sure, you can deflect a bunch of boss attempts with a few far sights, but then they go on cooldown and then the enemy team would normally have the opportunity to go for some different boss. Tinker can check every boss pit on the map on his own without a cooldown. However with that said, your suggested nerf will definitely make this weaker, but to see if it's enough of a nerf you'd have to play a game or two.

**Comment by carlosrpg** [comment]
"Should be changed to:
When Tinker casts the second Far Sight it should replace the previous effect. He can always cast a new one as long as it's off cooldown but they don't overlap."

This is a minor nerf. Tinker will still be able to track all locations with rearm but this will make the vision limited to one region at the time.

This most harmfull thing would be to have the whole map with true sight, tinker can do that now for almost free, being a nerf to invis heroes.

late game most heroes are 6 sloted so not needing a inventory slot for detection is huge!

**Comment by Haganeko** [comment]
Well, I guess this does prevent him from spamming the map then backpacking the thing

**Comment by Melongod** [comment]
I think it shouldn't be able to be rearmed at all, but then have the overall cd scale from 90/75/60/45 to 60/50/40/30. but maybe the invis-detection should be changed?

**Comment by Melongod** [comment]
the benefit to that is that if you have a refresher core you can have a 10 second down time on farsight, but only having vision in that specific place for those 10 seconds of up time.

**Comment by Haganeko** [comment]
I think the invis detection is part of the point of the item.

**Comment by l34Um1** [comment]
What about this. A new Far Sight effect can't be cast until the previous duration fully ended.

**Comment by Haganeko** [comment]
That works. Make it the Chakram of items.

**Comment by imaGecko** [comment]
This just nerfs farsight with refresher while still being absurdly strong on tinker for keeping vision up at all times. Refreshing farsight isn't a problem, tinker refreshing farsight is a problem. Thus justadding it to the rearm list would be a better and more straightforward solution
