### ISSUE TITLE
Underlord Ultimate: Make it not castable on and from the fountain

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1831]
Basically stop Underlord from teleporting enemies into his teams fountain.

**Comment by imaGecko** [comment]
Could also just stop underlord teleporting enemies altogether. An ability teleporting an entire team to any spot on the map is already strong without swapping enemies away from that position

**Comment by SquawkyArctangent** [comment]
alternative one of the solutions i never got around to implementing was just to make it so that the tp would fail for a person if they'd end up in the enemy fountain

'cept the caster so that anyone who tried to tp their team into the enemy well would just end up only tossing themselves into it

**Comment by carlosrpg** [comment]
Is this fixed? I think it was, not sure

**Comment by Haganeko** [comment]
Don't think so.

**Comment by mikibun** [comment]
@Haganeko @carlosrpg Has this been fixed yet?

**Comment by Haganeko** [comment]
I believe it hasn't. Might actually want to throw a bounty at it.
