### ISSUE TITLE
Make Scan not trigger on Bosses

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1832]
Currently, if you Scan a location with a Boss then the Scan shows red, meaning there is an enemy hero there. That shouldn't happen, Scan should only show as red when there actually is a hero.

**Comment by Trildar** [comment]
Oof. Dunno if this is fixable. The vanilla Scan portion is not currently custom, and I'm not sure if it's even recreatable. And vanilla Scan presumably acts like this because the bosses are all creep heroes, which can't be changed.

**Comment by Trildar** [comment]
Actually, probably not that hard to do, it'll just look kinda crappy cause the animation for scan on the minimap would reset every time it went from red to normal or back. Dunno if there's a way to actually make it look nice.
