### ISSUE TITLE
Pause Boss HP regeneration during duels

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1833]

**Comment by Melongod** [comment]
Too big of a change to have before the tournament.
All for this, but after the tournament.

**Comment by mikibun** [comment]
@l34Um1 has this been fixed?

**Comment by Booty-Smasher** [comment]
Cast break on all of the players, creeps, and bosses once the Duel begins. If a player is in the Duel then purge all buffs and debuffs for the players in it. Edit the bosses purge of they have ome which could remove the break.

**Comment by Trildar** [comment]
Break would have absolutely no effect the way things are right now. Break affects passive abilities and not items. Bosses get fast regen from a Heart in their inventory.

**Comment by Booty-Smasher** [comment]
I meant mute, but I didnt think about that mute doesn't affect passive items like a heart or skadi

**Comment by Booty-Smasher** [comment]
Create an item that stops passive items, like an upgraded scythe of vice, and cast it on the bosses once the duel begins.

**Comment by SquawkyArctangent** [comment]
Not only is that the most indirect way of handling this issue, but it also involves _recoding every single passive item effect from scratch, as the vanilla items aren't programmed for a context where such an effect exists._

**Comment by Booty-Smasher** [comment]
It wouls be a neat item for OAA that most gamemodes don't have, which Baumi loves topping other game modes. I k ow it isn't the easiest or simplist fix, but it is still a fix which no one else seems to have any "Suggestions"

**Comment by chrisinajar** [comment]
it'd be easier to just store the HP values with the savestate the game runes during duel start/stop. that or just remove the hearts during duels. either works.

**Comment by DimasDSF** [comment]
Would a modifier with `MODIFIER_PROPERTY_DISABLE_HEALING` not work with bosses?

**Comment by AbitTheGray** [comment]
Or do not give them hearth but different boss-only item which provides regeneration and is disabled while duels are active?
It would also prevent the boss from taking any damage while duels are active (in one game, Pudge killed twins by being out of duel while having Rot active).

**Comment by DarkoniusXNG** [comment]
Fixed long time ago.
