### ISSUE TITLE
Discussion: New Item Ideas

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1836]
- Linkens Upgrade: Basically a large Raindrop. Every X seconds blocks Y magic damage. Has no charges.

- Shivas Guard Upgrade: Active: Select AOE. All enemies in the AOE have their movement speed slightly slowed and their attack speed greatly slowed for ~10 seconds.

- Pipe upgrade with charges that grants magic resistance per charge. Each time the hero takes magic damage a charge is used, reducing the magic resistance total.

- Deso upgrade with a stacking minus armor debuff that starts out very low.

- Abyssal Upgrade: Bogduggs Cudgel: https://dota2.gamepedia.com/Siltbreaker/Bogdugg%27s_Cudgel

- Generally we actually need more interesting right click stuff.

- Blink boots as a possible use for the farming core

- item that breaks

**Comment by l34Um1** [comment]
- Allows your spell amp to amplify attack damage

**Comment by haxel96** [comment]
Are there any particular hero archetypes that lack item choices and need brainstorming?

**Comment by l34Um1** [comment]
Physical dps

**Comment by carlosrpg** [comment]
We have options for dps. what I feel is lacking is worth mobility options for melee right click.
blink boot is nice but will not be viable until we stop having boots that generate GPM I think.

 - I would like a upgrade path for desolator + reflect core where you could get stacks (with duration not too short) for each sucessful reflect and those stacks would make you deal more damage.

- echo saber needs a upgrade path. Ideally it would upgrade into a pangolier Q increasing is range and number of attacks (it would become a good late mobility tool)

**Comment by l34Um1** [comment]
The options for DPS is always the exact same stuff. We need more.

**Comment by haxel96** [comment]
What about some blade that, on attack, gives you a stacking (up to 3* stacks) movement speed buff for a couple of seconds, possibly attack speed too.

**Comment by arrowpack** [comment]
an item that gives u atk dmg/speed for every stack, stacks are obtained for every debuff u have on u, this also counters aura stacking

**Comment by TTHGreenLight** [comment]
A Mjolnir that has its active removed but has an additional passive, which: When you move you gain charges. At 100 charges your next attack will do a concentrated electric shock. Dealing a lot more magic (at least more than the regular proc) but only chains to a few targets, and your charges go to 0. When this occurs you also get a massive increase in move speed but only for a few seconds. Upgrading this increases move speed duration and shock damage?

**Comment by Haganeko** [comment]
All of you, including @l34Um1, do know that we have a separate repository for suggestions?

**Comment by zelding** [comment]
I saw a passive in a workshop for Isaac which might be interesting as a rightclick item, it sewed together enemies and restricted their movement. In terms of DoTA, I would imagine it like this:

Whenever you attack an enemy that has an other enemy/neutral behind it  they get sewed together for a while and they can not go farther away from eachother than X units; or it will break after a distance and apply something to both; or they behave entangled similarly to LOD "train" skill that makes you follow an other hero and unable to move.
