### ISSUE TITLE
Captain's Mode and shop timers

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#1846]
Since the game time still proceeds during picking, Wards and Tome tend to be in stock or much closer to being in stock than they should be, and more importantly, it's inconsistent between games. Not sure how fixable this is.

**Comment by Haganeko** [comment]
Can the timer be set? Or at least jumped forward to a specific time?

**Comment by mikibun** [comment]
Has this been fixed/solved? @Haganeko @Trildar

**Comment by Haganeko** [comment]
I don't think it has.

**Comment by DerpySoccerBall** [comment]
this still needs to be fixed
