### ISSUE TITLE
Always start the old Reflex items at their max level ability

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1849]
Currently some of the old Reflex items start with their early level abilities. This should be changed so that they are always at their old max level.

Example: 

Enrage Crystal starts with "Purges the first debuff applied to you".
Then at next upgrade gets "Hard Dispel on yourself".
And then with the last level "Hard Dispel on yourself. Can be used while stunned".

That last level should be the base level. We'll just scale stats and cooldowns and such.

This applies to the following items:

Enrage Crystal. Reduction Orb. Reflection Shard.

**Comment by ThatMusicWriter** [comment]
#1855
