### ISSUE TITLE
Fix Siltbreaker Boss Aggro

### ISSUE THREAD

**Issue by imaGecko** [OpenAngelArena/oaa#1860]
When a siltbreaker boss deaggros they start moving towards their spawnpoint, if you go back into range before they have fully returned they'll reaggro on the spot unlike e.g. shielder who returns to spawn before reaggro
The chase distance is also too high, being able to drag a boss through multiple pits

This makes dropping aggro rather difficult especially if your target is anywhere within the area

Furthermore the small ogres aggro whenthe big ogre is attacked. This can aggro ogres from the adjacent pits if multiple ogres happened to spawn next to each other.

**Comment by Haganeko** [comment]
They also aggro on any damage instead of using the same threshold as other bosses.
