### ISSUE TITLE
Create custom end screen to show scores and Bottlepass unlocks (€30 Bounty)

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#1864]
Create a custom end screen replacing the existing one which shows a basic scoreboard of all players. The scoreboard should match the dota style and include all their standard information. The scoreboard should also include:
 * MMR change (`+6` or `-11`, for example)
 * Bottlepass xp change
 * Bottlepass current level, with an effect upon leveling up

The endgame screen should also support optionally showing a *new Bottlepass unlock* UI either over the scoreboard or another place you think looks better. This UI should have space for a title, an image, and a short description.

The lua side component which feeds the data to the panorama element should have a place for the mmr, xp, and item metadata field, however don't worry about populating it right away. Once everything else is working I will edit this in to the pull request.

**Comment by chrisinajar** [comment]
This ticket now has a €30 bounty on it. Anyone able to close this ticket with a completed pull request will receive the bounty via paypal once it's merged into the game.

Since this piece involves art, but sure to post early screenshots ASAP so that we can give feedback early so you can get your bounty faster.

**Comment by RodneyMcKay** [comment]
Alright i'm on it! I did it for imba will be done in few hours, beginning now.
