### ISSUE TITLE
Give all Bosses true sight

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1868]
This needs to include seeing through Smoke.

**Comment by CptBabineaux** [comment]
Could just give them a gem right

**Comment by Haganeko** [comment]
Or a true sight ability.

**Comment by Chogex** [comment]
regular true sight doesn't detect through smoke

**Comment by imaGecko** [comment]
Bosses could break smoke, on a shorter range than heroes perhaps
