### ISSUE TITLE
Only spawn Bosses after 3 minutes into the game

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1869]
Currently Bosses are always on the map. Spawn them at the 3 minute mark instead.

**Comment by Haganeko** [comment]
There is abuse of this?

**Comment by Chogex** [comment]
3 minutes is still too early, it will only delay this strat by 1 minute

**Comment by CptBabineaux** [comment]
A delay of at most 5 mins would be good I think, I been in a game where we started a boss at 4:30

**Comment by Chogex** [comment]
also giving the bosses truesight wouldn't fix this, since smoke gives invisibility that can't be seen with truesight

**Comment by carlosrpg** [comment]
Why is this a problem?
If there is any abuse we should fix the abuse not the spawn.

Early bosses rush usually open the map and the contesting team should take advantage of that.

I advise against it

**Comment by l34Um1** [comment]
Cheesing bosses super early, then getting mana boots on your entire team is the abuse. The true sight change should fix the current cheese, however by also making bosses spawn later we limit the amount of cheese that we don't know about yet. These extreme cheeses existing severly limits the hero pool since they are so overwhelmingly powerful. 3 minutes is a very generous spawn timer, in most games it will have absolutely no impact, even for early boss killing strats.

**Comment by carlosrpg** [comment]
This looks like mana boot problem.
Again, I dislike our GPM solution. Generate in game resource will always be problematic. Ideally this stray would create good boots but your team would not have were to farm after that.


I guess 3 minutes will work for now, but we should rethink our farming boots later, missing bosses does not have purpose and is not easily understandable 
 fonew players.r

**Comment by Haganeko** [comment]
I agree. Items generating gold is ech. There are a few ways to correct this, but fact is that even if one farms nothing, right now Arcanes are better than killing creeps.
And that's not mentioning travels, where you just plain get more gold than your ally who is farming.

**Comment by l34Um1** [comment]
We could have the GPM boots tied to ingame time but that's not for now. That's a post tournament change.

**Comment by KarmaticNeutral** [comment]
Correct me if I'm wrong, but the problem here was people would smoke then intentionally not break it and use that to avoid tanking the rosh and get 2 minute farming cores? I know it doesn't future proof anything, but to avoid that issue couldn't just have bosses break smoke?

**Comment by carlosrpg** [comment]
https://github.com/OpenAngelArena/oaa/pull/1899
