### ISSUE TITLE
lvl one dungeon unbalanced

### ISSUE THREAD

**Issue by PerTzo** [OpenAngelArena/oaa#1890]
i get the point of the team doing dungeon 2. getting more xp/gold as kind of a comeback mechanic but this shouldnt apply before the first duel. its literally impossible to win with 4 lvl 1 heroes against 4 lvl 2 heroes on same skill level. either noone should reach lvl 2 or everyone should if both teams do the same. you shouldnt be awarded with being slow on clearing lvl 1

**Comment by Haganeko** [comment]
Level one cave is as expected. If you still have suggestions or comments, there are a suggestions repository and a community discord server where you can post them. This is for development tickets. Thank you.

**Comment by l34Um1** [comment]
I actually agree with this. Cave should only spawn after first duel like everything else.

**Comment by imaGecko** [comment]
I wouldn't mind a form of investment for an early level 2. level 1 specifically can be a drag

**Comment by imaGecko** [comment]
could have tome of knowledge be available from minute 0 with a max stack of 1 or 2
or otherwise at least fix shop timers running during the picking phase

**Comment by l34Um1** [comment]
Current cave strat is dumb though, especially since pertzo is right you can't win lvl 1 vs lvl 2. So it forces players to do it.

**Comment by imaGecko** [comment]
in theory you give up map control but it's just not significant enough because the time to kill camps level 1 is so high
Cave should spawn when regular creeps spawn

**Comment by Haganeko** [comment]
Or I could buff the cave creeps.

**Comment by PerTzo** [comment]
my thread wasnt really about the comparison of dungeon vs normal creeps but both teams doing one dungeon room and only getting lvl2 before first duel, this seems weirdly unbalanced.

**Comment by carlosrpg** [comment]
Yep, I think it is fine, (also you usually get lvl2 during the fight)
Chris was casting a game where the team did that, they totally lose a lot of farm in the firsts 3 min. It is a trade off. if you are confident your team can regain control by you give it a try.

The other team must take advantage of that tho, and should farm the other team camps

**Comment by imaGecko** [comment]
you don't actually lose anything, with early level 2 plus extra gold from winning the duel you already gained what little you lost from going to the map a little later. No tradeoff, just strictly better

And again the issue of both teams doing the cave pre duel and on occasion only one actually hitting level 2 for the start of the duel despite both teams clearing the room entirely

**Comment by l34Um1** [comment]
I don't think it's fine. There is very little strategic decision making, you'll see literally everybody do it. It will limit the hero pool to only heroes that are helpful for this.
