### ISSUE TITLE
Captains Mode Screen improvements

### ISSUE THREAD

**Issue by Bigpadaa** [OpenAngelArena/oaa#1895]
Improving the captains mode screen could be one of theese things that might be already in work
-Beeing able to give captain to another Person
-A chat box in the screen
-Beeing able to See whos the Captain
-Maybe when you click on a hero you see the Heroes Spells stats gain etc. and other information that got changed in the game

**Comment by Trildar** [comment]
Split up into #1897, #1900, #1901, and #1902.
