### ISSUE TITLE
Please dont make Fountain Regen linger

### ISSUE THREAD

**Issue by Bigpadaa** [OpenAngelArena/oaa#1896]
Its getting abused in many cases.
The Fountain Regen range is realy big and lingers for so long that it can be abused by Storm Spirit
or many other heroes. STorm spirit is able because of the fountain regen lingering to Zip accross half of the map and then back to fountain again because of the fountain Regen.
It's realy painful

**Comment by carlosrpg** [comment]
Dota normal behaviour.
Should we discuss this on discord before opening Issues?

**Comment by Haganeko** [comment]
Once again, this repository is for things that have been decided and are up for implementation.
