### ISSUE TITLE
Spells That Require Recreating - Summons

### ISSUE THREAD

**Issue by SquawkyArctangent** [OpenAngelArena/oaa#19]
Summon spells that spawn different units for different levels instead of modifying a single base unit are not hardcoded to allow for additional levels. To bypass this, we'll need to code them from scratch so that they can be given a higher maximum level - or at least, give their heroes another spell to take up the skill points.

- [ ] Call of the Wild ( both )

- [x] Chaotic Offering

- [ ] Demonic Conversion

- [ ] Mass Serpent Wards

- [ ] Nether Ward

- [x] Plague Ward

- [ ] Primal Split

- [ ] Summon Familiars

- [x] Summon Spirit Bear

- [ ] Summon Wolves

- [ ] Tombstone

Might need to check Homing Missile, too, as AAR ( iirc ) limited it to four levels max, although that might've been because the spell previously summoned different units in the past but no longer does.

Also, this goes for Necronomicon as well, but as every Necro level is actually a different item due to how leveled items work in DOTA 2, adding further upgrades does not require remaking the previous ones ( aside from recreating how they work in the new ones are supposed to work similarly ).

**Comment by Yahnich** [comment]
homing missile, spirit bear and plague ward work fine just need to add additional units for the levels, chaotic offering works fine as well

**Comment by Yahnich** [comment]
epic boss fight literally does it, you need to make additional units following the naming convention

**Comment by chrisinajar** [comment]
This list is super out of date, we've had a lot of them implemented a few turned out to not need it. We'll open granular tickets for each broken one as they're found and tested to be broken.
