### ISSUE TITLE
Tusk sigil levels 5 & 6

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#190]
Doesn't spawn

**Comment by warpdragon** [comment]
interesting...

**Comment by warpdragon** [comment]
Should be easy.  I'll add
```
"npc_dota_tusk_frozen_sigil5"
"npc_dota_tusk_frozen_sigil6"
```
to npc_units_custom.txt.

**Comment by ProstoSanja** [comment]
yeah this should work, error is below
`[ W Entity System ]: Cannot create an entity because entity class is NULL -1`
