### ISSUE TITLE
Award points for Cave clears and Duel wins

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#1904]
Split Duels count independently, so if there are 2 Duels and each team wins one, they both get a single point, and so on.

Caves are a single point for each clear.

@l34Um1 Is this okay to be done now, or should it wait until after tournament?

**Comment by l34Um1** [comment]
No this should totally be in before the tournament, since it just speeds up the games and OAA is a bit long at times.

**Comment by carlosrpg** [comment]
Deprecated?

**Comment by Haganeko** [comment]
The duel part still works, but a new ticket may be in order.

**Comment by carlosrpg** [comment]
Does it? Baumi just said in the stream he does not want to give cores for duel wins!

**Comment by Haganeko** [comment]
Uh, where does it say cores here? It says points.
