### ISSUE TITLE
Techies can place mines in the duel arena

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#191]
Needs to be prevented.

EDIT:
At the start of each duel, the code should remove all types of techies mines, and all types of wards, from both duel arenas.

**Comment by warpdragon** [comment]
no it doesn't. it needs to be allowed via code. we're trying to keep players inside a small space (as if nothing existed outside of that space during the duel, and after the duel we're trying to keep players from entering that space (as if it didn't exist). Instead of disabling all the spells and heroes that break the game, we should just fix the game.

**Comment by warpdragon** [comment]
on duel start{
-create a table of every player and which arena they belong in
-if a player-controlled unit is not inside one of the arenas AT ANY POINT, make it take 25% max damage per second.

that way, things like meepo poof, spectre ult, nature teleport, etc can be allowed to happen between arenas (something baumi has stated he wanted) but they can't go anywhere outside the arenas.

**Comment by warpdragon** [comment]
but of course you ahve the problem of players trying to push players out of the arena to kill them. so maybe having them take damage is not the best option.

**Comment by KarmaticNeutral** [comment]
I think I failed to communicate my point. Techies can place mines inside the duel arena when there is not a duel active. I've seen 3 techies rampages because people spawn on top of mines and can't react before they all explode. I don't care about thought process or the design concepts, but a play that makes it so that the enemy dies without an opportunity to react is bad.

**Comment by warpdragon** [comment]
oh yes that certainly is a problem. lol

**Comment by Chronophylos** [comment]
We could clear the duel area of anything that is not suppose to be there, like  items, wards, summonables and mines.
