### ISSUE TITLE
Fix Siltbreaker Bosses Aggro

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1918]
Currently they trigger at the sound of a hair falling and pursue with the fury of a starved lion. Make them behave like the other bosses.

**Comment by Haganeko** [comment]
#PoeticBaumi

**Comment by carlosrpg** [comment]
Need to know the threshold values to aggro.

**Comment by carlosrpg** [comment]
Can we close this as duplicated?
https://github.com/OpenAngelArena/oaa/issues/1860

**Comment by Haganeko** [comment]
Weird closing the older issue.

**Comment by l34Um1** [comment]
this is important, people don't check second page

**Comment by Haganeko** [comment]
Makes sense.

**Comment by carlosrpg** [comment]
I'll doit

- Aggro: (threashold = tier*BOSS_AGRO_FACTOR damage).
- Leash: (some bosses like Lycan won't work with default leash, some minions like ogre seer should have lower leash)
- Return Home: for now I'll increase think time until next action to 6 seconds when returning. Add the code to wait until reach home I'll take more time

**Comment by Haganeko** [comment]
Do note the mini ogres seem to aggro upon any damage being dealt to any ogre on the map, according to reports.

**Comment by carlosrpg** [comment]
This is false.
Ogre Seer aggro only on it taking damage or his Boss getting aggro

**Comment by Haganeko** [comment]
I see. We had reports of them crossing the map upon trying to fight an ogre boss. Guess people were confused.

**Comment by carlosrpg** [comment]
having his boss kill will make him mad, He will always be on aggro, that is the only reason I can think they got confused

**Comment by carlosrpg** [comment]
https://github.com/OpenAngelArena/oaa/pull/1920

**Comment by Haganeko** [comment]
There have also been reports that stunning some of the units (particularly the Seers) while they are returning would make them stay where they are. Was this an issue in the code, and, if so, does this fix it?

**Comment by carlosrpg** [comment]
Is the Aggro ok now? can we close this?

**Comment by l34Um1** [comment]
fixed
