### ISSUE TITLE
Urn of sorcery doesn't work at upgrade level 2

### ISSUE THREAD

**Issue by CynicalDemon** [OpenAngelArena/oaa#1931]
Non of it seemed to work. Couldn't gain charges, stats weren't given. Dropping the item had no effect. Upgrade level one worked fine however. Upgrade levels 3 and above didn't work either.

**Comment by Chogex** [comment]
The item should just be removed so that no one accidentally buys it.

**Comment by carlosrpg** [comment]
What? I played with it today, and was working. Also, would should try the discord first to validate before opening issues here, we have other repository for those

**Comment by Haganeko** [comment]
There is a separate repository for bug reports. Thank you.
