### ISSUE TITLE
Change to Boss Drops

### ISSUE THREAD

**Issue by spar36** [OpenAngelArena/oaa#194]
This is what Baumi suggested during the Stream.

When a boss is killed, everyone gets a farming core, everyone get an upgrade core of that tier, and an upgrade core of the tier below. So 3 items per hero.

The bosses will also drop other super rare items that you then NGP on.

**Comment by Haganeko** [comment]
Wait, more than one farming core?

**Comment by spar36** [comment]
So when a team kills a boss, say tier 2, Everybody on the team gets 1x Farming Core, 1x Upgrade Core 2, 1x Upgrade Core 1. 

Then they NGP on a single, rare item.

**Comment by Haganeko** [comment]
There is no meaning to getting another farming core - only one is needed. Also, I am pretty sure we had decided bosses drop only cores directly under their level (remember, upgrade core n upgrades items to tier n+1). After all, higher level cores can be used to substitute for lower level ones.

**Comment by chrisinajar** [comment]
weird this about that is that it means you don't get new items between tier 1 and 2 bosses, so we'll need to make sure that tier 2 is somewhat reasonable.

**Comment by Haganeko** [comment]
Well, gotta give people time to experiment with their fancy new cores. I've also been thinking we need money sinks of some kind, or maybe a nerf to money in general, but we'll see.

**Comment by Haganeko** [comment]
Close this?
