### ISSUE TITLE
At the beginning of each duel make both teams briefly invincible

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1946]
# Announcing the Auto Chess Open in partnership with BTS and Drodo Studios! Everyone is welcome to join!

Yo, hope you're having a great day.

I'm really excited to announce the Auto Chess Open, a **completely open tournament that everyone can join**. 

This tournament is partnered with BTS and Drodo Studio.

## The Format
- Single elimination bracket.
- 8 players go into a lobby. 
- Top 4 move on, bottom 4 are eliminated. *Fighting for top 4 is the key to success.*
- If the tournament has more than 2048 sign ups all rounds before the round of 1024 will only have the top 2 advance. *We want to accomodate as many players as possible.*
- Next round is seeded according to previous rounds placements. *Every lobby has 2 people that got 1st, 2 that got 2nd, 2 that got 3rd and 2 that got 4th in the previous round. Getting higher placements helps you get easier matches in the future.*
### Finals
- Once only 8 players are remaining they have reached the finals.
- Finals are a singular match, the order in which players get knocked out determines their final placing in the tournament.
## Date and Time
- The tournament starts Saturday the 16. February 2019 at 18:00 CET. 
- The second day of the tournament start at 17. February 2019 at 18:00 CET. 
- Each round of the tournament is expected to take about 1 hour.
- At most we'll have 5 rounds a day.
## Sign ups and Rules
- It's required for you to have a discord account to participate in this tournament.
- [Sign up link](https://docs.google.com/forms/d/e/1FAIpQLSf-T7EVv5OJxAlFLCgO1aSQQk0iEyB4f3LdyTqT38xND4qBDw/viewform?usp=sf_link)
- [Rules](https://docs.google.com/document/d/1Zconski4C81ivabxUPYxCkSX7QicP5xDN2CZvnyGz6M/edit#)
## Bracket
The bracket will become publicly available soon. We'll be posting it in the discord.
## Prize
There will be a prize for the winner. More details will be announced in the near future. If anyone is interested in contributing to the prize please send me an email to baumi@thinkingbottle.com.
## Stream
The tournament will be produced, streamed and commentated by Beyond The Summit!

I hope we'll see you at the tournament! It'll be a ton of fun!

**Comment by Melongod** [comment]
perhaps a hard purge too?

**Comment by Haganeko** [comment]
Whatever is committed before duel will stay committed after. Shouldn't the players who manage to debuff an enemy at the exact timing get an advantage instead of a punishment?

**Comment by Trildar** [comment]
Just for context, why is this necessary?

**Comment by l34Um1** [comment]
Some heroes with massive teamfight ultimates can start a duel by blinking on the enemy team and instantly hitting all of them with the AOE, essentially instantly winning the fight. The only solution to this was to activate BKB before the fight even started but I think that's stupid. 

This will give both teams a brief moment to reposition themselves before the fight starts. It's not really abusable since both teams can't really interact with each other and since it's very brief it only affects these extreme corner cases.

**Comment by warpdragon** [comment]
You will have to make a particle. Perhaps a blue shield particle or maybe the "glyph" particle except on heroes.

**Comment by Haganeko** [comment]
Could also be a BKB derivative.

**Comment by arrowpack** [comment]
If u set blink on like a 3 sec cd when a duel starts, they cant come in early enough right? Offcourse qop or am can blink in but they dont have a black hole or any big aoe stun that is significant.

**Comment by Haganeko** [comment]
Void has a jump. Force staff and Toss can be used. There's ways to force movement, though blink is admittedly the best.
Also, this way people get to keep their movement abilities.

**Comment by arrowpack** [comment]
Wich is good right?

**Comment by Haganeko** [comment]
Yeah. That's why temporary invincibility is best. It covers all the cases and people can still use their stuff.

**Comment by mikibun** [comment]
Has this been implemented? @Haganeko @warpdragon @arrowpack
