### ISSUE TITLE
Zeus: Make Nimbus cloud strike interval unaffected by cooldown reduction (€10 Bounty)

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1948]
Currently it is. From the wiki: "The base interval of the Lightning Bolts is affected by percentage-based cooldown reductions (Octarine Core icon.png Octarine Core and Arcane Rune minimap icon.png Arcane Rune)."

This is the only attribute of the spell that should change. If the ability is rebuilt from scratch, it must maintain all of its other properties (sounds, particles, damage/spell amp interactions, etc)

**Comment by chrisinajar** [comment]
This ticket has a $10 bounty on it. Anyone who completes a pull request which closes this ticket will receive the bounty.

**Comment by OTAJumperjay** [comment]
On it! (Pls no race-erino for the scrubberino that i am)

**Comment by chrisinajar** [comment]
changed to €

**Comment by l34Um1** [comment]
This is a 20% increase btw lmao

**Comment by warpdragon** [comment]
Catch these hot deals while they last!
