### ISSUE TITLE
Change Phantom Lancer's talent to avoid lag

### ISSUE THREAD

**Issue by Chogex** [OpenAngelArena/oaa#1961]
Phantom Lancer's +4 max illusions talent has been reported multiple times to cause an insufferable amount of lag. Before the talent was introduced the maximum amount of illusions was 10 from juxtapose, which while caused a bit of lag was not even nearly as bad as  the 14 illusions now.

Suggested changes to existing talents:
+15% evasion | meepo lvl 20 talent
+20 strength | pangolier lvl 20 talent

**Comment by imaGecko** [comment]
if I understand it right #1952 should have reduced that lag a bit now

**Comment by Chogex** [comment]
I have tested pl myself a few times after that was patched in. It hasn't done anything to reduce lag from pl's illusions.

**Comment by Trildar** [comment]
Given someone complained about PL lagging the game pre-25. I don't think the stats calculation actually has anything to do with it. I'm not sure #1952 was even necessary.

**Comment by mikibun** [comment]
Does this need to stay open?
