### ISSUE TITLE
Result of voting for game length

### ISSUE THREAD

**Issue by ProstoSanja** [OpenAngelArena/oaa#197]
I personally think it should be printed to gamemode title row during pick, and i made a setup for how to output it at #196 
I think the easiest solution will be to use localizable strings
  "aaa_game_length_short_title"     "Short Game"
  "aaa_game_length_normal_title"    "Normal Game"
  "aaa_game_length_long_title"      "Long Game"

we only need a person who knows where result is calculated and how to set text through localizable strings.

**Comment by Chronophylos** [comment]
`GameRules.GameLength`

**Comment by Trildar** [comment]
Is `GameRules` accessible from Panorama script under the same name? If it's not accessible from Panorama at all, some events from Lua or something to send the info over might be needed.

**Comment by ProstoSanja** [comment]
Evrything done at #196 
closing
