### ISSUE TITLE
Intentional D/c abuse during tournament

### ISSUE THREAD

**Issue by Melongod** [OpenAngelArena/oaa#1977]
It's actually super hard to prove that someone is doing this, so i wonder if in captains mode we could make the game immediately pause itself if someone d/cs and then make it so that people arent invulnerable while d/ced and are always put into duels.

I think that doing this in **ONLY** captains mode is a good idea due to tournament etiquette. People will respect pauses for people who d/c, and it also prevent people from being able to abuse d/cs.

**Comment by Haganeko** [comment]
Included in #2006.
