### ISSUE TITLE
Remake Meepo ult to balance for the late game

### ISSUE THREAD

**Issue by Melongod** [OpenAngelArena/oaa#1978]
Edit - Due to the item-centric nature of oaa, Meepo clones tend to get completely ruined by ***EVERYTHING*** late game. 

Conversation started with this original comment:
Due to the item-centric nature of oaa, Meepo clones tend to get completely ruined by ***EVERYTHING*** late game. Even creeps can kill him. So I wonder if making the last two levels of his ult grant more stats to share, like armour/hp regen/mana regen/MR/SR instead of granting more clones.
I'm not sure if that is actually possible code-wise but i feel that this is a decent way to make him viable late game.

**Comment by warpdragon** [comment]
i think the problem is that it's actually (and this is in  no way an exageration) impossible to fix Vanilla divided we stand. coupled with the fact that the reimplementation certainly created more problems than it fixed. 
again. the way to fix meepo isn't divided we stand. the elegant solution would, by definition, be mutually exclusive from divided we stand

**Comment by Melongod** [comment]
I've heard that abilities like this and spell steal are actually possible to fix as of recent updates.

Source - chris

**Comment by Haganeko** [comment]
Just increase the stat reduction constant for meepo. Add a fake ability which starts out already skilled and which says he gets more stats after level 25. Done!

**Comment by warpdragon** [comment]
i had proposed maybe just exempting meepo from diminishing stats.

**Comment by Haganeko** [comment]
Just buff the constant. The current constant is actually pretty buffed from my original proposal, anyways. I have old graphics for it; we can pick and choose later.

**Comment by Melongod** [comment]
stats arent what he lacks. he lacks regen and armour more than anything else

**Comment by Melongod** [comment]
just giving him better numbers wont fix the issue with the hero late game.

**Comment by Haganeko** [comment]
Uh... He'll have armor, and regen, from stats.
Also, this serves to further my point that regen is given a bit too freely these days.

**Comment by Melongod** [comment]
you have to give copious amounts of agility and strength to give the needed amount of armour and regen. doing that will also cause way more problems.

**Comment by Haganeko** [comment]
Lucience should help with the regen, as should other aura regen items.
As for armor... We do need more aura armor options, especially for summon based heroes, but I hope Cuirass+vlads or mekans would be enough.

**Comment by Melongod** [comment]
so you force him to buy items that aren't what the hero wants?

**Comment by Haganeko** [comment]
Or you design items he'd want and are good on him.
In any case, I don't think whatever meepo ends up building would be the same as vanilla; the way he works there just doesn't mesh well with OAA.

**Comment by Melongod** [comment]
Forcing heroes to buy items is just not a good way to go about balance.

**Comment by Haganeko** [comment]
It's only forced in that one is "forced" to buy good items. We do need more aura options, but auras being good on heroes with multiple units isn't forced; it's just a fact.

**Comment by Melongod** [comment]
Also the way that he plays should work in oaa, if not be better in oaa.

**Comment by Melongod** [comment]
that's true, but it's a separate issue. To make meepo better, we should change meepo and not everything else.

**Comment by Melongod** [comment]
having more items choices is also nice, but it just doesnt solve the current issue with the hero which is that his clones die to anything late game.

**Comment by Melongod** [comment]
they shouldnt do that regardless of item choices

**Comment by Haganeko** [comment]
That's a bad way to balance things. You don't change them to remove weaknesses, you highlight their strengths and change their context to make it so their virtues shine.
You don't balance meepo by removing his weaknesses (difficult time itemizing, bad late game), you make sure his advantages (fast leveling, multiple bodies) are strong and viable.

**Comment by Haganeko** [comment]
His clones will die less if they have more HP (more str) and he has item options to share some buffs around.

**Comment by Melongod** [comment]
there is no circumstance where putting points into an ability should be completely detrimental to the hero.
this isnt a "weakness", it's unplayable. your clones ***WILL*** die to easy camps past minute 30 regardless of item choice unless you can instantly kill the camp. that isnt ok.

**Comment by Melongod** [comment]
As of right now, the ***OPTIMAL*** way to play meepo is to not skill your ult. How is that an item problem and not a hero problem?

**Comment by Haganeko** [comment]
It is an item problem because there apparently aren't enough item options for a tankier meepo.
Also, as I said, more stats from levels would help.
A proper item build can do wonders for a hero.

**Comment by Haganeko** [comment]
Also, I bet you don't like Tiny, then.

**Comment by Melongod** [comment]
i love tiny? how on earth is that relevant?

**Comment by Melongod** [comment]
Please answer the question;
How is it OK that it is optimal to ***NOT SKILL YOUR ULT***?

**Comment by Melongod** [comment]
even with better items, that will be the case.

**Comment by Haganeko** [comment]
"Skilling an ability should never be detrimental for a hero"
I don't know about right now, but used to be Tiny didn't skill ult until he had enough AS from items to support it.
In a game as item intensive as ours, makes sense some heroes might have a similar situation.

**Comment by Haganeko** [comment]
You are stating that about the situation after better stats and items with no evidence or even argument. How am I supposed to take your statement seriously when it comes unsupported?

**Comment by Haganeko** [comment]
It's not okay that his ult is useless right now. All I'm trying to say is we can fix it without changing it into something else, because the base concept isn't broken like Underlord's was.

**Comment by Melongod** [comment]
literally the only change i proposed was that he shares armour and hpregen with the later levels. the hero's ult is so garbage right now that i'd say that it is worse than underlords situation. underlords ult didnt do anything useful but also did nothing detrimental. meepos ult ONLY provides more vulnerability.

**Comment by Haganeko** [comment]
But the problem is only numbers - his clones are too weak.
That's solved by giving him stats, which will make his clones stronger, and by implementing more minion items, which we need to do anyways.
No need to get complicated and add features to an already buggy and complicated ult, which players will need to learn and which will drive him away from his uniqueness.

**Comment by Melongod** [comment]
adding an invisible ability to that gives more stats and then adding more items to a game with literally hundreds of items is less complicated that allowing him to share more stats?

**Comment by Melongod** [comment]
adding more items ALSO requires players to learn. meepos ult already shares stats, so making them share more stats hardly takes from his uniqueness.

**Comment by Haganeko** [comment]
The items need to be added anyways. They're necessary to spice up/buff creep and summon strats.
And the ability won't be invisible, PLUS it's only a modification to an already existing mechanic.
And it's intuitive! "You get more stats". Can't be easier than that.

**Comment by Haganeko** [comment]
The thing is that meepo ult shares only some stats. That restricts what he can build effectively, and restriction is the mother of creativity. Add more stats, you make him closer to other heroes, thereby reducing his uniqueness.

**Comment by carlosrpg** [comment]
Does this ticket has enough information to make it doable by someone?
If not we should close it. Open another one with the information needed to be implemented. this should not be the place to discuss but to get the information that a collaborator could use to fix the issue

**Comment by Haganeko** [comment]
This is a discussion ticket, not an implementation one. Still, it went nowhere.
