### ISSUE TITLE
Regeneration Crystal Provides the wrong HP Regen

### ISSUE THREAD

**Issue by Bigpadaa** [OpenAngelArena/oaa#1993]
Without the Regen crystal active:
https://imgur.com/a/hJEHS
Regen crystal active:
https://imgur.com/a/8tyX6
Instead of the mentioned 225 i got 700 hp regen

**Comment by Naeily** [comment]
regen scales with strenght and the regen that regen crystal gives has been balanced accordingly, theres nothing wrong going on here.

**Comment by Bigpadaa** [comment]
TOOLTIP DOESNT SAY

**Comment by Haganeko** [comment]
This is not the place for bug reports. Also, "this works like everything else" is not a bug.

**Comment by Haganeko** [comment]
This is not the place for bug reports. Also, "this works like everything else" is not a bug.
