### ISSUE TITLE
Refresher (in all variants) refreshing in duels

### ISSUE THREAD

**Issue by Melongod** [OpenAngelArena/oaa#1997]
What is the point of ultimates being left on CD at the start of a duel if any heroes who have good team fight ults will just go for some form of refresher?

**Comment by Haganeko** [comment]
This is such a commonsensical idea I am surprised we don't have a ticket for it already.

**Comment by l34Um1** [comment]
I disagree with this. You buy refresher for this exact purpose. The item is fine now with the Cooldown nerf.

**Comment by Trildar** [comment]
Maybe the change should be to instead not restore CD on Refreshers. Cause currently, using Refresher in Duels is pretty much free, since you'll get back the CD it had prior to the Duel.

**Comment by Melongod** [comment]
I agree with that change trildar.

**Comment by Melongod** [comment]
hmmm, I feel like a "golden-mean" approach wouldn't work in this scenario. I'm not sure that weakening it in duels solves the issue any more than just having it not refresh. If anything, it creates inconsistencies in the items mechanics. Long CD ults will be unaffected by a 30 second reduction in the same way as having the refresher's cd not restored.

**Comment by Haganeko** [comment]
I meant have duels reduce CD by thirty instead of refresh cooldowns, not change how refresher works.

**Comment by Melongod** [comment]
ahh, my misunderstanding.

**Comment by Melongod** [comment]
It still adds a level of unnecessary complexity. 
Just more that players have to keep track of.

**Comment by Haganeko** [comment]
Well, it might make "don't refresh ults" obsolete, which is a thing.

**Comment by Melongod** [comment]
true.

**Comment by l34Um1** [comment]
I actually like that idea the most. It's not really complex. Explaining "Duels reduce your cooldowns by 30 seconds" isn't more complicated than "Duels refresh your cooldowns". I think we should print a small message in chat though.

**Comment by Melongod** [comment]
Sounds good.
Definitely a post-tournament change though.

**Comment by Trildar** [comment]
So that would be for both abilities and items? And does everything still restore CD after the Duel? Exclude ultimates? Or just axe it completely?

**Comment by Haganeko** [comment]
Yes, goes back to what it was before duels I guess, no, and yes.
