### ISSUE TITLE
Duel number of players uneven

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#200]
Reported ratios:
1v5
4v5
3v4

Supposedly the player was just not teleported in.

**Comment by KarmaticNeutral** [comment]
2v1
3v2

**Comment by Haganeko** [comment]
Has this been fixed?

**Comment by chrisinajar** [comment]
This should have been fixed, there were multiple problems with the duel code. Could use more testing if you guys know how to make it happen (or know how often it used to happen)
