### ISSUE TITLE
Rework interaction between disconnects and Duels

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#2006]
Disconnects are currently really abusable to mess with Duels. Proposals to mitigate this are currently to:

~~- [ ] Make disconnects during Duel not freeze heroes~~
- [ ] Don't exclude disconnected players from Duels in Captain's Mode

Anybody have anything to add on the matter?
Edit: Apparently freezing is being removed entirely in favor of disconnected players being invulnerable in Fountain, thus making not freezing in Duels obsolete.

**Comment by Haganeko** [comment]
Does #2005 do this?

**Comment by Melongod** [comment]
The freezing of people i believe is being completely removed.
Having people be invulnerable in the fountain.
I dont remember if there was anything else.

**Comment by Trildar** [comment]
That seems kind of unnecessary. What purpose would that serve?

**Comment by Haganeko** [comment]
The idea is to prevent people from abusing DC's, while still keeping them from being camped.
IIRC it's not people being invulnerable in the fountain, it's DC'd people being invulnerable in the fountain.

**Comment by Trildar** [comment]
Does that also include always including people in Duels? Or is the point just to prevent people from d/cing in the middle of the fight to avoid dying? Cause I doubt it's really all that beneficial outside of Duels. Plus, we're eventually going to have some 5 minute abandon rule, most likely.

**Comment by Melongod** [comment]
I believe baumi made notes of the discussion we had at the *not-townhall*

**Comment by Trildar** [comment]
Ah. Probably should have actually looked at that. It doesn't include any reasoning though. Also...
* duels always uses all players in the game
* in CM the disconnected player gets loaded into the duel
* in any other mode disconnected players stay in the fountain for duels

That seems contradictory. I'm guessing the first one was meant to be Final Duels?

**Comment by Haganeko** [comment]
The first one means if the game is 4v5, the duels are 4v5

**Comment by Trildar** [comment]
Then what does the last one mean?

**Comment by imaGecko** [comment]
In a regular mode:
All connected players get loaded into the duel

In captains mode:
All players including disconnected players get loaded into the duel

**Comment by imaGecko** [comment]
though there was also a mention of only the final duel using all players since split duels would end up with a 2v2 and a 2v3

**Comment by Trildar** [comment]
Oh... I get it now. It never occurred to me it could have been about games that weren't full to begin with. I thought we didn't really care about that.

**Comment by Haganeko** [comment]
Problem is because of MMR or spite people stay in 1v5s, making them last forever.

**Comment by imaGecko** [comment]
The changes are for duels especially the final duel to not to be skewed in favour of the disconnected team consisting only of strong members versus random sometimes weaker members of the winning team

**Comment by Trildar** [comment]
Okay. So to be 100% clear. Disconnected players are left out of Duels (except maybe Final Duels) like it is right now, except for in CM?

**Comment by imaGecko** [comment]
yes, disconnected players are only loaded into any duels in captains mode
disconnected players are never loaded into duels in any other mode

**Comment by Melongod** [comment]
Except for the final duels

**Comment by Haganeko** [comment]
Why except for final duels? In case someone's connection drops right before the duel, I guess?

**Comment by Melongod** [comment]
To make a game that has a team who has a few players missing not be drawn out because key heroes from the full team weren't selected for the final duel.

**Comment by Melongod** [comment]
People arent **ever** frozen. D/ced heroes become invulnerable in the fountain.

**Comment by imaGecko** [comment]
People not in the duel are still frozen

**Comment by Trildar** [comment]
Obsoleted by #2070
