### ISSUE TITLE
Implement the new hero "Sohei"

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2010]
Below is the zip given to me by Maelstrom.
[Sohei.zip](https://github.com/OpenAngelArena/oaa/files/1740113/Sohei.zip)

This is a hastebin with OAA numbers. https://hastebin.com/ozixunehag.scala

Make sure to exclude him from Captains Mode but enable in all other game modes.

**Comment by Melongod** [comment]
NICE!

**Comment by warpdragon** [comment]
New Priorities:

1. Implement Attachments Library for implementing custom wearables on any hero
2. Give Juggernaut legs and a weapon
3. Optionally: Give juggernaut a custom weapon and head using Blender

**Comment by warpdragon** [comment]
### Update

- Sohei has custom model and matierials.
- Sohei uses juggernaut armature and mesh and animations
- Sohei needs additional in-game testing for sound effects, particles, and death animation on PR #2016
