### ISSUE TITLE
Give cores some stats

### ISSUE THREAD

**Issue by Miniwoffer** [OpenAngelArena/oaa#2024]
I dont know if this has been discused earlier, a quick search in issues showed nothing.

I have noticed that early in the game, you dont really need anything else then the farming core. Getting a full inventory can take some time, and often teammates compete to get the few creeps that spawn. 

Giving cores somting along the lines of +10 in all stats, hopefully gives a bigger sentiment to get the cores early. And also cause more early game pvp, since players will try to steal the other teams cores earlier.

**Comment by Haganeko** [comment]
Thank you for your input. Do note there is a separate repository for suggestions.
