### ISSUE TITLE
Permadeath resurfaces

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#203]
Supposedly on occasion people do not respawn after duels. It looks as though the next duel fixes this problem. I have not been able to reproduce this at all but I have ~7 errors reporting this.

#### Reports:
* After dying on the duel i was invisible on a cliff just outside of the duel arena when enemies came close i was able to attack 'although dead'. The killed me again with aoe spells and post the duel i didn't respawn
* Everyone on the other team who died didnt respawn. I survived the duel and was stuck glitched out in the duel arena
* Playing Clinks and died in a Duel, stayed dead until the next duel began.

##### What were you doing?
Finishing a duel
##### What was supposed to happen?
all teleport back to places before duel
##### What happened instead?
we were pushed to the edge of arena and had to teleport out with scrolls and some of the enemies didn't resurrect(Gyro,Wraith,Omni)
##### Anything else
just in case Lone Druid+Slark+Sniper+Techies+Pudge VS Bristleback+KOTL+Wraith King+Omni+Gyro.     My team Pudge(DC), Enemy Gyro(DC)

Edit by @Chronophylos: Markdown

**Comment by KarmaticNeutral** [comment]
What were you doing?
I was in a 4v4 duel. One of my teammates (Sven) used Travel Boots to get to our fountain. All my team died except for Sven
What was supposed to happen?
The three members of my team (me included) were supposed to respawn after the duel time ran out
What actually happened?
We never respawned. After more than 5 minutes the host just quit.

**Comment by Haganeko** [comment]
Wait, so Sven got out of the duel using tp boots?

**Comment by KarmaticNeutral** [comment]
Apparently
