### ISSUE TITLE
Sven: Storm hammer doesn't stun

### ISSUE THREAD

**Issue by DerpySoccerBall** [OpenAngelArena/oaa#2036]
The new dota update changed some of sven's talents and broke sven's stun. It doesn't have a value on the tooltip either.

**Comment by Haganeko** [comment]
Thank you for the report. Do note, however, that there is a separate repository for bug reports: https://github.com/OpenAngelArena/Bug-Reports
Additionally, updating the game for parity takes some work, so please have some patience.
