### ISSUE TITLE
Puck invulnerability

### ISSUE THREAD

**Issue by Melongod** [OpenAngelArena/oaa#2037]
If you shift queue phase shift, you are completely invulnerable when holding a maxed out refresher core.

**Comment by Melongod** [comment]
4.05 second duration with a 4.02 second cd.

**Comment by Melongod** [comment]
Either this has to be fixed before the tournament or puck has to be banned.

**Comment by GymLeaderGiovanni** [comment]
Reduce duration again?

**Comment by Melongod** [comment]
would fix it

**Comment by GymLeaderGiovanni** [comment]
Give me a couple minutes

**Comment by Melongod** [comment]
I'm currently testing the degree of invulnerability by sitting in offsides with phase shift queued up.
Most of the time I take no damage but rarely I take a single tick of the offsides. With this, I can stay alive with more than 50 offsides stacks without dying.

**Comment by Haganeko** [comment]
Ideas: 0.60/1.20/1.80/2.30/3.00/3.60
          0.75/1.30/1.85/2.40/2.95/3.50
          1.00/1.50/2.00/2.50/3.00/3.50

**Comment by Melongod** [comment]
0.75/1.50/2.25/3.25/3.5/3.75

**Comment by warpdragon** [comment]
phase shift is one of the most powerful tools in vanilla dota in the hands of a **skilled** player. giving it retarded up-time does nothing except make the hero feel really stupid.

**Comment by warpdragon** [comment]
it doesn't have to scale crazy hell make it 3.5

**Comment by Haganeko** [comment]
0.75/1.40/2.00/2.50/2.95/3.50

**Comment by Melongod** [comment]
let's do hagas 3rd idea.
