### ISSUE TITLE
Duel Arena Border

### ISSUE THREAD

**Issue by Illidan-Stormrage** [OpenAngelArena/oaa#2039]
Just had one of the (arguably) worst matches I've had since starting OAA, where an antimage would blink onto the border of the arena and spam illusions, and not coming down to let final duel end, this dragged on for another solid half hour, I suggest that we make that you cannot blink or forcestaff or any kind of movement ability onto the border. 

Not to mention the dude was plain toxic.

**Comment by Haganeko** [comment]
Thank you for the report/suggestion. A few points:
1. It's not supposed to be possible to climb up there. A screen shot might help.
2. This is not the place for reports. This is for actionable issues and important, highly controversial debate
3. The capturable areas were implemented precisely for this. Go back, capture the area and then run the guy down.
