### ISSUE TITLE
Scoreboard for Duals

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#204]
This would be good for debugging as well as give players information on how their team is doing during a duel. Should be a simple thing to code, I'd think.

**Comment by ProstoSanja** [comment]
So like overlay about ongoing duel, or an addition to scoreboard with overall stats, I didn't quite understand.

**Comment by warpdragon** [comment]
Just like two numbers at the top of the screen.

**Comment by ProstoSanja** [comment]
I'll take it, you can assign to me

**Comment by warpdragon** [comment]
your name isn't under assignees. i can't assign it to you for some reason.

**Comment by ProstoSanja** [comment]
Anyways, I'll deal with it.
@chrisinajar should deal with assignments.

**Comment by warpdragon** [comment]
![image](https://cloud.githubusercontent.com/assets/13878439/24110797/c5529ce0-0d6a-11e7-9aef-fc73347d3fe7.png)
I can assign others. i just can't assign you.

**Comment by warpdragon** [comment]
anyway. thanks!

**Comment by Chronophylos** [comment]
You can only assign members or collaborators

**Comment by ProstoSanja** [comment]
@Chronophylos well that's the matter of you accepting me :)

**Comment by Chronophylos** [comment]
I don't think I have the rights to do that, only chris has.

**Comment by Haganeko** [comment]
Did this get done?
