### ISSUE TITLE
Boss: Swiper (deprecated)

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#2050]
# Boss: Swiper

### 1.1. Lua
- AI: The unit should utilize a thinker to attempt to cast spells from a sub-list of his spells but only if they are off cooldown. The sub-list of spells, the level of the spells, and their respective cooldowns, should depend on the boss phase. In Phase 3 the boss should cast Deathly Apparition immediately before the wind-up of his other spells when possible.

### 1.2. KV
- Armor: boss average
- Magic Resist: boss average
- Status Resist: boss average
- Hitpoints: boss average
- Hitpoint Regen: boss average
- Manapoints: boss average
- Manapoints Regen: boss average
- Attack Behavior: No auto attack
- XP Bounty:
- Gold Bounty:
- Inventory: Upgrade Core, Boss Heart
- Abilities: Thrust, Frontswipe, Backswipe, Reaper's Rush, Deathly Apparition
- Any settings typical to other bosses.

### 1.3. Tooltip 
- Name: Sabnock 
- Description: the Swordsman
- Lore: Demon. 

### 1.4. Model

Boss models should appear unique and different from existing Dota 2 units.

- Style: Demon with a sword. 
- Base Model: Custom or existing Dota 2 Model
- Wearables: Custom or existing wearables rigged using Blender and/or FollowEntity(). Lion head if possible. Weapon should be a very large sword.

### 1.5. Animations
- Run: Normal
- Stun/Flail/Spawn/Death/Idle
- Additional ability animations detailed in Abilities section.

## 2. ABILITIES

All abilities should be telegraphed by a particle effect outlining the location, area, and general motion of the ability. Abilities require a significant "wind-up" animation to play accompanied by a targetting reticle before executing the damage, so players will learn to dodge his abilities. All art associated with his abilities should follow a similar style/color palette.

### 2.1. Lua

- Boss Resistance: Used by all bosses.

- Cliffwalking: Used by all bosses 

- Thrust: Long range (~600u), targeting the ground at the location of a player furthest away from the boss up to a certain range. Damages in an AOE line.

- Frontswipe: Swing the sword in a 180-degree arc counter-clockwise. Short range (~200u), targetted to hit as many players as possible.

- Backswipe: Occasionally (~25%) and immediately follows frontswipe swinging the sword in a 180-degree clockwise arc. Short range (~200u).

- Reaper's Rush: Holds the sword to the right, perpendicular to his facing direction. Runs quickly to a far away location in the arena in the direction of the highest concentration of players. Players hit by the sword take massive damage. Enemies hit by the boss's body take moderate damage, are pushed away (~100u), and are slowed. Upon reaching his destination, swings the sword in a 360-degree arc counter-clockwise.

- Deathly Apparition: Blink into advantageous position (with lots of convenient targets nearby). 

### 2.2. KV

KV should account for abilities with 3 levels corresponding to the 3 phases. Damage should increase per level. Cooldown should decrease per level.

- Thrust: Delay, Range, Width, Target_Max_Range, Target_Min_Range, Damage, Cooldown
- Frontswipe: Delay, Start_Angle, End_Angle, Range, Min_Targets, Target_Max_Range, Damage, Cooldown
- Backswipe: Delay, Start_Angle, End_Angle, Range, Damage, Cooldown
- Reaper's Rush: Delay, Speed, Max_Range, Min_Range, Min_Targets, Push_Length, Slow, Slow_Duration, Max_Damage, Min_Damage, Start_Angle, End_Angle, Cooldown
- Deathly Apparition: Range, Cooldown

### 2.3. Tooltip
- Name, Description, KV-entries, Lore

### 2.4. Icons
- Custom icons for each ability

### 2.5. Particles
Particles should accompany the wind-up animation and be of equal length.

- Thrust: A long, narrow targeting rectangle renders from the boss outward over the duration of the wind-up, indicating the precise location of impending damage. This particle should disappear after the wind-up but before the ability animation completes. 
![Rectangle](https://user-images.githubusercontent.com/13878439/37106200-2fe28ff8-21ff-11e8-93af-5655402b0382.png)
Additionally, the Ability animation should emit a copy of his sword as a large, poking, sword particle.

- Frontswipe: A targetting circle centered on the boss's position should begin as an expanding pie slice counter-clockwise until it reaches the total arc of the location of impending damage. This particle should disappear after the wind-up but before the ability animation completes. 
![Frontswipe](https://user-images.githubusercontent.com/13878439/37107944-b0b374a4-2203-11e8-8029-467d08b74748.png)
Additionally, the Ability animation should emit a trailing particle similar to juggernaut spin.

- Backswipe: The frontswipe particle should play in reverse at the appropriate time. The particle should disappear before the ability animation completes. 
![Backswipe](https://user-images.githubusercontent.com/13878439/37107925-a5b88b98-2203-11e8-8055-97a15ca2b7c2.png)
Additionally, the Ability animation should emit a trailing particle similar to juggernaut spin.

- Rush: Two parallel targeting rectangles emit from the boss outward over the duration of the wind-up, indicating the precise location of impending damage. Once the boss begins moving a new indicator circle particle should appear at the target location indicating the total arc of the location of impending damage. The particle should dissappear before the ability animation completes.
![Reaper's Rush](https://user-images.githubusercontent.com/13878439/37107192-b960c540-2201-11e8-9fc9-78261ae9b421.png)

- Deathly Apparition: Simple start/end blink-style particles.

### 2.6. Animations
- Run: With sword perpendicular to him
- Ability: Thrust forward
- Ability: Swipe clockwise
- Ability: Swipe Counterclockwise

### 3.1. Lua
- Slow Modifier: Units slowed by Rush should have a modifier indicating this
- Any other modifier required by previous coding.

### 3.2. Tooltip
- Name: Required.
- Description: Required. Should reference KV entry for any relevant values.

### 3.3. Icons
- Possibly the same as the rush ability icon

### 3.4. Particles
- Overhead particle indicating slowed status

### 4.1 Phase One
- Active while boss is between 100 and 75% HP
- Sub-list of abilities: Thrust, Frontswipe and Backswipe

### 4.2. Phase Two
- Active while boss is between <75% and 50% HP
- Sub-list of abilities: Thrust, Frontswipe, Backswipe, Rush
- Particle/Model: Boss model should gain an indicator particle or model modification to indicate that he is in stage 2

### 4.3. Phase Three
- Active while boss is between <50% and 0% HP
- Sub-list of abilities: Thrust, Frontswipe, Backswipe, Rush, Teleport
- Particle/Model: Boss model should gain an indicator particle or model modification to indicate that he is in stage 3

**Comment by Haganeko** [comment]
Yeah. We're splitting it up, then putting up a bounty

**Comment by GymLeaderGiovanni** [comment]
Does that include the lore or am I still doing that for free?

**Comment by carlosrpg** [comment]
I'd like to let you guys know I'm working on the Code already. Meaning AI/Abilities implementation

**Comment by warpdragon** [comment]
see #2065
