### ISSUE TITLE
Swiper: Boss (code)

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#2065]
# Boss: Swiper (Code)

We have several bosses already implemented which you should feel free to use as inspiration/reference. Also you can reference some other open source custom games on [Github](http://github.com) which have boss fights including [Second Day of Frostivus](http://www.github.com/openangelarena/frostivus2017) where you will find our IO boss (designed by Yahnich).  Files should follow the structure already established in the components subfolders (such as /abilities/, /boss/, etc).

### 1.1. Lua

- Unit AI: The boss should utilize a thinker in order to attempt to cast spells from a sub-list of his spells but only if they are off cooldown. The sub-list of spells, the level of the spells, and their respective cooldowns, depends on the boss phase. Furthermore, in Phase 3 the boss should cast Deathly Apparition immediately before the wind-up of his other spells when possible. Finally, AOE spells should perform a calculation to attempt to hit as many units as possible and ranged spells should attempt to hit far away units, and this is discussed later under "Abilities".

### 1.2. KV

The following list of required unit properties to be outlined in KV is not exhaustive and coders should expand upon it as required.

- Armor: boss average
- Magic Resist: boss average
- Status Resist: boss average
- Hitpoints: boss average
- Hitpoint Regen: boss average
- Manapoints: boss average
- Manapoints Regen: boss average
- Attack Behavior: No auto attack
- XP Bounty:
- Gold Bounty:
- Inventory: Upgrade Core, Boss Heart
- Abilities: Thrust, Frontswipe, Backswipe, Reaper's Rush, Deathly Apparition
- All settings typical to other bosses which are relevant.

### 1.3. Tooltips

A tooltip file should be created and list 

- Name: Sabnock 
- Description: the Swordsman
- Lore: Demon. 

### 1.4. Model & Animations

Temporary models are needed for the purposes of coding and testing the boss properly. The base boss model should be used from the pool of existing dota 2 models respecting considerations such as attack range and basic necessary animations. Use FollowEntity() or equivalent to give him a sword.

Range: Melee

### 1.5. Animations

- Additional ability animations detailed in Abilities section.

## 2. ABILITIES

All abilities should be telegraphed by a particle effect outlining the location, area, and general motion of the ability. Abilities require a significant "wind-up" animation to play accompanied by the creation of this targetting reticle particle before executing the damage, so players will learn to dodge his abilities. For the purposes of coding the basic boss, custom particles are not required, but a filler particle must be used. Particles can be hidden or commented out at the coder's discretion, but the particle code must be complete and working.

### 2.1. Lua

- Boss Resistance: Used by all bosses.

- Cliffwalking: Used by all bosses 

- Thrust: Long range (~600u), targeting the ground at the location of a player furthest away from the boss up to a certain range. Damages in an AOE line.

- Frontswipe: Swing the sword in a 180-degree arc counter-clockwise. Short range (~200u), targetted to hit as many players as possible.

- Backswipe: Occasionally (~25%) and immediately follows frontswipe swinging the sword in a 180-degree clockwise arc. Short range (~200u).

- Reaper's Rush: Holds the sword to the right, perpendicular to his facing direction. Runs quickly to a far away location in the arena in the direction of the highest concentration of players. Players hit by the sword take massive damage. Enemies hit by the boss's body take moderate damage, are pushed away (~100u), and are slowed. Upon reaching his destination, swings the sword in a 360-degree arc counter-clockwise.

- Deathly Apparition: Blink into advantageous position (with lots of convenient targets nearby). 

### 2.2. KV

KV should account for abilities with 3 levels corresponding to the 3 phases. Damage and cooldown especially should be adjustable to balance the phases.

- Thrust: Delay, Range, Width, Target_Max_Range, Target_Min_Range, Damage, Cooldown
- Frontswipe: Delay, Start_Angle, End_Angle, Range, Min_Targets, Target_Max_Range, Damage, Cooldown
- Backswipe: Delay, Start_Angle, End_Angle, Range, Damage, Cooldown
- Reaper's Rush: Delay, Speed, Max_Range, Min_Range, Min_Targets, Push_Length, Slow, Slow_Duration, Max_Damage, Min_Damage, Start_Angle, End_Angle, Cooldown
- Deathly Apparition: Range, Cooldown

### 2.3. Tooltip
- Name, Description, KV-entries

### 2.4. Icons
- Filler icons

### 2.5. Particles
Telegraph particles should accompany the wind-up animation and have a lifespan of approximately the same timespan.

### 2.6. Animations

If the following animations cannot be found in the same hero, get as close as you can with as many as you can:

- Run: With sword perpendicular to him (the model used should have a "special" run animation in addition to his normal run. Use that animation here. Animations can be viewed in the Dota 2 tools model editor)
- Ability: Thrust weapon forward
- Ability: Swipe weapon clockwise
- Ability: Swipe weapon Counterclockwise 

### 3.1. Lua
- Slow Modifier: Units slowed by Rush should have a modifier indicating this
- Any other modifier required by previous coding.

### 3.2. Tooltip
- Name: Required.
- Description: Required. Should reference KV entry for any relevant values.

### 3.3. Icons
- Filler icons

### 3.4. Particles
- Overhead filler particle indicating slowed status

### 4.1 Phase One
- Active while boss is between 100 and 75% HP
- Sub-list of abilities: Thrust, Frontswipe and Backswipe

### 4.2. Phase Two
- Active while boss is between <75% and 50% HP
- Sub-list of abilities: Thrust, Frontswipe, Backswipe, Rush
- Particle/Model: Boss model should gain an indicator particle or model modification to indicate that he is in stage 2

### 4.3. Phase Three
- Active while boss is between <50% and 0% HP
- Sub-list of abilities: Thrust, Frontswipe, Backswipe, Rush, Teleport
- Particle/Model: Boss model should gain an indicator particle or model modification to indicate that he is in stage 3

**Comment by carlosrpg** [comment]
I have a question.
Frontswipe is counter-clockwise and backswipe is clockwise?
shouldn't both follow the same movement so the boss can immediately connect one after the other?

**Comment by l34Um1** [comment]
The idea is that the boss swipes from right to left and then instead of going back into the starting position swipes from left to right.

**Comment by carlosrpg** [comment]
oh, so it is the same area of effect, not a complete roll?

**Comment by l34Um1** [comment]
Yes same area of effect. Swipe should be pretty fast.

**Comment by carlosrpg** [comment]
having Start_Angle and End_Angle for swipes will probably not be compatible with the animations I think.
align the boss to hit more heroes with a single swipe is a AI feature, not ability.
Will we still have those specials for the abilities?

**Comment by warpdragon** [comment]
you be the judge on that. if i listed KV that you don't need that's my fault.

**Comment by warpdragon** [comment]
much of this is unexplored territory. i have tried to be as accurate as possible when writing this. i would rather err on the side of too much info than not enough. in the end if you do not need some of the things i put in there to complete the boss I will not deny the bounty on a technicality if, by all other metrics, you did a great job.

**Comment by carlosrpg** [comment]
Np, this is supposed to be an iterative  work. It is part of what we call extracting requirements

**Comment by Trildar** [comment]
You should fill in all the "boss average" stuff so that people don't have to go looking at files just to figure that out. I don't know if "boss average" hp even has any real meaning right now.
Similarly for XP and gold bounty. I believe all bosses currently have 0?

**Comment by Haganeko** [comment]
They do, or they should. The small ogres apparently give a bit of bounty.
