### ISSUE TITLE
Fix selection focus at start of game

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#2067]
At the start of the game, there's some kind of focus that's on the hero unit that causes Enter to act like selecting the hero instead of opening the chat. Left-clicking on the ground changes the focus and allows you to open chat.

This seemed to start happening around the time chat was added to the pick screen, so it could have something to do with that.

**Comment by chrisinajar** [comment]
This started happening when we added the pick screen, it's always been a side effect.

**Comment by Trildar** [comment]
Really? I feel like there was a period of time after the pick screen was implemented when I didn't have to do this.

**Comment by DarkoniusXNG** [comment]
This was accidentally fixed when hero selection was changed.
