### ISSUE TITLE
Surrender Option | 15€ Bounty

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#2068]
Allow a team to vote to surrender once they are fifty kills behind. Four votes in favor are necessary to give up a game. If less than five players are in the team, then reduce the necessary amount of votes accordingly:
```
Players | Votes
   5    |   4
   4    |   3
   3    |   2
   2    |   2
   1    |   1
```

After the threshhold has been reached players can type "-surrender" into chat. If they do an interface pops up that lets them vote to surrender or not to surrender. If a player abstains they count as a "no".
This vote interface stays for up to a minute or until a conclusive vote has been reached. It will then announce it in chat. If a surrender has been voted for, the game will end after a 10s timer and a message "The Radiant/Dire team surrendered" displays for both teams on the top of the screen.

A surrender vote can only be initiated after at least a minuted passed after the last one. A single player can only intitate one surrender vote every 5 minutes.

**Comment by l34Um1** [comment]
You need to be more precise about how this vote would happen. What's the interface for it?

**Comment by RodneyMcKay** [comment]
I'm working on that for IMBA, once it's done and fully working i'll do it in OAA if no-one did it in the meantime.

**Comment by carlosrpg** [comment]
I Claim this

**Comment by carlosrpg** [comment]
I unclaim due to lack of time

**Comment by M-i-k-e-l** [comment]
I claim this
