### ISSUE TITLE
Safe to Leave Mechanics | 30€ Bounty

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#2069]
Involves a few items:

- [ ] Make it so, if a player abandons prior to three minutes, the game is reported as void, except for the player who left, who is reported as an abandon.
- [ ] Make it so, if a player has DC'd for a total of five minutes, they are considered to have abandoned the game.
- [ ] Make it so, if a team has a disadvantage (in terms of abandons) of two or more players, a timer starts. Once that timer reaches zero, award victory to the opposing team.
- [ ] Make it so, for each abandon, the score limit decreases by 10, to a minimum of the top current score plus ten.

Bottlepass:

- [ ] Players who abandon should not get any Bottlepass experience for their next two games.

**Comment by carlosrpg** [comment]
I Claim this

**Comment by carlosrpg** [comment]
I unclaim due to lack of time

**Comment by Yahnich** [comment]
gottem

**Comment by Jacob-Koger** [comment]
Claim this

**Comment by Jacob-Koger** [comment]
Psych nm

**Comment by carlosrpg** [comment]
If no one is working on It I would like to claim it.
Question. I need a better definition of abbandon cause the first item says about abandon within 3 min while the second defines abandon as 5 seconds total DC time.

Also I think this requires some changes on the API for the bottle pass to calculate the MMR.
So this ticket may be blocked until these are implemented there

**Comment by Haganeko** [comment]
An abandon is when you click the "leave game" button in the DotA client. Can we not detect that?
The line about total DC time is so that if someone just DC's for too long, they are considered as having abandoned, even though they haven't actually clicked the "leave game" button.

**Comment by carlosrpg** [comment]
I Reclaim this 😄
