### ISSUE TITLE
Find and fix the bug that's causing the hero selection screen failure. (20€ bounty)

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2073]
We know little about this bug. It's inconsistent and we don't know a way to reproduce it.

When the hero picking screen is supposed to pop up none of the heroes are selectable. Here is a screenshot: 
![unbenannt](https://user-images.githubusercontent.com/24982519/37487352-8bb52ba4-2891-11e8-9436-945d5442709e.PNG)

Then one of two things happens: Either the picking timer runs out and you get loaded into the game or you are stuck at that screen and nothing else happens.

Here is console data from somebody that experiences this crash: https://drive.google.com/file/d/1LDgkxhN6XSMq9i8KjuCVuP7qPt6hS0GD/view

This issue started 3 days ago with the Dota+ patch. If anyone else has any more information please leave a comment.

**Comment by EternusPhoenix** [comment]
I submitted the console data for be the example, which I then looked through comparing it with a working one, as I couldn't replicate also the crash itself. Here is my working console data itself:
https://drive.google.com/open?id=184ZZHrnE_4_RiqNrIJqHhfp1-SWQ4hT2

> [Client] CL:  Receiving uncompressed update from server
> [Client] CL:  Signon traffic "client":  incoming 244.530 KB [53 pkts], outgoing 200.501 KB [4426 pkts]
> C:Gamerules: entering state 'DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD'
> [Client] LoadingDisplay changed from LOADING to WAITING_FOR_PLAYERS (map="oaa")
> [Client] CDOTA_Hud_Main::EventGameRulesStateChanged DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD
> Warning: Fell out of small block heap!
> [Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 3298 (was 4875)
> [Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 1896 (was 3565)
> [ResourceSystem] Error loading resource file "panorama/images/heroes/selection/npc_dota_hero_sohei_png.vtex_c" (Error: ERROR_FILEOPEN)
> [Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 451 (was 2151)
> [PanoramaScript] [Server] [gamemode:104]	First Player has loaded	
> [WorldRenderer] Long grass load frame: 10.015006 ms for 406 grass tiles
> [WorldRenderer] CWorldRendererMgr::ServiceWorldRequests long frame: 10.060887ms
> [PanoramaScript] [Server] [components/bottlepass/server:91]	Sending auth request 03/15/1817:02:32	
> C:Gamerules: entering state 'DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP'
> [Client] LoadingDisplay changed from WAITING_FOR_PLAYERS to CUSTOM_GAME_SETUP (map="oaa")
> [Client] CDOTA_Hud_Main::EventGameRulesStateChanged DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP
> [PanoramaScript] [Server] [components/bottlepass/server:103]	Authed with dev server!	
> [PanoramaScript] !! (s2r://panorama/scripts/custom_game/pointsmanager.vjs_c, line:19, col:4) - ReferenceError: FindDotaHudElement is not defined
> [PanoramaScript] [Server] [gamemode:91]	Performing Post-Load precache	
> [PanoramaScript] [Server] [gamemode:114]	All Players have loaded into the game	
> C:Gamerules: entering state 'DOTA_GAMERULES_STATE_HERO_SELECTION'
> [Client] LoadingDisplay changed from CUSTOM_GAME_SETUP to NONE (map="oaa")
> [Client] CDOTA_Hud_Main::EventGameRulesStateChanged DOTA_GAMERULES_STATE_HERO_SELECTION
> C:Gamerules: entering state 'DOTA_GAMERULES_STATE_WAIT_FOR_MAP_TO_LOAD'
> [Client] CDOTA_Hud_Main::EventGameRulesStateChanged DOTA_GAMERULES_STATE_WAIT_FOR_MAP_TO_LOAD
> [ResourceSystem] Error loading resource file "panorama/images/heroes/npc_dota_hero_dummy_dummy_png.vtex_c" (Error: ERROR_FILEOPEN)
> [PanoramaScript] !! (s2r://panorama/scripts/custom_game/health_mana.vjs_c, line:35, col:24) - TypeError: Cannot set property 'text' of undefined
> [PanoramaScript] [Server] [components/heroselection/heroselection:137]	Starting HeroSelection Process	
> [PanoramaScript] [Server] [components/heroselection/heroselection:138]	oaa	
> [PanoramaScript] [Server] [components/music/music:12]	Init music	
> [PanoramaScript] [Server] [components/music/music:42]	Playing6	
> [PanoramaScript] PlayerTables.TableFullUpdate callback error for 'gold -- {"gold":{}}': ReferenceError: FindDotaHudElement is not defined
>     at UpdateGoldHud (s2r://panorama/scripts/custom_game/gold.vjs_c:40:19)
>     at Object.onGoldChange (s2r://panorama/scripts/custom_game/gold.vjs_c:35:3)
>     at TableFullUpdate (s2r://panorama/scripts/playertables/playertables_base.vjs_c:154:19)
> C:Gamerules: entering state 'DOTA_GAMERULES_STATE_PRE_GAME'

This part from my crash report seems to be one part of the problem by my perspective. I don't know what could the "Warning: Fell out of small block heap!" do or regarding for the problem, but other than this it seems comparing with a good console data, that the below part is the starting point of it.

> [PanoramaScript] !! (s2r://panorama/scripts/custom_game/pointsmanager.vjs_c, line:19, col:4) - ReferenceError: FindDotaHudElement is not defined

Then the next which also seems to happen is this:
> [ResourceSystem] Error loading resource file "panorama/images/heroes/npc_dota_hero_dummy_dummy_png.vtex_c" (Error: ERROR_FILEOPEN)
> [PanoramaScript] !! (s2r://panorama/scripts/custom_game/health_mana.vjs_c, line:35, col:24) - TypeError: Cannot set property 'text' of undefined

After this there is more comming with this being the first:
> [PanoramaScript] PlayerTables.TableFullUpdate callback error for 'gold -- {"gold":{}}': ReferenceError: FindDotaHudElement is not defined

After this many more lines are coming with all having the "FindDotaHudElement is not defined" as for their error/failure and then this starts to repeat itself as it goes on until I disconnected.
For information this is what I found out so far that could indicate the problem, however I might have missed something hence I encourage others, that are better at coding dota lines than me should take a look at the crash data and the working one. 

Lastly this was made by 1 player (me) lobby, so I don't know if there are more people in it would have a different effect or not.

**Comment by chrisinajar** [comment]
carlos may have fixed it, we'll see!

**Comment by l34Um1** [comment]
Fixed by carlos and paid out.
