### ISSUE TITLE
Moving through objects

### ISSUE THREAD

**Issue by dkNykita** [OpenAngelArena/oaa#208]
You can move almost inside of this statue

![statue](https://cloud.githubusercontent.com/assets/26550793/24112452/d5b210d2-0d99-11e7-9ddb-36ee37687d38.png)

**Comment by dkNykita** [comment]
Another one
![statue_2](https://cloud.githubusercontent.com/assets/26550793/24115096/8f856f6a-0da2-11e7-892b-a10b616d0f5a.png)

**Comment by warpdragon** [comment]
outdated.
