### ISSUE TITLE
Carapace Boss - Code | 50€ Bounty

### ISSUE THREAD

**Issue by Shusama** [OpenAngelArena/oaa#2080]
# Boss: Carapace
We have several bosses already implemented which you should feel free to use as inspiration/reference. Also you can reference some other open source custom games on Github which have boss fights including Second Day of Frostivus where you will find our IO boss (designed by Yahnich). Files should follow the structure already established in the components subfolders (such as /abilities/, /boss/, etc).

**See also:**
Carapace: Boss - Model/Animations/Icons #2081
Carapace: Boss - Sound #2082 
Carapace Boss - Particles #2083 

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

## Original Description
Has a strong shell with crystals in it. Hitting with an attack or spell from the direction of a crystal (10 degree window) will bypass the bosses usually high resistances.
After a crystal has sustained a threshold of damage (this has a range, so for example it’s not 100 but 50-150) it will start to glow. After two seconds, the crystal will deal AoE damage in a cone (the same area from which extra damage is possible). Then the crystal disappears.
As the bosses HP drops he gains more crystals. He starts with 2 and every 10% of HP lost he gains another one. These can spawn at either preset locations or randomly, I don’t mind. If preset they should be spread around his body.

The boss attacks regularly.
The boss also has a headbut forward. After a short backwards motion windup the bosses entire body slams forward, dealing physical damage and a very short duration slow. This is essentially a delayed, short range AOE attack that moves the boss forward. After doing it the boss lands on the ground and lays there for a brief moment.

Has a slow turn rate.

## 1. Lua
Unit AI: The boss should utilize a thinker in order to attempt to cast spells from a sub-list of his spells but only if they are off cooldown. Finally, AOE spells should perform a calculation to attempt to hit as many units as possible and ranged spells should attempt to hit far away units. If an ability requires special care or treatment this is discussed later under "Abilities".

## 2. Boss Abilities
Every ability should have a tooltip (Name, Description, KV-entries).

* Boss Resistance: Used by all bosses.
* Cliffwalking: Used by all bosses
* Crystal Generation (Passive): The boss starts out with 2 crystals and creates another one after every 10% hp loss. Each of the crystals work like a 10° wide bristleback. The damage received from within this 10° cone, instead of being reduced, gets amplified. After a certain threshold the crystals explode after a short delay damaging everything within the cone and disappear. The threshold is within a certain range and not a fixed number
* Headbutt: After an one second ability animation the boss lunges forward, slowing all enemies hit for a short duration and dealing 1500 magical damage. Afterwards the boss lays on the ground, stunned for 2 seconds  (for reference https://youtu.be/Tyh5sXaKaFc?t=9 )

## 3. KV
The following list of required properties to be outlined in KV is not exhaustive and coders should expand upon it as required.

**Unit**
Armor: 60
Magic Resist: 30
Hitpoints: 4000
Hitpoint Regen: 10 
Manapoints: 2500
Manapoints Regen: 5 
Attack Damage: 300-320
Attack Rate: 1.45
Turn rate: 0.3
XP Bounty: 900
Gold Bounty: 0
Inventory: Upgrade Core, Boss Heart
Abilities: Crystal Generation, Crystal Break, Headbutt

**Abilties**
Crystal Generation: Damage_Amplification, Threshold_Min, Threshold_Max, Delay, Start_Angle, End_Angle, Range, Damage
Headbutt: Delay, Range, Width, AOE, Slow_Value, Slow_Duration, Self_Stun, Target_Max_Range, Target_Min_Range, Damage, Cooldown

## 4. Model & Animations
Temporary models and animations, as well as particles and sounds are needed for this ticket to be considered completed. You don't have to create anything from scratch, you may reuse anything that already exists in Dota. The base boss model may be used from the pool of existing dota 2 models respecting considerations such as attack range and basic necessary animations. (Maybe Nyx Assassin)
Range: Melee

## 5. Modifiers
* Slow Modifier: Units slowed by Headbutt should have a modifier indicating this
* Any other modifier required by previous coding.

**Comment by Yahnich** [comment]
i claim this

**Comment by l34Um1** [comment]
Yahnich unclaimed it since he doesn't have time to work on it.

**Comment by TideSofDarK** [comment]
Claimed.

**Comment by TideSofDarK** [comment]
https://streamable.com/f0cmo
Here is **Headbutt**
Let me know if damage area should look different.
Current range/width are adjustable through KV

**Comment by l34Um1** [comment]
That's pretty much exactly on point.

**Comment by TideSofDarK** [comment]
11 premade crystal points
Also it wasn't clear if they should rotate along with hero
https://streamable.com/y9ku3

**Comment by l34Um1** [comment]
Yes they should, they are supposed to be attached to its body.

**Comment by TideSofDarK** [comment]
Merged/Paid
