### ISSUE TITLE
Slime Boss - Code | 50€ Bounty

### ISSUE THREAD

**Issue by Shusama** [OpenAngelArena/oaa#2085]
# Boss: Slime
We have several bosses already implemented which you should feel free to use as inspiration/reference. Also you can reference some other open source custom games on Github which have boss fights including Second Day of Frostivus where you will find our IO boss (designed by Yahnich). Files should follow the structure already established in the components subfolders (such as /abilities/, /boss/, etc).

### See also:
Slime: Boss - Model/Animations/Icons #2086
Slime: Boss - Sound #2088
Slime Boss - Particles #2087

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

### Original Description
The boss is a long circular slime unit. There is a picture below, I recommend checking that to better understand his abilities. Tbh this boss is a very close replication of a Zelda boss from minish cap. Here is a video of the fight: https://youtu.be/RswiLpt9Zmc?t=5m8s 

Instead of dying, the boss splits into two smaller copies of itself, each with 75% of the original's HP. This happens only once. The smaller slimes have the same abilities as the big one.

This boss has no regular attack and instead rotates mostly between attack 1 and 2. Attack 3 has a % chance to happen between attacks 1 and 2 but once it’s used it’s on cooldown until the death phase. After the split each slime may use it again.

Attack 1 - Jump
Jumps into the air, towards a target location; a shadow (particle) appears below him to show where he is. Traveling speed should be slow enough (suggestion: 300) to allow for dodging.
Once the boss lands, all enemies on the area should take damage, be pushed out and slowed (suggestion: 80%). After landing the boss is stunned for a few seconds.

Attack 2 - Slam
The Slime slams it’s whole body into one direction. This has a significant range, 700. Enemies hit take damage, get pushed and are slowed. Afterwards the boss is stunned for a few seconds, ideally while still laying on the ground.

Attack 3 - Shake
The boss becomes invulnerable and starts shaking violently. It then throws small, randomly sized projectiles at random points in the arena. Each one does damage and slows. Suggested duration: five seconds.

Once the boss hits 0 HP, it does a “Shake”. Then the Slime splits.

## 1. Lua
Unit AI: The boss should utilize a thinker in order to attempt to cast spells from a sub-list of his spells but only if they are off cooldown. Finally, AOE spells should perform a calculation to attempt to hit as many units as possible and ranged spells should attempt to hit far away units. If an ability requires special care or treatment this is discussed later under "Abilities".

## 2. Boss Abilities
Every ability should have a tooltip (Name, Description, KV-entries).

* Boss Resistance: Used by all bosses.
* Cliffwalking: Used by all bosses
* Jump: The boss jumps into the air towards a specific location, a shadow particle on the ground him indicates his movement while in the air. The entire jump should give the player enough time to avoid the targeted location. Upon landing all enemies within the aoe take damage, are pushed outside the aoe and are slowed significantly.
* Slam: The Slime slams it’s whole body into one direction. This has a significant range, 700. Enemies hit take damage, get pushed and are slowed. Afterwards the boss is stunned for a few seconds.
* Shake: After each Slam/Jump this ability has a random chance to trigger and once the Original Slime HP reaches 0 (So it can only trigger twice a life). The boss becomes invulnerable for the duration of the skill. Similar to crystal maiden ultimate, projectiles of randomized size appear in the arena. Each one damages and slows the player on hit.
* Split: The boss splits, once it's HP reach 0 and the last Shake is over, into two smaller slimes. Those have 75% of its original HP and all of its original abilities **accept** Split itself. 

## 3. KV
The following list of required properties to be outlined in KV is not exhaustive and coders should expand upon it as required.

**Unit**
Armor: 28
Magic Resist: -25
Hitpoints: 2000
Hitpoint Regen: 10 
Manapoints: 2500
Manapoints Regen: 5 
Attack Damage: 1
Attack Rate: 200
Attack Behavior: No auto attack
XP Bounty: 900
Gold Bounty: 0
Inventory: Upgrade Core, Boss Heart
Abilities: Jump, Slam, Shake, Split

**Abilties**
Jump: Target_Max_Range, Target_Min_Range, Movement_Speed, Damage, Knockback, Slow_Value, Slow_Duration, AOE_Width, Cooldown
Slam: Target_Max_Range, Target_Min_Range, Movement_Speed, Damage, Slow_Value, Slow_Duration, Self_Stun, Cooldown
Shake: Trigger_Chance, AOE_Width, Projectile_Min_Size, Projectile_Max_Size, Damage, Slow_Value, Slow Duration
Split: HP_Percentage, Inherited_Skills (Jump, Slam, Shake)

## 4. Model & Animations
Temporary models and animations, as well as particles and sounds are needed for this ticket to be considered completed. You don't have to create anything from scratch, you may reuse anything that already exists in Dota. The base boss model may be used from the pool of existing dota 2 models respecting considerations such as attack range and basic necessary animations. 
Range: Melee

## 5. Modifiers
* Slow Modifier: Units slowed by a spell should have a respective modifier indicating this
* Any other modifier required by previous coding.

**Comment by Yahnich** [comment]
i claim this

**Comment by l34Um1** [comment]
Yahnich unclaimed it since he doesn't have time to work on it.

**Comment by TideSofDarK** [comment]
claimed

**Comment by TideSofDarK** [comment]
how shake projectiles should work?
im thinking if its either starfall style stuff or something else

**Comment by TideSofDarK** [comment]
https://streamable.com/mzu4t shake, slam and then jump
let me know if some of these should work differently
