### ISSUE TITLE
Slime Boss - Model/Animation/Icons | 150€ Bounty

### ISSUE THREAD

**Issue by Shusama** [OpenAngelArena/oaa#2086]
# Boss: Slime
We have several bosses already implemented which you should feel free to use as inspiration/reference. Also you can reference some other open source custom games on Github which have boss fights including Second Day of Frostivus where you will find our IO boss (designed by Yahnich). Files should follow the structure already established in the components subfolders (such as /abilities/, /boss/, etc).

### See also:
Slime: Boss - Code #2085 
Slime: Boss - Sound #2088
Slime Boss - Particles #2087

[General Guidelines for Model Issues](https://docs.google.com/document/d/15VtqjOfyL8aZiK7ufJp-G-rPkVGza-K3IkBHrMrLN-U/edit)
[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

## 1.Model
Pretty sure everybody saw a slime monster before. Reference:
![300px-chuchuboss](https://user-images.githubusercontent.com/25332142/37710821-2042829a-2d0f-11e8-871e-9ab05f10a226.jpg)

* The Slime should be constantly moving up and down/get a bit smaller and than bigger again like a beating heart for example.
* Slime drops of various sizes should be dripping of.
* An addidtional stun animation is also needed. Maybe have him lie on the ground like a deflated balloon.

## 2. Animations
As reference you can take a look at the [slime boss fight from Zelda Minish Cap](https://www.youtube.com/watch?v=RswiLpt9Zmc&feature=youtu.be&t=5m8s). Also there is a "Slime-Hero" in League of Legends called [Zac](https://euw.leagueoflegends.com/com/game-info/champions/Zac/) whose animations could help. 

His basic walking animations should be a slow woobling forward. 

**Jump:** Retracting for a short moment he jumps up and leaves nothing but a shadow particle on the screen, this particle effect moves towards his targeted area at a moderate movement speed. Once it reaches the area the Slime falls down again.

**Slam:** Pulling back into the opposite direction at first the boss shoots its body into the targeted direction like a snapping rubberband. Afterwards the boss ends up stunned especially for this please use the already mentioned new stun animation.

**Shake:** Shaking non stop drops of it's body should spill out and hit random places, those drops size should be relative to the randomized size of the aoe effect. Maybe have the slime drops return to the boss ([the second part of Zac's Cell division ability as reference](https://euw.leagueoflegends.com/com/game-info/champions/Zac/))

**Split:** The boss divides itself into two smaller versions of itself.
![150px-stdef2](https://user-images.githubusercontent.com/25332142/37712414-12f6ecde-2d14-11e8-9eb2-5257d28676eb.png)

## 3. Icons
We need Icons for all of his abilities and all of his modifiers.

**Comment by Herakmon** [comment]
can I claim this?

**Comment by l34Um1** [comment]
Absolutely. Just make sure you read the guidelines.

**Comment by mikibun** [comment]
@Herakmon Are you still working on this?
