### ISSUE TITLE
Slime Boss - Sound | 10€ Bounty

### ISSUE THREAD

**Issue by Shusama** [OpenAngelArena/oaa#2088]
# Boss: Slime
We have several bosses already implemented which you should feel free to use as inspiration/reference. Also you can reference some other open source custom games on Github which have boss fights including Second Day of Frostivus where you will find our IO boss (designed by Yahnich). Files should follow the structure already established in the components subfolders (such as /abilities/, /boss/, etc).

### See also:
Slime: Boss - Model/Animations/Icons #2086
Slime: Boss - Code #2085  
Slime Boss - Particles #2087

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

## Abilties
*  His jump and slam attacks need a strong bludgeoning sound when they land. There should be a slight modification when he hits something, the sound of impact. Keep in mind though that his body is somewhat liquid.
* For his shake there should lots of smaller slam sounds. Like a bunch of waterballons exploding for example.

**Comment by AnArnaut** [comment]
I'll take this one.

**Comment by Booty-Smasher** [comment]
Without a picture of the boss, I dont know what type of slime it is. Like a terraria slime? Or the poison slime in konosuba? Or if hes slimey but not an actual ball of slime.

**Comment by Booty-Smasher** [comment]
I so claim this

**Comment by Booty-Smasher** [comment]
Will*

**Comment by Booty-Smasher** [comment]
https://youtu.be/qFTdYtxL9J8
https://youtu.be/6nhulRpkw0g
Sorry I will not be able to work on it, so go ahead and reopen the thread, but here are some watermelon sounds that might be good for it.
