### ISSUE TITLE
Electrician New Hero - Code | 50€ Bounty

### ISSUE THREAD

**Issue by Shusama** [OpenAngelArena/oaa#2089]
# Hero: Electrician

### See also:
Electician New Hero - Model/Animation/Icons #2091
Electician New Hero - Particles #2092
Electician New Hero - Sound #2090 

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

## This hero is a port! He already exists in Heroes of Newerth!
There is plenty of footage of this hero out there. Here just a few: 
[HoN Gamepedia](https://hon.gamepedia.com/Electrician)
[Electrician Gameplay](https://youtu.be/c7WjghMDwL8)

## 1. HeroAbilities
Every ability should have a tooltip (Name, Description, KV-entries).

* [Q] Static Grip:
![q](https://lh6.googleusercontent.com/pteR7nJqi0Kp7vCAEia_or00OGt_N1cPqAXAlkMuUyz8dLGvzUKmCrgkR8kXksKXe327UmEuN0nXTWdjtckkxqZjuuRIL6hRvmbej5_7N7Cx8N6MLx0XWZWzH0Ro0tc9fGBSjphJ)
  * This is a channeling ability.

* [W] Electric Shield:
![w](https://lh4.googleusercontent.com/nya_B0voYbcjCtWSKNg5sZnWfd1vWlN3aRTA5y8N6kNDzyET5f9u9OAsDLirev_dBU6sz7QUi5Ths8eXiX-azENcv1j6X1YtCxvRmWfKsp4KwAFD097W_knPSiOutCYvC2bnFRu-)

* [E] Energy Absorption:
![e](https://lh3.googleusercontent.com/MPzuaacASOzrHlnk6MlOw-MazcDT-q_AirDK5_D3QWLBNwQzs-1zzcyI8sqof0t6Dq4Q_w1E_HsJrM1HqHGc-Ih2x8TQXaSo60el1xWGQAjnRyY8NLfK38pEUjR_sBu3aMOqZJNL)
 * Drains mana on percentage base but replenishes a flat amount per hit (heroes count triple) and grants a 50 movement speed buff.
 

* [R] Cleansing Shock:
![r](https://lh6.googleusercontent.com/C8M96NM01twlgwMv1dIVKzET3XDDz2-sOYRclx44ZotLK8SaXl_cGsjqA8b6mn5vYdC0DdXlWf-7kOMuiDwM-U-YT5vY25bovdZjvnD80BPGQZyMvzb5MYw808Ac5AmvU_7_EARa)
 * His ultimate should by default only hit a single person instead of 0/1/2. The chaining to additional targets will be his aghanims and always be 2 additional targets. It should be able to hit both enemies and allies chaining the ability and it should prioritize heroes.
* Also keep in mind that the movement speed in-/decrease is not a flat amount but increasing over the abilities duration.

## 2. Talents
Choice One | Level | Choice Two
----------------|------- | -------------
+2 Mana Regen | 10 | +10 Health Regen  
+20 Movement Speed | 15 | +150 Cast Range
Heroes now give 6 times the Mana for Energy Absorbtion | 20 | +800 Mana
Cleansing Shock now aditionally always hits yourself as well when casted | 25 | +1000 HP

## 3. KV
The following list of required properties to be outlined in KV is not exhaustive and coders should expand upon it as required.

**Unit**
Attack Range: Melee
Turn rate: 0,5
Base Attack Time: 1.7
Starting Strength: 23
Starting Agility: 13
Starting Intelligence: 25
Base Damage: 30-38
Starting Strength damage + Base damage: 53-61
Strength Growth (Main Attribute): 2.4
Agility Growth: 2
Intelligence Growth: 1.5
Base Armor: 2.5
Base Health Regen: 1.5
Movement Speed: 300
Base Health: 200
Base Health + Starting Strength Health: 660
Base Mana: 100
Base Mana + Starting Intelligence Mana: 400

**Abilities**
Static Grip: Duration, Mana_Cost, Cooldown, Damage_per_Second, Break_Distance, Self_Movement_Speed, Range

Electric Shield: Percentage_Mana_Cost, Cooldown, Duration, Mana_to_Shield_Percentage, Damage_aoe, Damage_per_Second

Energy Absorbtion: Mana_Cost, Cooldown, Damage, Mana_Drain_ Percentage, Mana_Gain_per_Charge, Hero_Charge_Multiplier, Movement_Speed_Buff

Cleansing Shock: Range, Mana_Cost, Cooldown, Movement_Speed_Increase_per_Second, Movement_Speed_Decrease_per_Second, Duration, 
Aghanims: Additional_Chain_Targets, Chain_Range

## 4. Model & Animations
Temporary models and animations, as well as particles and sounds are needed for this ticket to be considered completed. You don't have to create anything from scratch, you may reuse anything that already exists in Dota. The base model may be used from the pool of existing dota 2 models respecting considerations such as attack range and basic necessary animations.
Range: Melee

## 5. Modifiers
* Slow Modifier: Units slowed by a spell should have a respective modifier indicating this
* Ultimate Modifier: A modifier for both the buff and the debuff coming from the ultimate
* Electric Shield buff Modifier
* Energy Absorbtion buff Modifier
* Any other modifier required by previous coding.

**Comment by SquawkyArctangent** [comment]
stakin' my claim on this

**Comment by mikibun** [comment]
Electrician is in the game now, right? Can I close this? @SquawkyArctangent

**Comment by mikibun** [comment]
Arctangent has been paid, issue closed
