### ISSUE TITLE
Weird blink spots

### ISSUE THREAD

**Issue by dkNykita** [OpenAngelArena/oaa#209]
I dont know if it's intended or not but inside of left farming cave there are some weird spots where you can blink.

Behind statue
![blink](https://cloud.githubusercontent.com/assets/26550793/24112771/e3bcc130-0d9a-11e7-8c08-181807ddff3c.png)
This part of wall 
![blink_2](https://cloud.githubusercontent.com/assets/26550793/24112862/2450568a-0d9b-11e7-8d6d-a1ddec7ebd96.png)
This probably whole really high cliff just near the end of map
![blink_3](https://cloud.githubusercontent.com/assets/26550793/24113021/a9362e24-0d9b-11e7-9de5-c9f94470258b.png)
Also behind those trees near the boss arena wall
![blink_4](https://cloud.githubusercontent.com/assets/26550793/24113090/ebcf819a-0d9b-11e7-8623-a0ebe4e8c284.png)

I will post more weird locations when I find them

**Comment by dkNykita** [comment]
This is probably just a cliff farming location but just wanted to be sure
![blink_5](https://cloud.githubusercontent.com/assets/26550793/24113498/4a1adf32-0d9d-11e7-9806-76070cb889f0.png)

Probably just the same as upper screen
![blink_6](https://cloud.githubusercontent.com/assets/26550793/24113593/94721474-0d9d-11e7-9d27-c1602a50aa26.png)

This probably shouldn't be a spot to blink also the rock just under this one and the next one
![blink_7](https://cloud.githubusercontent.com/assets/26550793/24113686/d3f36b02-0d9d-11e7-8121-c922d609fd5e.png)

Another not so great blink spot
![blink_8](https://cloud.githubusercontent.com/assets/26550793/24113851/69723f64-0d9e-11e7-841d-087622aef8b9.png)

**Comment by Chronophylos** [comment]
Keep finding them!

**Comment by dkNykita** [comment]
I will but probably I will rehost and enable cheats :D it's pain doing it with 12s dooldown on blink 🗡

**Comment by dkNykita** [comment]
This one really shouldn't be there
![blink_9](https://cloud.githubusercontent.com/assets/26550793/24114268/e0bdab0c-0d9f-11e7-8d07-9fbcdc3a8d65.png)

Moving outside of the farming cave
![blink_10](https://cloud.githubusercontent.com/assets/26550793/24114327/162d18d6-0da0-11e7-90fe-a659e425d0d1.png)

This wall is walk/blinkable from here
![blink_11](https://cloud.githubusercontent.com/assets/26550793/24114385/49b546a6-0da0-11e7-8645-845b8884e5af.png)

Up to here + those marked spots
![blink_12](https://cloud.githubusercontent.com/assets/26550793/24114457/97640dce-0da0-11e7-8823-04c500caaa2a.png)

**Comment by dkNykita** [comment]
Tree spots
![blink_13](https://cloud.githubusercontent.com/assets/26550793/24114605/266fa348-0da1-11e7-8a7a-869bf78cbc08.png)

This was also not mentioned before
![blink_14](https://cloud.githubusercontent.com/assets/26550793/24114690/64ace6a2-0da1-11e7-9a11-dad299b94e71.png)

There is some kind of a pit
![blink_15](https://cloud.githubusercontent.com/assets/26550793/24114753/9b484148-0da1-11e7-9436-0b36d148d9c5.png)

Another spot
![blink_16](https://cloud.githubusercontent.com/assets/26550793/24114881/f89d5e96-0da1-11e7-9812-cb8f1c3c0f6e.png)

There were many spots
![blink_17](https://cloud.githubusercontent.com/assets/26550793/24115035/66abd692-0da2-11e7-9ffd-ab9478d6b2f0.png)

Next to this statue
![blink_18](https://cloud.githubusercontent.com/assets/26550793/24115130/b41c7300-0da2-11e7-8e35-e7509582e2e3.png)

**Comment by dkNykita** [comment]
Stuck insede of trees
![blink_19](https://cloud.githubusercontent.com/assets/26550793/24115208/e70433a2-0da2-11e7-84ad-8bc5848c6ba1.png)

Cliff from this point
![blink_20](https://cloud.githubusercontent.com/assets/26550793/24115278/1f80e0c2-0da3-11e7-9212-670737d962fa.png)

Up to this point
![blink_21](https://cloud.githubusercontent.com/assets/26550793/24115322/44fe9844-0da3-11e7-9f95-2500c6dec5fa.png)

And you can blink there
![blink_22](https://cloud.githubusercontent.com/assets/26550793/24115369/69c3ae62-0da3-11e7-8758-e4a512a2bc4b.png)

**Comment by Chronophylos** [comment]
The last one includes your desktop

**Comment by dkNykita** [comment]
Working on it

**Comment by dkNykita** [comment]
Corrected :)
![blink_22](https://cloud.githubusercontent.com/assets/26550793/24115660/5b6fb47c-0da4-11e7-9b2b-4c08084bb94b.png)

**Comment by dkNykita** [comment]
Top-left arena
![blink_23](https://cloud.githubusercontent.com/assets/26550793/24115749/b03f9166-0da4-11e7-9ee4-82afe570b32e.png)

Also contains some weird buggy location
Teleporting here
![blink_24](https://cloud.githubusercontent.com/assets/26550793/24115828/e75c5d0a-0da4-11e7-8835-549350780579.png)
Puts me here
![blink_25](https://cloud.githubusercontent.com/assets/26550793/24115859/063efe1c-0da5-11e7-9faa-09cb320a875d.png)

**Comment by dkNykita** [comment]
I am able to get up here from this location
![blink_27](https://cloud.githubusercontent.com/assets/26550793/24116058/bc8a5090-0da5-11e7-8534-c067cae0d19f.png)
And from other side
![blink_28](https://cloud.githubusercontent.com/assets/26550793/24116102/db7b3f6e-0da5-11e7-92ea-fe39058086da.png)

**Comment by dkNykita** [comment]
Moving to right by edge of map
![blink_29](https://cloud.githubusercontent.com/assets/26550793/24116148/05faf9f0-0da6-11e7-8c15-15759d0933c7.png)

Okay... you are able to get up there from almost anywhere on the top side and also there are tons of cliffs
And just an addition, you can blink around unblinkable walls because of this out of map blink

**Comment by dkNykita** [comment]
Out of map works for right side from top-right corner up to here so far
![blink_30](https://cloud.githubusercontent.com/assets/26550793/24116292/981892f2-0da6-11e7-8937-2d8edbb99e0e.png)

**Comment by dkNykita** [comment]
There is just this specific point how to get out of map
![blink_31](https://cloud.githubusercontent.com/assets/26550793/24116340/c7ba9a64-0da6-11e7-9b03-dd42a79c29dd.png)

After long time I found a non out of map weird cliff :D 
![blink_32](https://cloud.githubusercontent.com/assets/26550793/24116396/ef7f2358-0da6-11e7-89c4-8853b81084ef.png)
From where you can blink out of map :/
![blink_33](https://cloud.githubusercontent.com/assets/26550793/24116449/212a7394-0da7-11e7-8758-dd8cbf62a86e.png)

**Comment by dkNykita** [comment]
Gonna take a break for today, I will probably continue on wednesday.

**Comment by dkNykita** [comment]
I am back and I found some more spots

You can blink in to the boss arena from this spon when blinking to cursor location
![blink_34](https://cloud.githubusercontent.com/assets/26550793/24250602/c26fba70-0fd7-11e7-8d4d-cffb4c54e172.png)

Another blinkable areas near boss arena
![blink_35](https://cloud.githubusercontent.com/assets/26550793/24250737/32cafe9c-0fd8-11e7-862f-dc30beb99ce6.png)

**Comment by warpdragon** [comment]
outdated. Thank you we will certainly revisit this issue in future if some of these same spots cause problems.
