### ISSUE TITLE
Item Reintegration | 20€ Bounty

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2094]
Some items are being integrated into the upgrade path of other items. This is experimental and this is the first wave, with more to follow, depending on user feedback. Items integrated like this can’t be bought as a tier 1 item anymore.

Blade Mail out of AC 2. Martyrs Mail out of Blade Mail 2.
Echo Sabre out of Skadi 4.
Crimson Guard out of Heart 3. Reduction Orb out of Crimson Guard.
Aeon Disk out of Bloodstone 3.

### The Atos Tree

This is also experimental. Any item from a lower tier can be build into items from higher tiers. Unlike above, in this system you can always branch back to the original path.

**Tier 1** | **Tier 2** | **Tier 3** | **Tier 4** | **Tier 5**
-----------|------------|-----------|------------|--------
Rod of Atos 1 | Rod of Atos 2 | Rod of Atos 3 | Rod of Atos 4 | Rod of Atos 5
Blank | Meteor Hammer 1 | Meteor Hammer 2 | Meteor Hammer 3 | Meteor Hammer 4
Blank | Blank | Euls 1 | Euls 2 | Euls 3
Blank | Blank | Blank | Hex 1 | Hex 2

Example Paths:
Atos 1 -> Hammer 1 -> Euls 1 -> Hex 1 -> Atos 5
Atos 1 -> Atos 2 -> Atos 3 -> Hex 1 -> Hammer 4
Atos 1 -> Atos 2 -> Euls 1 -> Atos 4 -> Euls 3

**Comment by Newton314** [comment]
i would like to try this

**Comment by imaGecko** [comment]
aw i was just about to do it, damn naps :D

**Comment by Newton314** [comment]
what should happen with the euls for allies? still build from euls 1 and adjust the tiers? or are there other plans?

**Comment by l34Um1** [comment]
That would be Euls 3.

**Comment by fordyford1** [comment]
Just an idea for uses of excess cores in the future, in these integrated FIles you could use a core to swap between items of a level in the tree. Either any core works or it has to be the same level as the switched items.

**Comment by l34Um1** [comment]
Please remove the first levels of the items from the shop as well. Currently Hex 1 can be bought and so can the other items. They should only be available at their new level. Then I'll need your paypal so I can pay you.

**Comment by mikibun** [comment]
@Newton314 have you been paid for this yet?
