### ISSUE TITLE
Mana Boots Rework | 20€ Bounty

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2095]
Mana boots still give passive GPM but the amount is attached to a new variable. This variable starts at 100 and slowly ticks down to 30. At 100 the boots give 100% of their written GPM, at 30 they give 30%. The counter ticks down by 1 every 4 seconds. 
The counter can be reset by picking up a bounty rune or upgrading the boots.

Guardian Grieves can no longer be upgraded into at any point. Instead, at level 4 Mana Boots the players get a choice between upgrading to Mana Boots 5 and keeping the farming property or upgrading to Guardian Grieves and losing the farming property. 

Please create a KV file with the following

* Mana Boot values
* Passive GPM
* Tick interval
* Maximum %
* Minimum %

The boots should also no longer give GPM while the hero is dead.

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

**Comment by emperorgustaviiadolf** [comment]
I claim this bounty

**Comment by fcalife** [comment]
If this is open for re-claiming, I'd like to do so (based on inactivity time).

**Comment by emperorgustaviiadolf** [comment]
I haven't been inactive, just haven't made a pull request in a couple days due to work + testing.

**Comment by Trildar** [comment]
Well, you didn't give any response to the comment I left on your PR over a week ago. I can't even review anything there unless I do it by looking at the commit history since the branch actually doesn't have anything in its current state.

**Comment by fcalife** [comment]
My bad, I didn't see the PR. Do use a reference to the issue you're fixing in the future to make that easier! :D

@Trildar his latest PR (there are two) has the code in it.

**Comment by emperorgustaviiadolf** [comment]
I'm really sorry! I'm new to working in this kind of format, so I'm still learning. I will make a pull request with what I have tonight so it can be seen, and please inform me if I do anything wrong in the future!

**Comment by Trildar** [comment]
It's okay. Was just pointing it out. Didn't even realise there was a different PR. You should close the other one.

**Comment by mikibun** [comment]
@emperorgustaviiadolf Are you still working on this?
