### ISSUE TITLE
Remove Tier 6 Bosses | Bounty 20€

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2096]
Remove boss tier 6. Tier 5 is the new highest. There are no bosses exclusive to tier 5. Instead tier 5 houses all bosses from all previous tiers, rebalanced with new stats. This means every boss needs 2 different KV files, one for their original tier and one for their tier 5 version. This includes their summons and abilities.

Example: Shielder is a tier 2. Shielder stays a tier 2 but also appears as a tier 5 with new stats, adequate for tier 5. Uriel is currently a tier 6. He is getting changed to be a tier 4 and, like all other bosses, a tier 5. Temple Guardians are also going to be a tier 4 and a tier 5.

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

**Comment by srxzr** [comment]
I will do it 👍

**Comment by mikibun** [comment]
@srxzr Is this being worked on?

**Comment by Haganeko** [comment]
I think this is done.
