### ISSUE TITLE
Sohei W Rework - Wholeness of Body + New level 20 talent | 20€ Bounty

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2098]
This replaces Guard.
New name: Wholeness of Body
"Sohei gains 75/80/85/90/95/100% status resistance for 2 seconds. Afterwards he gets healed for 75/150/225/300/600/900 + 25% of the damage taken during its duration."

New level 20 talent, replacing “Momentum reduces Guard cooldown”. 
“Wholeness of Body can be used on allies”. When activated on allies the ability works as it would on Sohei.

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

**Comment by Yahnich** [comment]
i want to do this

**Comment by l34Um1** [comment]
Yes but can you expand the radius to 500 units while you are at it? ty

**Comment by Yahnich** [comment]
#2129

**Comment by l34Um1** [comment]
Reopening because some things need to be changed:

* W needs a proper tooltip with numbers diplayed
* W currently doesn't apply status resistance
* W needs the healing number displayed when its healing triggers

**Comment by Yahnich** [comment]
well i've tried both status resistance modifier properties; if it's not working that means they're borked and there's no way to properly do status resistance

what tooltip do you mean, the buff?

**Comment by l34Um1** [comment]
Implemented and paid out.
