### ISSUE TITLE
Bunch of KV work | 5€ Bounty

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2099]
#### Move Charger from Tier 3 to Tier 2

No need to change his numbers.

#### Move Lycan from Tier 2 to Tier 3

No need to change his numbers.

#### Remove Refresher Core from the game

Just completely delete it. We need KV files for Refresher 1-5 and Octarine Core 1-5. Satanic core is going to be kept but loses its cooldown reduction property. It no longer builds out of Octarine 2 and Satanic 2 but instead out of Octarine 2, Satanic 1 and Upgrade Core 2.

#### Remove Urn of Sorcery
Just delete it.

**Comment by imaGecko** [comment]
gonna do this really quick
