### ISSUE TITLE
Frozen Sigil LUA help

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#210]
I created the NPC units for Frozen Sigil and added them to npc_units_custom.txt and they still don't spawn. Same thing happened with beastmaster. Anyone know the solution?

**Comment by Chronophylos** [comment]
Does Dota know what to do at level 5 & 6?

**Comment by ProstoSanja** [comment]
I looked through files, and I couldn't find any Lua associated with tusk or sigil...
Pretty strange

**Comment by KarmaticNeutral** [comment]
Demonic Conversion levels 5&6 work. Maybe compare to that?

**Comment by warpdragon** [comment]
maybe i made a mistake. there's a first for everything right?

**Comment by Trildar** [comment]
@ProstoSanja There is no Lua currently written for Tusk sigil cause it's currently using the built-in ability. A Lua rewrite of the ability will probably need to be done though.

@KarmaticNeutral Demonic Conversion only works cause it was rewritten in Lua to spawn the level 5 and 6 stuff. The Eidolons aren't even named numerically internally, so it would never work with the built-in ability. Beastmaster Call of the Wild needed to be rewritten for some reason even though the units *are* named numerically (probably Valve being silly about not looking for units dynamically like a number of the other summon abilities seem to do). Possibly the same thing is happening here with Tusk sigil.
