### ISSUE TITLE
Capture Points | 25€ Bounty

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2100]
Starting at 15 minutes capture points will appear every 10 minutes in random mirrored locations on the map. There are always 2 capture points. The captures points do not appear on the same horizontal line as the center highground. 

![unknown 3](https://user-images.githubusercontent.com/24982519/37803728-d095fed4-2e30-11e8-8eb0-9df08a4542e7.png)
This is the map.

![unknown 3](https://user-images.githubusercontent.com/24982519/37803737-e0573dec-2e30-11e8-907f-13305d739d60.jpg)
This is the area in which capture points may spawn. They always spawn mirrored both horizontally and vertically. So if one capture point spawns in the top right corner, the other one spawns in the bottom left.

Capture points are pinged out on the minimap with an announcement 1 minute before spawning, then again 30 seconds before spawning. Capture points can't be announced 90 seconds before a duel or during a duel. If they would be announced during that timeframe they get delayed until 15 seconds after the duel is over.

Capture points stay active until captured, they do not have a time limit. 

Each capture point takes 3x as long to capture as a regular boss capture. They look visually very similar although not exactly the same. They use the same capture mechanics.

Capturing a capture point gives all players on your team cores. The first set of capture points give a tier 1 core. The second a tier 2. Third tier 3. Fourth tier 4. All captures from then on give a tier 4.

**Comment by M-Faraday** [comment]
Can capture point be announced 90 seconds before a duel but then they will take place 30 second  before the actual dual?

**Comment by Haganeko** [comment]
No. Doing that means the fight over the capture points will be interrupted by the duel.

**Comment by M-Faraday** [comment]
So a capture point cant start 90 seconds before a duel. Should I also add a timer encase of a stale mate?

**Comment by Haganeko** [comment]
A... Stalemate? If the capture point would be triggered and there's <90s to a duel or it's currently a duel, defer it and trigger it 15s after the duel. You'll likely want a custom announcement for that.

**Comment by Haganeko** [comment]
BTW @L34UM1 may want to increase the timer on that to 30s

**Comment by M-Faraday** [comment]
A stalemate as in it take to long and nobody wins so that it wont interfere with other events such as duels

**Comment by l34Um1** [comment]
15s until announcement seems fine to me, that means there is still a full minute before the point appears.

**Comment by l34Um1** [comment]
Don't worry about adding an extra timer for a stalemate, we need to see this in action first.

**Comment by M-Faraday** [comment]
If the capture points are only different in colour to the boss capture points is that fine? I want to avoid capture points on ledges, is it ok if I make a list of like 50 different capture points to randomly choose from? Should the minimap ping be a full on ping with sound and everything or just an icon like bosses?

**Comment by l34Um1** [comment]
Yes. Yes, but please make sure that we can modify it in the future. Full ping with sound.

**Comment by Haganeko** [comment]
They should probably be listed in mirror pairs so as to never select two near each other

**Comment by M-Faraday** [comment]
Should the be able to spawn in boss areas?

**Comment by l34Um1** [comment]
No. Sorry, that should have been in the ticket.

**Comment by M-Faraday** [comment]
I have created a lot of points but very often if they get mirrored on the dire side the is trees in the way because the map isn't completely symmetrical. The zones in the corners clips the offside penalty and there isn't really a place to putt them so that they don't clip it. Is this fine for now?

**Comment by Haganeko** [comment]
The mirroring needn't be exact. The point is merely that a team never be near both at once. But I'll let Baumi be the judge of that.

**Comment by Haganeko** [comment]
The mirroring needn't be exact. The point is merely that a team never be near both at once. But I'll let Baumi be the judge of that.

**Comment by l34Um1** [comment]
Doesn't have to be exact. If you are manually putting the spot, then chose reasonable ones.

**Comment by M-Faraday** [comment]
Two pings cant happen at the same time (volvo). Should I let the ping happen in quick succession and them draw the spots on the minimap?

**Comment by l34Um1** [comment]
What do you mean with draw the spot?

**Comment by M-Faraday** [comment]
How spawned camps are indicated

**Comment by l34Um1** [comment]
Yes, sounds good.

**Comment by M-Faraday** [comment]
Should I notify you when I'm done or is just making a pull request enough?

**Comment by l34Um1** [comment]
It's all good, give us a bit to test and make sure it's all working.

**Comment by M-Faraday** [comment]
No problem just wanted to make sure you guys now it is actually complete

**Comment by M-Faraday** [comment]
I noticed the pull request got closed is there anymore work that needs to be done?

**Comment by M-Faraday** [comment]
I'll try to fix it as soon as possible but my university break has ended and my time is a bit divided can take up to a week.

**Comment by mikibun** [comment]
@M-Faraday Any updates on this?

**Comment by Haganeko** [comment]
This was implemented.

**Comment by Haganeko** [comment]
It's buggy tho.

**Comment by mikibun** [comment]
@Haganeko So, should I leave it open or get Baumi to open a new issue for bug fixing for it and close this one?

**Comment by mikibun** [comment]
@M-Faraday Have you been paid for this yet?

**Comment by M-Faraday** [comment]
No but I didn't finish it got busy at university sorry

**Comment by carlosrpg** [comment]
how we are handling that? we should pay him at least a share, I fixed most the bugs on the Cap point already. there is nothing else to do on this I think

**Comment by mikibun** [comment]
@M-Faraday @carlosrpg Do you guys wanna split the bounty evenly?
