### ISSUE TITLE
Hero laggs in duels

### ISSUE THREAD

**Issue by squidmaster39** [OpenAngelArena/oaa#211]
For some reason, my hero like blinks in and out of existence whilst fighting in duels. Haven't played since yesterday so it might be patched so not sure.

**Comment by Chronophylos** [comment]
Do you have a video or something?

**Comment by squidmaster39** [comment]
No sorry. I'll check now to see if the problem is still there

**Comment by squidmaster39** [comment]
ok nevermind it is patched now

**Comment by Chronophylos** [comment]
There is a button on the bottom of the page.

**Comment by squidmaster39** [comment]
ok ty
