### ISSUE TITLE
Azazel Purchasables - Summons | 30€ Bounty

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2111]
# Azazel

Azazel is a fallen angel that runs a shop in the center area of the map. This is a major new feature. This issue contains the second set of purchasable items.

Unlike the regular shop, Azazel does not trade in gold. Instead all items in his shop are only available for purchase via cores. Purchasables listed as Tier 1 will require a Tier 1 core and a 100 gold recipe, Tier 2 requires a Tier 2 core and a 100g recipe, etc.

## Summons

Summons are one time consumables that summon a controllable creature when used. These don’t get oneshot by charger, aren’t able to dominated or stolen away. They are considered heroes for all ability purposes. They can't be stacked in inventory and only one may be active at a time. Using a summon when another one is active destroys the previous one.  We currently have 3 Summons and each Summon comes at 4 power levels. All Summons last 5 minutes or until killed.

#### The Summons
* Tank: A slow, very tanky unit that does close to no damage, used for tanking bosses. Ogre Model. Melee.
* Scout: An invisible, small and fast unit. No attack values. Used for scouting. Small Satyr Model.
* Farmer : A unit with a cleaving attack and damage block, used for killing creeps. Ancient Prowler Acolyte model. Melee.

#### Tier 1
* Tank 1: 50 Armor, 10 000HP, 250 MS, 2s Attack time, 100 damage, 800 day/night vision, 0% Magic Resistance, 0 HP Regen.
* Scout 1: 0 Armor, 350 MS, 500 HP, 1200 day/night vision, 0% Magic Resistance, 0 HP Regen. Permanent Invisibility, can't attack.
* Farmer 1: 0 Armor, 2000 HP, 50 damage block with 100% chance, 2s Attack time, 300 damage, 800 day/night vision, 0% magic resistance, 0 HP Regen. 50% Cleave with 200 range.

#### Tier 2
* Tank 2: 50 Armor, 20 000HP, 250 MS, 2s Attack time, 100 damage, 800 day/night vision, 0% Magic Resistance, 0 HP Regen.
* Scout 2: 0 Armor, 350 MS, 1000 HP, 1600 day/night vision, 0% Magic Resistance, 0 HP Regen. Permanent Invisibility, can't attack.
* Farmer 2: 0 Armor, 4000 HP, 150 damage block with 100% chance, 2s Attack time, 600 damage, 800 day/night vision, 0% magic resistance, 0 HP Regen. 50% Cleave with 200 range.

#### Tier 3
* Tank 3: 50 Armor, 30 000HP, 250 MS, 2s Attack time, 100 damage, 800 day/night vision, 0% Magic Resistance, 0 HP Regen.
* Scout 3: 0 Armor, 350 MS, 2000 HP, 2000 day/night vision, 0% Magic Resistance, 0 HP Regen. Permanent Invisibility, can't attack.
* Farmer 3: 0 Armor, 6000 HP, 300 damage block with 100% chance, 2s Attack time, 1200 damage, 800 day/night vision, 0% magic resistance, 0 HP Regen. 50% Cleave with 200 range.

#### Tier 4
* Tank 4: 50 Armor, 40 000HP, 250 MS, 2s Attack time, 100 damage, 800 day/night vision, 0% Magic Resistance, 0 HP Regen.
* Scout 4: 0 Armor, 350 MS, 4000 HP, 2400 day/night vision, 0% Magic Resistance, 0 HP Regen. Permanent Invisibility, can't attack.
* Farmer 4: 0 Armor, 8000 HP, 600 damage block with 100% chance, 2s Attack time, 2400 damage, 800 day/night vision, 0% magic resistance, 0 HP Regen. 50% Cleave with 200 range.

All summons need KVs with their corresponding stats.

### Related Issues
Azazel Baseline functionality #2107 
Azazel Model #2108 
Azazel Voice #2109
Azazel Purchasables
* Elixirs #2110 
* Summons #2111 
* Buildings #2120 

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

**Comment by fcalife** [comment]
I'd like to claim this one.

**Comment by fcalife** [comment]
Implementing this, progress can be tracked on PR #2156.

Missing values used:
 - 300 MS for Farmer;
 - 1.0 turn rate for all summons.

Would you guys prefer the items to show all their levels' values, or only the current level?

e.g. for the level 2 tank summon, should it say "Tank Health: 10000/**20000**/30000/40000", or just "Tank Health: 20000"?

**Comment by l34Um1** [comment]
All values. 300 MS seems fine, sorry for leaving that out.

**Comment by fcalife** [comment]
Finished this issue with PR #2156. Included some tooltips and placeholder icons.
