### ISSUE TITLE
Magma Mage: Boss - Code | 50€ Bounty

### ISSUE THREAD

**Issue by Shusama** [OpenAngelArena/oaa#2112]
# Boss: Magma Mage
We have several bosses already implemented which you should feel free to use as inspiration/reference. Also you can reference some other open source custom games on Github which have boss fights including Second Day of Frostivus where you will find our IO boss (designed by Yahnich). Files should follow the structure already established in the components subfolders (such as /abilities/, /boss/, etc).

### See also:
Magma Mage: Boss - Model/Animations/Icons #2113 
Magma Mage: Boss - Sound #2114
Magma Mage: Boss - Particles #2115

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

### Original Description
Ranged attacking boss. Relatively low range, maybe 300. His ability is targeted at a random enemy hero.

Ability 1:
Starts out very similar to Kunkkas torrent ability but instead of being blue and water I want it to be red and magma. The outline of the torrent appears on the ground, visible to the players. The torrent then appears after a delay, pushing people into the air, damaging and stunning them.
This is where the ability diverges. After the hero lands/the torrent is back on the ground a totem spawns in the middle. This totem takes X attacks to kill. The totem starts leaking magma. This creates a circular magma field around the totem that slowly but steadily increases in size. The magma does damage to enemy heroes standing on top of it and if the Magma Mage stands on top of it, it heals him. If a totem gets destroyed the magma emitted from that totem fades away.
This ability is used whenever it’s off cooldown.

As the bosses HP drops lower he summons more torrents at once. 1 torrent from 100% - 75% hp, 2 torrents from 75% to 50%, 3 from 50% to 0%.

## 1. Lua
Unit AI: The boss should utilize a thinker in order to attempt to cast spells from a sub-list of his spells but only if they are off cooldown. If an ability requires special care or treatment this is discussed later under "Abilities". Once he is in his last phase he starts to actively try to get into the magma to heal himself.

## 2. Boss Abilities
Every ability should have a tooltip (Name, Description, KV-entries).

* Boss Resistance: Used by all bosses.
* Cliffwalking: Used by all bosses
* Volcano: The first part of this ability is basically just Kunkkas torrent. Also similar to Kunkkas torrent the location it will hit should be shown ahead of time by a particle effect on the ground. The torrents appear at random places within the abilities cast range.
After the magma torrent a totem appears at the torrents place, similar to Undyings tombstone and zeus' nimbus. With this totem as a center an aoe is slowly spreading (like overlords in Star Craft), damaging the heroes standing inside of it and healing Magma Mage if he stands inside of it. Once the totem is killed, after X attacks, the aoe effect also vanishes.  

## 3. KV
The following list of required properties to be outlined in KV is not exhaustive and coders should expand upon it as required.

**Unit**
Armor: 25
Magic Resist: -25
Hitpoints: 8500
Hitpoint Regen: 5
Manapoints: 1000
Manapoints Regen: 5 
Movement Speed: 120
Attack Damage: 4500
Attack Range: 300
Attack Rate: 2.0
XP Bounty: 900
Gold Bounty: 0
Inventory: Upgrade Core, Boss Heart
Abilities: Volcano

**Abilties**
Volcano: Cooldown, Cast Range, Torrent_AOE, Torrents_Casted, Torrent_Damage, Torrent_Stun_Duration, Totem_Health, Totem_Magma_AOE, Magma_Spread_Speed, Magma_Damage_per_Second, Magma_Heal_per_Second

## 4. Phases
* Phase 1 (100%-75%): Casts 1 torrent at once and keeps attacking when it is on cooldown.
* Phase 2 (75%-50%): Casts 2 torrents at once and keeps attacking when it is on cooldown.
* Phase 3 (50%-0%): Casts 3 torrents at once and tries to walk into the closest magma aoe while it is on cooldown.

## 5. Model & Animations
Temporary models and animations, as well as particles and sounds are needed for this ticket to be considered completed. You don't have to create anything from scratch, you may reuse anything that already exists in Dota. The base boss model may be used from the pool of existing dota 2 models respecting considerations such as attack range and basic necessary animations. 
Range: Range

## 6. Modifiers
* Any other modifier required by previous coding.

**Comment by jboxGIT** [comment]
ill claim this issue

**Comment by jboxGIT** [comment]
are these bosses supposed to be able to be infinitely scaled or just have 3 levels?

**Comment by jboxGIT** [comment]
oh is the 3 phases the 3 levels of the ability?

**Comment by l34Um1** [comment]
Yes, the three phases are the three levels of the ability. You can change the KVs but make sure you include everything important.

**Comment by jboxGIT** [comment]
Here is some progress. It is very unfinished LOL. 
https://streamable.com/6x1aw

**Comment by jboxGIT** [comment]
a little more
https://streamable.com/ci95q

**Comment by l34Um1** [comment]
Nice, although the visual effect needs to be a bit tighter. Currently it overflows super hard and it's difficult to tell where exactly the AOE is. It should be visually the same AOE as gameplay wise.

**Comment by jboxGIT** [comment]
Yea im doing particles later. I just looked for a circular one and an explody one.

**Comment by jboxGIT** [comment]
since i claimed the particles one too I worked on that some. finished the indicator at least. scales OK with delay and aoe KV's .

https://streamable.com/p1cbc

**Comment by carlosrpg** [comment]
@jboxGIT any progress?

**Comment by jboxGIT** [comment]
@carlosrpg yea sorry ill post video later today. actual ability should be done by the weekend then i just have to do the AI bit.

**Comment by jboxGIT** [comment]
https://streamable.com/0pbvx

is damage/heal from different magma pools supposed to stack or not?

**Comment by jboxGIT** [comment]
i am pretty much done with this except for like tooltips/sounds and maybe a couple particles. does this need to pass travis before anyone even looks at it?

ai is rudimentary but appears to work okay.

**Comment by jboxGIT** [comment]
here is pretty much every thing

https://streamable.com/cc98y

ill post another in a second showing knockup/stun i was playing naix oops
