### ISSUE TITLE
Magma Mage: Boss - Model/Animations/Icons | 150€ Bounty

### ISSUE THREAD

**Issue by Shusama** [OpenAngelArena/oaa#2113]
# Boss: Magma Mage
We have several bosses already implemented which you should feel free to use as inspiration/reference. Also you can reference some other open source custom games on Github which have boss fights including Second Day of Frostivus where you will find our IO boss (designed by Yahnich). Files should follow the structure already established in the components subfolders (such as /abilities/, /boss/, etc).

### See also:
Magma Mage: Boss - Code #2112 
Magma Mage: Boss - Sound #2114
Magma Mage: Boss - Particles #2115

[General Guidelines for Model Issues](https://docs.google.com/document/d/15VtqjOfyL8aZiK7ufJp-G-rPkVGza-K3IkBHrMrLN-U/edit)
[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

## 1.Model
A fiery and old mage. Should have a staff of some sort.
 
![maxresdefault 2](https://user-images.githubusercontent.com/25332142/37837622-f9fcfc48-2eb5-11e8-9fc2-839da11507e7.jpg)

## 2.Animations
His attack animation should be shooting big fireballs out of his staff or maybe his other hand. While walking he casually holds his staff on his site. 

### Phases
* In his second phase he should look a bit worn out, maybe hunching forward a bit. 
* In his third phase he should use his long staff as an additional support while walking. Keep in mind that his movement speed is generally very slow.

### Abilities
* Casting his torrent he should raise his had (similar to how it is pictured in the model image).
* The totem appearing after the torrent should look like a fire version of tusks frost sigil or zeus nimbus.

## 3.Icons
* Every ability needs its own Icon,
*There needs to be a modifier Icon for the torrent stun and the magma effect.

**Comment by DarkoniusXNG** [comment]
150 euros lmao #3291
