### ISSUE TITLE
Magma Mage: Boss - Sound | 10€ Bounty

### ISSUE THREAD

**Issue by Shusama** [OpenAngelArena/oaa#2114]
# Boss: Magma Mage
We have several bosses already implemented which you should feel free to use as inspiration/reference. Also you can reference some other open source custom games on Github which have boss fights including Second Day of Frostivus where you will find our IO boss (designed by Yahnich). Files should follow the structure already established in the components subfolders (such as /abilities/, /boss/, etc).

### See also:
Magma Mage: Boss - Model/Animations/Icons #2113  
Magma Mage: Boss - Code #2112 
Magma Mage: Boss - Particles #2115

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

## Sound
His right clicks should sound like fire/explosion, somewhat like ogre magi stun maybe.
Needs a sound effect for the magma torrent, magma leaking from the totem and for when he is healing while on top of magma/when the magma does damage to a hero. 
Overall is everything fire/magma themed

**Comment by AnArnaut** [comment]
I'll take this one.

**Comment by DarkoniusXNG** [comment]
#3291
