### ISSUE TITLE
Magma Mage: Boss - Particles | 25€ Bounty

### ISSUE THREAD

**Issue by Shusama** [OpenAngelArena/oaa#2115]
# Boss: Magma Mage
We have several bosses already implemented which you should feel free to use as inspiration/reference. Also you can reference some other open source custom games on Github which have boss fights including Second Day of Frostivus where you will find our IO boss (designed by Yahnich). Files should follow the structure already established in the components subfolders (such as /abilities/, /boss/, etc).

### See also:
Magma Mage: Boss - Model/Animations/Icons #2113  
Magma Mage: Boss - Sound #2114 
Magma Mage: Boss - Code #2112  

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

## 1.Abilities
Volcano: Before the torrents appear a particle effect on the ground indicates it (similar to Kunkka torrent). The earth should crack up and smoothly translate into the torrent of magma coming out after a short delay. 
The totem appearing after the torrent is constantly leaking magma (maybe take a look at Overlord from Star Craft 2, kind of like that).

## 2. Modifiers
Enemies standing on the magma should be visibly burning.
Magma Mage standing on the magma should be also clad in flames but it should be obvious that his flames are different since they are healing him instead of damaging him (maybe color the flames blue or green).

**Comment by jboxGIT** [comment]
i will claim this one as well.

**Comment by mikibun** [comment]
@jboxGIT Hey, any updates on this?

**Comment by jboxGIT** [comment]
yea i was doing it while i did the code and its almost done.

**Comment by DarkoniusXNG** [comment]
#3291
