### ISSUE TITLE
Second Day Spiders: Boss - Code | 50€ Bounty

### ISSUE THREAD

**Issue by Shusama** [OpenAngelArena/oaa#2116]
# Boss Second Day Spiders: 
We have several bosses already implemented which you should feel free to use as inspiration/reference. Also you can reference some other open source custom games on Github which have boss fights including Second Day of Frostivus where you will find our IO boss (designed by Yahnich). Files should follow the structure already established in the components subfolders (such as /abilities/, /boss/, etc).

### See also:
Second Day Spiders: Boss - Model/Animations/Icons #2119 
Second Day Spiders: Boss - Sound #2118
Second Day Spiders: Boss - Particles #2117

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

### Original Description
Some sort of big muscly guy. carries a backpack with little balls in them, attached to a big cannon that he carries on his back. during the fight he is always slowly moving around the arena. kinda waddling like a penguin. maybe 150 speed.

Instead of attacking he shoots some of the balls out his cannon. there are two kinds of shots: cannon and spider. they look distinctly different. the balls travel slowly and there is an indicator of where they are going to land. it’s random which ball is going to be shot.

cannon shot: when these land they explode in an area, pushing enemies 400 units away from its center and dealing damage. these shots will be fired with the intention of pushing enemies together and the boss needs adequate AI to be able to do that.

spider shot: enemies hit directly take damage and are slowed. 
the balls stay there, they can be attacked and killed. If they are not killed, 5 seconds after thrown they hatch and small spiders spawn. These are the suicide spiders from the second day of frostivus and use the same AI as them. They’ll hunt down enemy heroes and try to find the biggest cluster of units amongst them. Then they suicide, dealing damage and applying a slow in an AOE.

As he drops low on HP he will start attacking quicker.. 100% - 75% he just stands there and attacks, throwing two projectiles into a single location. 75% - 50% he starts throwing 2 two projectiles into two different locations, 4 projectiles total but they are all the same kind. past 50% he throws all 4 projectiles independently and they can be different kinds.
Sound

## 1. Lua
Unit AI: He does not attack the player but and uses his abilities while slowly waddling in a circle in the arena.The boss should utilize a thinker in order to attempt to cast spells from a sub-list of his spells but only if they are off cooldown. Finally, AOE spells should perform a calculation to attempt to hit as many units as possible and ranged spells should attempt to hit far away units. If an ability requires special care or treatment this is discussed later under "Abilities".

## 2. Boss Abilities
Every ability should have a tooltip (Name, Description, KV-entries).

* Boss Resistance: Used by all bosses.
* Cliffwalking: Used by all bosses
* Canonshot: The boss shoots out one projectile. The projectile explodes dealing damage and pushing the heroes away from the center of the explosion aoe. The boss should try to make the heroes stack up with this ability and needs an adequate AI to do so.
* Spidershot: The boss shoots out one projectile. These projectile damage and slow the enemy. Unlike the other bullets they don't explode but leave an attackable ball behind. Is this ball not killed within 5 seconds it will spawn the suicide spiders from "The Second day of Frostivius"(you can find them on github). You should keep their AI the way it is. When they explode they deal damage and slow.

## 3. KV
The following list of required properties to be outlined in KV is not exhaustive and coders should expand upon it as required.

**Unit**
Armor: 25
Magic Resist: -25
Hitpoints: 8500
Hitpoint Regen: 5
Manapoints: 1000
Manapoints Regen: 5 
Movement Speed: 150
Attack Damage: 1
Attack Rate: 200
XP Bounty: 900
Gold Bounty: 0
Inventory: Upgrade Core, Boss Heart
Abilities: Canonshot, Spidershot

**Abilties**
Canon Shot: Target_Area, Damage

Spider Shot: Target_Area, Hit_Damage, Hit_Slow, Spider_Egg_Health, Spider_Spawn_Delay, Spider_Explosion_Damage, Spider_Explosion_Slow

## 4. Phases
* Phase 1 (100%-75%): The boss shoots out two projectiles either two Canon Shot projectiles or two Spider Shot projectiles. The projectiles are hitting in the same location next to each other, similar to invokers sunstrike upgraded through his talent. Both abilities share the same Cooldown and it is randomized which kind of projectiles he shoots.
* Phase 2 (75%-50%): The boss shoots the two projectiles two times at once now. So he shoots basically two Phase 1 shots at once, a total of 4 projectiles. Like in Phase 1, all projectiles are either all Canon Shot projectiles or all Spider Shot projectiles.
* Phase 3 (50%-0%): He still shoots 4 projectiles but now they are all independendly randomized and all hit independendly, too.

## 5. Model & Animations
Temporary models and animations, as well as particles and sounds are needed for this ticket to be considered completed. You don't have to create anything from scratch, you may reuse anything that already exists in Dota. The base boss model may be used from the pool of existing dota 2 models respecting considerations such as attack range and basic necessary animations. 
Range: Melee

## 6. Modifiers
* Any other modifier required by previous coding.

**Comment by TideSofDarK** [comment]
claimed

**Comment by TideSofDarK** [comment]
Spidershot ability done
https://streamable.com/wx8y3
Banelings and their AI is imported from your frostivus2017 game

**Comment by l34Um1** [comment]
Nice. Yeah AI should just be imported. Can you make the shots go higher into the air and have a longer travel time? There also should be an indication where they land.

**Comment by TideSofDarK** [comment]
@l34Um1 there is indicator, sorry for it being hard to notice on the vid (its obsward above clinkz name)
https://i.imgur.com/o23ldZP.png
yeah i will make the height and travel speed adjustable in ability kv

**Comment by l34Um1** [comment]
Nice!

**Comment by TideSofDarK** [comment]
@l34Um1 should phase 1 projectiles be fired at once?

**Comment by l34Um1** [comment]
Yes.

**Comment by TideSofDarK** [comment]
@l34Um1 okay, so you want him to use cannonshot to stack up heroes. should this calculation be made only for one of the projectiles while the other one be targeted say 100 units from calculated target point? or should both targets be calculated?
if its second variant, can you provide quick example?

**Comment by TideSofDarK** [comment]
@l34Um1 still i'm a bit confused. some part say it wants to deal as much damage as possible and some say it needs to push heroes together, i just dont get what should be prioritized
thats what i have https://streamable.com/jojn1 (its phase 1, enabled cannonshot only)
can you check this and tell me if it's ok or maybe you have some suggestions

**Comment by l34Um1** [comment]
So Cannonshot tries to clump the enemies together. It doesn't prioritize hitting as many enemies as possible. Spidershot however tries to hit as many enemies as possible.

The idea is that Cannonshot pushes them together and Spidershot does the damage when they are together.

**Comment by TideSofDarK** [comment]
okay please review my work

**Comment by TideSofDarK** [comment]
Merged/Paid
