### ISSUE TITLE
Second Day Spiders: Boss - Sound | 10€ Bounty

### ISSUE THREAD

**Issue by Shusama** [OpenAngelArena/oaa#2118]
# Boss Second Day Spiders: 
We have several bosses already implemented which you should feel free to use as inspiration/reference. Also you can reference some other open source custom games on Github which have boss fights including Second Day of Frostivus where you will find our IO boss (designed by Yahnich). Files should follow the structure already established in the components subfolders (such as /abilities/, /boss/, etc).

### See also:
Second Day Spiders: Boss - Model/Animations/Icons #2119 
Second Day Spiders: Boss - Code #2116 
Second Day Spiders: Boss - Particles #2117 

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

## Sound
* His walking should sound heavy and impactfull with each step.
* Sounds for firing his canon and the impact of hitting canon balls.
* A sound for the spiders hatching, for the spiders themself and for the explosion of the spiders.

**Comment by AnArnaut** [comment]
I'll take this one.

**Comment by TearsOfMIllennials** [comment]
I claim this issue
