### ISSUE TITLE
Azazel Purchasables - Buildings | 30€ Bounty

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2120]
# Azazel

Azazel is a fallen angel that runs a shop in the center area of the map. This is a major new feature. This issue contains the third set of purchasable items.

Unlike the regular shop, Azazel does not trade in gold. Instead all items in his shop are only available for purchase via cores. Purchasables listed as Tier 1 will require a Tier 1 core and a 100 gold recipe, Tier 2 requires a Tier 2 core and a 100g recipe, etc.

## Buildings

Summons are one time consumables that summon an uncontrollable structure when used. These don’t get oneshot by charger, aren’t able to be dominated or stolen away. They are considered buildings for all ability purposes. They can be stacked in inventory. 

When a building is activated the player gets to select the location at which it is build. Buildings have a "construction time", during which they slowly rise out of the ground. They start the construction time with 1% of their maximum HP which linearly builds up to 100% at the end. If they take damage during this construction time that is subtracted from their current HP and also their final HP. If they reach 0 HP they get destroyed.
Example: 100 Max HP, 10s construction time. The tower gains 10HP/s. After 3 seconds construction it takes 10 damage. It's now missing 10 hp for the rest of the construction time and ends with 90HP.

We currently have 3 Buildings and each Building comes at 4 power levels. All Buildings last until destroyed.

#### The Buildings
* Defense Tower: A tower that attacks enemies in range and provides true sight. Uses a regular tower model.
* Watch Tower: A tower that gives flying vision in a large area. Uses a slimmer tower model, one from last years international would surely work.
* Wall: A wide wall that blocks movement until destroyed. Is sectioned into smaller individual parts that can be individually destroyed. Multiple [Effigy Buildings](https://dota2.gamepedia.com/Buildings#Effigy_buildings) are constructed next to each other in a straight line to form the wall. During construction they all build at once. Each section of the wall has its own stats. Ideally the wall would be vector targeted but if that's not possible have the wall created perpendicular to the line between caster and the targeted point.

#### Tier 1
* Defense Tower 1: 20 Armor, 1000HP, 1s Attack time, 100-120 damage, 700 Attack Range, 800 day/night vision, 0 HP Regen. Provides true sight in an 800 radius.
* Watch Tower 1: 20 Armor, 500 HP, 1500 flying day/night vision, 0 HP Regen. 
* Wall 1: 20 Armor, 1500 HP, 100 day/night vision, 0 HP Regen. 800 Units long (I'm not sure how many buildings that will take, you'll have to test that).

#### Tier 2
* Defense Tower 2: 20 Armor, 4000HP, 1s Attack time, 400-420 damage, 700 Attack Range, 800 day/night vision, 0 HP Regen. Provides true sight in an 800 radius.
* Watch Tower 2: 20 Armor, 2000 HP, 2000 flying day/night vision, 0 HP Regen. 
* Wall 1: 20 Armor, 6000 HP, 100 day/night vision, 0 HP Regen. 800 Units long (I'm not sure how many buildings that will take, you'll have to test that).

#### Tier 3
* Defense Tower 3: 20 Armor, 8000HP, 1s Attack time, 800-820 damage, 700 Attack Range, 800 day/night vision, 0 HP Regen. Provides true sight in an 800 radius.
* Watch Tower 3: 20 Armor, 4000 HP, 2500 flying day/night vision, 0 HP Regen. 
* Wall 3: 20 Armor, 12000 HP, 100 day/night vision, 0 HP Regen. 800 Units long (I'm not sure how many buildings that will take, you'll have to test that).

#### Tier 4
* Defense Tower 4: 20 Armor, 16000HP, 1s Attack time, 1600-1620 damage, 700 Attack Range, 800 day/night vision, 0 HP Regen. Provides true sight in an 800 radius.
* Watch Tower 4: 20 Armor, 8000 HP, 3000 flying day/night vision, 0 HP Regen. 
* Wall 4: 20 Armor, 24000 HP, 100 day/night vision, 0 HP Regen. 800 Units long (I'm not sure how many buildings that will take, you'll have to test that).

All buildings need KVs with their corresponding stats, as well as construction time.

### Related Issues
Azazel Baseline functionality #2107 
Azazel Model #2108 
Azazel Voice #2109
Azazel Purchasables
* Elixirs #2110 
* Summons #2111 
* Buildings #2120 

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

**Comment by ZzZombo** [comment]
I'll look into this.

**Comment by l34Um1** [comment]
What do you mean?

**Comment by ZzZombo** [comment]
I retract my claim, I haven't been able to familiarize myself with the code in the meantime enough, due to an unexpected turn of events IRL. Maybe some time later I'll try again.

**Comment by warpdragon** [comment]
No problem

**Comment by fcalife** [comment]
Does this require building ghosts?

**Comment by l34Um1** [comment]
Yes

**Comment by ZzZombo** [comment]
I'm working on this.

**Comment by ZzZombo** [comment]
Should the model of buildings be affected by the team?

**Comment by l34Um1** [comment]
would be neat although not required

**Comment by ZzZombo** [comment]
Here is a screenshot (building, defense tower in construction phase): https://www.dropbox.com/s/lw5nmp30f9sktg3/shot_0002.tga?dl=0. I have some questions though:

- I couldn't find any tower models for the Watch tower as you described in the Asset Browser. Do you happen to know the names?
- What are the construction times for the buildings?
- Am I not supposed to create the item definitions? If the answer is no, then I need all the desired values for their properties, like cast range and so on.
- How much default-tower-like do the first two types of buildings have to be? The default tower base class has a bunch of unwanted traits, like destruction messages and the like, so I based my structures on the filler base class, but it's not an exact replica, of course, namely it doesn't have the Tower Protection and Tower Armor abilities, and have a bit different AI: it can attack neutral creeps, for instance.

**Comment by ZzZombo** [comment]
I'm about 90% done with this (see https://www.dropbox.com/s/tu7c9keomc5wx3d/shot_0198.jpg?dl=0 and https://www.dropbox.com/s/2mhv7g7ds595l67/shot_0199.jpg?dl=0), but there are some more questions:

- What to do, if a unit occupies a building's location? Especially relevant for the Wall segments.
- Am I supposed also to make the default translations?

**Comment by l34Um1** [comment]
Answering your questions:
- shouldn't there lots of different tower models because of last year's ti compendium? Just use the one of those that fits the description the best
- 10s construction time but make sure to put it into of
- just put whatever and make sure to put it into kv. I'll balance it later
- as you have it seems good
- push them out
- I'm not sure what you mean. You should put tooltips

**Comment by ZzZombo** [comment]
@l34Um1:

> shouldn't there lots of different tower models because of last year's ti compendium? Just use the one of those that fits the description the best

I am apparently unable to find any. I tried different keywords with the "models only" filter in the Asset browser, but nothing other than the default structure models comes up.

**Comment by ZzZombo** [comment]
Paid, thanks.
