### ISSUE TITLE
Swiper: Boss - Code | 50€ Bounty

### ISSUE THREAD

**Issue by Shusama** [OpenAngelArena/oaa#2123]
# Boss Swiper
We have several bosses already implemented which you should feel free to use as inspiration/reference. Also you can reference some other open source custom games on Github which have boss fights including Second Day of Frostivus where you will find our IO boss (designed by Yahnich). Files should follow the structure already established in the components subfolders (such as /abilities/, /boss/, etc).

### See also:
Swiper: Boss - Model/Animations/Icons #2124
Swiper: Boss - Sound #2126
Swiper: Boss - Particles #2125

[Bug Bounty Guideline](https://docs.google.com/document/d/1Tpm0j1ekVc6X-LRlF_6Q81RMGVlOOO5EBvSf_xAQk4I/edit)

## 1. Lua
Unit AI: The boss should utilize a thinker in order to attempt to cast spells from a sub-list of his spells but only if they are off cooldown. Finally, AOE spells should perform a calculation to attempt to hit as many units as possible and ranged spells should attempt to hit far away units. If an ability requires special care or treatment this is discussed later under "Abilities".

## 2. Boss Abilities
All abilities should be telegraphed by a particle effect outlining the location, area, and general motion of the ability. Abilities require a significant "wind-up" animation to play accompanied by a targetting reticle before executing the damage, so players will learn to dodge his abilities. All art associated with his abilities should follow a similar style/color palette. Every ability should have a tooltip (Name, Description, KV-entries). 

* Boss Resistance: Used by all bosses.
* Cliffwalking: Used by all bosses
* Thrust: Long range (~600u), targeting the ground at the location of a player furthest away from the boss up to a certain range. Damages in an AOE line.
* Frontswipe: Swing the sword in a 180-degree arc counter-clockwise. Short range (~200u), targetted to hit as many players as possible.
* Backswipe: Occasionally (~25%) and immediately follows frontswipe swinging the sword in a 180-degree clockwise arc. Short range (~200u).
* Reaper's Rush: Holds the sword to the right, perpendicular to his facing direction. Runs quickly to a far away location in the arena in the direction of the highest concentration of players. Players hit by the sword take massive damage. Enemies hit by the boss's body take moderate damage, are pushed away (~100u), and are slowed. Upon reaching his destination, swings the sword in a 360-degree arc counter-clockwise.

## 3. KV
The following list of required properties to be outlined in KV is not exhaustive and coders should expand upon it as required.

**Unit**
Armor: 25
Magic Resist: -25
Hitpoints: 4000
Hitpoint Regen: 10
Manapoints: 2500
Manapoints Regen: 5 
Movement Speed: 350 
Attack Damage: 200-320
Attack Rate: 1.45
XP Bounty: 900
Gold Bounty: 0
Inventory: Upgrade Core, Boss Heart
Abilities: 

**Abilties**
* Thrust: Delay, Range, Width, Target_Max_Range, Target_Min_Range, Damage, Cooldown
* Frontswipe: Delay, Start_Angle, End_Angle, Range, Min_Targets, Target_Max_Range, Damage, Cooldown
* Backswipe: Delay, Start_Angle, End_Angle, Range, Damage, Cooldown
* Reaper's Rush: Delay, Speed, Max_Range, Min_Range, Min_Targets, Push_Length, Slow, Slow_Duration, Max_Damage, Min_Damage, Start_Angle, End_Angle, Cooldown

## 4. Phases
**Phase 1 (100%-75%)**
*  Sub-list of abilities: Thrust, Frontswipe and Backswipe

**Phase 2 (75%-50%)**
* Sub-list of abilities: Thrust, Frontswipe, Backswipe, Rush

**Phase 3 (50%-0%)**
* Sub-list of abilities: Thrust, Frontswipe, Backswipe, Rush, Teleport 

## 5. Model & Animations
Temporary models and animations, as well as particles and sounds are needed for this ticket to be considered completed. You don't have to create anything from scratch, you may reuse anything that already exists in Dota. The base boss model may be used from the pool of existing dota 2 models respecting considerations such as attack range and basic necessary animations. 
Range: Melee

## 6. Modifiers
* Any other modifier required by previous coding.

**Comment by damiangweber** [comment]
claimed

**Comment by TideSofDarK** [comment]
Claimed

**Comment by TideSofDarK** [comment]
Is delay supposed to be cast animation time?
If you are going to have custom models i suppose animations should be that delay.

**Comment by l34Um1** [comment]
So all of this guys attacks have a wind-up time. The delay described here is that wind-up. It's supposed to indicate to the players what attack is going to come out and where it's going, giving them time to react. You should not be able to interrupt his attacks, not during this delay or at another point, because he doesn't regularly auto-attack.

**Comment by TideSofDarK** [comment]
It's still unclear if that windup time is animation or something else like he stands still and there is some particle or whatever.

**Comment by TideSofDarK** [comment]
Im just curious if this delay is "AbilityCastPoint" which is animation time before ability impact

**Comment by l34Um1** [comment]
Yes, essentially. It's just important that it can't be interrupted, like a normal cast point.

**Comment by TideSofDarK** [comment]
https://streamable.com/a8htb
Look, here i press frontswipe and backswipe manually but i wonder if animation speed is right.
The issue states that backswipe should be immediate so i made it as fast as animation allows me to.
Red dots indicates the 180 arc (damage area)

**Comment by l34Um1** [comment]
Animation speed seems good. You misunderstood backswipe. Frontswipe is basically a swing going from right to left, backswipe then connects to that afterwards and after a short delay goes from left to right, without resetting the sword he is supposed to have back to the starting position. Check out the Model/Animation ticket, it has some pictures.

**Comment by TideSofDarK** [comment]
so basically a mirrored version of frontswipe

**Comment by TideSofDarK** [comment]
Merged/Paid
