### ISSUE TITLE
Stackable Bottles

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#215]
Very curious to see what happens when u make bottle stackable. Baumi mentioned this in the video. It was more of a joke than anything. Figure we might as well just try it.
Should just require
`"ItemStackable" "1"`

**Comment by dkNykita** [comment]
Tell us how this works when you will test it

**Comment by Chronophylos** [comment]
I don't think this will work.

**Comment by Declow0** [comment]
I tried do it. https://github.com/Declow0/oaa/blob/stackable_bottles/game/scripts/npc/items/item_bottle.txt

But 9 and over charges crashed game.

**Comment by Declow0** [comment]
I think drop from creeps should be like in darkmoon:
item_health_potion, item_mana_potion.
Or something new...

And change list of item here https://github.com/OpenAngelArena/oaa/blob/master/game/scripts/vscripts/components/creeps/item_drop.lua .

**Comment by Honeth** [comment]
Declow0 you probably joined the party late we've talked about doing what darkmoon had but due to people loving bottle's were probably going to keep bottle's in the game might reduce drop rate a bit and make empty bottles stack-able instead of normal bottles. we might change the other items to drop things like darkmoon had.

**Comment by warpdragon** [comment]
Are you serious?

**Comment by warpdragon** [comment]
The creep drop system is currently absolutely fucking retarded. Also Honeth the stackable bottles thing was kind of a joke.

**Comment by warpdragon** [comment]
I just wanna see what it would do if we changed that kv. Sux i havent tested it yet and wont be able to for a while

**Comment by Honeth** [comment]
i could test giving bottle's stackable in kv i just think it's gonna stack them like tango's would stack but instead of using 1 charge every time it's gonna use 1 charge of every bottle in the stack every time. at least thats what i think

**Comment by warpdragon** [comment]
Will be interesting. If its awsome take a vid if u can and put it on youtube

**Comment by Trildar** [comment]
I'm pretty sure I saw someone saying somewhere that giving Bottles the stackable property in KV made it crash above 9 charges.

**Comment by warpdragon** [comment]
Its over 9000!!!

**Comment by Honeth** [comment]
welp stackable added to bottles does this https://www.twitch.tv/videos/130622799 6 min steam of me messing with it untill it crashed the game when i picked up 2 new bottles with 1 in my inv making it have 9 charges which crashed the game

**Comment by Chronophylos** [comment]
We should create our own bottle:
* You can't buy them
* Infinitely stack-able
* Not rechargeable by the fountain
* Trade-able to other players

**Comment by warpdragon** [comment]
sorry i made a duplicate thread. >>334

**Comment by warpdragon** [comment]
sorry i made a duplicate thread. >>#334
