### ISSUE TITLE
Fix Bounty rune timing | 5€ Bounty

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2163]
Bounty runes currently don't spawn every other minute on the X:00 mark. Instead they spawn at a random timing based on how long the picking took. This is due to the way our custom pick screen works, the game is already running, we just manually reset the clock.

Fix the timing on the bounty rune spawns so they always spawn every other minute at x:00, starting at 0:00. So at 2:00, 4:00, 6:00, 8:00, etc.

**Comment by Trufllehunt** [comment]
claimed

**Comment by DarkoniusXNG** [comment]
Give bounty to @chrisinajar or we riot. xP
