### ISSUE TITLE
Rework TPs

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2164]
- [ ] Add a button for TPing. This button is the same as our current buttons for Scan and Wards. It's placed close to the other 2.  When activated, this button acts exactly the same as a TP scroll. It displays its cooldown just as Scan and Wards do. This button uses the hotkey for "saved camera position 10" and replaces its functionality

- [ ] Remove TP scrolls from the shop.

- [ ] TP Boots now require a farming core to be upgraded to TP Boots level 2. Meaning that regular TP Boots don't let you teleport to allied heroes, only if you upgrade your TP boots with a farming core will you be able to TP to allied heroes. This also means all TP Boot values need to be pushed down one level as it loses one level in total.

- [ ] TP Boots and the TP button share cooldown.

**Comment by DarkoniusXNG** [comment]
This can be closed too I guess.
