### ISSUE TITLE
Add a Duel Timer, Kill Score Limit and capture point timing indicator | 20€ Bounty

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2165]
![unbenannt-1](https://user-images.githubusercontent.com/24982519/35267044-50285c80-0025-11e8-8179-d96915598fc1.jpg)

Picture taken from Black Star. Similar to this. The menu below the clock shows up when you hold alt. Add the text "Score limit" and "Next Duel" in front of the 2 numbers, as well as a third value "next capture point" and the corresponding timer.

**Comment by chrisinajar** [comment]
I like not having duel timer, I disagree it should be added. I'd be fine with it appearing during the last 60 seconds, but not before then.

**Comment by Haganeko** [comment]
Why so? I thought this had been debated and all objections overruled.

**Comment by carlosrpg** [comment]
Claim

**Comment by carlosrpg** [comment]
@l34Um1 I would like to receive that on a different paypal account, let me know when you plan to pay this

**Comment by DarkoniusXNG** [comment]
This was implemented.
