### ISSUE TITLE
Can't load mod on aaa map

### ISSUE THREAD

**Issue by Declow0** [OpenAngelArena/oaa#219]
I download mod and install it following instruction.

I can launch mod by:
`dota_launch_custom_game oaa dota`

But I can't load on aaa map. Because:
`[ W ResourceSystem ]:
Error loading resource file "particles/rain_fx/econ_weather_aurora_j.vpcf_c" (Error: ERROR_FILEOPEN)`

And my dota client doesn't have this file, but it has
econ_weather_aurora_e.vpcf
econ_weather_aurora_i.vpcf

**Comment by Chronophylos** [comment]
Is normal Dota running too?

**Comment by Declow0** [comment]
Yes. Standart Dota match works.

**Comment by Chronophylos** [comment]
I mean is it running at the same time?

**Comment by Declow0** [comment]
1) I rightclick on Dota 2 in Steam, choose Launch Dota 2 - Tools.
2) In Custom Games category double click on oaa.
3) Open console click '\' on keyboard.
4) Execute in console
`dota_launch_custom_game oaa aaa`

**Comment by Chronophylos** [comment]
Try verifying your game cache.
This shouldn't happen and has never happened to me.

**Comment by Declow0** [comment]
Nothing change. Do you have this file
econ_weather_aurora_j.vpcf_c

in dota 2 beta\content\dota\particles\rain_fx?

**Comment by DoctorGester** [comment]
Missing particle won't stop a map from loading.

**Comment by Declow0** [comment]
[   WorldRenderer        ]: Failed to mount world vpk fike maps\aaa.vpk, file could not be found.

**Comment by DoctorGester** [comment]
Then you didn't build the map properly.

**Comment by Chronophylos** [comment]
Oh
Yes
You need to build the map.
Start hammer and press `F9`

**Comment by Declow0** [comment]
@DoctorGester @Chronophylos Thanks a lot! It works now. I think this part should be in instruction.

**Comment by Chronophylos** [comment]
Will be added.
