### ISSUE TITLE
Re-implement Drums of Endurance

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#2191]
Vanilla Drums seem to not appreciate being told to not use charges. There have been numerous reports of it causing lag and the active only working the first time. Easiest solution is probably just to re-implement the item since it should be a fairly simple item.

**Comment by Sythrus** [comment]
Doesn't Imba already have drums without charges?

**Comment by Trildar** [comment]
Dunno, if it does, we can probably just ask them if we can ~~steal~~ use their code. Though there aren't really many active OAA developers to even do that right now.

**Comment by DarthRecca** [comment]
I'm on it. Will try to report by tomorrow. Also won't be using branch/forks so how do I submit the code?

**Comment by Haganeko** [comment]
If you don't use git, someone will have to use it for you.

**Comment by mikibun** [comment]
Has this been submitted yet? @DarthRecca @Haganeko

**Comment by DarthRecca** [comment]
@mikibun It has been submitted. But before it is closed or merged, I am going to test it out. Just need to find some free 1-2 hours time. Will be done before this week-end.

**Comment by MountainEucalyptus** [comment]
Has this been resolved and the issue not closed or is it still not fixed? I am wanting to start trying to help with OAA and if this is not resolved then it could be ideal

**Comment by DarkoniusXNG** [comment]
There is a Pull Request for this. But it was never added for some reason.
