### ISSUE TITLE
There are 2 different Euls in the game

### ISSUE THREAD

**Issue by zelding** [OpenAngelArena/oaa#2195]
Both the vanilla and the OAA Euls are available in the shop somehow.

I can't remember how I bought them, but i have [pics](https://imgur.com/a/bE6iau3)

They **don't** share cd.

**Comment by Haganeko** [comment]
Isn't one of them Eul's Scepter of Sanctity (a different item)?

**Comment by zelding** [comment]
No, check the screenshots ;)
