### ISSUE TITLE
Night stalker's passive

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#221]
doesn't appear to do anything and didn't feel like it

**Comment by chrisinajar** [comment]
at all levels? did it not appear to do anything, or did it actually not increase any numbers at all?

**Comment by KarmaticNeutral** [comment]
I didn't do anything at any level as far as we could tell.

**Comment by ProstoSanja** [comment]
I'll test in couple of hours

**Comment by ProstoSanja** [comment]
night stalker works okay, stats update in info bars and also ingame

![20170321114212_1](https://cloud.githubusercontent.com/assets/26527928/24141243/90842af8-0e2b-11e7-8205-58a970301f45.jpg)
![20170321114221_1](https://cloud.githubusercontent.com/assets/26527928/24141245/909a2150-0e2b-11e7-91e5-febc0fe3f158.jpg)
![20170321114225_1](https://cloud.githubusercontent.com/assets/26527928/24141246/90a84da2-0e2b-11e7-94a3-ae7464e3c425.jpg)
![20170321114228_1](https://cloud.githubusercontent.com/assets/26527928/24141247/90a85004-0e2b-11e7-95a8-8ba0822ac684.jpg)
![20170321114231_1](https://cloud.githubusercontent.com/assets/26527928/24141250/90aadc5c-0e2b-11e7-9798-020decd02083.jpg)
![20170321114234_1](https://cloud.githubusercontent.com/assets/26527928/24141249/90aa1fa6-0e2b-11e7-92ce-5c386821beaa.jpg)
![20170321114237_1](https://cloud.githubusercontent.com/assets/26527928/24141248/90a98f50-0e2b-11e7-9c4a-ef9fe6c4fe99.jpg)


can be closed
