### ISSUE TITLE
Fervor values for troll

### ISSUE THREAD

**Issue by WispY** [OpenAngelArena/oaa#2211]
```
\oaa\game\scripts\npc\abilities\troll_warlord_fervor.txt
DOTAAbilities.troll_warlord_fervor.AbilitySpecial.01.max_stacks = "7 7 7 7 6 4"
```
This does not look right, should it really decrease at lvl 5/6?

**Comment by Trildar** [comment]
Yes. If you check the attack speed per stack and do the math, you'll see you get around the same increase in attack speed at max stacks. The rationale was to buff it by making you hit max faster rather than increasing the max amount.
