### ISSUE TITLE
Come up with a new name for Cofveve and give it a new icon

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2228]
Old name is an outdated meme. Will take any suggestions.

**Comment by Haganeko** [comment]
I suggest "Blade of the Erelim"
Blade because it is a weapon, and the Erelim are a class of angels associated with delivering earthly justice.

**Comment by zelding** [comment]
Bloodfreezing ? Cryo-blood ?

**Comment by Haganeko** [comment]
Blade of Judecca, then? The fourth and central ring of the ninth circle of hell in the Divine Comedy, where Satan sits within a frozen lake?

**Comment by Haganeko** [comment]
Could also use Cocytus, the name of the lake itself.

**Comment by BigButtsLover** [comment]
There's a Norse mythcal sword that fits perfectly-"Dáinsleif":

Dáinsleif (Dáinn's legacy), king Högni's sword that gave wounds that never healed and could not be unsheathed without killing a man.
(Source Wikipedia)

**Comment by fcalife** [comment]
For reference, the weapon that causes wounds which never heal is a semi-common trope in ancient mythos. Some alternate versions of the Dáinsleif include the [Shamshir-e Zomorrodnegār](https://en.wikipedia.org/wiki/Shamshir-e_Zomorrodnegar), the [Gáe Bolg](https://en.wikipedia.org/wiki/G%C3%A1e_Bulg) and the [Skofnung](https://en.wikipedia.org/wiki/Skofnung). I like the last two names better for being less obscure and easier to pronounce, but that might be my final fantasy bias speaking.

**Comment by Haganeko** [comment]
The issue with most of these suggestions is they escape the already frail and beaten oaa thematic of judeo christian mythology

**Comment by fcalife** [comment]
I mean, its current name is _**covfefe**_.

**Comment by SquawkyArctangent** [comment]
Would "Heartbreaker" be too on-the-nose? :v

**Comment by Haganeko** [comment]
Yes, a temporary meme name. Now we're probably settling on a permanent one.

**Comment by fcalife** [comment]
@Haganeko there's like zero (?) custom item names currently having anything to do with judeo christian mythology. Item names are usually downright descriptive like "giant form" or "far sight". The only reference to said mythology is a giant demon in the center of the map that had no function until his shop was added. I think it's somewhat safe to say sticking to this mythos is not a high priority or even a priority at all currently.

@SquawkyArctangent Iceblaster https://imgur.com/WCtQXqs

**Comment by Booty-Smasher** [comment]
Skaði (Skadi) is the Goddess of Winter in Norse mythology.
Skaði (Skadi) means "damage" or "harm" in Old Norse and Icelandic, pronounced "Skathi".
Þjazi (Thiazi), Skadi's father in Norse mythology, had his eyes placed in the night sky as stars.

The lore behind skadi is deep, and as such the "Covefe" should be related to skadi or the eyes, and should relate back to norse mythology. Skadi is known for skiing and using a bow, so an ice Bow would make since, or you could relate it to her husband, who she was given by the gods for compensation for killing her father, or relate it to the venom she dipped on Loki, since it reduces the healong effect. Sorry For All Of The Words!

**Comment by Booty-Smasher** [comment]
Healing*

**Comment by chrisinajar** [comment]
The name is okay, it'll be hard to replace. The icon is a meme, it will be trivial to replace.

**Comment by DarthRecca** [comment]
I think If we are to stick to Judeo-christian theme, then a possible contender would be, Leraje. He is a Marquis of Hell. A demon from the Ars Goetia, who is said to incite wars and cause "Gangrene wounds" from the arrows. And Gangrene Wounds kind of matches the current description of Covfefe. The Gangrene is tissue death, and is almost impossible to heal unless decapitated/surgically removed. 
But with magic, angels and demons in this world it would be easier to heal Gangrene. As such having Leraje's Bow as the name would suit it quite well.
Citations:
Gangrene: https://en.wikipedia.org/wiki/Gangrene
Leraje: https://en.wikipedia.org/wiki/Leraje
Hope it helped.

**Comment by warpdragon** [comment]
It's fine now. Why? Because I am here!

**Comment by warpdragon** [comment]
A concept for an Ice "Skofnung" ![concept](https://user-images.githubusercontent.com/13878439/42741052-a1af9228-8863-11e8-9af0-fa435b1e1f43.png)

Based on this: 
![source](https://user-images.githubusercontent.com/13878439/42741063-b7aa018a-8863-11e8-9b77-0e894270f2e0.png)

**Comment by warpdragon** [comment]
I also like the idea of lerajes bow. Hmmm

**Comment by DarthRecca** [comment]
![leraje s bow](https://user-images.githubusercontent.com/22368319/43012639-4ccd093e-8c64-11e8-9c4b-6eb7691e9f52.jpg)
Made a small quick icon for leraje's bow(I know it's crappy but I don't have warpdragon level of skill)

**Comment by warpdragon** [comment]
call me crazy but that sure looks like you ripped off an existing asset from somewhere

**Comment by warpdragon** [comment]
Version 2
![image](https://user-images.githubusercontent.com/13878439/43027702-b776a0ee-8c30-11e8-868c-4fd8ed557c85.png)

**Comment by warpdragon** [comment]
Version 3
![image](https://user-images.githubusercontent.com/13878439/43029020-3badaf72-8c38-11e8-9c87-5b124a43620a.png)

**Comment by warpdragon** [comment]
Version 3
![image](https://user-images.githubusercontent.com/13878439/43029126-cbad466e-8c38-11e8-8299-e4ffc250f239.png)
