### ISSUE TITLE
Fix Arc Warden illusion having access to Azazel consumables

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2235]
Currently Arc Warden can buy a tower or summon or elixir and when using his ultimate the illusion will have it in its inventory. It can then place the tower/use the consumable, effectively ignoring the cost associated with purchasing the item.

Arc Warden already has a banlist of items that the illusion can't have in its inventory. Simply add the Azazel consumables to that list.

**Comment by SquawkyArctangent** [comment]
For reference, saying that Arc Warden has a banlist is inaccurate in important ways - namely, phrasing it like that makes it sound like it'd require modifying Tempest Double, which would be an _incredible_ amount of work.

It's the exact opposite, though, in difficulty and in what's preventing the copying - this is literally a single line fix per item, somebody just needs to slap "IsTempestDoubleClonable" "0" onto each item's KV file.

**Comment by Jacob-Koger** [comment]
I am doing this now

**Comment by GymLeaderGiovanni** [comment]
Fuck my bad already did this sorry

**Comment by Jacob-Koger** [comment]
*thumbs up* glad i said something :P

**Comment by GymLeaderGiovanni** [comment]
Yeah sorry didn’t think anyone would claim cause there was no bounty so I just did it

**Comment by chrisinajar** [comment]
pretty sure this is done
