### ISSUE TITLE
Implement a new farming boot: Blink Boots | 15€ Bounty

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2238]
Requires: 
Brown Boots + Blink Dagger + Farming Core + 100g Recipe

Active: Teleport to a target point up to 400/500/600/700 units away. 

Blink Dagger cannot be used for 3 seconds after taking damage from an enemy hero.

No manacost. Cooldown 15/14/13/12s. 
Movement Speed Bonus: 60/70/80/90.

**Comment by Booty-Smasher** [comment]
That doesnt directly make you money, or help you kill creeps...

**Comment by zelding** [comment]
What about this:
if you blink near creeps it deal a percentage of your attack damage around you + some nice landing/impact animation

**Comment by DarthRecca** [comment]
I think I can work on Blink Boots. Will need to know if you want to add any farming item potential.

**Comment by DarthRecca** [comment]
Claimed please 😄
