### ISSUE TITLE
Game wont count boss kills after disconect and duels wont work.

### ISSUE THREAD

**Issue by Botinha93** [OpenAngelArena/oaa#2264]
If you disconnect right before a duel and reconnect after it finds that there are no players left for the duel the game wont count boss kills for any of the teams, duels also wont get triggered till one of the teams gets 100 kills, them the final duel works as intended.

OBS: if you die the kills count gets back to normal but the duels still wont trigger and your last death will not show up on the score board.

![bug1](https://user-images.githubusercontent.com/23388260/42415459-9c9418a2-8225-11e8-9a68-1f9658c8be50.png)
![bug2](https://user-images.githubusercontent.com/23388260/42415460-9cb3fa8c-8225-11e8-860d-daf88ee4fa03.png)

**Comment by carlosrpg** [comment]
Not able to reproduce
