### ISSUE TITLE
Make Cleave physical damage that's reduced by armor

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2289]
Currently cleave is physical damage that isn't reduced by armor. Change this to be physical damage that is reduced by armor. Don't change any of the other cleave calculations.

**Comment by fcalife** [comment]
Use 3 findunitsinline - find the enemies in a rectangle that contains the trapezoid, then remove from that list the ones in the two triangles that belong to the rectangle, but not the trapezoid

**Comment by fcalife** [comment]
https://hastebin.com/urabewohab.lua

**Comment by Trildar** [comment]
`Vector( vDirection.y, -vDirection.x, 0.0 )` That's not how you get a perpendicular vector. Assuming that's what you wanted.

**Comment by fcalife** [comment]
I've no idea what the creator wanted, all i know is its implemented in dota imba, so I assume it works.

**Comment by Trildar** [comment]
Ignore me. Got confused. This code definitely makes a number of assumptions though. Such as `vDirection` being a unit vector and `endRadius` never being less than `startRadius`. Would probably make much more sense to change it to use a line search as the basis.

**Comment by AbitTheGray** [comment]
Work-In-Progress
I hope to get it ready in 2 weeks to have it ready for tournament.

```
CDOTABaseAbility:PerformCleave()
CDOTA_BaseNPC:PerformCleave()
```

**Comment by DarkoniusXNG** [comment]
https://github.com/OpenAngelArena/oaa/blob/81e9680b04d77735e1d42f5a7f8c1fc090af54e7/game/scripts/vscripts/abilities/swiper/boss_swiper_swipe.lua#L18

**Comment by DarkoniusXNG** [comment]
This can be closed. Cleave is reworked.
