### ISSUE TITLE
Purge ongoing abilities/buffs/debuffs when going into a duel

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2294]
Currently: Activate Medusa ult, duel starts, Dusa ult is still happening.
Changed to: Activate Medusa ult, duel starts, Dusa ult isn't happening anymore.

Currently: Activate BKB, duel starts, BKB is still happening.
Changed to: Activate BKB, duel starts, BKB isn't happening anymore.

Currently: Affected by Fury Swipes, duel starts, still affected by Fury Swipes.
Changed to: Affected by Fury Swipes, duel starts, no longer affected by Fury Swipes.

The only exception to this are elixiers. Please make an orange note on elixiers that states that these will not be purged when going into a duel.

**Comment by Trildar** [comment]
There isn't really any way to do this in a blanket manner. Modifiers to be removed would have to be in a specific list. Given, I'm not sure if we currently have a strong purge applied at start of Duel, but all of the things you listed here would not be affected by that anyway.

**Comment by Trildar** [comment]
I guess one way might actually be to just kill everyone. That'll probably get rid of most things.

**Comment by l34Um1** [comment]
Wouldn't get rid of TB transform. But yeah other than that, just killing everybody sounds like a great idea.

**Comment by DarkoniusXNG** [comment]
This should work in theory:
```
local modifier_exceptions ={
    "modifier_elixier_burst_active",
    "modifier_elixier_burst_trigger",
    "modifier_elixier_burst_bonus",
    "modifier_elixier_sustain_active",
    "modifier_elixier_sustain_trigger",
    "modifier_elixier_hybrid_active",
    "modifier_elixier_hybrid_trigger"
	}
-- Find All modifiers (ALL buffs, debuffs, passives)
local all_modifiers = unit:FindAllModifiers()
-- Iterate through each one and check their duration
for _, modifier in pairs(all_modifiers) do
	-- Get the duration of the modifier
	local modifier_duration = modifier:GetDuration()
	-- Modifiers with duration -1 (infinite duration) are passive modifiers - auras, item stats etc.
	if modifier_duration ~= -1 then
	-- Get the name of the modifier
		local modifier_name = modifier:GetName()
		-- Initializing handle: safe_to_remove
		modifier.safe_to_remove = true
		for i=1, #modifier_exceptions do
			if modifier_name == modifier_exceptions[i] then
				modifier.safe_to_remove = false
			end
		end
		if modifier.safe_to_remove == true then
			unit:RemoveModifierByName(modifier_name)
		end
	end
end
```
It removes all modifiers with non-infinite duration. It doesn't purge/dispels the unit, it **removes** everything that has a duration from the unit - so there may be some errors if Valve messed up some buffs and debuffs. I have a feeling Morphling's Morph will be a problem. But maybe I am not right. You can always test it, you have nothing to lose.
