### ISSUE TITLE
Giant Form attack rate should override everything else

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2295]
Currently Sohei and Riki ult bypass Giant Forms attack rate debuff. Instead they should be slowed to Giant Forms attack rate.

**Comment by DarkoniusXNG** [comment]
Just an idea how to easily fix this. Giant Form maybe doesn't work while someone is invulnerable. Add the following:
```
function modifier_item_giant_form_grow:GetAttributes() 
	return MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE
end
```
inside giant_form.lua somewhere here: https://github.com/OpenAngelArena/oaa/blob/master/game/scripts/vscripts/items/transformation/giant_form.lua#L35

If this doesn't work you will need a way to detect when abilities like Riki/Sohei ults are cast and then override the fixed attack rate with a new modifier (or force the refresh event on the modifier_item_giant_form_grow).

**Comment by Trildar** [comment]
That's not the issue. If it didn't work at all, it wouldn't be a balance issue. It still gives the bonus attack damage and splash effect. It doesn't affect those abilities because those abilities don't care at all about the hero's attack rate.

**Comment by DarkoniusXNG** [comment]
Ah my bad. Then you need reworked Sohei ult and reimplemented Riki ult.

**Comment by AbitTheGray** [comment]
How do you imagine that?
React to current attack-speed? Or check whenever is `Giant Form` active to use its attack speed?
