### ISSUE TITLE
Implement item: Preemptive Reflex 1

### ISSUE THREAD

**Issue by zelding** [OpenAngelArena/oaa#230]
**Active**: 50% dmg reduction for 2s

Expose all variables for KV files:
 - duration (use the existing `duration`)
 - damage reduction

**Notes**:
- Damage reduction shouldn't apply on `pure` damage
- shouldn't require targeting, always applies to caster

**Comment by chrisinajar** [comment]
cooldown?

**Comment by Haganeko** [comment]
You sure this doesn't apply to pure? It's supposed to be a safeguard against ganks.

**Comment by warpdragon** [comment]
i think in the spirit of the item being "super useful" in a very active, interaction-based outplay-your-opponent type of game, lets keep the CD low if possible.

**Comment by chrisinajar** [comment]
I did 20s cd and 50 mana cost.

I guess it could be more like 10s cd. Either way those values are nicely in the KV, so balance team can tweak those very very easily.
