### ISSUE TITLE
Implement Item: Preemptive Reflex 2

### ISSUE THREAD

**Issue by zelding** [OpenAngelArena/oaa#231]
Official Documentation - http://tinyurl.com/Reflex-Items

**Active**: Constant soft dispell for 2s for incoming debuffs

Expose all variables for KV files:
 - duration (use the existing name `duration)`
 - tickrate *or* number of ticks (?)

**Notes**:
- Damage reduction shouldn't apply on `pure` damage
- shouldn't require targeting, always applies to caster

**Comment by chrisinajar** [comment]
"soft dispell" = purge but don't break stun, right?

**Comment by Trildar** [comment]
Dota has soft and hard purges/dispells and corresponding definitions on ability effects/modifiers on whether they can be purged by soft, strong, or not at all.

I believe all stun effects require strong dispells.

**Comment by chrisinajar** [comment]
these are the actual parameters, fwiw
`(bool RemovePositiveBuffs, bool RemoveDebuffs, bool BuffsCreatedThisFrameOnly, bool RemoveStuns, bool RemoveExceptions)`
