### ISSUE TITLE
OAA Donation Bottles/Sohei Arcanas

### ISSUE THREAD

**Issue by mikibun** [OpenAngelArena/oaa#2311]
Hi, 
For the Fundraiser stream we said everyone who donated 3€ or more gets a donator bottle. We need this implemented. 
https://docs.google.com/spreadsheets/d/13WrW0wkaAMMBOJZ0XDZAhKGxao5SnTtvZfUNg_viKHg/edit?usp=sharing
This is a list of the steam IDs (Steam32) for people who get the rewards, Most people get both, they're listed under Sohei Arcana + DB, but the ones listed under Just DB only get the donator bottle.

**Comment by imaGecko** [comment]
would need to know which bottle it actually is

**Comment by Satsaa** [comment]
Surely its this
![](https://cdn.discordapp.com/attachments/404979387121795074/449944619241963541/unknown.png)
