### ISSUE TITLE
Re-implement Lycan Summon Wolves

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#2345]
The wolves aren't scaling past level 4. Likely the ability needs to be re-implemented. Though maybe there's some other issue.

**Comment by Yahnich** [comment]
iirc you just need to add wolfnpcname_5 to 7 to the unit list, thats how i did it in ebf

**Comment by Trildar** [comment]
I kinda assumed that had already been done. Seems they're named wrongly.
