### ISSUE TITLE
Implement Item: Preemptive Reflex 3 C

### ISSUE THREAD

**Issue by zelding** [OpenAngelArena/oaa#235]
Official Documentation - http://tinyurl.com/Reflex-Items

**Active**: Creates a bubble that protects you from from all spells originating from the outside

Expose all variables for KV files:

 - duration (use existing `duration`)

**Notes**:
- shouldn't require targeting, always applies to caster
- interrupts spell projectiles.

**Comment by zelding** [comment]
@warpdragon could you provide some insight on this: `spell-triggered invulnerability/blink-until-action`?

**Comment by warpdragon** [comment]
"Insight, foresight, more sight, the clock on the wall reads a quarter past midnight
