### ISSUE TITLE
Implement new creep camps

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#2411]
# New Creep Camps

We want to introduce more interesting creep camps. Below you see a map. Each camp will be replaced as is marked on the map and described below.

![creep camps](https://user-images.githubusercontent.com/24982519/45715975-da318600-bb95-11e8-92af-7fe56beaba02.jpg)

The new creep camps each have at least one unit each with two abilities. These creeps will use the abilities described randomly while they are fighting an enemy.

Abilities that will have to be newly created are marked in **bold**.

## 3 Corner camps
- Camp #1 
- Black ancient dragon
- Ability 1: The fireball ability of the Ancient Black Dragon as described [here](https://dota2.gamepedia.com/Ancient_Black_Dragon).
- **Ability 2: Armor Aura. Provides all allies in a 900 radius with additional armor. Unlike the Black Ancient Dragon armor aura it doesn't stack.** 
- Spawn quantity: 1 
- Max quantity: 1

### 2 base camps are the same
- Camp #2 
- uses ghost model
- **Ability 1: Passive. On attack reduces all healing the target receives by 40% for 5s.**
- **Ability 2: Active. Slows the attack speed of enemies in a small AOE for a few seconds.**
- Spawn quantity: 3
- Max quantity: 6

### top near the bosses is different

- Camp #3 
- Always spawns as 1 big centaur and 2 small ones
- Ability 1: Active: Centaur stun as described [here](https://dota2.gamepedia.com/Centaur_Camp).
- Ability 2: Passive: Provides allies in a 900 radius with bonus attack speed.
- Only the big centaur has abilities.
- Spawn quantity: 3 
- Max quantity: 6

### 1 bottom near the bosses boss

- Camp #4
- Blueberrys
- Ability 1: Hellbear clap as described [here](https://dota2.gamepedia.com/Hellbear_Camp).
- Ability 2: Provides allies in a 900 radius with magic resistance.
- Spawn quantity: 3
- max quantity: 3

### 2 near the base exits

- Camp #5
- give most XP, but that xp is split up into both mud golems and smaller golems
- mud golems but without the insane magic resistance
- Ability 1: Active. Hurl Boulder as described [here](https://dota2.gamepedia.com/Golem_Camp).
- Ability 2: Passive. Shard Split as described [here](https://dota2.gamepedia.com/Golem_Camp).
- Spawn quantity: 4
- Max quantity: 8

### 1 near the center highground

- Camp #6
- Harpy Stormcrafters
- Ability 1: Active. Chain Lightning as described [here](https://dota2.gamepedia.com/Harpy_Camp).
- **Ability 2: Passive. Reduces the magic resistance of all enemies in a 900 radius.**
- Spawn quantity: 4
- Max quantity: 4 

### 2 in the base

- Camp #7
- kobold camp
- Always spawns 1 kobold foreman and 4 smaller kobolds.
- Only kobold foreman has abilities.
- **Ability 1: Active: Buffs all allies in an AOE with attack speed and flat damage.** 
- Ability 2: Passive. Provides all allies in a 900 radius with bonus % movement speed.
- Spawn quantity: 5
- Max quantity: 10

### 2 out of the base

- Camp #8
- Wolves
- Always spawns one big wolf and 2 small ones.
- Only big wolf has spells.
- Ability 1: Passive: Base damage aura as described [here](https://dota2.gamepedia.com/Wolf_Camp).
- Ability 2: Passive: Critical strike as described [here](https://dota2.gamepedia.com/Wolf_Camp).
- Spawn quantity: 3
- Max quantity: 9

## 1 ancient camp

- Camp #9 
- 2 Ogres, one is blue, other orange
- Ability 1: Both have the slam forward from the ogre boss but with a drastically reduced AOE.
- But they have different secondary abilities.
- Blue ability 2: Prowler Aura as described [here](https://dota2.gamepedia.com/Prowler_Camp).
- Orange ability 2: Granite Aura as described [here](https://dota2.gamepedia.com/Large_Golem_Camp).
- Spawn quantity: 2
- Max quantity: 2

## KVs

Each creep camp will need its own entry in our creep camp list and the abilities need their own KV files.

**Comment by DarkoniusXNG** [comment]
I can start this by creating KV files. I have some questions:
1) In camp 2: the active ability should be a point target ability or no target ability? If point target: Should it be like Ice Vortex (affects the area for a few seconds) or Arcane Curse (affects the area only on cast)?
2) In camp 4: Aura that gives magic resistance should be recreated, or this: [Cloak Aura](https://dota2.gamepedia.com/Hellbear#Cloak_Aura).
3) In camp 8: Can we merge the passives into one aura that provides critical strike to allies? And can we add an active: Howl (reduces attack damage of enemies around you when activated) or basic Invisibility with mana cost?

**Comment by l34Um1** [comment]
1. Ice Vortext but actually old off on making new abilities for a second. We want the Thinking Bottle programmers to play with the dota engine a bit so we want them to make the custom abilities for this.
2. Yes cloak aura is fine.
3. I think those are good ideas. Crit aura sounds good, Invisibility sounds good as well. The howl is a neat ability but I think invis is better for the game.

**Comment by DarkoniusXNG** [comment]
I am just making templates for now.

**Comment by l34Um1** [comment]
Don't worry about waiting anymore. Also the #4 camps have been moved a bit inward in the newest version of the map.

**Comment by genious97** [comment]
@DarkoniusXNG are you still working on this issue

**Comment by DarkoniusXNG** [comment]
I stopped working 2 months ago. I was planning to finish it after the Major. Contact me on discord if you want to help somehow.
