### ISSUE TITLE
Chatterjee + Cast Range bonuses

### ISSUE THREAD

**Issue by DarkoniusXNG** [OpenAngelArena/oaa#2523]
When you have too much cast range bonuses, Chatterjee's Q ability (Static Grip) can instantly break on use. The issue is probably break distance not increasing with cast range bonuses.

**Comment by SquawkyArctangent** [comment]
Have we actually gotten a function to get a hero's bonus cast range yet? I don't think we have.

Though, I suppose this could be solved by instead, like, just removing the break limit entirely. It's not like it's exactly relevant outside of the niche trick of being able to break it with Force Staff.
