### ISSUE TITLE
Greater Phase Boots rework for melee heroes

### ISSUE THREAD

**Issue by DarkoniusXNG** [OpenAngelArena/oaa#2525]
Greater Phase boots needs a rework for melee heroes. 

Reason: Because of Valve changes in 7.20, all attack proc rules are messed up. Melee heroes can proc any attack modifier on splintered attacks. Because of this, melee heroes can cleave on every splintered attack and oneshot camps.

How to rework: For melee heroes, make a splinter shot like a normal projectile that deals fixed damage (damage of the wielder * damage reduction). And don't use PerformAttack.

**Comment by lovesmuffins** [comment]
range units can also use projectiles right?

**Comment by Trildar** [comment]
I would have changed Phase Boots to do an attack damage based ApplyDamage or whatever ages ago if only the DotA API wasn't so stupid about querying a hero's attack damage.

At this point maybe I should just concede and use the GetAverageTrueAttackDamage nonsense and accept that it'll act weirdly with percentage outgoing damage modifiers

**Comment by DarkoniusXNG** [comment]
GetAttackDamage() should be better.

**Comment by Trildar** [comment]
Think that's only base damage. Unless they actually added a function that returns total attack damage and I didn't notice.

**Comment by DarkoniusXNG** [comment]
I didn't see its only base damage. GetAverageTrueAttackDamage it is then.
