### ISSUE TITLE
NGP is pretty much completely broken

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#258]
Randomly, users are voting on items that belong to the other team. Figure out what is causing this and fix it.

Additionally, it seems like sometimes no one gets the item.

**Comment by ProstoSanja** [comment]
#255

**Comment by KarmaticNeutral** [comment]
@chrisinajar fixed? mostly?

**Comment by Haganeko** [comment]
#255 is still waiting to be finished.

**Comment by KarmaticNeutral** [comment]
The improved NGP is still being waited on, but I think our current one is at least mostly functional is it not?

**Comment by Chronophylos** [comment]
The NGP mismatch problem was fixed so, yes.
