### ISSUE TITLE
Remove second upgrade core from all boss drops

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#259]
Currently every boss drops a tier n-1 and a tier n-2 upgrade core. They should only drop the n-1 core.

**Comment by Declow0** [comment]
https://github.com/OpenAngelArena/oaa/blob/master/game/scripts/vscripts/components/boss/ai.lua
Line 90. Just remove lines?

**Comment by chrisinajar** [comment]
yeah, remove line 113, 118, 123.....
