### ISSUE TITLE
If you cast an ability with a cast point as the duel starts you will be teleported hilariously

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#260]
Blink blockers check your location before and after you cast an ability and enforce blink blocking. Since duels teleport you, this can falsely cause it to trigger the blink blocker to teleport you back to the wall, then zone control teleports you back into the duel but at the point closest to your location.

Here is a video of it happening:

https://www.youtube.com/watch?v=AUrTUtp-r-E&t=2h47m33s

**Comment by darklordabc** [comment]
I couldn't reproduced this, tried about 10 times.

**Comment by KarmaticNeutral** [comment]
The video here doesn't show something without a cast point. This shows a spell that started being cast before the duel started and finished after trying to stun the original location.
