### ISSUE TITLE
Fix rate at which heroes get ability points passed level 25

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#261]
After level 25, heroes should not get any new ability points until level 28. At 28 they get 1 point, and receive 1 more point each 3rd level thereafter. So ability points would be gained at 28, 31, 34, 37, 40, 43, 46, and 49.

**Comment by darklordabc** [comment]
It seems a bit odd for players to be able to get levels and not get ability points, takes away a lot of the fun of leveling up. I would of thought it be a better idea to reduce the maximum level so as that you can get an ability point each level.

**Comment by chrisinajar** [comment]
that would make the xp required to level up and stats gained from doing so really disproportional for just levels 25-50. Instead we just give an ability points once every 3 levels, which also correlates directly with the level requirements for the final 2 ability points
