### ISSUE TITLE
Underlord Ultimate in duels

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#266]
Currently when Underlord attempts to use his ult in a duel, it takes him 2 uses of the ult to cross the gap. The first maintains the Y value of the location but changes the X value to be equal to the new location. The second changes the Y value making Underlord end up inside the other duel. When he tries to return to his own duel, it only takes one use.

https://www.youtube.com/watch?v=8Eyx33CRvd4

Also, if it's supposed to be able to jump to heroes it does not at the moment.

**Comment by chrisinajar** [comment]
bahahaha what the fuck xD

I guess design should decide what should happen here. I can fix it so that he stays locked in, at least.

**Comment by Haganeko** [comment]
I believe current consensus is that global heroes should be able to teleport between arenas, but not outside. Will probably need further discussion.

**Comment by KarmaticNeutral** [comment]
I've been thinking about this and the reason it occurs is that when you leave your own duel you have to go through 2 duel blockers to get to the other arena. When you go back into your own, it welcomes you ion meaning you only have to go through one. That matches up nicely with the required number of ults for each direction of movement.

**Comment by darklordabc** [comment]
I would just disable global teleport abilities for when a duel starts. A duel is meant to be a cage match where you are forced to fight, allowing Nature's prophet simply to teleport out of the duel arena into another duel arena, defies the point of the duel. I'd recommend a list of all the global teleport abilities and items, and a loop that puts them all on a 80second cooldown, that gets removed after the duel.

**Comment by KarmaticNeutral** [comment]
The goal is actually to make it so that people with globals can go to any duel but can't leave them if I understood Baumi correctly.

**Comment by darklordabc** [comment]
Thats only really Natures Prophet, and Underlord and IO tho isn't it? Its a fun idea, but it sounds like its abuseable. Imagine you are just about to win a 3 vs 3 duel, chasing the last hero down, and then a Wisp + Sven teleport in from the other duel arena.

**Comment by Haganeko** [comment]
There's also Spectre. And meepo, if one of the others helps him get part of himself to another duel. Then there's ember spirit, if he leaves a remnant in one arena and fights on the other next.

**Comment by KarmaticNeutral** [comment]
I'm gonna call this closed due to the way duels work now and how useless this interaction is even if you know it exists.
