### ISSUE TITLE
Documentation on interaction between hero movement and different blockers

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#269]
I started at the end of the alphabet and worked up. Puck was the last hero I did before going to bed. I will do the rest tomorrow I just figured this info might help someone before I get a change to finish the list.
[hero list.txt](https://github.com/OpenAngelArena/oaa/files/860428/hero.list.txt)

**Comment by Chronophylos** [comment]
Nice!
But throwing bosses into duel could be a cool strategy.

**Comment by KarmaticNeutral** [comment]
out dated and incomplete
