### ISSUE TITLE
Probably ngp is broken

### ISSUE THREAD

**Issue by ProstoSanja** [OpenAngelArena/oaa#274]
Found some mismatches at [`game\scripts\vscripts\components\boss\ngp.lua`
at line 37](https://github.com/OpenAngelArena/oaa/blob/master/game/scripts/vscripts/components/boss/ngp.lua#L37) `votes` element isnt applied to array, but to local variable, what do you think?

Edit by @Chronophylos: Link

**Comment by Chronophylos** [comment]
Lua uses references. Instead of
```Lua
local item = NGP.activeItems[tonumber(id)]
[...]
item.votes[playerID] = option
``` 
you could write
```Lua
NGP.activeItems[tonumber(id)].votes[playerID] = option
```
If that is what you mean.

**Comment by ProstoSanja** [comment]
yes, i was talking exactly about it, 
still i am pretty new to lua

**Comment by Chronophylos** [comment]
Yeah me too.
