### ISSUE TITLE
Fix illusions to use diminishing stat return

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#276]
Currently any time you summon an illusion passed level 25, the illusion is stronger than you. This is because dota calculates the stats for that level when they spawn them, so our level up code doesn't edit the stats. We need to hook on them being summoned and adjust their stats to match the hero they were created from.

**Comment by lindleya1** [comment]
Tested on Naga, seems to be fixed

**Comment by Haganeko** [comment]
The bughas been addressed, but persists on some weirder illusions like arc warden and morphing aghs, I believe.
