### ISSUE TITLE
Invoker ability levelling broken

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#282]
We forgot about Invoker when implementing the custom ability level requirements, so his levelling is incredibly weird. Not too sure what his requirements should actually be. Hopefully someone can comment on that here.

His ability point gain should also be checked since I don't think Invoker's intended levelling pattern is the same.

**Comment by warpdragon** [comment]
He follows normal invoker pattern. He gets 14×3=42 level ups. 1 per lvl id say

**Comment by warpdragon** [comment]
Just quietly try it. Protip baumi hates invoker. Just quietly implement.

**Comment by mokonaDesu** [comment]
Will implement the 'custom levelling patterns' thingie in the progression component along with some chat cmds for testing as soon as I get the time (which is most likely going to be saturday or sunday)

The basic rule is that he gets his APs until level 46 (42 skill points + 4 talents), right?

**Comment by warpdragon** [comment]
That sounds great

**Comment by mokonaDesu** [comment]
I've noticed that heroes don't get ability points on level 19, 21, 22, 23, 24. It creates this weird behavior where some of the AP skips are controlled by the system and others are not (and those look differently. When you don't get an AP on levels mentioned above, the levelup effects are not played out). Do we do anything about it?

**Comment by Trildar** [comment]
Like fix it to not show the level up effects? That would be nice, but would likely require some different implementation. The lack of ability points on those levels is just normal Dota behavior. It doesn't try to check if there's anything to level, it's just hardcoded.

**Comment by Trildar** [comment]
Fixed by #328 and #329.
