### ISSUE TITLE
Manta style bug

### ISSUE THREAD

**Issue by dkNykita** [OpenAngelArena/oaa#289]
When I used normal Manta Style as Anti-Mage they spawned with more HP than they should (I had 4390 HP). Maybe it was caused by my level that was 5000 I think.

![manta](https://cloud.githubusercontent.com/assets/26550793/24251080/3a4f2fe8-0fd9-11e7-9a55-03f9aae709c8.png)

**Comment by warpdragon** [comment]
Already reported in #279
