### ISSUE TITLE
Change NGP to use net tables

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#29]
Currently it's event driven,

* [ ] Change it to net tables.
* [ ] Make a nice lua API 
* [ ] Document it in `/docs/api.md`

**Comment by Chronophylos** [comment]
But why do we not want to use Events?

**Comment by chrisinajar** [comment]
Net tables automatically repopulate when you reconnect. The net table should just be the current NGP state, and then the UI still uses events to tell the server its choice.
