### ISSUE TITLE
Stoneskin Armor tooltip update

### ISSUE THREAD

**Issue by dkNykita** [OpenAngelArena/oaa#290]
I think it's kind of weird how it is written. From start you are using third person form "grants the user" and later second person form "but slows your movement speed"

![stoneskin](https://cloud.githubusercontent.com/assets/26550793/24251599/f405e412-0fda-11e7-882a-6627a28ea18c.png)

**Comment by chrisinajar** [comment]
"pct" is ridiculous, too.

**Comment by Chronophylos** [comment]
And formatting..

**Comment by warpdragon** [comment]
what's that shit on the top right?

**Comment by Chronophylos** [comment]
"Level"
Different Localizations.
Our English text and dotas text that got localized.

**Comment by darklordabc** [comment]
Most of the item tooltips seem first drafts which is fine but for the final version I think most of them willl need to be fleshed out a bit more and maybe polished by somebody who is good at wordcraft (I'm terrible at it).

**Comment by warpdragon** [comment]
i will fix it. closing.
