### ISSUE TITLE
Level dots for abilities with 6 levels don't show properly

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#304]
Previously attempted to fix using CSS file overrides. Unfortunately doesn't seem to work when actually published in Workshop, possibly because Workshop doesn't allow publishing such files that override ones in normal Dota.

P.S. If it does actually work at this point, feel free to tell me as I don't currently have access to the Workshop version of the game.

**Comment by Chronophylos** [comment]
You could override CSS in a different file...

**Comment by Trildar** [comment]
@Chronophylos If that were possible it would have been a separate file in the first place. CSS in Dota is scoped only to the XML layout file they're referenced in, so there isn't any way to get new CSS files to affect default UI elements. Not unless you remake the element as a custom one or something.
