### ISSUE TITLE
Dagger of Moriah rework

### ISSUE THREAD

**Issue by DarkoniusXNG** [OpenAngelArena/oaa#3060]
Some ideas:
1) Negative Pipe with duration - Provides negative magic resistance aura that affects enemies around you while active. Has duration. Doesn't pierce BKB. Doesn't affect bosses.
2) Timeless Relic with an active - Target an area and apply negative status resistance to all enemies in the area. Dispellable. Has duration.
3) Me Bane now - Converts all spell damage into pure damage for the duration. Doesn't pierce BKB. Has duration.
4) Mage Slayer for supports - Target an area and apply negative spell amplification debuff to all enemies in the area. Dispellable. Has duration.
5) Spell Crit passive - 30% chance to deal 1.75x/2x dmg with a spell.
6) What every support wants - Target an area and apply a buff to all allies in the area. Buff reduces spell damage from all sources by a percentage. Dispellable. Has duration.

**Comment by POCKETMONEY99** [comment]
**Idea 1 is the best idea**, keeps the intention of the item the same and simultaneously makes it less extreme.
Idea 3 sounds OP but it could be balanced idk.
Idea 2, 4, 6 are ok but it changes the item from its original purpose of being an offensive spellcaster item. 
 and 5 would be OP.
