### ISSUE TITLE
Remove Combiner

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#309]
We're removing combiner in favor of Upgrade cores, right?

**Comment by Chronophylos** [comment]
I think so.

**Comment by ProstoSanja** [comment]
a question: are we talking about that yellow item combiner? if yes, do we even need ngp then?

**Comment by warpdragon** [comment]
i dunno

**Comment by warpdragon** [comment]
no clue

**Comment by ProstoSanja** [comment]
cuz we only use it for combiners. and for t2 boss cores. 
@chrisinajar  what can you say?

**Comment by KarmaticNeutral** [comment]
eventually it will be used for boss specific items. (EX: Azazel's Crossbow) but those are yet to be implemented. At the moment I don't think anything in the game is supposed to use it.
