### ISSUE TITLE
Flying movement camping spot over dire spawn

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#322]
![image](https://cloud.githubusercontent.com/assets/24883381/24319799/2ddc76c6-10ec-11e7-82bf-62269c249577.png)
The fountain can not hit someone at this position.

**Comment by Haganeko** [comment]
Is this a duplicate of #428?

**Comment by KarmaticNeutral** [comment]
No, they are on opposite sides of the spawn area but cover the same concept. The two could be combined to create one more complete ticket.
