### ISSUE TITLE
Rubick can move bosses into the duel arena

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#323]
![image](https://cloud.githubusercontent.com/assets/24883381/24319822/1c6651a4-10ed-11e7-8e3a-a1b627d71130.png)

**Comment by Haganeko** [comment]
Have you tried to throw them with Gust and the like? I have found Gust with a good aether lens quite proficient at boss-pushing.

**Comment by KarmaticNeutral** [comment]
Gust does not push the boss far enough to clear the wall

**Comment by KarmaticNeutral** [comment]
I propose making it so rubick can't lift bosses.

**Comment by Chronophylos** [comment]
Is it possible to not even allow Rubic to target Bosses with the lift?

**Comment by KarmaticNeutral** [comment]
probably not, but we could probably prevent bosses from being effected by it

maybe make them become disabled but can't be moved. Don't remove it's effectiveness but make it so you can't telekinesis them onto cliffs

**Comment by Chronophylos** [comment]
We could lock them in like the players during duel but for bosses...

**Comment by Haganeko** [comment]
I propose giving bosses cliff walking. Also, it's not just telekinesis, Gust can move bosses pretty well too.

**Comment by KarmaticNeutral** [comment]
that would work. and it would stop the cheaty cliff farming that happens.

**Comment by Chronophylos** [comment]
It's the simplest solution I'd think.

**Comment by KarmaticNeutral** [comment]
So we just need to give all bosses cliff walking/flying movement.

**Comment by KarmaticNeutral** [comment]
moved to a more inclusive ticket
