### ISSUE TITLE
Icons are buggy

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#331]
The issue of the icon bugs are well known by now:
- In the first test stream Baumi couldn't see some icons while others could.
- Icons tend to work in dota2tools and tend to not work in the Workshop.
- Games with some players having icons and others not.
- Last night in a test game someone said an icon that was working stopped working immediately after they respawned (sadly no video confirmation).
- In the strategy screen if you hover over certain icons they blink to black.
- These bugs are... intermittent and thus difficult to diagnose.

If we are implementing any sort of scripting involving gold, the shop, purchasing, etc i really think we should look there. The next test stream needs to have icons. The art team is doing a great job we definately want to show off their work!

**Comment by warpdragon** [comment]
Also this
https://moddota.com/forums/discussion/1192/compiling-spell-icons

**Comment by Chronophylos** [comment]
I never had this problem...

**Comment by warpdragon** [comment]
issued pull request that should solve this.

**Comment by DarkoniusXNG** [comment]
Read this: https://github.com/ModDota/BugTracker/issues/90

Item icons (.png) needs to be placed into resource/spellicons/custom too.

**Comment by warpdragon** [comment]
@DarkoniusXNG  oh shit you're right

**Comment by chrisinajar** [comment]
@warpdragon did this get resolved with your PR or is there still more to do?

Also, a document on how to properly manage icons would be great so we can survive if you get hit by a buss :D

**Comment by Chronophylos** [comment]
I don't think a doc will help us survive in that situation.

**Comment by Haganeko** [comment]
If Chris,  Baumi or Warp get hit we're done. Single points of failure.

**Comment by warpdragon** [comment]
@chrisinajar this got resolved with the PR. Doc will come when i get time.
