### ISSUE TITLE
New Bottle Implementation from the Meeting

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#334]
New Implementation
- [ ] Pseudo RNG to make drop-rate more consistent
- [ ] Only ever have <=1 bottle in inventory
- [ ] Bottle resell value -> 0
- [ ] With a bottle in inventory, picking up a bottle gives x charges (x=1; source = baumi)
- [ ] Max charges - y (y=essentially infinite; source = baumi)

**Comment by warpdragon** [comment]
Update:
changed "- Pseudo RNG to make drop-rate more consistent"
to read
"- One bottle per creep spawn to make drop-rate more consistent"

**Comment by Haganeko** [comment]
Close this? Not very relevant given how much has happened after.
