### ISSUE TITLE
Locking Boss Cores

### ISSUE THREAD

**Issue by spar36** [OpenAngelArena/oaa#350]
If for any reason a boss core becomes locked from combining, you can't unlock it. 
Happened mostly when dissembling another item that included an upgrade core.

@KarmaticNeutral If you want a video, just ping me, but seemed pretty self explanatory.

**Comment by Declow0** [comment]
If cores has attribute sellable, you can unlock. May be this way can solve problem.

**Comment by KarmaticNeutral** [comment]
@spar36 I found this issue myself last night. Thanks for writing it up so I don't have to.

**Comment by spar36** [comment]
Them being sellable would be a design/balance team decision.
