### ISSUE TITLE
Rebalance XP For Number of Heroes

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#355]
Introduce a multiplying factor of n/10 for creep experience, where n is the number of players in the game at start.
This should help playtest data more accurately reflect EXP balances.

**Comment by spar36** [comment]
So you want the xp that creeps give out to be scaled based on how many players there are a the start of the game? correct?

**Comment by Haganeko** [comment]
Yes. This will help see how much of an imbalance we have with leveling. Leveling is currently too fast, but that was to be expected when one or two heroes have access to a whole map of creeps.
