### ISSUE TITLE
Duel location if dead when duel begins can put you back into a team fight.

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#358]
I think the best option is when saving a players location at the start of a duel just check if they are dead and if so set their location to be their fountain instead.

**Comment by warpdragon** [comment]
>>be me. get killed in gangland fashion from a gank that will be heralded through the ages
>>go to duel, lose.
>>respawn where i died originally, proceed to relive the terror of my original death.
FeelsBadMan
