### ISSUE TITLE
Bosses can be pulled into fountain with the new extended leashes

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#360]
If we were worried about creeps in fountain unbalanced... well.... XD

**Comment by warpdragon** [comment]
yeah the leash range is insane. and the bosses are too easily pulled when farming the easy and medium camps adjacent to the tier 1 boss. those bosses will chase you half way across the map just for farming a camp with zeus's static field and wind ranger's power shot.

**Comment by amund91** [comment]
A video on it: https://www.youtube.com/watch?v=zj4tJlpuTBg

**Comment by Haganeko** [comment]
Is this fixed?

**Comment by Chronophylos** [comment]
I haven't seen a PR for this.

**Comment by Trildar** [comment]
No idea. My observation previously was that it's not the leash range that is actually bugged. Some of the bosses just seemed to not have the boss AI attached. I didn't test it though.

**Comment by KarmaticNeutral** [comment]
This is kind of being fixed as bosses are given personal custom AI. The generic Boss AI has conditional loops where if you time it right, you can break their lua and then they just effectively use unleashed creep AI. 

We can wait on new bosses or fix generic boss AI

**Comment by Haganeko** [comment]
New fountain sort of fixed this, I guess...?

**Comment by Trildar** [comment]
Sort of. You can't instakill bosses with it anymore, but leashes breaking can still be an issue if bosses decide to just randomly follow you around the entire map or suddenly just decide to sit in the middle of it.

**Comment by warpdragon** [comment]
Mostly outdated. Leashes are constantly being tweaked as needed. Closed.
