### ISSUE TITLE
Implement Capturable Area during Duels

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#366]
The large high ground area in each arena is supposed to be a capturable zone. If any team can keep undisputed custody of it for over 40 seconds (this should be easily editable for balance), every hero they have in that arena should get double damage, haste, an arcane rune, and a small radius of true sight, for the rest of the duel.

**Comment by Haganeko** [comment]
The buffs from the capture should also be adjustable... we all know stuff goes broken easily in this mod.

**Comment by warpdragon** [comment]
1. define a region on the high-ground
2. track all hero's contiguous duration inside of this region.
3. if a hero leaves the region, their respective capture meter gets reset to zero. 
4. Once any hero's capture meter reaches 40, their team receives a semi-permanent buff and the capture meter resets until... maybe the next duel?

Or something like that.

**Comment by Haganeko** [comment]
The capture meter should only increase if no enemy heroes are also on the high ground area. If there are any, then it should slowly drain away.

**Comment by darklordabc** [comment]
Dota Imba has this mechanic in its arena mode map, we could check out their code to see how todo it. 
![image](https://cloud.githubusercontent.com/assets/16277198/24541157/019a02f8-1642-11e7-8638-5a84110975db.png)
