### ISSUE TITLE
Localisation KVs for unit names, grammar, variable names, etc.

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#368]
Most of the units found in `game/scripts/npc/units` have not had localisation for their unit names put in `game/resource/addon_english.txt` yet. Most of the ones with numbers on the end are units for the 5th and 6th level of abilities and just need the same name as the first 4 levels have in normal Dota (Necronomicon units are also the same). Main exception is the Eidolons, which are named according to their file, i.e. "Giant Eidolon" and "Colossal Eidolon".

The bosses could maybe also be given generic names like "Tier 1 Boss" until the proper named bosses are implemented.

**Comment by warpdragon** [comment]
i've been loathing editing this monstrous file. i have a checklist:

1. fix broken variable identifiers
2. add units/unit names
3. correct grammar mistakes
4. more..?

**Comment by Haganeko** [comment]
Has this been fixed by #674 and #672?

**Comment by Haganeko** [comment]
Once again, isn't this fixed? What's left to do? @warpdragon

**Comment by Chronophylos** [comment]
Except grammar mistakes it's fixed
