### ISSUE TITLE
Shadow Shaman's Ult only goes to level 3

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#400]

**Comment by spar36** [comment]
It skills to level 5, but doesn't spawn the units in level 4 or 5, kinda like the tusk sigil problem. I found an implementation in pizzalol, just have to put it in and get everything set up right. Will hopefully do that tonight.

**Comment by Trildar** [comment]
Before you do that, check if just adding the units works. There are currently no level 4 or 5 Shaman wards in KV.
