### ISSUE TITLE
Level restraints have been removed

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#401]
You can have  level 7 spells by level 13 again.

**Comment by Trildar** [comment]
Did this happen on multiple heroes? Last I checked, the level requirements still seemed to be working on at least some abilities. Unless something other than the Invoker level requirement patch messed it up somehow.

**Comment by KarmaticNeutral** [comment]
It happened on everyone as far as we could tell

**Comment by Trildar** [comment]
Oh... I think Dota only allows one Filter function per Filter type. i.e. calling `SetExecuteOrderFilter` pretty much overwrites previous calls to it. Hence why the recent [d6e9c7f](https://github.com/OpenAngelArena/oaa/commit/d6e9c7f265737aba9ec620e827797409f98d4259) broke ability level requirements.

We're going to need something to manage and compose these filters it seems.

**Comment by DarkoniusXNG** [comment]
@Trildar That's exactly what happened. Every custom game can have only one Order Filter. Easy to fix: Just combine the contents of two filters into one.

**Comment by Trildar** [comment]
Easy to fix for right now, yeah, but we probably want a FilterManager for better organisation and since it's likely we'll need a bunch more Filters yet.

Not that making a FilterManager would be incredibly difficult I would think.
