### ISSUE TITLE
Fix our XP table to match vanilla dota's

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#414]
DotA's Values:

![image](https://cloud.githubusercontent.com/assets/24883381/24583801/29882ff6-1714-11e7-9998-46575aa0feb0.png)

**Comment by kallleeeeh** [comment]
Link: [http://dota2.gamepedia.com/Experience#Leveling](http://dota2.gamepedia.com/Experience#Leveling)

**Comment by Haganeko** [comment]
XP for next level from level 25 and onwards can stay the same: 300*(current level - 15)

**Comment by Chronophylos** [comment]
Fix? We were told to change it to what it is now...

**Comment by Chronophylos** [comment]
@Haganeko Yes that is how it is implemented atm.

**Comment by Haganeko** [comment]
Close this?
