### ISSUE TITLE
Fix Gold and Experience

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#415]
Three assumptions of our current gold and XP model have been debunked:
First, there are three medium camps
Second, there are five easy and medium creeps per easy/med camp
Third, people can't farm medium camps at all in the first few minutes

Fixing this goes in three steps. Please implement them.

## Reduce number of medium creeps to four per spawn
Self explanatory.

## Refactor gold to account for greatly increased number of creeps
Easy creeps now give 12 base gold per creep, mediums 17. Hard creeps stay the same, as does the gold multiplier.

## Refactor experience to account for early farming and extra creeps
 - Easy creeps now give 48 base EXP
 - Medium creeps now give 90 base EXP
 - Hard creeps now give 100 base EXP
 - The EXP multiplier at minute n (remember, n starts at 0!) is (21n² - 19n +3002)/3002

Bonus step: Implement the farming cave. I have the docs on it, if anyone wants to tackle it.

**Comment by Haganeko** [comment]
This one is pretty important. Should fix gold flood somewhat, as well as leveling.
Managing to kill medium/hard camps early should be more important now, as they are a reserve of experience. At the same time, medium creeps aren't necessary for reaching low levels anymore.
This may necessitate further balance.

**Comment by l34Um1** [comment]
Medium creeps attack range also need to be reduced to 200.

**Comment by Chronophylos** [comment]
> Reduce number of medium creeps to four per spawn

This has to be done via map changes? (I think)

**Comment by Chronophylos** [comment]
To confirm:
```Lua
-- "creep name", Health, Mana, Damage, Armor, Gold Bounty, Exp Bounty
CreepTypes = {
  -- 1 "easy camp"
  {
    {                                         --HP    MANA  DMG   ARM   GOLD  EXP
      {"npc_dota_neutral_kobold",               240,  0,    10,   0,    13,   48},
      {"npc_dota_neutral_kobold",               240,  0,    10,   0,    13,   48},
      {"npc_dota_neutral_kobold_taskmaster",    400,  0,    14,   1,    13,   48},
      {"npc_dota_neutral_kobold_taskmaster",    400,  0,    14,   1,    13,   48},
      {"npc_dota_neutral_kobold_tunneler",      325,  0,    14,   1,    13,   48}
    }
  },
    -- 2 "medium camp"
  {
    {                                         --HP    MANA  DMG   ARM   GOLD  EXP
      {"npc_dota_neutral_harpy_storm",          550,  400,  33,   2,    17,   90},
      {"npc_dota_neutral_harpy_storm",          550,  400,  33,   2,    17,   90},
      {"npc_dota_neutral_harpy_storm",          550,  400,  33,   2,    17,   90},
      {"npc_dota_neutral_harpy_scout",          400,  0,    31,   1,    17,   90},
      {"npc_dota_neutral_harpy_scout",          400,  0,    31,   1,    17,   90}
    }
  },
    -- 3 "hard camp"
  {
    {                                         --HP    MANA  DMG   ARM   GOLD  EXP
      {"npc_dota_neutral_centaur_outrunner",    1400, 400,  62,   2,    45,   100},
      {"npc_dota_neutral_centaur_khan",         800,  400,  44,   2,    45,   100},
      {"npc_dota_neutral_centaur_khan",         800,  400,  44,   2,    45,   100},
    },
    {
      {"npc_dota_neutral_alpha_wolf",           800,  400,  31,   4,    45,   100},
      {"npc_dota_neutral_alpha_wolf",           800,  400,  31,   4,    45,   100},
      {"npc_dota_neutral_giant_wolf",           1700, 600,  82,   8,    45,   100}
    }
      -- {"npc_dota_neutral_jungle_stalker",       1600, 400,  55,   2,    61,   40},
  }
  -- ...
}
```

**Comment by Chronophylos** [comment]
Because we often have only 3v3s someone based Creep XP on PlayerCount as well as time.
Should I remove this or do you want to make a new function?

**Comment by Trildar** [comment]
@Chronophylos I think you can change the number of creeps per spawn by just changing the table. Notice how the number of units listed in the table match the number of creeps per spawn?
Changing attack range would require unit KVs, or possibly changes to `spawner.lua` so that attack range can also be defined in the spawn table.

**Comment by Chronophylos** [comment]
I was thinking about maximum creeps per camp. Yes you're right
Attack Range seems possible. Gotta look into that.

**Comment by Haganeko** [comment]
The multiplier for number of players is okay. It cam stay. Thanks!
