### ISSUE TITLE
Bottles crashing Dota

### ISSUE THREAD

**Issue by RamonNZ** [OpenAngelArena/oaa#426]
I'm playing from the \addons\ directory.

I only mention this because it hasn't been put in "Issues" yet and it's a big issue.

I pick up a bottle and am welcomed to a view of my desktop.

**Comment by spar36** [comment]
so you were playing on a local copy?

**Comment by RamonNZ** [comment]
Yeah it's in a local copy. Though I just tried through the workshop just now and the same thing happens. I would be surprised if it was only happening to me.

**Comment by chrisinajar** [comment]
It happened to a few people reliably on the workshop version. It should, hopefully, be fixed now.

**Comment by RamonNZ** [comment]
I will test on Saturday.

**Comment by RamonNZ** [comment]
This problem appears to be fixed.
