### ISSUE TITLE
Bosses freeze when thrown off cliffs

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#442]
Rubick with stolen Gust can do it to the bosses near Dire spawn. Probably doable to other bosses as well.

**Comment by darklordabc** [comment]
Bosses should be immune to some spells, like telekinesis, this is the same for Roshan. Many normal dota spells have limited or no effects on Roshan.

**Comment by Haganeko** [comment]
They should be immune to forced movement, mostly. I can imagine people doing similar things with Magnus, Barathrum, maybe even invoke.

**Comment by KarmaticNeutral** [comment]
moved to a moer inclusive ticket
