### ISSUE TITLE
Items purchased before game disappear

### ISSUE THREAD

**Issue by spar36** [OpenAngelArena/oaa#445]
If you buy items before the game starts, in the strategy phase, they sometimes disappear. It happened to me with boots. Did not happen with all items bought (also bought a faerie fire).

The shop has a tick mark in it like you bought the item, but it is not in your inventory and the gold is gone.
Happened to multiple people today.

v0.4.2

**Comment by KarmaticNeutral** [comment]
There were players left completely unaffected. I bought boots and faerie fire and didn't lose either upon loading into the duel.

**Comment by Haganeko** [comment]
I had four faeries and a stick, and didn't lose anything.

**Comment by chrisinajar** [comment]
video from duplicate ticket

https://www.youtube.com/watch?v=oYyG70lXg_I

**Comment by KarmaticNeutral** [comment]
|X|O|O|O|O| TIMER |X|O|O|O|O| only players in X positions are affected.

**Comment by Chronophylos** [comment]
The fist player of every team? That's interesting..

**Comment by chrisinajar** [comment]
tested it today, still happening, totally insane.

**Comment by KarmaticNeutral** [comment]
[VScript] [components\courier\courier:18]    Creating Courier for Team 2
Attempt to set 'item_branches' in inventory slot already occupied by 'item_courier'!
Attempt to set 'item_gauntlets' in inventory slot already occupied by 'item_flying_courier'!
[VScript] [gamemode:121]    Hero spawned in game for first time -- npc_dota_hero_furion
[VScript] [components\courier\courier:18]    Creating Courier for Team 3
Attempt to set 'item_branches' in inventory slot already occupied by 'item_courier'!
Attempt to set 'item_branches' in inventory slot already occupied by 'item_flying_courier'!

**Comment by Chronophylos** [comment]
I forgot people can have items before the gamestart.

**Comment by KarmaticNeutral** [comment]
@chrisinajar is this fixed?
