### ISSUE TITLE
Add new stats to reflex items

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#451]
The following items have stats added to their KV's. Make them actually do stuff!

 * item_preemptive_3a
 * item_preemptive_3b
 * item_preemptive_2a
 * item_preemptive_2b
 * item_preemptive

**Comment by Haganeko** [comment]
What's left of this?

**Comment by Trildar** [comment]
This should be fixed already I think.

**Comment by Chronophylos** [comment]
Then I'm closing this
