### ISSUE TITLE
Adopt "all-contributors" style contributors list in main project README

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#455]
Lets do this: https://github.com/kentcdodds/all-contributors

This is our super-out-of-date contributors list: https://github.com/OpenAngelArena/oaa/blob/master/contributors.md

**Comment by Chronophylos** [comment]
Do it nau!

**Comment by chrisinajar** [comment]
mmmmmmmmmmmm oh yeah that's the stuff https://www.npmjs.com/package/all-contributors-cli

**Comment by Chronophylos** [comment]
Let Travis to it!
