### ISSUE TITLE
Items bought before the game starts disappear

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#456]
If a player buys items during the 'Strategy Time' any items in the first 2 inventory slots disappear. You still have the reduced gold value as though you had bought the items but you don't have them.

https://www.youtube.com/watch?v=oYyG70lXg_I

Baumi lost 2 Faerie Fires in this game. 

For some reason this does not happen to all players and I will try to find a case as to which players are and which players are not affected.

**Comment by Haganeko** [comment]
It seems to affect mostly the radiant, from my n=2 experience.

**Comment by RamonNZ** [comment]
This is the same issue as:

Items purchased before game disappear #445

**Comment by Haganeko** [comment]
Close one of them?

**Comment by chrisinajar** [comment]
Duplicates #445
