### ISSUE TITLE
Players who are supposed to die don't

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#457]
Players will drop to 0 HP and not be targetable but they don't actually die. They still stand where they should have died unable to move, completely invulnerable not responding to any stimulant until the next duel starts and they are respawned normally. In every documented case the person had a large amount of lifesteal (lich with an active satanic, legion with moment of courage). 

Looking for more cases of this happening.

**Comment by chrisinajar** [comment]
what the actual fuck

**Comment by Haganeko** [comment]
Video evidence (this time using divine orb of reduction): https://clips.twitch.tv/EnergeticElatedMelonWholeWheat

**Comment by Trildar** [comment]
Can't confirm by reproduction, but I suspect it's most likely some bugged interaction with Trump's Fists heal reduction since it uses `SetHealth`, which has been known to cause issues if ever passed anything 0 or less.

**Comment by KarmaticNeutral** [comment]
after some basic testing I believe this is fixed. I would like to get @l34Um1 to test for it first since he has experience with our known reproducible case.

**Comment by KarmaticNeutral** [comment]
checked and fixed
