### ISSUE TITLE
Update Title Screen

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#464]
Something similar to this (not my original work. i just changed the logo):
http://orig14.deviantart.net/d3bc/f/2017/097/8/8/oaa_title_concept_by_3i20d99e-db4yss2.png

**Comment by Chronophylos** [comment]
I still would like the OC to change the image...
But we could use this as a temporary solution.

**Comment by chrisinajar** [comment]
![logoredo](https://cloud.githubusercontent.com/assets/422331/24808545/fd94fe72-1b70-11e7-8f6c-519f8832a30e.png)

If you have that background without the text on it then you can just put this over it (created by steamhat, i just didn't have a plain image to put it on)

**Comment by chrisinajar** [comment]
that said, your image is actually super sick...

**Comment by Chronophylos** [comment]
I don't like it that much..
Maybe you could change the text colors a bit..

**Comment by warpdragon** [comment]
This is using your logo.
http://orig04.deviantart.net/df0a/f/2017/097/e/d/another_oaa_title_concept_by_3i20d99e-db4yula.png

**Comment by Haganeko** [comment]
Looks weird.

**Comment by warpdragon** [comment]
I mean... it's better than having the wrong name.

**Comment by warpdragon** [comment]
i can put in a pull request and get one of the two done right now. or we can fart around for a bit longer.

**Comment by Chronophylos** [comment]
Let's use the first one until we have a better one.

**Comment by warpdragon** [comment]
i'd just like to point out that the loading screen is 26.9 mb

seems kinda big, doesn't it? >1/2 of the size of the entire mod. Anyway. It was 26.9 before I changed it and it's still 26.9.

**Comment by darklordabc** [comment]
Is it saved as a jpg?

**Comment by Haganeko** [comment]
I would assume it's a png, given it's the format warp posted it in

**Comment by warpdragon** [comment]
u can compress png, but i just left it the same quality as the OC. he should be the one to make the call i guess.

**Comment by darklordabc** [comment]
The image as a jpg is 2.8mg, after compression its 500kb, and this is it below:
![image](https://cloud.githubusercontent.com/assets/16277198/24811628/1afa3218-1c0a-11e7-93ed-5bb352c565bc.png)

**Comment by Haganeko** [comment]
That's the wrong one, I think

**Comment by darklordabc** [comment]
Yeah, this is the compressed one http://imgur.com/a/vAuSh

**Comment by warpdragon** [comment]
no he means you compressed the wrong image @darklordabc 
please compress this one and submit it:
http://orig06.deviantart.net/473a/f/2017/097/9/8/loading_background_by_3i20d99e-db4z2jb.png

**Comment by warpdragon** [comment]
actually. we'll have to update all the references to panorama with the new filetype also. I trust you to handle this.

**Comment by Trildar** [comment]
Running it through Pngcrush also reduces the file size to 6.18 MB.
![test](https://cloud.githubusercontent.com/assets/17514824/24811949/bab25c0a-1bfa-11e7-85c6-012f68f81671.png)

This has the advantage of being lossless, but it's probably not that noticeable anyway.

**Comment by darklordabc** [comment]
https://github.com/OpenAngelArena/oaa/pull/466

**Comment by chrisinajar** [comment]
good enough for now! :+1:
