### ISSUE TITLE
Sometimes players get stuck in duel location after duel finishes.

### ISSUE THREAD

**Issue by RamonNZ** [OpenAngelArena/oaa#485]
Like in this video: at 19:40

https://www.youtube.com/watch?v=yCTHauNfSdQ

This seems to be cropping up again. The hero is shaking like in the video.

It will be a hero that won the duel, not one that died.

In addition, sometimes somebody will respawn just outside of the duel arena and have to walk back. I'm guessing that that is probably the same problem, but one respawns just outside, and one respawns just within (perhaps slightly in the wall)

I'm spamming duels using a local game with bots.

**Comment by RamonNZ** [comment]
So far so good.

**Comment by chrisinajar** [comment]
It's been 2 weeks since this was last reported fixed, and I haven't heard any cases of this being broken. Closing.

First ticket in 1.0 milestone down :)
