### ISSUE TITLE
Tooltips Aren't Finished

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#494]
Postactive reflexes have unspecified "x" values in their descriptions.

**Comment by Chronophylos** [comment]
`game\resource\English\ability\items\tooltip_postactive_2.txt`
`game\resource\English\ability\items\tooltip_postactive_3.txt`
`game\resource\English\ability\items\tooltip_postactive_3c.txt`

**Comment by Chronophylos** [comment]
`game\resource\English\ability\items\tooltip_preemptive_2a.txt`
`game\resource\English\ability\items\tooltip_preemptive_2b.txt`
`game\resource\English\ability\items\tooltip_preemptive_3.txt`
`game\resource\English\ability\items\tooltip_preemptive_3b.txt`

**Comment by Chronophylos** [comment]
`game\resource\English\ability\items\tooltip_reactive.txt`
`game\resource\English\ability\items\tooltip_reactive_2.txt`
`game\resource\English\ability\items\tooltip_reactive_3.txt`

**Comment by warpdragon** [comment]
X gonna give it to ya

**Comment by warpdragon** [comment]
I was gonna try and fix everything before stream... didn't have time. Anyway anybody can fix those now. You just refer to the KV raw-data name directly in teh description surrounded with %%. For instance:
"DOTA...<itemname>_Description"          "Item does %charger_damage% damage."

**Comment by Haganeko** [comment]
Just to add from #505, the items apparently also don't work.

**Comment by Haganeko** [comment]
This is pretty much "implement these items". Closed.
