### ISSUE TITLE
Reflex invincibilty

### ISSUE THREAD

**Issue by eevee911** [OpenAngelArena/oaa#505]
Reflex invincibilty not working

Amount x propably not defined
Reproducable yes

**Comment by spar36** [comment]
Which item was this?

**Comment by eevee911** [comment]
well i clicked it on the right time and didnt do anything

it's the sword you get for the reflex core with the 2400g recipe. cant look up the name

**Comment by Haganeko** [comment]
Shard of Invincibility

**Comment by chrisinajar** [comment]
duplicate of #494
