### ISSUE TITLE
Uneven number of players in duels supposedly caused by charger

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#506]
https://youtu.be/0qUD-vPgitw?t=30s

**What were you doing?**
killing a new boss in upper right corner of the map and then the duel started
**What was supposed to happen?**
tp to duel with full health 
**What happened instead?**
the game gave me full health/mana but I stayed in the boss arena

**Comment by KarmaticNeutral** [comment]
What was supposed to happen?
Duel started, everyone get teleported to duel arena
What actually happened?
Everyone was teleported to the arena and I was stuck in map to continue farming and fighting the boss.
Anything else
Im not sure how it happened, but it was during the new boss, with 250 armor that you have to lead into the stone pillars. And I did not get teleported to the duel arena with everyone else. After the timer finished, it was corrected but there was no way for me to kill myself and end the duel.

**Comment by Haganeko** [comment]
It may be caused by the t1 boss spawn - didn't we mess with the barriers around it recently?

**Comment by KarmaticNeutral** [comment]
I believe this to be caused by the charge. I think it sets the players location as they get pushed backward so if they are getting pushed back as the duel starts they'll stay where they are. (very possible I'm wrong.)

**Comment by KarmaticNeutral** [comment]
This may have been fixed when charger was removed from the t1 pits. I have never been able to reproduce it so we won't know for sure but if we can't reproduce it and a public test doesn't make it pop up I think we can assume it's fixed. I would like to get a number of test games in before we close the ticket though
