### ISSUE TITLE
Courier's Q ability doesn't send it back to fountain

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#508]
The Q has no target and doesn't get cast because we are using the secret shop as our homebase shop. If you use the W it does return to base since that is normally the side shop. We should probably change this so the Q goes to the home base and if Azazel has been taken it sends the cour to his platform.

**Comment by Trildar** [comment]
Fixed when the base shop was changed to be a proper base shop.
