### ISSUE TITLE
Update abilities for parity with 7.05

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#519]
Ability KVs were written based on 7.03, so changes from patches 7.04 and 7.05 need to be reviewed and merged into OAA. If anyone is able and willing to make a list of the necessary changes, that could make things easier. Only values for ability levels existing in normal Dota should be changed (correct me if I'm wrong).

**Comment by Chronophylos** [comment]
We need a script to do that in the future as well

**Comment by onc** [comment]
maybe i could help on this one... do you prefer any programming language for the script? do you need a graphical user interface for merging the changes or are you ok with having a command-line tool?

**Comment by Chronophylos** [comment]
I don't think so Chris has been using JS and I like Python a lot.
We already have some JS scripts, try to do that.
no GUI.

**Comment by Haganeko** [comment]
Gotta make sure it doesn't touch custom stuff, though.

**Comment by spar36** [comment]
I'll be doing work on the talents this wknd, so I will do all the parity with talents then.

**Comment by Trildar** [comment]
@onc Chris also made a simple JavaScript KV parser called parse-kv. I'm not sure it's good enough for this purpose, but do take a look at it. Chris said he wanted to improve it at some point, but I don't think he's found the time yet. Perhaps you could even contribute to that.

**Comment by onc** [comment]
thank you for the hint to the parse. i also found your guide on how to handle kv files. 
so just to make sure we are talking about the same goal right here. 

you need a script to update ability stats on new dota releases. 
if i understand your file structure these files are included in `oaa/game/scripts/npc/npc_abilities_override.txt`.

i found [this](https://github.com/dotabuff/d2vpkr) repository which (i think) contains up-to-date data from original dota, including KV's.

so should we try to write a script, which is able to parse this file
https://raw.githubusercontent.com/dotabuff/d2vpkr/master/dota/scripts/npc/npc_abilities.txt
and brings updates into your KV's?

**Comment by Chronophylos** [comment]
Yes that is what is should do. Dotabuffs Repo  is always up to date.

**Comment by Trildar** [comment]
Done long ago. Already have parity with 7.06c I believe. Would still be nice to have that script at some point though.
