### ISSUE TITLE
Improve duel code to bring in additional units

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#524]
Duel code needs to be able to handle a few things that it currently can't. 

- Multiple hero units as the same player (Meepo)
- Dominated Creeps (Enchantress, Chen, and maybe any helm of the dom units)

**Comment by Haganeko** [comment]
Please be careful not to bring in mines. Please.

**Comment by KarmaticNeutral** [comment]
Additional thought, we bring visage's ult off cool down, so we don't need to (but could) bring his birds into the arena. In my opinion they are a very integral part of the hero and if we could we would want to return those to their state before the duel like heroes especially because of how long that abilities cool down is.

**Comment by Haganeko** [comment]
This has been done, no?

**Comment by warpdragon** [comment]
Yes this has been done. Any problems with duel code should be put in a new issue in bug-reports. closing.
