### ISSUE TITLE
Fix Haganeko's stupid fix

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#561]
So I front-loaded the XP for the first two minutes, because people won't have access to mid and hard creeps. 
Small issue: this shouldn't apply to the farming cave.
Reduce XP from alpha wolves by 80 for the first spawn. Further spawns should be OK unless I screwed up royally.

**Comment by Haganeko** [comment]
Addendum to #538. @Chronophylos?

**Comment by Haganeko** [comment]
I may have found more problems. Will comment further.

**Comment by Haganeko** [comment]
Preliminary:

- [ ] cut base XP and gold for everything by 50%.
- [ ] Additionally, exclusively the first room''s first spawn needs to get its XP cut down to 40 per creep.
- [ ] Buff all creeps from second room on. Go **nuts** on them. I'm talking lasers and smoke machines and sit. 
We'll test this and go back in.

**Comment by Chronophylos** [comment]
Smoke? Will try!
The cave needs to be a lot stronger.

**Comment by Haganeko** [comment]
We fixed the gold and XP - will comment on the issue.
