### ISSUE TITLE
Charger gains magic resist instead of losing it

### ISSUE THREAD

**Issue by imaGecko** [OpenAngelArena/oaa#584]
Charger Normal: 200% Magic Resist
Charger debuffed: 480% Magic Resist
Expected debuffed: -80% Magic Resist

Flipping the value from -280 to 280 causes the charger to go from 200% magic resist to 100% when debuffed

**Comment by Haganeko** [comment]
200% resist? That makes little sense.

**Comment by KarmaticNeutral** [comment]
It makes a lot of sense if you include the fact that a lot of things can reduce magic resistance and the goal is to make it literally impossible to damage him unless you use towers. I would actually argue it needs to go higher because of elder titan.

**Comment by Haganeko** [comment]
I know of only Elder Titan aura. Most stuff increases magic damage instead, which stacks multiplicatively with resistance

**Comment by imaGecko** [comment]
Elder Titan Reduces 140% of their magic Resist, not 140% Magic Resist. Currently this causes the debuffed charger to get 200 -575 Magic Resist after hitting a tower. This also would be fixed if the Charger didn't get affected by the aura, just like the other bosses

**Comment by Haganeko** [comment]
So Charger also needs to be made an ancient.

**Comment by imaGecko** [comment]
Throwing Ice Vortex, Veil and EBlade on the charger caused his magic resist to go over 300

**Comment by KarmaticNeutral** [comment]
Proposed Fix:

ya so he has 20% magic resist and a buff raising that to 100% and when he hits a tower we remove (not break) the buff
the buff can't be broken with silveredge
leaving him at 20% resistance

**Comment by chrisinajar** [comment]
Really he should just use damage reduction... Pure damage and ET wreck him.

**Comment by Haganeko** [comment]
Titan is an easy fix. Pure damage, on the other hand...

**Comment by KarmaticNeutral** [comment]
so rather than increasing magic resistance with the buff we just give him 100% magic resistance?

**Comment by imaGecko** [comment]
How about a variation of the boss resistance? Just reduce all damage not just magic resist and then lose that buff

**Comment by KarmaticNeutral** [comment]
that is what was suggested. 100% complete magic resistance.

**Comment by Haganeko** [comment]
That, or just an additional 9%. Damage reduction stacks additively, no? That would make him very tanky

**Comment by Trildar** [comment]
Keep in mind that making him completely damage immune (and possibly even 99% damage resist) would make it impossible to break the Heart healing when the boss isn't debuffed.

**Comment by KarmaticNeutral** [comment]
This was closed with a PR. I don't know how it was done, but magic damage works.
