### ISSUE TITLE
Let's get the tooltips for Reflex items wrapped up

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#585]
It would be nice. AFAIK all the items work as advertised in our google doc (link can be found on my site.)
Should be easy to just go in and update everything. Remember to backup and restore addon_english.txt and create a new branch before starting!

**Comment by Trildar** [comment]
The Preemptives don't technically purge only modifiers received after activation right now, but that should hopefully be possible. I don't know if Chris has started any work on that yet.

**Comment by warpdragon** [comment]
The ones that say "usable while stunned" are usable while stunned? All that type stuff is functioning?

**Comment by Trildar** [comment]
Needs testing for confirmation, but the usable while stunned should work. I've lost track of which Reflex items haven't been implemented yet. I know Bubble Orb hasn't. Probably Negation Shard as well.
