### ISSUE TITLE
Bonuses from modifier_generic_bonus do not stack

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#586]
Multiple items/abilities using `modifier_generic_bonus` don't stack the bonuses and seem to choose value priority in an odd way. Since only Reactive Items currently use that and you should only have one, it's not really an issue, but something to keep in mind in case we end up using `modifier_generic_bonus` for stat bonuses for other items.

**Comment by Haganeko** [comment]
How would one rework them to avoid this problem?

**Comment by SquawkyArctangent** [comment]
Overriding GetAttributes to return MODIFIER_ATTRIBUTE_MULTIPLE would likely help.
