### ISSUE TITLE
Holes in blink blocker

### ISSUE THREAD

**Issue by imaGecko** [OpenAngelArena/oaa#589]
There are some parts on the map where you can blink on top of walls, through walls outside the map and into farming caves

Map:
https://i.gyazo.com/81fa3480fe25fb1585ed207cf138b8d8.jpg

1:
https://i.gyazo.com/00cfd1ad4226d8de18329076c05883f1.mp4

2:
https://i.gyazo.com/b81df9cbd4c3868d345a2622beb49bca.mp4

3:
https://i.gyazo.com/91e95c3012c9f0eed1c50773ad4ecf45.mp4

4:
https://i.gyazo.com/affdfc41ac3bae797e535c0636087f83.mp4

4 is probably the most useful as you can very consistently jump on the wall to the left and then escape through the bottom

You can also leave the map at any part at the top border which can be used to jump between the areas as well as into the end of the farming cave
https://i.gyazo.com/8927ba058402529e6885dc9549589184.mp4

**Comment by warpdragon** [comment]
Outdated. Will revisit ife these same locations pose problems in future. Closing.
