### ISSUE TITLE
Mini Rosh Fixes

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#595]
A couple of points:

1. Fix the shrinkage.
2. Rosh needs to have a max leash distance.
3. More?

**Comment by Chronophylos** [comment]
That getting smaller was intended. But not that much. I wanted it to be only noticeable after clearing the cave multiple times

**Comment by chrisinajar** [comment]
smaller > bigger, agreed it should go slower.

**Comment by Haganeko** [comment]
We're working under the supposition that the farming cave will be cleared some six times in a 50 minute game. Scaling the Roshan down by 12% each time should about halve his size by then, which is definitely noticeable.

**Comment by Haganeko** [comment]
(he'd be just over 50% size during the sixth clear)

**Comment by warpdragon** [comment]
Why on earth would he get smaller as he becomes more powerful?

**Comment by l34Um1** [comment]
its funny

**Comment by Haganeko** [comment]
Because this is Bleach and Roshan is an Espada. 
More seriously, because growing would make his hull size huge and a we know this is a problem

**Comment by warpdragon** [comment]
Well then can Roshan atleast get a Green Yellow and Red beanie that says "I <3 Weed"?

**Comment by RamonNZ** [comment]
The Mini Roshan leash really needs to happen because you can just kite them merrily to your fountain.
