### ISSUE TITLE
Add particle effects to reflex items

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#604]
Reflex items need a particle effect on activation so people can tell they got activated. 

On activation I want a big text pop up on top of the heroes head that says "REFLEX", similar to the arcana text pop ups. This text lingers a tiny bit.

Further there should be a very short outward moving bubble effect on the hero. This effect should be very short and fade away very quickly, imagine a slightly slower and less violent burst from Abaddons shield. 

Further there should be a lingering color changing effect on the hero. This color change should be the same color as the bubble burst and lasts for the duration of the reflex core effect (so in some cases 4 seconds, in others 0,5s, for zone based cores you gain the color change while inside of the zone). 

The text is the same for all reflex cores and always comes up. The color change should be different for each category of reflex item, so 3 different ones overall.

**Comment by Trildar** [comment]
I feel like the text might be somewhat overkill assuming the items already have other particle and sound effects. It would tell people that Reflex Items are in play, but their effects are pretty varied, so I'm not sure how valuable that would be. Though it could be a good idea for the Reactive class since their effects are so short.

**Comment by Haganeko** [comment]
This would look very silly, especially for some of the longer duration ones. Additionally, we already have people thinking up particle and sound effects specific to each, which would be much more informative. I don't like this.

**Comment by warpdragon** [comment]
REFLEX

**Comment by warpdragon** [comment]
combining with issue 605
