### ISSUE TITLE
Include Particles and Projectiles for all items.

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#605]
In particular: 

### Reflex Items

Reflex items need a particle effect on activation so people can tell they got activated.

On activation I want a big text pop up on top of the heroes head that says "REFLEX", similar to the arcana text pop ups. This text lingers a tiny bit.

Further there should be a very short outward moving bubble effect on the hero. This effect should be very short and fade away very quickly, imagine a slightly slower and less violent burst from Abaddons shield.

Further there should be a lingering color changing effect on the hero. This color change should be the same color as the bubble burst and lasts for the duration of the reflex core effect (so in some cases 4 seconds, in others 0,5s, for zone based cores you gain the color change while inside of the zone).

The text is the same for all reflex cores and always comes up. The color change should be different for each category of reflex item, so 3 different ones overall.

### Trump's Fists 

Trumps Fists need a color changing effect similar to Skadi, so when you hit a guy they become purple (or whatever, pick whatever color you think works best).

Ranged heroes using Trumps Fists should also gain a new projectile, similar to Skadi or Desolator.

etc.

**Comment by Haganeko** [comment]
Needs to be orange.

**Comment by Chronophylos** [comment]
Orange small hands?

**Comment by l34Um1** [comment]
Closed because old.
