### ISSUE TITLE
Disable Rearm on Reflex Items

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#606]
Currently Tinker can rearm Reflex Items. He shouldn't be able to.

**Comment by Trildar** [comment]
I'm guessing Refresher Orb/Core also shouldn't refresh them?

**Comment by l34Um1** [comment]
Nah those are okay since it's got a longer cooldown. Rearm is a problem because of 100% uptime.

**Comment by Honeth** [comment]
we need to add ```
function item_refresher_core:IsRefreshable()
  return false
end
```

to all reflex items

**Comment by Trildar** [comment]
Unless I'm somehow remembering wrongly, Rearm doesn't respect `IsRefreshable`. So adding that would only make it not refreshable by Refresher Orb. Probably needs a rewrite of Rearm. Shouldn't be hard. The SpellLibrary can be used as reference for how to do the audiovisual effects and the refreshing can reuse the Refresher Core code.
