### ISSUE TITLE
Introduce cooldown for bashes 

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#607]
Add cooldowns for bashing abilities, including items, into their KV files. Don't worry about the values, I'll adjust them later.

**Comment by Haganeko** [comment]
Basher already has a cooldown, no? Or do you mean MKB as well?

**Comment by l34Um1** [comment]
FV and Slardar need it

**Comment by Haganeko** [comment]
True. I asked because you said items. Doesn't troll need one too?

**Comment by Haganeko** [comment]
Done!
