### ISSUE TITLE
Limit "room x cleared"-text to only people in the farming cave

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#610]
Title.

**Comment by Haganeko** [comment]
Should this display at all? It sounds like a debug thing.

**Comment by Trildar** [comment]
Maybe when we have the visible doors we can consider taking it out, but right now it's good to inform people not familiar with how the farming cave works.

**Comment by warpdragon** [comment]
Limit teleporting to fountain to players in the cave or implement teleporter pad

**Comment by warpdragon** [comment]
Take a look in the assets browser for a suitable model. I bet theres some cool ones in there

**Comment by Chronophylos** [comment]
There are some good particles as well

**Comment by warpdragon** [comment]
I know. Either way. I dont much like the duct tape used at the entrances of the individual boss arenas

**Comment by warpdragon** [comment]
Has anyone done this? Seems simple enough.
