### ISSUE TITLE
Add in particle effects to indicate the doors between farming cave rooms

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#611]
In the farming caves you can only move on to the next level if you clear the previous one. To prevent that movement we have invisible doors between the caves that only unlock if the condition is met. These doors should become visible. Add in some sort of particle effect indicating that the door is shut that dissappears once it opens.

**Comment by Chronophylos** [comment]
(there is no door)

**Comment by Chronophylos** [comment]
(there is no door)

**Comment by warpdragon** [comment]
You're a door

**Comment by Chronophylos** [comment]
If you say so..

**Comment by Honeth** [comment]
it's a movement blocker that is keeping you from moving which means we can probably add a particle to the blocker

**Comment by warpdragon** [comment]
Possibly

**Comment by warpdragon** [comment]
Some ideas <https://youtu.be/t5iiYrOl6y8>

**Comment by warpdragon** [comment]
What about something like this? 
![image](https://cloud.githubusercontent.com/assets/13878439/25551653/e80ce222-2c55-11e7-9b5e-2942efdc3a69.png)
