### ISSUE TITLE
Farming Cave XP values are seriously overblown.

### ISSUE THREAD

**Issue by RamonNZ** [OpenAngelArena/oaa#614]
First off, 5 manning the first 3 rooms of the Farming Cave within the first couple of minutes of the game guarantees the team instant level 4 pretty much. With 5 players who have nukes and some sustain that is not hard.

Then you may as well just 5v2 the Roshans until they die, because after they die in about 5 minutes, you can do the whole Farming Cave again and get another 3-4 levels. Rinse and Repeat. After the first 2-3 times it becomes really fast because you have enough money for MKBs etc, and by minute 20 you're easily level 50+

The farming cave really **shouldn't give enough xp to gain a level per wave clear** for a start or a team may as well stay there for the whole game, and **the first 3 rooms probably shouldn't be able to be walked over at the beginning of the game**, or else that should be a team's first priority every game.

**Comment by Haganeko** [comment]
I've discussed this with Chris and I have addressed the problem in #561. I don't know if what we came up with has been implemented yet, but it should be a major help with that problem.

**Comment by RamonNZ** [comment]
My game must have been out of date. 

I see that the farming cave monsters have been buffed tremendously. The XP is still high, but completing the caves at the beginning of the game is a lot harder. I'll withdraw this issue.

**Comment by RamonNZ** [comment]
After testing I can say that the farm cave XP is still overblown. 

They can't be done at level 1 now, which is good, but they could be done at approx level 4 and then just power levelled every minute or two with +3-4 levels every time they're cleared.

The XP probably needs to be halved, and the power of the farming caves increased exponentially each time, so that you can't just keep on doing it over and over imo.

**Comment by Trildar** [comment]
Unless the design has changed, the intention was for one room (single camp) to be cleared around every two minutes. So it's probably not so much the XP that's the problem as the creep power levels.

**Comment by Haganeko** [comment]
I believe this is fixed.
