### ISSUE TITLE
Make Invulnerability and Reflection Shards block everything (or as much as possible)

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#619]
The Reactive Items mentioned in the title currently only block damage rather than blocking all effects. Using actual Dota invulnerability is likely undesirable as it would prevent most targeting during the buff period. Unless something better can be thought of, the Bubble Orb method of using a `ModifierGained` filter and `AbsorbSpell` is probably a good place to start.

Magic Immunity could also be used, possibly instead of the `ModifierGained` filter. This would require figuring out a way to dodge attacks fully instead of just blocking the damage though, in order to prevent attack effects.

**Comment by Chronophylos** [comment]
I found some functions that may be useful:
```Lua
bool CDOTA_BaseNPC.TriggerModifierDodge()
bool CDOTA_BaseNPC.TriggerSpellAbsorb(handle hAbility) -- Query whether the passed ability will trigger spell absorb on this unit. 
ProjectileManager.ProjectileDodge(handle unit) --  Makes the specified unit dodge projectiles 
```
And modifier properties

Name | Value | Lua function | Description
------------ | ------------ | ------------ | ------------ 
MODIFIER_PROPERTY_ABSORB_SPELL | 77 | GetAbsorbSpell | Allows the parent to ignore targeted abilities. (Similar to linken's sphere) 
MODIFIER_PROPERTY_REFLECT_SPELL | 78 | GetReflectSpell | Allows the parent to reflect targeted abilities. (Similar to Lotus Orb) 
MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PHYSICAL | 87 | GetAbsoluteNoDamagePhysical |  
MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_MAGICAL | 88 | GetAbsoluteNoDamageMagical |  
MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PURE | 89 | GetAbsoluteNoDamagePure |

**Comment by Chronophylos** [comment]
That table....

**Comment by Trildar** [comment]
`TriggerAbsorbSpell` is just for checking, so probably not too useful for actually blocking. No idea what `TriggerModifierDodge` does, and I'm not even sure how to test it.

**Comment by RobbertdeJel** [comment]
Wouldn't it be better to just avoid the unit from taking any damage at all? 

I found this on the valve wiki: https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/API/CDOTABaseGameMode.SetDamageFilter

I would say it would be better to apply a variable to the player entity such as `self.hasRefraction = true` And check within that function and set the damage he was suppoced to take to 0

**Comment by Trildar** [comment]
@RobbertdeJel I don't think there's any real difference between this and doing damage block from the modifiers directly. Using a Filter unnecessarily just creates potential for things to go wrong since Filters work on a larger scope. The issue isn't the damage blocking anyway, I think that part is working fine. The issue is that just blocking damage isn't exactly "invulnerability" and the Postactive Reflex Items pretty much have better damage blocking since they have longer duration.
