### ISSUE TITLE
Implement "Honorable Angel" boss

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#62]
## Notable stats
Lots of magic resistance and armor.

phase 2 at 80% hp
phase 3 at 50% hp
phase 4 at 20% hp

## Arena Modifications
none

## Abilities
 * Phase 1: Just regular rightclicks, nothing special
 * Phase 2: he gets fed up with people ganging up on him. Every now and then he'll scream "fight me honorably, curs!" and push away and disarm everyone near him who's not his current target. The push/disarm is a constant effect like havres wind. It is canceled once the boss gets stunned.
 * Phase 3: he'll start saying "I challenge thee!", and pulls the farthest hero to himself (like a forcestaff push) 
 * Phase 4: he'll scream "I have had enough"; the pull now creates an arena that the pulled enemy can't leave

## Balance
Expose the following as configurable variables, either at the top of the lua file or in KV format

 * Base movement speed, hp, regen, damage, attack speed
 * pull range
 * wind effect push speed
 * duel arena aoe

**Comment by warpdragon** [comment]
putting these into 1 issue.
