### ISSUE TITLE
Make Refresher Orb not refresh Refresher Cores

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#623]
Should just be a matter of adding `IsRefreshable` to the Refresher Core Lua.

**Comment by Honeth** [comment]
wouldn't that be KV

**Comment by Chronophylos** [comment]
No it's [Lua](https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/API/CDOTA_Ability_Lua.IsRefreshable)

**Comment by Honeth** [comment]
alright i hate myself XD where is it located i can prob add it to my current PR

**Comment by Chronophylos** [comment]
`game\scripts\vscripts\items\refresher_core.lua`

**Comment by Haganeko** [comment]
While you're at it, can you make it so different octo cores don't stack? We have the whole CDR problem all over again.

**Comment by Haganeko** [comment]
Oh okay there's #624

**Comment by Honeth** [comment]
just adding IsRefreshable = false or IsRefreshable(0) or IsRefreshable() = false 

either makes the refresher core not work or just doesn't fix the issue at hand

**Comment by Chronophylos** [comment]
don't you need to do
```Lua
function refresher_core:IsRefreshable()
  return false
end
```
?

**Comment by Honeth** [comment]
alright will try

 i just got this error message ingame aswell 

> [ W VScript                ]: Script Runtime Error: scripts/vscripts/components\reflexfilters\bubble.lua:16: Parameter type mismatch
[ W VScript                ]: stack traceback:
[ W VScript                ]: 	[C]: in function 'EntIndexToHScript'
[ W VScript                ]: 	scripts/vscripts/components\reflexfilters\bubble.lua:16: in function 'fun'
[ W VScript                ]: 	scripts/vscripts/libraries\fun.lua:30: in function 'gen_x'
[ W VScript                ]: 	scripts/vscripts/libraries\fun.lua:586: in function <scripts/vscripts/libraries\fun.lua:584>
[ W VScript                ]: 	[C]: in function 'LaunchLoot'
[ W VScript                ]: 	scripts/vscripts/components\creeps\item_drop.lua:58: in function 'CreateDrop'
[ W VScript                ]: 	scripts/vscripts/components\creeps\item_drop.lua:76: in function <scripts/vscripts/components\creeps\item_drop.lua:69>


every time i killed a creep and it dropped an item

**Comment by Chronophylos** [comment]
Ignore that.
I think @Trildar fixed these errors already in #602.

**Comment by Honeth** [comment]
alright so the line you tossed didn't work but i'll try keeping the isrefreshable as a function instead of a variable this time

**Comment by Honeth** [comment]
Got it in the PR #622 travis AI checked it
