### ISSUE TITLE
Implement Twin Boss

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#625]
# **Notable stats**

Twint bosses, which reset each other's HP to the highest among the three
phase 2 at 85% hp
phase 3 at 50% hp

# **Arena Modifications**

There should be plenty of space for the boss to move.

# **Phase 1:**

The bosses reset HP every 3s

# **Phase 2:**

The bosses reset HP every 1,5s

# **Phase 3:**

The bosses reset HP every second.

# **Balance**

Expose the following as configurable variables, either at the top of the lua file or in KV format

Base movement speed, hp, regen, armor etc.
Reset Rate for each phase.

**Comment by KarmaticNeutral** [comment]
This is in the game. I have a few bugs to fix then it will be done.

**Comment by KarmaticNeutral** [comment]
Created a new ticket just for bugs.
