### ISSUE TITLE
Implement "Slime" boss

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#63]
## Notable stats
instead of dying the boss splits into 2 smaller slimes
 * smaller slimes have 75% HP of the original
 * splits a total of 3 times

## Arena Modifications
none

## Abilities
 * jumps into the air to attack
		* shadow appears below him while he is in the air to show where he is
		* travel time is significant enough to allow for proper dodging
		* deals damage where he lands
			* all enemies hit are pushed away and slowed massively
			* this is his highest single source of damage
 * if you "kill" him he starts shaking violently
		* during that stage he is invincible and throws small projectiles all over the arena
			* they work just like the regular jump, thrown into the air, with a shadow telegraphing where they land
			* come in different sizes
			* players need to focus on dodging them
			* if hit they take damage and are slowed

## Balance
Expose the following as configurable variables, either at the top of the lua file or in KV format

 * Base movement speed, hp, regen
 * Size of the Slime
 * damage of the jump
* duration of the jump
* push distance and slow duration and %

**Comment by warpdragon** [comment]
pout into 1 issue.
