### ISSUE TITLE
Boss Drop System

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#631]
Bosses have 2-4 items in their inventory (besides heart) and every boss drops one of the items that they have in their inventory at random (besides heart) in addition to the normal upgrade cores. This item is of the level of the core that boss drops.

**Comment by Trildar** [comment]
I'm not sure how feasible the inventory thing is since they have to somehow be muted. Putting them in backpack could work possibly, but that would only support up to 3.

**Comment by KarmaticNeutral** [comment]
why mute them?

**Comment by Honeth** [comment]
heart isn't muted either and it only gives it's hp regen

**Comment by Chronophylos** [comment]
What about "stop fighting yourself"? He duplicates enemy heroes inventorys

**Comment by Honeth** [comment]
at the moment any stats on items don't change boss value's they don't get anything from the stats as far as i know, so any passive's on the items will probably work

**Comment by KarmaticNeutral** [comment]
We could do it still

**Comment by Chronophylos** [comment]
What about a treasure chest displaying the bosses loot?

**Comment by Minnakht** [comment]
Whatever the solution, if the bosses' drops are randomized, it could cause them to be swingy. Radiance and Lucience both would make bosses significantly tougher, for one. If bosses had set items to drop and they were included as part of their balance, it'd be another matter entirely...

**Comment by Chronophylos** [comment]
I'm sure stats work...

**Comment by Chronophylos** [comment]
![image](https://i.imgur.com/4jY8baC.jpg)
Base Movespeed is at 300

**Comment by KarmaticNeutral** [comment]
Okay evidently communication on my end was poor. 

We are assigning each boss 2-4 items that they might drop. 
They will only ever drop one of these 2-4 items each time you kill them.
We will not randomly assign these. 
The effects of these items in the game will be considered carefully.
Players will then be able to build items like Azazel's Crossbow.
It will be a large investment if you don't get the drop.
We will have some bosses only have 1 possible drop
Stats don't work on bosses because we hard code all their values in their KVs meaning as long as we don't add AI to use them items they won't do anything in a boss's inventory.

Did I miss anything?

**Comment by warpdragon** [comment]
Outdated
