### ISSUE TITLE
Implement "Stop Fighting Yourself" Boss

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#64]
## Notable stats
Lots of magic resistance and armor.

phase 2 at 66% hp
phase 3 at 33% hp

## Arena Modifications
none

## Abilities
* phase 1
  * he applies all debuffs on him on every attack
* phase 2
  * every 5 seconds he duplicates the item set of the next hero to attack him
  * active items would be used instantly and on random targets
  * except bloodstone
  * if aegis is in the game also needs to be muted
  * attribute bonuses would have to be converted into their factual bonuses
  * not sure if cooldowns should be reset
* phase 3
  * creates illusions of all enemy heroes in the arena that can use all items and abilities
  * illusions deal less damage, take more
  * use their spells and items on random targets but not all at once
  * can be killed but dont have a timer
  * dissappear if the boss dies
## Balance
Expose the following as configurable variables, either at the top of the lua file or in KV format

 * Base movement speed, hp, regen, damage, etc
 * damage variables for illusions

**Comment by Chronophylos** [comment]
This is funny

**Comment by Chronophylos** [comment]
@l34Um1 what do you mean with
> if aegis is in the game also needs to be muted

and
> attribute bonuses would have to be converted into their factual bonuses
