### ISSUE TITLE
Improve Boss Spawning to allow continued boss development

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#644]
Allow for a randomization of of multiple tiers of bosses in the same pit.

The objective is the chance to spawn npc_dota_boss_tier_1 and npc_dota_boss_shielder and npc_dota_boss_rotating_shielder in the same pit depending on randomization at the beginning of the game.

**Comment by chrisinajar** [comment]
Randomization, round robin, or both (RR with randomized order each round)?

**Comment by Haganeko** [comment]
There should be only one of each per team.

**Comment by Haganeko** [comment]
This is obsolete now, no?

**Comment by warpdragon** [comment]
Outdated.
