### ISSUE TITLE
Add particle effects to the rune hill

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#646]
Currently being in the rune hill (high ground area in duels which gives you buffs if you stay in there) applies a modifier but no visual effects to the hero. Lets get some sort of "powering up" effects to appear around heroes actively holding the high ground area.

Bonus points for making the effects scale based on current charges on the modifier.

**Comment by Haganeko** [comment]
A recolor of the GG activation effect would do it.

**Comment by l34Um1** [comment]
I also want particles indicating the area where you can stand to get the bonuses. Kinda like this: http://cdn.blizzardwatch.com/wp-content/uploads/2016/04/hanamura-1.jpg

**Comment by Haganeko** [comment]
Maybe use a different tiling on that part of the map?

**Comment by kallleeeeh** [comment]
Legion Commanders Duel circle could also work
