### ISSUE TITLE
Write a script to detect missing tooltips

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#647]
We need a script that parses the item KV's and the modifier lua files to find translatable tooltips like modifiers or item descriptions, then they use the existing scripts to read in all tooltips and confirm that each expected tooltip is present at minimum.

This is a large undertaking to do well, but it also should be somewhat simple. I think it's important to scan for the `:IsHidden` function and see if the modifier is always hidden, and not bother checking for their tooltips in that case. We can scan for LinkLuaModifier to find the modifier names, and those lines also inherently indicate if the modifier is built in or not (meaning no tooltip is required).

glhf

**Comment by Chronophylos** [comment]
Make sure it's cross platform

**Comment by chrisinajar** [comment]
Done.
