### ISSUE TITLE
Implement "Swiper" boss

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#65]
## Notable stats

doesn't attack regularly
* instead his attacks follow a more "dark souls" logic
		* he swings his sword in a big arc
		* any enemy that touches the sword takes damage
		* if you are in 200(?) range of the boss you will always get it

*every attack has a lengthy wind-up
* during wind-up the ground will have particles showing where the hitbox of the sword will be, allowing people to dodge
* every attack deals significant damage although people should be able to tank 4-5 hits
* there are 3 different kinds of sword swipes (see images in folder)
		*swipe 1 "Thrust": long range, targeted at an enemy in the backlines
			* selects an enemys location at the beginning of wind-up, doesn't home afterwards
![swipe 1](https://cloud.githubusercontent.com/assets/24982519/22711401/53eb0258-ed81-11e6-8ee9-d4eeba49e160.jpg)
		* swipe 2 "frontswipe": short range, targeted in such a way that it hits as many enemies in range as possible
![swipe 2](https://cloud.githubusercontent.com/assets/24982519/22711398/53e4be5c-ed81-11e6-991c-6c7523b181ee.jpg)
			* swipe 3 "backswipe": same range as frontswipe, comes out at random times as a fast follow up to frontswipe
![swipe 3](https://cloud.githubusercontent.com/assets/24982519/22711399/53e6b536-ed81-11e6-92f4-c48c18874ca7.jpg)
			* has a shorter wind-up than frontswipe
			* covers mostly the same area as the frontswipe, doesn't do new targeting

phase 2 at 66% hp
phase 3 at 33% hp

## Arena Modifications
none

## Abilities
* Phase 1:
	* just the regular attacks to get people used to what the boss can do
* Phase 2:
        * boss gains "rush" ability
		* long cooldown (10s?)
		* needs to be visually obvious
		* boss holds out sword with active hitbox to the right of him 
	![rush 1](https://cloud.githubusercontent.com/assets/24982519/22711400/53e8f4a4-ed81-11e6-8034-956407b0552d.jpg)
		* boss rushes to a location in the arena
![rush 2](https://cloud.githubusercontent.com/assets/24982519/22711397/53e3a5bc-ed81-11e6-943e-0487e4da978f.jpg)
			* enemies hit by the sword take massive damage
			* enemies hit by the boss get pushed away, get slowed and take a little damage
* when the boss finishes the rush he does a big aoe swing attack that deals massive damage 

![rush 3](https://cloud.githubusercontent.com/assets/24982519/22711396/53e30940-ed81-11e6-85f0-af7c3f76000a.jpg)

* Phase 3:
	* boss gains teleport ability
	* before each swing he teleports behind a random enemy in the arena and then the wind up starts

## Balance
Expose the following as configurable variables, either at the top of the lua file or in KV format

 * Base movement speed, hp, regen, damage, etc
 * AOE of Attacks
 * Rush Speed
 * Windup speed

**Comment by warpdragon** [comment]
Putting into 1 issue.
