### ISSUE TITLE
Get a lua linter that detects when we leak variables into global scope

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#659]
It causes bugs and it's super hard to notice.

**Comment by Chronophylos** [comment]
lualint and luacheck would work if we tell them to ignore dota api globals

**Comment by chrisinajar** [comment]
I had to configure semistandard to ignore them too

**Comment by Haganeko** [comment]
I'm assuming the luacheck we currently have didn't fix this?

**Comment by warpdragon** [comment]
Progress?

**Comment by Chronophylos** [comment]
ask travis
