### ISSUE TITLE
Implement "Mirror" Boss

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#66]
## Notable stats
Is always floating around the arena into random directions with 150 or so movement speed

phase 2 at 66% hp
phase 3 at 33% hp

## Arena Modifications
* The entire arenas border has a mirror effect going on 
	* preferably even a visual effect 
	* maybe people can even bounce spells off of it 
	* If any of the bosses abilities hit the mirror they are reflected and continue flying

## Abilities
* Phase 1: 
	* throws out orbs that deal damage when you touch them 
	* These orbs are relatively big, don't dissappear until the boss is dead and bounce of the mirrors 
	* There is a maximum amount of them, like 4 or so

* Phase 2: 
	* the boss starts firing a Kamehameha style laser 
	* Before he does so he makes a dash away from the enemies 
	* The lasers direction is clear 
	* The laser bounces of the mirrors multiple times (unsure about the speed but either very fast or instant) 
	* You take damage for every frame you touch the laser

* Phase 3: 
	* the boss now starts throwing smaller but faster orbs into the fight 
	* There is no limit to these so the fight becomes a race against the clock since eventually the entire arena will be covered

## Balance
Expose the following as configurable variables, either at the top of the lua file or in KV format

 * Base movement speed, hp, regen, armor etc
 * damage, speed, aoe of orbs 
 * damage, speed, aoe, length of laser

**Comment by warpdragon** [comment]
putting into 1 issue
