### ISSUE TITLE
Fix Twin death handling and phase control

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#662]
1) Make the second death be the death that drops cores
2)Fix phase control to reduce heal time (2 1.5 1)

**Comment by Haganeko** [comment]
Is this done?

**Comment by KarmaticNeutral** [comment]
no. It's on my to do list but I'm busy

**Comment by KarmaticNeutral** [comment]
#833 is trying to fix this.

**Comment by warpdragon** [comment]
moved to bug-reports. post there next time.
