### ISSUE TITLE
Implement Rotating Shield Boss

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#664]
A boss that has simple agro mechanics but has a rotating shield making timing of spell usage highly important.

Most of this boss will be copied from the shield boss.

**Comment by warpdragon** [comment]
Thread is dead. Closed.

**Comment by Haganeko** [comment]
Shouldn't this be merged into the boss implementation issue?

**Comment by warpdragon** [comment]
sure why not.
