### ISSUE TITLE
Make dumb twin ranged

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#666]

**Comment by KarmaticNeutral** [comment]
Also, make smart twin AI change targets if it gets too close to its brother to the furthest target from its brother.

**Comment by warpdragon** [comment]
you should write why this needs to be done in your [No description provided.]. Cmon bruh.

**Comment by l34Um1** [comment]
If they are apart the fight becomes actually interesting. Currently its just a silly cleave and AOE fest.

There also needs to be a particle effect that happens when the healing occurs. I propose just using Sunders animation.

**Comment by Minnakht** [comment]
this is done already, no?

**Comment by Chronophylos** [comment]
Yes, in #671
