### ISSUE TITLE
Need sound effects for significant boss mechanics

### ISSUE THREAD

**Issue by RionTwist** [OpenAngelArena/oaa#673]
Sounds should be implemented for existing bosses to convey significant mechanics. These should include:

**All bosses-**

- [ ]  when the boss is hurt by an autoattack in a way that causes the damage dealt to be significantly reduced. (suggestion: Blade mail targeted sound)
- [ ] when the boss is hurt by a spell in a way that causes the damage dealt to be significantly reduced. (suggestion: Linken's Sphere proc)
- [ ] when the boss is hurt by an autoattack that deals unreduced damage (suggestion: Maim effect proc)
- [ ] when the boss is hurt by a spell in a way that deals unreduced damage (suggestion: Echo Saber proc?)

**Charger**

- [ ] when the charger charges (suggestion: Magnus' skewer cast)
- [ ] when the charger hits a player (suggestion: Magnus' skewer on hit)
- [ ] when the charger hits a pillar and his defenses are down (suggestion: Earthshaker's Enchant totem)

**Shielder**

- [ ] when the shield radius is increased (suggestions: cast buckler or crimson guard)

**Twins**
- [ ] when either twin heals for over 5% of their HP (suggestions: Hill Troll Priest's healing cast)

**Finally**
- [ ] consider for future boss implementations

Obviously custom sounds would be great, but as a placeholder standard dota sounds should be used.

**Comment by Haganeko** [comment]
Blade mail sounds like it'd evoke the wrong idea, of it hurting the attacker. 
For charger, why not charge of darkness?

**Comment by l34Um1** [comment]
Closed because old.
