### ISSUE TITLE
Implement the Black Star shop

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#678]
Get the shop from blackstar to allow us to have a third tab in our shop.

**Comment by warpdragon** [comment]
Yeah im looking into it. Anyone interested in helping tackle this leme know i can assist. Or contact chronophylos. Its a bunch of js mostly, and some lua that needs to be patched in

**Comment by warpdragon** [comment]
@Chronophylos has patched the shop code in #692 
If anyone wants to help him test it... play around with the code... etc... Just add him to your remotes, and then pull his repo into a development branch. I think I got that right.

**Comment by KarmaticNeutral** [comment]
I'm gonna close this issue. We have an improved shop and will continue to improve it without this
