### ISSUE TITLE
Implement new reflex and core icons

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#686]
Angels blood, demons blood, angels soul, demons soul, reflex core, etc. https://imgur.com/a/BdcnN

**Comment by warpdragon** [comment]
started a branch for this. stand by

**Comment by Haganeko** [comment]
Implement names for them while at it?

**Comment by warpdragon** [comment]
possibly. dunno. raw-data doesn't really matter, in the end. it would be nice to keep the names as close as possible. the problem is that it would involve changing every mention of the name of the file and i don't have the option of doing gameplay testing at the moment. i think we could do a separate PR in future and update the names of everything but at the moment no i don't think it's necessary.

**Comment by Haganeko** [comment]
I didn't mean the internal name. I meant the item's display name.

**Comment by warpdragon** [comment]
The reflex ones are already changed to be correct. The upgrade cores aren't. Baumi said he liked them as-is.
