### ISSUE TITLE
Boss battle system

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#7]
We need some generic API's for composing boss battles. This is not for the bosses or their abilities, but everything around that.

* [ ] API to teleport players to a given zone where a boss fight can happen
  * [ ] stub in flow to pass which boss is summoned*
  * Consider that some boss battles people can join later, while others they cannot.
* [ ] need / greed / pass for item drops
  * [x] Panorama UI displayed to players
  * [ ] Logic to give out items based on selections

* We can decide what the object that is passed through looks like later, when we design the actual bosses.

**Comment by salacryl** [comment]
I'll try to compose some draft in pseudo-code (just function signatures) so we can easily go in the direction we want to.

**Comment by salacryl** [comment]
Json? Like:
local json = require("json")
local filename = "f:/boss1.txt"


local f = io.open(filename, "rb")
    local content = f:read("*all")
    f:close()

local o= (json.decode(content))
table.foreach(o,print)

**Comment by chrisinajar** [comment]
Perhaps? It might also be KV driven. I would just leave a spot in the method signatures to pass a "boss object" that we can define later.

```lua
function startBossBattle (players[], zone_name, boss)
{
  -- do teleport
  -- do other stuff?
  activateBoss(zone_name, boss);
}
function  activateBoss(zone_name, boss)
{
  -- noop for now
}
```

**Comment by salacryl** [comment]
Exactly what I was thinking. Like a folder for each Boss. KVs and like "phase1.lua", "phase2.lua" etc. Lua kann load and execute files like 
`assert(loadfile('phase1.lua')`

and we had a lean & mean setup for each boss.
