### ISSUE TITLE
Implement Havres

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#707]
# **Notable stats**

While fighting Havres, she is always indicating a direction. All units fighting her experience a pull in that direction. While they can act fully, they will always have to make time to compensate for that pull with their movement. Example: She indicates to the right. If you now try to walk to the right you'll go faster; if you try to go to the left you'll be slower and if you try to walk up or down then you'll actually end up tilted to the right.
To go along with this, her main source of damage are paintings she draws on the ground. There'll be a line of particles that draws a pattern on the ground and after it is complete the pattern lights up and becomes active. If you touch this pattern you take damage and become disarmed. While fighting him you'll always have to be moving to avoid being pulled into these drawings.
Phase 2 at 70% hp
Phase 3 at 40% hp

# **Arena Modifications**

None are necessary.

# **Phase 1:**

Havres draws simple patterns, which last for a short time and expire

# **Phase 2:**

Havres now adds to patterns already in place, and each one lasts longer.

# **Phase 3:**

Havres now also has two projectile spells she can throw out:
- A fast-moving projectile, which deals damage on hit
- A low-moving, large projectile which deals damage over time during contact

# **Balance**

Expose the following as configurable variables, either at the top of the lua file or in KV format

Base movement speed, hp, regen, armor etc.
Pattern damage, frequency (cooldown?), and duration.
Projectile damage and speed.
Pull strength and direction change frequency.

**Comment by Haganeko** [comment]
I noticed we didn't have one of these.

**Comment by warpdragon** [comment]
combining with others.
