### ISSUE TITLE
Implement Shield Boss

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#71]
# **Notable stats**

Has a shield or barrier of sorts blocking an angle around it, centered on the direction it's facing, which functions like Bristleback (from the eponimous hero), reducing all damage caused  by sources in that angle. The shield does not offer any protection from stuns or spells beyond the damage reduction.
Has a decent-powered melee attack.
Keeps track of how much damage (before all reductions) each unit has dealt it in the last X seconds (value up to balance), and always aggro's the one which has dealt the most.

phase 2 at 75% hp
phase 3 at 50% hp

# **Motivation**
The boss should challenge players' aggro management (can they afford to cast a spell at the boss without having it turn?), positioning (to stay inside the unshielded sector, from which they can cause damage)) and mobility (if the boss's aggro does turn, to keep their positioning).

# **Arena Modifications**

The available space should be a disk, or a square if that's unavailable.

# **Phase 1:**

The shield covers 45 degress to either side of the direction the boss is facing (total span 90 degrees).

# **Phase 2:**

The shield covers 100 degrees to either side of the direction the boss is facing (total span 200 degrees).

# **Phase 3:**

The shield covers 160 degrees to either side of the direction the boss is facing (total span 320 degrees).

# **Balance**

Expose the following as configurable variables, either at the top of the lua file or in KV format

Base movement speed, hp, regen, armor etc.
Damage reduction from the shield.
Time window for the aggro change.

**Comment by KarmaticNeutral** [comment]
Update to ticket:

These mechanics are being split into two bosses. 
1) We want a default AI creature that has a shield that rotates slowly around the thing.
  -Goal: Continued Rotation and movement by all attackers
2) We want a complex DPS based AI creature that has a shield statically locked to the location vector of the boss.
  -Goal: One person attempts to help the agro to give their allies an opening to strike behind the shield

**Comment by chrisinajar** [comment]
Leaving this open until shield has decent particle effects, we can track the rotating one in a different ticket

**Comment by chrisinajar** [comment]
Making explicit ticket.
