### ISSUE TITLE
Implement Carapace Boss

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#72]
# **Notable stats**

Has a carapace of sorts with chinks in it. Hitting from the direction of a chink (a ~10 degree window?) automatically crits (or otherwise shows clearly that it causes extra damage).
Has a decent-powered melee attack.
Has a slow turn rate.

Phase 2 at 80% hp
Phase 3 at 30% hp

# **Arena Modifications**

None are necessary.

# **Phase 1:**

The boss has two chinks, and attacking from a 10 degree window around the chink's center will deal extra damage.

# **Phase 2:**

Every now and then (say, 10 seconds), a chink will start to glow. After two seconds, the chink will deal AoE damage in a cone (the same area from which extra damage is possible)

# **Phase 3:**

More chinks (four), the charge-up is quicker (one second?) and it happens more frequently (every 5 seconds?)

# **Balance**

Expose the following as configurable variables, either at the top of the lua file or in KV format

Base movement speed, hp, regen, armor etc.
Angle and bonus damage for attacking a chink.
Charge time, frequency, angle and damage for the AoE cone ability.

**Comment by warpdragon** [comment]
putting all these into 1 issue
