### ISSUE TITLE
Roshlings scale wrong

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#726]
They are scaling off vanilla roshan and not our KVs. Find out why, please.

**Comment by Haganeko** [comment]
If this gets fixed, increasing the value of
`local CaveProgressionBuff`
at `oaa\game\scripts\vscripts\components\cave\cavetypes.lua` should buff the cave

**Comment by Chronophylos** [comment]
Remove this line https://github.com/OpenAngelArena/oaa/blob/master/game/scripts/npc/units/npc_dota_mini_roshan.txt#L19

**Comment by Haganeko** [comment]
Will do
