### ISSUE TITLE
Giving upgraded Aghanims with Alchemist

### ISSUE THREAD

**Issue by kallleeeeh** [OpenAngelArena/oaa#729]
When Alchemist gives an upgraded Aghs away the recipient will only receive Level 1 stats but it should use the stats from the used Agh's level. If there is a buff present it should be replaced/upgraded to the new effect. 
For example, Alch gives Lina an Aghs 1 very early in the game and later he gives her an Aghs 5 to upgrade the stats. The old buff will be overridden by the new one. 

This should not be a balance issue since Alch will need the cores for himself in early game. However, it could be a lategame option (especially in long games).

**Comment by warpdragon** [comment]
Moving to bug reports.
