### ISSUE TITLE
Implement Runaway Boss

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#73]
# **Notable stats**

This boss moves around the boss arena in a pattern, shooting projectiles in its wake. Maybe it is moving backwards and shooting, maybe it is shooting from its back.
No autoattack.
Anyone standing directly on the way gets trampled (damaged and stunned).

phase 2 at 80% hp
phase 3 at 40% hp

# **Arena Modifications**

There should be plenty of space for the boss to move.

# **Phase 1:**

The boss moves in a simple pattern, like a circle or a figure eight.

# **Phase 2:**

More complex movement pattern (example below), chosen from a pool of two.
![hexagon](https://cloud.githubusercontent.com/assets/25013178/23051031/21e46eb0-f4ad-11e6-8da2-1ef93e7943d5.png)
Shooting is faster.

# **Phase 3:**

Movement pattern is erratic, changing between a few patterns every now and then (can be comprised of all the earlier ones). Bullet hell.

# **Balance**

Expose the following as configurable variables, either at the top of the lua file or in KV format

Base movement speed, hp, regen, armor etc. Movement speed is especially important.
Rate of fire.
Damage and duration of the trample stun.

**Comment by warpdragon** [comment]
putting all of these into 1 issue
