### ISSUE TITLE
Farming cave bad teleportation

### ISSUE THREAD

**Issue by Bellwar** [OpenAngelArena/oaa#731]
I'm not sure if there is any bug report about, I looked around and I don't think so.

Every time we cleared the farming cave we all had to TP out because we got stuck inside of it

**Comment by spar36** [comment]
Yeah, Ive been hearing different reports about that. Where would it TP you instead of the base? / How were you getting stuck?

**Comment by Bellwar** [comment]
PA got stuck right in Roshlings and they killed her.
Techies got stuck in trees north from Roshlings. 
I got stuck every time inside the cliff (north of the Roshling place), I could see my self and I couldn't move had to TP.

**Comment by imaGecko** [comment]
You do not teleport at all. The cave resets which puts the blockers back in place causing players to get pushed out which in most cases is down on radiant or up on dire

**Comment by Bellwar** [comment]
Well I got moved up so I think it tries to teleport you but for me it was the opposite way.

**Comment by KarmaticNeutral** [comment]
@chrisinajar was this fixed?

**Comment by Bellwar** [comment]
I think it was, I saw note in update log about fixing it

**Comment by Chronophylos** [comment]
should have been fixed
