### ISSUE TITLE
Stat gain reduction doesn't apply to disconnected players

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#732]
`OnPlayerLevelUp` apparently doesn't fire for disconnected players. So we have to figure out some other way to reduce stats for that case.

**Comment by Trildar** [comment]
Current suggestions include basically running a thinker that resets stats of disconnected players on some interval (watch for Morphling if this is done). Global thinker is not the most elegant solution though, and could potentially cause other issues.

Haganeko also suggested freezing levels of disconnected players. Would probably be possible using a ModifyExperienceFilter, but that method would cause disconnected players to absorb XP, i.e. XP is still distributed to them but they don't actually get it.

**Comment by Haganeko** [comment]
Is it possible to save that XP and apply it when the reconnect?

**Comment by Trildar** [comment]
Should be doable.

**Comment by Trildar** [comment]
Resolved by XP freeze in #980. Still needs storing XP to grant on reconnect.
