### ISSUE TITLE
Duel Permadeath

### ISSUE THREAD

**Issue by imaGecko** [OpenAngelArena/oaa#735]
Juggernaut (dire) disconnected during duel, radiant team got wiped. Luna (dire) and dc'd jugg (dire) got stuck in the duel arena and the radiant team never respawned

**Comment by l34Um1** [comment]
I ad the same issue last night. A way for players to respawn is to disconnect and reconnect

**Comment by Honeth** [comment]
this is only really even a big issue if the host has it happen to them as they can't disconnect and reconnect.

**Comment by imaGecko** [comment]
Happens quite consistently when someone leaves during the duel

**Comment by Chronophylos** [comment]
The duel only ends when all players are dead.
We should kill everyone who disconnects during a duel to fix this.

**Comment by KarmaticNeutral** [comment]
Fixed
