### ISSUE TITLE
Wraith King wraith form bug

### ISSUE THREAD

**Issue by laine4466** [OpenAngelArena/oaa#736]
If Wraith King is already in wraith form before the duel, he will teleport into the duel arena in wraith form, essentially meaning he has already died once.

**Comment by Haganeko** [comment]
He also counts as dead if he dies and reincarnates, potentially ending the duel.

**Comment by Haganeko** [comment]
This is fixed, no?

**Comment by Trildar** [comment]
I don't think it is. I don't recall seeing any changes to fix it.

**Comment by warpdragon** [comment]
Progress?

**Comment by Haganeko** [comment]
It's still apparently an issue - it even appears in a recent Baumi video

**Comment by warpdragon** [comment]
moved to bug-reports. post there next time.
