### ISSUE TITLE
Satanic and Satanic Core

### ISSUE THREAD

**Issue by murapix** [OpenAngelArena/oaa#742]
Satanic's direct upgrades (and maybe Satanic itself) do not currently give any lifesteal, while the Satanic Core does.

**Comment by Trildar** [comment]
Did anybody have Trump's Fists? I did some testing and the Satanic upgrades seem fine. Though I've discovered that Trump's Fists heal prevention is inconsistent, which I'm going to fix hopefully.

**Comment by murapix** [comment]
I wasn't getting any healing while just fighting creep camps, no players in sight.

**Comment by Chronophylos** [comment]
We need to find a reproduction case for this

**Comment by murapix** [comment]
Just tested it again on my own, Satanic level 1 and 2 work fine, but as soon as I got Satanic level 3, the lifesteal completely stopped. No other players were in the game, so Trump's Fists could not be the problem. Switching to a lower level Satanic afterwards still does not give any lifesteal. The Satanic Core is definitely healing me when I attack though.

**Comment by imaGecko** [comment]
I could not reproduce Satanic not giving lifesteal

**Comment by Haganeko** [comment]
Is this fixed?

**Comment by Trildar** [comment]
No idea. We never figured out what was up with this bug, especially since the straight Satanic line just uses vanilla code.

**Comment by murapix** [comment]
Tested it again, whatever the problem was seems to have fixed itself.

**Comment by Haganeko** [comment]
Can anyone confirm?

**Comment by imaGecko** [comment]
I cannot even confirm that the bug existed to begin with, never managed to reproduce following the steps described or in various other attempts. Never has been any evidence provided by anyone else as far as I know
