### ISSUE TITLE
Last Boss (so far) issues

### ISSUE THREAD

**Issue by Aknhide** [OpenAngelArena/oaa#754]
Can be easily killed solo by PA, but gives a hard time to int heroes, we could not kill it with 6-sloted silencer, lesh and luna. But thats not the issues)

The 4th skill works incorrectly (i suppose) cuz it was copying only one hero, and even when he left the arena there still were his copies apearing with items, that were on him when it first triggered. also those copies give scilencer int gain.

also offtopic, hard camps in late game are getting stronger than bosses. maybe thats how it's supposed to be, but that's wierd

Anyway great job making OAA, but Open Bottle Arena is still a better name)
GLHF!)

**Comment by Haganeko** [comment]
Bosses are just too weak.

**Comment by Chronophylos** [comment]
Thanks for the feedback.
Illusions are suppose to remain. But all heroes in the are should get copied.
Those illusions are acually heroes. Thats were all these Bug come from.

**Comment by prsnnami** [comment]
Might sound silly but where was this boss , could not find in yesterday.

**Comment by Haganeko** [comment]
He takes a long while to spawn - gotta defeat a tier 5 first.

**Comment by warpdragon** [comment]
Moving to bug-reports. Post there next time.
