### ISSUE TITLE
Boss resistance and damage amplification effects interaction

### ISSUE THREAD

**Issue by Minnakht** [OpenAngelArena/oaa#756]
Boss resistance acts as a -85% damage reduction effect, stacking additively (probably) with generic damage amplification effects. Known culprits are Bloodrage and Penitence (Soul Catcher would work if it could target creep-heroes, but it can't, so it can't be applied to bosses.) This makes taking bosses significantly easier.

A proposed fix, if possible, is making boss resistance work multiplicatively instead.

**Comment by Trildar** [comment]
You're late. There was already an issue and fix for this. :P

**Comment by Minnakht** [comment]
Is the fix live? I played a game an hour ago and it was still in effect with Penitence as far as I was aware.

**Comment by Trildar** [comment]
Abilities have to be handled individually pretty much, so Bloodrage and Soul Catcher (just in case) are handled, but I wasn't aware of Penitence when I was fixing it.

**Comment by Haganeko** [comment]
Then it's good we caught penitence, no?

**Comment by Haganeko** [comment]
Btw how do those interact with reduction orb?

**Comment by Trildar** [comment]
Probably the same way... sigh... Guess that needs the same fix.
