### ISSUE TITLE
Implement Azazel

### ISSUE THREAD

**Issue by RighteousBacon** [OpenAngelArena/oaa#76]
# Notable stats

**Crossbow Attack**: Azazel shoots 2 bolts into the air that comes down after a short delay with a visual indicator. The botls comes down one after another (in different areas), and deals damage in the indicated AoE. **This ability is used in all 3 phases**.

Starts out with a ranged autoattack, converts to melee at phase 3.

Phase 2 at 70% hp
Phase 3 at 40% hp

# Arena Modifications

Azazel is located in the middle arena.

# Phase 1:

Regular ranged rightclick.

# Phase 2:

As soon as phase 2 is triggered Azazel shoots (2 bolts) from his crossbow. As the bolts land he teleports to one of them, while the other location spawns an illusion.

The illusion and Azazel are linked up together. They then slowly move in a circular fashion around the arena. If you touch the link, you get damaged and stunned. Both Azazel and the illusion still do regular ranged attacks during this.

If you damage the boss enough, the illusion disappears and Azazel enters phase 3. If you kill the illusion he receives damage, which is just enough to trigger phase 3.

# Phase 3:

He gains a spear, becoming melee.

Spear Ability: A swiping attack that after a windup, pushes enemies caught in it across the arena.

Meteors: Meteors start raining down, leaving permanent fire marks where they land. The meteors deals damage in the indicated AoE, and the fire marks deals AoE damage over time.

# Balance

Expose the following as configurable variables, either at the top of the lua file or in KV format

HP, right click damage, armor, movespeed.
Damage of the crossbow blasts.
Phases HP threshold.

Phase 2 link's damage and stun duration.
Phase 2 movement speed.
Illusion damage dealt/taken.

Meteors damage, both the initial impact and the DoT.
Rightclick damage for phase 3 also need to be seperately adjustable.

**Comment by HarryPhoon** [comment]
Isn't it odd to swipe with a spear?? You mostly stab with it or not??

**Comment by zelding** [comment]
Are you familiar with Xin Zhao from Lol?

**Comment by Trildar** [comment]
Should the illusion be visibly an illusion?

**Comment by Haganeko** [comment]
I believe so. We probably wish to make attacking it or Azazel a strategic choice.

**Comment by Chronophylos** [comment]
Phase 2 looks like we have to make pseudo attack so they won't stop moving

**Comment by warpdragon** [comment]
putting all these into 1 issue
