### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by hallelsegel** [OpenAngelArena/oaa#763]
I've made a bunch of icons, and I wonder how can I contribute them best - is making a branch that includes them enough? Will it be looked at and merged or should I inform someone of authority and it will otherwise be ignored?

**Comment by Haganeko** [comment]
Put them on the discord for feedback. Art channel. Then if you think they're all well approved make a PR with them.

**Comment by hallelsegel** [comment]
What's the discord? I haven't figured out how to get to it really...

**Comment by Haganeko** [comment]
The link is somewhere in the repo docs.

**Comment by hallelsegel** [comment]
KK thank you!

**Comment by allanvbhg** [comment]
Found it?

**Comment by allanvbhg** [comment]
https://discord.gg/X6VPdgw

**Comment by hallelsegel** [comment]
Ok found it but god that wasn't easy ><
6 more minutes and ill comment

**Comment by Haganeko** [comment]
See? People can find it.
