### ISSUE TITLE
Bugs related to disconnections

### ISSUE THREAD

**Issue by Exofunny** [OpenAngelArena/oaa#764]
Unfettered stats:
whenever a disconnected hero gets past the lvl 50 threshold, their stat growth won't be nerfed and will grow naturally with levels. Their armor will be in the thousands as well as all of their stats by the time they get to max level. They can solo bosses and tank fountain. It's really annoying.

Perma-dead disconnected heroes ruin games:
Whenever a hero is dead forever (like in a duel) as well as disconnected (or abandoned b/c I can't test for a difference alone), then one team's deaths will be permanent until the next duel. It may also stop bosses from dropping cores, but I'm not sure if it's entirely related or just a correlation.

**Comment by Haganeko** [comment]
Thanks for the report, though this is not quite the place for it. 
First one is a known issue and actually starts at level 25.
Second is also a well known and well documented bug.
