### ISSUE TITLE
Instant Lag At Will 

### ISSUE THREAD

**Issue by prsnnami** [OpenAngelArena/oaa#767]
Steps to reproduce: 
1. Open the item tree for upgrade core 4
2. Hover/ Move mouse over the 5000 items that appear there.
3. If you are the host, everyone lags.

We were losing and my team mate made everyone quit. He was the host.

**Comment by Haganeko** [comment]
To report a bug (I'll do this one):
https://docs.google.com/forms/d/e/1FAIpQLSeNGCEJ6HFjNDVRKIBB_TXpa9m4ojStKKYSqjTnN2H85OXpzA/viewform?c=0&w=1
https://github.com/OpenAngelArena/Bug-Reports
