### ISSUE TITLE
Enable Change Hero for Long Mode

### ISSUE THREAD

**Issue by prsnnami** [OpenAngelArena/oaa#769]
So i am the type of player who likes a long chilled game, and yesterday after i finished farming all the items , the game just started to be boring. There wasnt a lot of fighting early game and the opponents rarely got out of the fountain. So maybe inplementing changing hero would be fun. Would also be good for heroes who dont have AOE farm but are strong. Just My opinion. Also i guess there is a lack of new items imo. Just the game got boring and I quit a game after 45 mins.

**Comment by Haganeko** [comment]
There is a suggestions repository for this.
