### ISSUE TITLE
Aghanim's Scepter above level 1 can be dropped and the upgrade stays

### ISSUE THREAD

**Issue by imaGecko** [OpenAngelArena/oaa#772]
https://i.gyazo.com/3c0c7959a37ba477f6b2cc52ff7a98c5.mp4

Tested on Zeus, Tusk, Lifestealer, Ogre Magi

Affected Heroes:
Earth Spirit, Lifestealer, Morphling, Nyx Assassin, Ogre Magi, Timbersaw, Treant Protector, Tusk, and Zeus.

**Comment by zelding** [comment]
`"ItemDroppable" "0"` might be a good temp fix

**Comment by Haganeko** [comment]
Would make other heroes unable to drop aghs, though.

**Comment by warpdragon** [comment]
moved to bug-reports. post there next time.
