### ISSUE TITLE
PL illusions and upper level bloodstone charges

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#777]
everytime you kill an ilusion of pl u get a bloodstone charge

**Comment by Honeth** [comment]
is this for normal bloodstone or did we rewrite bloodstone? if we rewrote it we need to make sure to add IsIllusion and IsReincarnating aswell as IsTempestDouble to the check and set them to not give a charge

**Comment by Trildar** [comment]
The higher level Bloodstones have custom code. Chris wrote it I believe. So, as always, #BlameChris :P And while you're at it, #BlameWarp as well, just for good measure.

**Comment by Honeth** [comment]
Could you check the code Trildar? i'm pretty sure you could fix it after reading it
