### ISSUE TITLE
Map bug. Become untargetable

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#778]
By Meg.A.Byte#8030: " Map bug (don't know if anyone noticed) – there is a hole on the edge of the central area. If you fly there you dissapear and became untargetable but still be able to cast spells here and there. Here is a video to show exactly what's happening: https://www.youtube.com/watch?v=NcHJr49izCQ

**Comment by warpdragon** [comment]
thta's beautiful

**Comment by warpdragon** [comment]
help me with the map! @KarmaticNeutral

**Comment by KarmaticNeutral** [comment]
@warpdragon was this fixed?

**Comment by warpdragon** [comment]
No i will take a look

**Comment by warpdragon** [comment]
i'm gonna look at this soon. i can't believe i forgot about this.

**Comment by warpdragon** [comment]
moved to bug-reports. post there next time.
