### ISSUE TITLE
Implementing Minimap Icons

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#780]
Pull request soon...

putting the files together... boilerplate.

**Comment by warpdragon** [comment]
Http://images.discordapp.net/.eJwVxFEOgyAMANC78D8KZYh4G4IEzbQlUOPHsrtvy0veW139UIvaRNpYANZ9ZO6rHsI91aIrcz1KavvQmU9IIilvZyEZgJNHdLMz9n98xhmcRRODDd7ECX98gItexDc9nG5U1ecLS2gjQA.vHfWfPBBXKbNTjuuUR7-6Z89AhI

**Comment by warpdragon** [comment]
Http://images.discordapp.net/.eJwVxFEOgyAMANC78D8KZYh4G4IEzbQlUOPHsrtvy0veW139UIvaRNpYANZ9ZO6rHsI91aIrcz1KavvQmU9IIilvZyEZgJNHdLMz9n98xhmcRRODDd7ECX98gItexDc9nG5U1ecLS2gjQA.vHfWfPBBXKbNTjuuUR7-6Z89AhI

**Comment by warpdragon** [comment]
---------------------
MINIMAP ICONS
---------------------
https://github.com/MNoya/DotaCraft
LUA code is here:
https://github.com/MNoya/DotaCraft/blob/556407021d22205001fb8b03d36c17bbb87a8db6/game/dota_addons/dotacraft/scripts/vscripts/mechanics/minimap.lua
There is an invisible unit with 0 vision called "minimap_<name>" which takes a bunch of modifiers like "MODIFIER_STATE_UNSELECTABLE", "MODIFIER_STATE_NO_HEALTH_BAR", etc. Here's the unit_custom.txt:
https://github.com/MNoya/DotaCraft/blob/556407021d22205001fb8b03d36c17bbb87a8db6/game/dota_addons/dotacraft/scripts/npc/npc_units_custom.txt

**Comment by l34Um1** [comment]
Gonna keep this open, definitely something we need to pick up again and there is good info here.

**Comment by carlosrpg** [comment]
refer to: https://github.com/OpenAngelArena/oaa/pull/1645

**Comment by carlosrpg** [comment]
We should close this
