### ISSUE TITLE
Pregame Screen Tweaks and Updates

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#781]
Working with Chrono to implement some jazzy stuff.

**Comment by Chronophylos** [comment]
## Current Status
#### Ingame Game Info
![Game Info](https://i.imgur.com/kfj0Msjr.jpg)
Need text
#### Hero Selection
**Hero Selection Screen:** 
*Concept 1*
![Concept 1](https://cdn.discordapp.com/attachments/261589235889471489/311874474515365891/2017-05-10_10.37.09.png)
*Concept 2*
![Concept 2](https://cdn.discordapp.com/attachments/261589235889471489/311878830249738240/2017-05-10_10.54.33.png)
*Concept 3*
![Concept 3](https://cdn.discordapp.com/attachments/261589235889471489/311905032779988992/2017-05-10_12.38.31.png)
My Idea is to zoom out and display all chosen heroes. (And the map ind 3D)
**Strategy Screen:**
![Strategy Screen](https://cdn.discordapp.com/attachments/261589235889471489/311896561946722305/2017-05-10_12.04.57.png)

**Comment by allanvbhg** [comment]
Need help visualising this?

**Comment by Chronophylos** [comment]
What do you mean?

**Comment by allanvbhg** [comment]
Make it look real xd

**Comment by imaGecko** [comment]
I think concept 2 would look best

**Comment by Chronophylos** [comment]
@allanvbhg go for it
@imaGecko that's what I'm thinking too

**Comment by allanvbhg** [comment]
What needs to be in dueling and bosses?

**Comment by Chronophylos** [comment]
ask Warpdragon
> ![https://cdn.discordapp.com/attachments/261589235889471489/311906810749648896/unknown-2.png](https://cdn.discordapp.com/attachments/261589235889471489/311906810749648896/unknown-2.png)
> Something similar to this but probably smaller

**Comment by Haganeko** [comment]
Concept 2 looks very busy. Whether it works will depend on how large we need the displayed information to be.

**Comment by KarmaticNeutral** [comment]
I favor #2, but it Haga is right. If things get small, that could feel too busy.

**Comment by Chronophylos** [comment]
About Concept 2: I was thinking about removing one of the Images and making the selected hero thing bigger.
We could also make one slideshow instead of three still images

**Comment by warpdragon** [comment]
Information should be concise (brief but comprehensive.) If we're going to put information in front of the players it should be immediatedly absorbed at a glance. This was the idea from the beginning. You also mentioned wanting to turn the side-panel into a book. There is zero reason for this. It's a simple gamemode. The required information can easily be made to fit whatever designs you settle on.

**Comment by allanvbhg** [comment]
I will make all 3 haha

**Comment by allanvbhg** [comment]
We'll have a better overlook than

**Comment by warpdragon** [comment]
Work in progress. Any time you guys want I can slice these up into panels. I'll look and see about what to naming them. I noticed in oaa, for the title screen, they have names like "TeamSelect_Button_off.png" and stuff. I suppose those can be anything we want.
![unknown-4](https://cloud.githubusercontent.com/assets/13878439/26272377/944151b0-3ce4-11e7-87cc-9fbf6adb355c.png)

**Comment by chrisinajar** [comment]
That last screenshot looks fucking amazing, warp

**Comment by ProstoSanja** [comment]
How is progress going with this screen?

**Comment by Chronophylos** [comment]
Only concepts

**Comment by ProstoSanja** [comment]
Started work on concept one. Progress is at my repo

**Comment by l34Um1** [comment]
Unsure if I should close this, what do you think?

**Comment by Haganeko** [comment]
Warp/Chris might want to open a clean issue with stuff learned from frostivus.

**Comment by Haganeko** [comment]
Warp/Chris might want to open a clean issue with stuff learned from frostivus.

**Comment by warpdragon** [comment]
Yeah if we decide to do any more to this we'll open a new issue. Closed
