### ISSUE TITLE
Make Bosses untragetable by Blood Rage

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#789]
Blood Rage causes problems with charger and towers as well as all causing a reduction to boss resistance.

**Comment by Minnakht** [comment]
Trildar fixed the boss resistance interaction (or at least told me it was fixed, might not have been him) but I suppose it'll be easier in the long run.

**Comment by Trildar** [comment]
No idea about Charger and his pillars. What exactly happens there? General interaction should emulate multiplicative stacking though.

**Comment by KarmaticNeutral** [comment]
He heals when he kills a tower

**Comment by Minnakht** [comment]
Pillars have HP and Charger counts as killing them when running into them. Bloodrage ensues, working exactly as intended - healing on unit kill.

**Comment by KarmaticNeutral** [comment]
That is working exactly as is logical. Not as intended.

**Comment by KarmaticNeutral** [comment]
additional option. give towers 1 HP

**Comment by Haganeko** [comment]
Giving towers 1 HP should work.

**Comment by Trildar** [comment]
Unconfirmed, but I just thought of potential problems with Bloodrage/Penitence and stuff that's supposed to give the boss damage immunity like Shield boss. Assuming we don't want those modifiers to later give less than 100% reduction and don't want all damage amp to cause them to take damage, it might be better to change those modifiers to use the `ABSOLUTE_NO_DAMAGE` properties instead.

**Comment by Haganeko** [comment]
Shouldn't your damage reduction fix fix that? And I wasn't aware there existed such a modifier.

**Comment by Trildar** [comment]
The damage reduction fix is specific only to the Boss Resistance modifier. Shield currently works by adding an additional 15 or whatever resistance, which isn't handled in any special way, so it just stacks additively with the now effectively reduced boss resistance. So the boss will end up having less than 100% resistance.

**Comment by KarmaticNeutral** [comment]
Still targetable, but they are different types of damage modification so they blood rage doesn't matter anymore
