### ISSUE TITLE
Update Items for 7.06 parity

### ISSUE THREAD

**Issue by Haganeko** [OpenAngelArena/oaa#801]
Need to update recipes, cost, and numbers for all items affected by 7.06
For changed values, the standard progression by tier is
1/1.5/2.25/3.375/4.5 (then round, of course)

**Comment by Haganeko** [comment]
It has been brought to my attention that a separate progression for armor items is unnecessary.

**Comment by imaGecko** [comment]
I did update #779 for the 7.06 patch

**Comment by Haganeko** [comment]
Oh. Somehow forgot that had happened. I am sorry.
