### ISSUE TITLE
Add final duel

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#804]
When a team wins, it should instantly go into a full 5v5 duel. If the team with enough kills wins, the game ends, otherwise the goal is extended by 10 (so they need 6-10 more after the end of the duel depending on how they did)

**Comment by Haganeko** [comment]
Can we change the extended value to 7 if the duration selected is "short" and 13 if "long"? Also, a bunch of code depends of the original limit, so may wish to work around that.

**Comment by KarmaticNeutral** [comment]
This is implemented and we have a new ticket about specific bugs so I'm going to close this
