### ISSUE TITLE
Issues regarding Icons missing and wrong item icons! update 20-5-2017

### ISSUE THREAD

**Issue by allanvbhg** [OpenAngelArena/oaa#805]
So i made a test lobby to look at the new item icons and i saw a lot of issues.
Issues:
- Satanic doesn't have any pips at all levels. No upgraded icons.
- Blink doesnt have an upgrade path. No pips or upgraded icons.
- Diffusal doesnt have a level 3 icon yet.
- mekanism doesnt have an upgrade path yet. No pips or icons.
- Martyrs mail doesnt have pips and upgraded icons.
- Dagon doesnt have any pips at all levels. No upgraded icons.
- Butterfly doesnt have icons yet.
- Daedalus doesnt have upgraded icons yet.
- Shivas guard has 2 pips on level 3 instead of 3 pips.
- Mjolnir doesnt have icons yet.
- Necrobook doenst have icons yet.
- octarine core doesnt have a level 2 icon.
- BKB should have 1/2 pips but it has none.
- All standerd upgraded boots should have 1/6 pips but they have none.
- Refresher cores dont have any pips at all levels. level 1/2/3 should have 1.3/2.3/3.3 etc. No upgraded icons.
- Lucience level 2 and 3 doesnt have icons.
- Rod of Atos doesnt have any icons yet.
- Lotus orb level 1 has 1/4 pips , should be 1/2 . level 2 doenst have an icon yet.
- Manta style doesnt have icons.
- Armlet doesnt have icons yet.
- If you click on Eye of the Skadi on the upgraded page only level 1 shows up, level 2/3/4/5 are black.
- Dragon lance has no icons.
- Hand of midas idnt in the shop! you can only select it if you search for it. No upgraded icons yet.

**Comment by warpdragon** [comment]
Do not reopen until u figure out why ur getting bugs noones else is

**Comment by allanvbhg** [comment]
I edited it, this is a correct list for me
someone should check it in game.

**Comment by Trildar** [comment]
I can confirm that the list seems to be accurate. Regarding Lotus Orb and Linken's Sphere though, it's a little odd for them to have 4 total pips before Lotus Sphere is actually in the game, but eh. It's a relatively easy item to implement, but I'm not sure anyone is really free to do it at the moment. We also don't have any icons for it I believe.

**Comment by allanvbhg** [comment]
And i added 1 more: if you hover over items in shop they go black for a tiny second
