### ISSUE TITLE
Add 20 player support for the whole project

### ISSUE THREAD

**Issue by Chronophylos** [OpenAngelArena/oaa#82]
## Sometimes we're assuming we just have 10 player instead of possibly 20.
* Go through the whole code and find these occasions.
* Make sure we're using 20 players.

e.g. change this
```Lua
for playerId = 0,9 do
```
to this
```Lua
for playerId = 0,19 do
```
or look for arrays like this
```Lua
{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 }
```
and add the other 10 players

### Places where this needs to be done:
- [ ] gold.lua

**Comment by yeahbuddy-dota** [comment]
or just normalize it. You can attach data to existing structs like so

~~~
for playerId in PlayerResource:GetAllPlayers() do
...
end
~~~
than make your own PlayerResources.GetAllPlayers(self) function.

**Comment by Trildar** [comment]
Is there any reason to not use `DOTA_MAX_TEAM_PLAYERS` (which is currently 24) instead? Even if there are no plans for 12v12.

**Comment by Chronophylos** [comment]
No not really. But @yeahbuddy-dota 's solution is the more elegant solution.

**Comment by Trildar** [comment]
Where should a class extension like that go?

**Comment by yeahbuddy-dota** [comment]
Doesn't matter. In my code I put functions like that in the libraries they interface with, e.g. i have a unit:AddBonus function thats extended in my bonus.lua file. For this my best recommendation would be to make some playerhandler.lua or etc. file that has this function in addition to some others that may be helpful like GetConnectedPlayers(), GetAllRadiantPlayers(), or whatever or stuff like PlayerResource:MakePlayerTable() which will make that {1 = {}, 2 = {}, 3 = {}, ...} table as shown in chris's code.

**Comment by Trildar** [comment]
Why was this closed? It's still relevant though it's not a priority. Most of the code is even assuming 20 players. I've even started trying to implement yeahbuddy's solution. :p

**Comment by Chronophylos** [comment]
That'd be great.
