### ISSUE TITLE
Missing modifier icons

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#824]
A number of the new custom icons weren't copied to the `spellicons` folder, causing some modifiers to be missing icons. List as follows (mostly from memory of what has modifiers):

- (probably) Aghanim's Scepter (for Alchemist gifted Scepters)
- Mask of Madness
- Armlet
- Blade Mail
- Bloodthorn
- Echo Sabre
- Eul's Scepter
- Eye of Skadi
- Heart Transplant*
- Greater Greaves
- Greater Phase*
- Preemptive Reflex Orbs*
- Postactive Reflex Shards* (Enrage Shards shouldn't need it)
- Reactive Reflex Crystals*
- Radiance (higher levels)
- Shroud of Shadows* (or whatever it was called)
- Lucience* (higher levels)
- Satanic Core* (higher levels)

*Likely needs some Lua edits to actually use the icons

Demon's Blood is also duplicated as `demon_blood` and `demons_blood`. Also might want to make Abyssal, Agh's, Halberd, Mask of Madness, and MKB filenames lowercase for consistency, possibly also name Agh's properly (internal name is `ulitmate_scepter`, but `aghanims_scepter` would be fine too).

**Comment by Haganeko** [comment]
It's this fixed?

**Comment by Chronophylos** [comment]
should be
