### ISSUE TITLE
Disable Universal Shop

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#829]
Currently Universal Shop is enabled, which I think makes all purchasable items available at all shops, meaning the Arena Shop isn't actually limited. We need to disable Universal Shop and edit the item KVs so that the correct stuff is purchasable at the correct shops. Would mostly involve removing things from the Side Shop (Arena Shop) which are there in normal Dota and enabling Secret Shop stuff in Main Shop I think. Eventually we'll also want to remove vanilla Secret Shop things from there as we'll probably want to use that for Azazel Shop.

**Comment by Haganeko** [comment]
I thought @Warpdragon had done this though

**Comment by KarmaticNeutral** [comment]
Well valve and their genius called a game attribute "universal shop" and what it does is make it so you can buy items when you are away from the shop. Turning off that value would require you to be in the spawn base to buy anything. The ability to buy secret shop items (Like how LoDr does it) is something completely different.

**Comment by Trildar** [comment]
You're sure? Then why is everything purchasable from both shops? Did we copy that from LoD?

**Comment by Haganeko** [comment]
I'm saying I thought warp did all this when he redid the shop and added the duel arena shop.

**Comment by KarmaticNeutral** [comment]
OH there is another setting with the same name.... that's really awkward. We are both right. LoD's universal shop is currently active

**Comment by KarmaticNeutral** [comment]
As well as another setting that allows you to buy items globally

**Comment by KarmaticNeutral** [comment]
I'll fix this right now

**Comment by KarmaticNeutral** [comment]
#831 will close this
