### ISSUE TITLE
Simple Bosses

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#865]
This is just a bunch of simple bosses. These just have basic Dota abilities added into their toolset to make them slightly more interesting than a regular DPS race.

Please expose all the expected values in the KV (dmg, attack speed, armor etc) as well as values from the bosses abilities so they can be edited and adjusted.

- [ ] Juxtapose + Geostrike
Phantom Lancers Ultimate Juxtapose and Meepos Passive Geostrike.

- [ ] Tidebringer + Jinada
Kunkkas Tidebringer on autocast and Bounty Hunters passive Jinada.

- [ ] Marksmanship + Moon Glaives
Drow Rangers Ultimate Marksmanship with the Aghanims effect enabled to make the attacks split as well as Lunas Moon Glaives.

- [ ] Jingu Mastery
Monkey Kings passive Jingu Mastery.

- [ ] Desolate
Spectre's Desolate.

- [ ] Reactive Armor
Timbersaws passive Reactive Armor, has low HP, no magic resistance and high physical armor. A boss that casters excel at killing.

**Comment by chrisinajar** [comment]
In, but juxtapose doesn't work.

**Comment by l34Um1** [comment]
Closed because old.
