### ISSUE TITLE
Simple Bosses #4 Marksmanship Aghs + Moon Glaives

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#868]
This is just a bunch of simple bosses. These just have basic Dota abilities added into their toolset to make them slightly more interesting than a regular DPS race.

Please expose all the expected values in the KV (dmg, attack speed, armor etc) as well as values from the bosses abilities so they can be edited and adjusted.

This boss uses Drow Rangers Ultimate Marksmanship with the Aghanims effect enabled to make the attacks split as well as Lunas Moon Glaives.

**Comment by warpdragon** [comment]
combined with #865
