### ISSUE TITLE
Icons of vanilla toggled items

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#879]
The icon search names of the non-default state of vanilla toggled items appear to be hardcoded, though it'd be appreciated if someone could provide more confirmation as I didn't look into it much. This means that all these items would pretty much need to be rewritten in order for them to have proper leveled icons.

Once again, thanks Valve!

**Comment by warpdragon** [comment]
i noticed this as well. kinda messed up my implementation of aquila.

**Comment by l34Um1** [comment]
Closed because old.
