### ISSUE TITLE
Travel TP stopping

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#882]
Upper level Travels don't utilize the require Stop key setting

**Comment by Trildar** [comment]
I'm not sure this is fixable, unfortunately. I had hoped the in-built `modifier_teleporting` would do something, but it doesn't seem to. I don't think there's a way to query the setting, and if there isn't, there isn't any way we can fix this unless there's some other in-built thing we need to use.

**Comment by Trildar** [comment]
Managed to find a way we can possibly check the player setting for this client side. Settings are exposed as cvars. This setting is called `dota_player_teleport_requires_halt`.

**Comment by l34Um1** [comment]
Closed because old.
