### ISSUE TITLE
Satanic Core Unholy Rage tooltip

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#896]
The Unholy Rage tooltip for Satanic Core isn't quite right, mostly due to using the in-built Satanic modifier. I'm not really sure how it might be changed though, as modifier tooltips can only access property values, which aren't used for lifesteal. `MODIFIER_PROPERTY_TOOLTIP` allows one ability KV value to be exposed to the modifier tooltip, but this would mean the tooltip would probably say something like "Lifesteal increased to x". The other option is to have 2 or even 3 modifiers to describe the various lifesteal increases the way Satanic Unholy Rage says it (one each for attack lifesteal, hero spell lifesteal, and optionally creep spell lifesteal).

Unholy Rage description for reference: "Lifesteal increased by 175%."

**Comment by imaGecko** [comment]
Lifesteal is already described by "Increases Lifesteal percentage to %unholy_lifesteal_percent%%%"
Should be "Increases Lifesteal percentage to %unholy_lifesteal_total_tooltip%%%"
Which is correct in Satanic but seems to have been forgotten for Satanic core

**Comment by Trildar** [comment]
To clarify, the description here is the vanilla Satanic Unholy Rage description, which just happens to be the same for Satanic Core because we're reusing the modifier. So the norm, based on that, is not "to x%", it's "by x%". And the thing about just saying "Lifesteal increased to x%" is that it kind of assumes that the active spell lifesteal and attack lifesteal will always be the same.

**Comment by imaGecko** [comment]
All lifesteal variants are increased to the same 200% value, aren't they?

**Comment by Trildar** [comment]
They currently are. But there's no guarantee we'll always want to keep it that way.

**Comment by imaGecko** [comment]
Worst case, changing a tooltip is no effort. But this does accurately reflect the way the item currently works. Apart from the error in the Satanic Core description pointed out above

**Comment by Haganeko** [comment]
It should say "increased to". I must have missed one tooltip entry in #793 .

**Comment by Trildar** [comment]
Nah, the item is currently using in-built Satanic modifier, so the tooltip can't be edited without also overwriting that. Needs some minor changes to code to make it use a different modifier.

**Comment by Haganeko** [comment]
But the original Satanic also uses the "unholy_tooltip_total"key...

**Comment by Trildar** [comment]
This issue is about the Unholy Rage buff description, not the item description. Vanilla Unholy Rage simply says "Lifesteal increased by 175%" with a hardcoded number.

**Comment by Haganeko** [comment]
Oh. That's problematic.

**Comment by Trildar** [comment]
It's not a hard fix. I was just trying to get feedback on what the tooltip should actually say.

**Comment by Trildar** [comment]
Resolved in #922.
