### ISSUE TITLE
Sange and Yasha 3 & 4

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#901]
Make 2 new KV for SnY
Whoever makes the new Sange and Yasha 3 and 4 the following Item IDs should be available:  3839..3899(edited)

**Comment by warpdragon** [comment]
The gold cost for lvl 3 and 4 should probably be ~10k gold and ~18k gold or whatever

**Comment by KarmaticNeutral** [comment]
@warpdragon this done?
