### ISSUE TITLE
Need Tooltip Data fix

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#91]
The proper Tooltip Data does not display for our npc_items_custom.txt

**Comment by warpdragon** [comment]
Update: The items are in https://github.com/AngelArenaAllstars/aaa/pull/96 waiting hopeful merge. The file https://github.com/AngelArenaAllstars/aaa/blob/9a81d1b97bf389cc018848fea8eca152aecb8ebe/resource/addon_english.txt contains what you need to know to get started.

**Comment by warpdragon** [comment]
addon_english.txt needs to be saved in UTC 16 Encoding (also known as UCS-2 LE or UCS-2 LE BOM)

**Comment by warpdragon** [comment]
For tracking progress:
https://docs.google.com/spreadsheets/d/1ChIOH40RHMbQlps2UHMelHXN31nfnEegczKMLgbjQs0/edit?usp=sharing

**Comment by RamonNZ** [comment]
[dota_english.txt](https://github.com/AngelArenaAllstars/aaa/files/815673/dota_english.txt)
Here's the default dota_english.txt from the dota game. If you get stuck you can figure out how to do things using similar items.

Also the really simple way to make item_abyssal_blade_2 (for example) display is to search for item_abyssal_blade in the default dota_english.txt and we find:

		"DOTA_Tooltip_Ability_item_abyssal_blade"				"Abyssal Blade"
and also:
		"DOTA_Tooltip_Ability_item_recipe_abyssal_blade"			"Abyssal Blade Recipe"
and:
		"DOTA_Tooltip_ability_item_abyssal_blade_Description"							"Active: Overwhelm - Stuns a target enemy unit for %dstun_duration% seconds. Pierces Spell Immunity.\nPassive: Bash - Grants each attack a chance to stun the target for %bash_duration% seconds and deal %bonus_chance_damage% bonus damage, based on whether the equipped hero is ranged or melee.\nPassive: Damage Block - Grants the wielder a %block_chance%%% chance to block damage from incoming attacks based on whether the equipped hero is melee or ranged."
		"DOTA_Tooltip_ability_item_abyssal_blade_Lore"									"The lost blade of the Commander of the Abyss, this edge cuts into an enemy's soul."
etc...

To make it for Abyssal Blade 2 just change item_abyssal_blade to item_abyssal_blade_2 in all the Tooltips eg:

		"DOTA_Tooltip_Ability_item_abyssal_blade**_2**"				"Abyssal Blade"
		"DOTA_Tooltip_Ability_item_recipe_abyssal_blade**_2**"			"Abyssal Blade Recipe"
		"DOTA_Tooltip_ability_item_abyssal_blade**_2**_Description"							"Active: Overwhelm - Stuns a target enemy unit for %dstun_duration% seconds. Pierces Spell Immunity.\nPassive: Bash - Grants each attack a chance to stun the target for %bash_duration% seconds and deal %bonus_chance_damage% bonus damage, based on whether the equipped hero is ranged or melee.\nPassive: Damage Block - Grants the wielder a %block_chance%%% chance to block damage from incoming attacks based on whether the equipped hero is melee or ranged."
		"DOTA_Tooltip_ability_item_abyssal_blade**_2**_Lore"									"The lost blade of the Commander of the Abyss, this edge cuts into an enemy's soul."
etc...

**Comment by warpdragon** [comment]
### The item NPC source data:
https://github.com/warpdragon/aaa/blob/moar-items/game/scripts/npc/npc_items_custom.txt
https://github.com/warpdragon/aaa/tree/moar-items/game/scripts/npc/items

### Progress Tracker

https://docs.google.com/spreadsheets/d/1ChIOH40RHMbQlps2UHMelHXN31nfnEegczKMLgbjQs0/edit#gid=0

**Comment by RamonNZ** [comment]
To test your tooltip data is working, you need to make a file called addon_english.txt in \aaa\game\resource\ with your changed data in the following format:

"lang"
{ 
    "Language" "English" 
    "Tokens" 
    {
        "DOTA_Tooltip_Ability_item_abyssal_blade_2"                "Abyssal Blade 2"
        "DOTA_Tooltip_Ability_item_recipe_abyssal_blade"            "Abyssal Blade Recipe"
        "DOTA_Tooltip_ability_item_abyssal_blade_2_Lore"        "The lost blade of the Commander of the Abyss, this edge cuts into an enemy's soul."
    }
}

Don't forget to change the encoding to UCS-2 LE BOM or it won't display directly.

Also make sure that you have the full items file https://github.com/warpdragon/aaa/blob/moar-items/game/scripts/npc/npc_items_custom.txt in the location: \aaa\game\scripts\npc\

**Comment by warpdragon** [comment]
##Switching Encoding using Sublime Text 3
If you want to set to UTF-16 (or any other encoding) I figured out a way using Sublime Text 3. In: Preferences > Settings > User, make it say something like: 
```
{
    "font_size": 18,
    "show_encoding": true
}
```
Then you will see "UTF-8" on the bottom right corner. Click it and there's options, including "Set Encoding" and there's like 30 languages including UTF-16

**Comment by Chronophylos** [comment]
Encoding not language :P

**Comment by Trildar** [comment]
Also, for localization files (with the exception of `game/panorama/localization/addon_english.txt` (unless Valve's encoding rules are even more confusing than what I've already seen)) you specifically need UTF-16 LE with BOM. Unfortunately Sublime Text doesn't seem to show that in the menu @warpdragon mentioned. You can find it under `File > Save with Encoding` though.

**Comment by warpdragon** [comment]
Please do keep track of who's doing which items on the google sheet please. we're going to have 4 or 5 people on this and we dont' wanna overlap. Let's get all the basic items done first.
