### ISSUE TITLE
Bug with hero selection screen coming up after game start

### ISSUE THREAD

**Issue by finnaggann** [OpenAngelArena/oaa#926]
I was in a game with 8 players of OAA and just before the first duel I was taken back to a blank hero selection screen with no way to leave the game. After a while I was disconnected from the game.

**Comment by Chronophylos** [comment]
Do you have a recording?

**Comment by finnaggann** [comment]
no I did not the game basically froze and I could not leave until I shut it down because I was in fullscreen exclusive.

**Comment by warpdragon** [comment]
moved to bug-reports. post there next time.
