### ISSUE TITLE
perma death 

### ISSUE THREAD

**Issue by ultranoobkiller** [OpenAngelArena/oaa#931]
perma death with wk while enemy was killing oger boss wk(me) and jug went to kill them and got perma death not sure how it happened but coudnt respawn

**Comment by Chronophylos** [comment]
Do you have a recording or the console output?

**Comment by chrisinajar** [comment]
There was something that broke leading up to this, this is what happens when there is an exception during a duel.

**Comment by ultranoobkiller** [comment]
@Chronophylos unfortunatly i dont have any recording 
@chrisinajar  i think wk ulti was the problem as i died lvl 25 talent which i selected as wrath blast was triggered and i was resurected and died in an instant with jugg not sure wat happened second time it was so fast death

**Comment by Haganeko** [comment]
Permadeath seems to be permadead.
