### ISSUE TITLE
After a duel invoker got teleported to the enemy base

### ISSUE THREAD

**Issue by krisz989898** [OpenAngelArena/oaa#934]
https://clips.twitch.tv/TastyNeighborlyMangoFrankerZ

**Comment by chrisinajar** [comment]
Can we get a clip of right before the duel too?

**Comment by Chronophylos** [comment]
https://www.twitch.tv/videos/147798646 03:53:00
before duel https://clips.twitch.tv/NaiveClumsyFrogFutureMan

**Comment by krisz989898** [comment]
here you go https://clips.twitch.tv/SparklingAnnoyingInternTheThing

**Comment by warpdragon** [comment]
moved to bug-reports. post there next time.
