### ISSUE TITLE
So when are we getting Dedicated servers?

### ISSUE THREAD

**Issue by Michael939393** [OpenAngelArena/oaa#935]
Game is public , but it's actually not playable. I haven't finished SINGLE game for like 10 hours of trying. SERIOUSLY? Shouldn't You guys have dedicated servers FIRST and then release? Seems logic to me!

**Comment by Chronophylos** [comment]
Valve decides who gets dedicated servers.
It's not in our hands.

**Comment by Michael939393** [comment]
You should know that if they decide NOT to give YOu a server, game is as good as none.

**Comment by SquawkyArctangent** [comment]
That sure is an issue you should be bringing up with us, yes.

**Comment by Michael939393** [comment]
Game is great, but what good is that if it's not playable right?

**Comment by Minnakht** [comment]
well, maybe if we make the game good, they'll consider giving us a server?

**Comment by Michael939393** [comment]
so far, my expirience has been terrible...10 minutes into game and game just randomly ends, or my Dota just shut down....

**Comment by laine4466** [comment]
The thing here is that the game has just been released for 5 hours, so please give it some time for Valve to at least notice it to give it dedicated servers

**Comment by Minnakht** [comment]
Valve-senpai hasn't noticed us~
