### ISSUE TITLE
Black Screen after strategy

### ISSUE THREAD

**Issue by Twatwaffle** [OpenAngelArena/oaa#940]
Title. As soon as the strategy phase ends, it's just a black screen and nothing spawns in.

**Comment by Chronophylos** [comment]
Do you have the console output?

**Comment by imaGecko** [comment]
"Someone Dc'd during pikcscreen and we got in game and then it switched toa black screen witht eh connection failure message, but we could still hear the game in the background and move our characters ( we could hear them moving )
and we couldnt click anything
had to quit dota to get out"

Got this report, might be the same black screen bug

**Comment by Trildar** [comment]
Possibly fixed by #997. If it was the same as the DC during pick issue, it should be fixed.

**Comment by Chronophylos** [comment]
I'm sure it's fixed
