### ISSUE TITLE
Pushed off the map by Charger, can't recover because inventory too full

### ISSUE THREAD

**Issue by sctjkc01** [OpenAngelArena/oaa#944]
I was playing a game on my own (as in, I'm only player), reached 200 minutes, and was fighting the Charger  boss when I got pushed off the map.  Second time in the same game, so I bought a TP scroll from the shop... and my inventory was too full to take the scroll.  I fell too far down to be able to put anything in the Courier, so I wasn't able to take the TP scroll, which meant I lost.

And after getting down 20 bosses too...

**Comment by warpdragon** [comment]
moved to bug-reports. post there next time.

**Comment by sctjkc01** [comment]
I don't see where the "bug reports" are.  And I've a feeling that was created after I created the issue.

**Comment by Haganeko** [comment]
Here you go! https://github.com/OpenAngelArena/Bug-Reports/issues
If you look at the closed issues, you will see there are ones older than your post. (first issue was posted in May, while this dates back to June).

**Comment by sctjkc01** [comment]
Ah.  My bad, I didn't think to look in a whole other repo.  ( Might be worth putting a link to it in the Readme maybe... )

**Comment by Haganeko** [comment]
It *is* hard to find. We should probably start linking this: https://github.com/OpenAngelArena
instead.
