### ISSUE TITLE
Game doesn't end after reaching kill limit via boss kill

### ISSUE THREAD

**Issue by imaGecko** [OpenAngelArena/oaa#946]
Killed Uriel for the 100th point and the game didn't end
Played until 130 kills as the enemies had about 0 people leaving their base

**Comment by Chronophylos** [comment]
what was the game limit?

**Comment by imaGecko** [comment]
Everyone including host claimed to have selected nothing

**Comment by Chronophylos** [comment]
hm
I thought at least the points were stable

**Comment by chrisinajar** [comment]
I have ended a game with a boss kill.
