### ISSUE TITLE
Battlefury can't be upgraded to the final upgrade.

### ISSUE THREAD

**Issue by CynicalDemon** [OpenAngelArena/oaa#948]
I had an upgrade core 4 and the previous level battle fury with the recipe and the tool tip said there was another set of stats implying another level however the items wouldn't combine and it said there was not a bottle fury that needed and upgrade core 4 in the shop (the highest needed was an upgrade core require was level 3).

**Comment by Haganeko** [comment]
I can confirm we only have four bfurys, but the KVs have five entries.

**Comment by Trildar** [comment]
Fixed by #1017 I think.
