### ISSUE TITLE
Using enchant on a creep in the farming cave prevents progression

### ISSUE THREAD

**Issue by CynicalDemon** [OpenAngelArena/oaa#950]
If enchantress enchants a creep in the cave then you cannot enter the next room. If the creep dies under the effect of enchant then you can progress through the cave again though

**Comment by Chronophylos** [comment]
I don't think this is really a problem, but I can see people wondering why they can't progress..

**Comment by chrisinajar** [comment]
seems like a legit strat, and counting it as a kill before it's dead would be a significant buff.

**Comment by Haganeko** [comment]
Known bug, will probably be fixed soon (because Chen).
