### ISSUE TITLE
Global upgrade cores.

### ISSUE THREAD

**Issue by CynicalDemon** [OpenAngelArena/oaa#951]
Provided you have the recipe and the item and the upgrade cores equal to or above the level required, upgrade cores and recipes in the stash can be used to upgrade items regardless of where you are. This only works upon receiving a core.

Example: I was in the bottom center boss zone and had 3 level four upgrade core. I then bought all the recipes needed to upgrade silver edge. On killing the Killer tomato boss all the recipes and upgrade cores in my stash and backpack were used to upgrade the silver edge to the final upgrade.

**Comment by Chronophylos** [comment]
It's a Dota thing.
Eventually we'll fix this but this is not a priority.
And thank you for all the feedback!
