### ISSUE TITLE
Recipe cost for divine rapier is not as shown in shop

### ISSUE THREAD

**Issue by HoboClown** [OpenAngelArena/oaa#952]
The recipe cost for divine is displayed as 150,000 but the shop told me I didn't have enough gold to purchase it when I had much more (approx. 300,000)

**Comment by Minnakht** [comment]
That's an issue with how Dota works. Dota itself can't tell if you have more than 50k gold - it's a cap. The gamemode has backend code which keeps track of the amount of gold you SHOULD have and displays it where your ingame gold counter is, but in reality, you only ever have up to 50k "on hand".

And that's where the shop looks when asking you if you can afford the recipe, so you can't. Ever. So rapier isn't buyable.

[https://www.youtube.com/watch?v=a_rM2UTskI8](And given what happened here, it might be for the best.)

**Comment by Chronophylos** [comment]
That is not what is happening.
The cap is 99 999 Gold.
To allow more than that we implemented a custom Gold system.
Due to some reasons we set a threshhold of 50 000 Gold to allow buying and selling items.
As soon as we implement a custom shop this threshhold will be removed.

**Comment by chrisinajar** [comment]
Item is not at all balanced, we need to rethink it or remove it.
