### ISSUE TITLE
Charger Behaving Inconsistently, Spawning Pillars In Duel

### ISSUE THREAD

**Issue by RoastedFeznt** [OpenAngelArena/oaa#953]
I played quite a few games earlier this morning, and encountered several issues. One of which was a charger pillar spawning in the top left duel arena. This occurred after he missed a charge in his own arena and was briefly in the duel arena. I wound up losing the duel because I was bodyblocked by a pillar at the top of the stairs and couldn't avoid my opponent.

Another issue is inconsistency with the charger's, well, charge. Sometimes he charges in 3 seconds and I have time to move out of the way. Other times he can charge instantly and I am one shot in a way that feels unfair. Worse is when he charges instantly AND combo charges. I don't know if combo charging is intentional, but it feels even worse to be charged, survive, and then die anyways because the boss flipped out.

**Comment by imaGecko** [comment]
The issue with the pillars does sound weird. We will look into it.
The charge delay however is intentional. Charger has multiple phases, later phases have shorter charge time, the last phase has the combo charging. It's never unfair since you can see his model turning right before he channels his charge.

**Comment by Minnakht** [comment]
Charger generally spawns his pillars in random places in an area around him - that's how the code works. So wherever he is, he can spawn pillars - it's just that he should be within his arena most of the time. His charges taking him places is a known phenomenon, and it seems they coincided somehow.

You might've seen how Charger walks back to where he spawns before each charge early on - if he waited to do that before spawning pillars, it'd be a fix.

**Comment by Haganeko** [comment]
We're looking into displaying the phases note clearly, as well.

**Comment by chrisinajar** [comment]
Creating two tickets based on this
 * Add particle effects for boss phases #962
 * Move boss spawn position closest to duels #963
