### ISSUE TITLE
Random neutral Sniper spawned bottom middle of the map

### ISSUE THREAD

**Issue by laine4466** [OpenAngelArena/oaa#955]
In the middle of the game, a sniper was spawned at the bottom middle (close to radiant bosses entrance at the bottom) with the same items that the sniper on the enemy team had, but was neutral and had flying vision (can't detect invisibility). Killing the sniper doesn't add to the kill count, but adds to the DOTA hero kills, so the announcer could announce kill streaks you get from killing him (possibly because it is a neutral hero) and getting killed by him says that you have been killed by neutral creeps.

**Comment by chrisinajar** [comment]
Are you sure this wasn't the mirror boss?

**Comment by laine4466** [comment]
It constantly respawns where we kill him one second later, below the large area in the middle of the map, which was pretty far away from all the bosses, and the sniper wasn't around as far as I know when I triggered the boss by accident, so I don't think this is supposed to be the boss' normal behaviour.

**Comment by warpdragon** [comment]
moved to bug-reports. post there next time.
