### ISSUE TITLE
Necronomicon icon doesn't update in inventory

### ISSUE THREAD

**Issue by HoboClown** [OpenAngelArena/oaa#956]
The necromonicon icon in your inventory stays the same past lvl 3 after upgrading it past this point.

**Comment by Haganeko** [comment]
I believe necronomicon icons are a work in progress.

**Comment by Chronophylos** [comment]
#beccbb47d537c084599458716d5cff444385aa45 added new Necronomicon Icons.

**Comment by warpdragon** [comment]
moved to bug-reports. post there next time.
