### ISSUE TITLE
Links Remain Unset

### ISSUE THREAD

**Issue by martindale** [OpenAngelArena/oaa#957]
Clicking this:
![screenshot from 2017-05-29 11-13-15](https://cloud.githubusercontent.com/assets/129761/26558810/635617ba-4460-11e7-9924-4a6908e270c7.png)

Results in this:
![screenshot from 2017-05-29 11-13-22](https://cloud.githubusercontent.com/assets/129761/26558816/6dd403f0-4460-11e7-811a-2eb7d29a731a.png)

**Comment by Chronophylos** [comment]
Clicking where? Ingame?

**Comment by martindale** [comment]
Must be the mod listing?  It's in the main Steam interface.  I presume these links can be set in the publishing interface?

**Comment by Chronophylos** [comment]
Do you have a bigger image?

**Comment by Chronophylos** [comment]
As long as it isn't ingame meaning in the lobby or something we can't to anything.
