### ISSUE TITLE
End the game if one team leaves

### ISSUE THREAD

**Issue by chrisinajar** [OpenAngelArena/oaa#964]
If at least 3 people from a team disconnect, warn that the game will end to all players, and give them about 30 seconds for it to end. This lets people reconnect or pause if needed.

**Comment by Chronophylos** [comment]
Should the leading team win?

**Comment by Haganeko** [comment]
Could make people attempt to "win" by getting a kill advantage and leaving. Makes no sense, but trolls gonna troll. 
My opinion is we make the leaving team lose. Or just declare a tie, if possible.

**Comment by Chronophylos** [comment]
To end the game one team needs to win.
Or we could crash it.

**Comment by Haganeko** [comment]
Crashing is bad. I bet valve keeps track of when that happens. Can we make Dota_Team_Neutrals win?

**Comment by Chronophylos** [comment]
We should
Doesn't mean Valve allows us to do so

**Comment by chrisinajar** [comment]
Leaving team should lose, you never get rewarded for leaving. Also, if you left, you'll never know if you won or not :D

**Comment by Haganeko** [comment]
That stimulates the other team not to pause on DC because if the other team DCs they win.

**Comment by Chronophylos** [comment]
What if we pause for them

**Comment by l34Um1** [comment]
shouldn't end with 3 leavers, should end with 5

**Comment by imaGecko** [comment]
Should end with 5 leavers. In rare cases 2 people are enough to finish and win the game

**Comment by allanvbhg** [comment]
Just make a 'gg-option' if at least 3 people leave the remaining people can type 'gg' to concede, Like in tournaments but for leavers

**Comment by Trildar** [comment]
Should be done.
