### ISSUE TITLE
Banish/Exile/Phase Shift effects and Duel Teleports don't play nice

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#968]
Duel teleporting while heroes are under the effects of hiding/exiling abilities causes them to be teleported to wrong locations. Effects confirmed to cause this issue include Tricks of the Trade, Astral Imprisonment, Eul's Scepter, Sleight of Fist, and Phase Shift.

Should probably also make sure that Farming Cave teleportation has any fixes applied for this issue as well.

**Comment by l34Um1** [comment]
Closed because old.
