### ISSUE TITLE
Diffusal Blade not showing pips in inventory

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#969]
But shows in tooltip and shop.

The only reason I can think of why this is happening is that the item has some hardcoded icon despite there being no apparent reason to set icon from code since Diffusal doesn't seem to have any different icons.

**Comment by warpdragon** [comment]
Also someone go into the asset manager and turn on "hidden assets" and check for vmats called "diffusal"
it might be that we missed something

Same problem with Aquila.

If we're unable to fix the icon bug by simply overriding its vmat with a png file, then we'll have to make a new lua ability to replace both aquila and diffusal and I hear there's also problems with necronomicon... not sure if that's relevant here.

**Comment by warpdragon** [comment]
moved to bug-rports. post there next time.
