### ISSUE TITLE
Tier 1 Roshan Boss kill in first min.

### ISSUE THREAD

**Issue by shubidubapp** [OpenAngelArena/oaa#970]
There is a way of killing the roshan in the first minute. Basicly they are somehow making it enter to the fountain. Which than 1 shots it.

**Comment by Chronophylos** [comment]
Yeah, Leashes are broken, this is a know Bug.
Thanks for reporting this anyway.

**Comment by Haganeko** [comment]
Thank you for the report. This is a known bug-there's some problem with the leash which keeps bosses on their pen.
