### ISSUE TITLE
Particle "X"s - Precache Particles Showing Errors

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#977]
Ok so there's a few scripted particles in the game that cause "X"s to appear instead of particles. I'm guessing this is because nobody precached them. Can we fix these?

**Comment by chrisinajar** [comment]
Can someone document where this is happening?

**Comment by warpdragon** [comment]
Shielder, phase boots i believe too

**Comment by warpdragon** [comment]
Not sure which files...
