### ISSUE TITLE
Divine enrage crystal not usable during hex

### ISSUE THREAD

**Issue by Omniscience27** [OpenAngelArena/oaa#984]
Currently divine enrage crystal, although supposed to be able to be used during stuns to grant a hard dispel. is not usable during hex. not sure if this is intended or not.

**Comment by Haganeko** [comment]
Bex specifically mutes items. I am unsure whether we want to disregard that. Thank you for the report!

**Comment by SquawkyArctangent** [comment]
Abaddon's Borrowed Time can't be activated during silence or hex, despite being usable while disabled.

**Comment by DarkoniusXNG** [comment]
@Omniscience27 Dota mechanic: Hex is not exactly a stun, it disables channeling but it doesn't stun. Hex applies mute and silence. Therefore all spells (disregarding passive spells) and ALL items cannot be used while hexed. Simply put: Nothing should be usable during hex. 

Making something usable during hex would require inventing/coding a new mechanic.

**Comment by Chronophylos** [comment]
The above comment sum this up
