### ISSUE TITLE
Spectre dispersion (E) walk to fauntain easy kills.

### ISSUE THREAD

**Issue by Techniclinus** [OpenAngelArena/oaa#992]
When ever Spectre walk in the fauntain while there are players in it they die.
Bug?

Cause?
I dont know jet.
Thoughts of what the problem could be. Spectre haunt (R) illusions.

**Comment by Chronophylos** [comment]
Dispersion

**Comment by Chronophylos** [comment]
A fix is being worked on.
1.1.0 will have it fixed

**Comment by Haganeko** [comment]
Side note: the cause is Dispersion.
