### ISSUE TITLE
ALL ITEMS TO LVL 5 (Help Wanted!)

### ISSUE THREAD

**Issue by warpdragon** [OpenAngelArena/oaa#995]
<https://tinyurl.com/All-Items-Lvl-5>

YES EVERYTHING.

**Comment by Haganeko** [comment]
Except for things that build into other vanilla things, no?

**Comment by imaGecko** [comment]
Yup. Every vanilla item that has no further upgrade

**Comment by Chronophylos** [comment]
Tier 5 not Item Level 5

**Comment by TheObbyDragon** [comment]
Even tangos and clarities?
#the new cheese

**Comment by Minnakht** [comment]
If it's a nonconsumable item that doesn't build into anything, it'll now build into eating cores. If it already ate cores, it'll now eat four.

**Comment by TheObbyDragon** [comment]
eating cores?

**Comment by warpdragon** [comment]
Fairly certain this has reached its stopping point. Closed. GJ everyone!

**Comment by Haganeko** [comment]
Missed HotD and MM.
