### ISSUE TITLE
Spectre can fountain farm with Dispersion

### ISSUE THREAD

**Issue by szock** [OpenAngelArena/oaa#999]
Title. The fountain deals so much damage even the single strike against spectre before she dies is enough to kill everyone in the radius. When people disconnect there is no way to protect them from being farmed in this manner. All enemies should have Break applied to them when they get near the fountain, and be continually purged so they enemy can't eblade in.

**Comment by Haganeko** [comment]
Thank you for the report. This is a well known issue, and there's a fix coming. You'd do well to look at recently opened and closed issues, so as to know what has already been reported.
